#!/usr/bin/env bun
/*
 * Codegen for @vibeflow/connectors.
 *
 * Reads generated/connectors/normalized/*.json and produces one TypeScript
 * module per connector under src/_generated/. Each module exports a single
 * PascalCase namespace whose properties are factory functions for the
 * connector's operations. Each factory returns an ActionSpec / TriggerSpec
 * ready to hand to a Vibeflow FlowBuilder.
 */
import { mkdir, readdir, readFile, writeFile } from "node:fs/promises";
import { join, resolve } from "node:path";

interface NormalizedConnector {
  connectorId: string;
  displayName: string;
  sourceUrl?: string;
  operations: Record<string, NormalizedOperation>;
}

interface NormalizedOperation {
  operationId: string;
  kind: "action" | "trigger";
  displayName: string;
  deprecated: boolean;
  description: string;
  parameters: Array<{
    name: string;
    key: string;
    required: boolean;
    type: string;
    description: string;
  }>;
  returns?: { raw?: string };
}

const REPO_ROOT = resolve(import.meta.dir, "../../..");
const CATALOG_DIR = join(REPO_ROOT, "generated/connectors/normalized");
const OUT_DIR = resolve(import.meta.dir, "../src/_generated");

const RESERVED_TS_KEYWORDS = new Set([
  "break", "case", "catch", "class", "const", "continue", "debugger", "default",
  "delete", "do", "else", "enum", "export", "extends", "false", "finally", "for",
  "function", "if", "import", "in", "instanceof", "new", "null", "return", "super",
  "switch", "this", "throw", "true", "try", "typeof", "var", "void", "while", "with",
  "yield", "async", "await", "let", "static", "any", "boolean", "constructor",
  "declare", "get", "module", "require", "number", "set", "string", "symbol", "type",
  "from", "of", "package", "private", "protected", "public", "implements", "interface",
]);

async function main(): Promise<void> {
  await mkdir(OUT_DIR, { recursive: true });

  const files = (await readdir(CATALOG_DIR)).filter((f) => f.endsWith(".json")).sort();
  const indexEntries: Array<{ namespaceName: string; moduleName: string; displayName: string; connectorId: string; opCount: number }> = [];

  for (const file of files) {
    const data = JSON.parse(await readFile(join(CATALOG_DIR, file), "utf8")) as NormalizedConnector;
    const namespaceName = pascalCase(data.displayName);
    const moduleName = file.replace(".json", "");
    const code = renderConnectorModule(data, namespaceName);
    await writeFile(join(OUT_DIR, `${moduleName}.ts`), code);
    indexEntries.push({
      namespaceName,
      moduleName,
      displayName: data.displayName,
      connectorId: data.connectorId,
      opCount: Object.keys(data.operations).length,
    });
  }

  const indexCode = renderIndexModule(indexEntries);
  await writeFile(join(OUT_DIR, "index.ts"), indexCode);

  console.log(
    `Generated ${indexEntries.length} connector modules (${indexEntries.reduce((s, e) => s + e.opCount, 0)} operations) -> ${OUT_DIR}`,
  );
}

function renderConnectorModule(connector: NormalizedConnector, namespaceName: string): string {
  const apiId = `/providers/Microsoft.PowerApps/apis/${connector.connectorId}`;
  const lines: string[] = [];
  lines.push("// AUTO-GENERATED by packages/connectors/scripts/generate.ts.");
  lines.push("// Do not edit by hand. Re-run `bun --filter @vibeflow/connectors generate`.");
  lines.push(`// Connector: ${connector.connectorId} — ${connector.displayName}`);
  if (connector.sourceUrl) lines.push(`// Source: ${connector.sourceUrl}`);
  lines.push("");
  lines.push(`import { buildConnectorCall, type ActionSpec, type ConnectorCallOptions, type ExpressionOrValue, type TriggerSpec } from "../_runtime.js";`);
  lines.push("");
  lines.push(`const API_ID = ${JSON.stringify(apiId)};`);
  lines.push(`const DEFAULT_CONNECTION_NAME = ${JSON.stringify(connector.connectorId)};`);
  lines.push("");
  lines.push(`export const ${namespaceName} = {`);
  lines.push(`  /** Connector id (\`${connector.connectorId}\`). */`);
  lines.push(`  connectorId: ${JSON.stringify(connector.connectorId)},`);
  lines.push(`  /** Power Automate apiId for this connector. */`);
  lines.push(`  apiId: API_ID,`);

  const seenFunctionNames = new Map<string, number>();
  const sortedOpIds = Object.keys(connector.operations).sort();
  for (const opId of sortedOpIds) {
    const op = connector.operations[opId];
    if (!op) continue;
    const fnName = uniqueIdentifier(camelCase(op.operationId), seenFunctionNames);
    lines.push("");
    renderOperation(lines, op, fnName);
  }
  lines.push("} as const;");
  lines.push("");
  return lines.join("\n");
}

function renderOperation(
  lines: string[],
  op: NormalizedOperation,
  fnName: string,
): void {
  const isTrigger = op.kind === "trigger";
  const returnType = isTrigger ? "TriggerSpec" : "ActionSpec";

  // JSDoc
  lines.push(`  /**`);
  lines.push(`   * ${escapeJsDoc(op.displayName)}`);
  if (op.deprecated) lines.push(`   * @deprecated Marked deprecated by Microsoft.`);
  if (op.kind === "trigger") lines.push(`   * @remarks This is a trigger operation; pass it to flowBuilder.setTrigger().`);
  const returnsRaw = op.returns?.raw ?? "";
  if (returnsRaw) {
    const returns = returnsRaw.split("\n").map((s) => s.trim()).filter(Boolean).slice(0, 4);
    if (returns.length > 0) lines.push(`   * @returns ${escapeJsDoc(returns.join(" "))}`);
  }
  lines.push(`   * Operation id: \`${op.operationId}\``);
  lines.push(`   */`);

  // Dedupe parameters by key (Microsoft Learn sometimes lists the same key twice
  // for variant signatures; we keep the first occurrence and treat the param as
  // required if any of the duplicates are required).
  const dedupedParams = new Map<string, NormalizedOperation["parameters"][number]>();
  for (const p of op.parameters) {
    if (!p.key) continue;
    const existing = dedupedParams.get(p.key);
    if (!existing) {
      dedupedParams.set(p.key, { ...p });
    } else if (p.required && !existing.required) {
      existing.required = true;
    }
  }
  const uniqueParams = [...dedupedParams.values()];
  const requiredParams = uniqueParams.filter((p) => p.required);
  const optionalParams = uniqueParams.filter((p) => !p.required);
  const hasParams = uniqueParams.length > 0;

  if (!hasParams) {
    lines.push(`  ${fnName}(options?: ConnectorCallOptions): ${returnType} {`);
  } else {
    lines.push(`  ${fnName}(`);
    lines.push(`    parameters: {`);
    // All parameters typed as optional in TS to accommodate connectors that
    // use grouped parameter keys (e.g. "emailMessage/To") not represented in
    // the Microsoft Learn-derived catalog. Required-ness is enforced at
    // validation time by the catalog-aware validator.
    for (const p of requiredParams) {
      lines.push(`      ${quoteKey(p.key)}?: ExpressionOrValue;${formatParamComment(p, true)}`);
    }
    for (const p of optionalParams) {
      lines.push(`      ${quoteKey(p.key)}?: ExpressionOrValue;${formatParamComment(p, false)}`);
    }
    lines.push(`    } & Record<string, ExpressionOrValue>,`);
    lines.push(`    options?: ConnectorCallOptions,`);
    lines.push(`  ): ${returnType} {`);
  }

  lines.push(`    return buildConnectorCall({`);
  lines.push(`      kind: ${JSON.stringify(op.kind)},`);
  lines.push(`      apiId: API_ID,`);
  lines.push(`      defaultConnectionName: DEFAULT_CONNECTION_NAME,`);
  lines.push(`      operationId: ${JSON.stringify(op.operationId)},`);
  if (!hasParams) {
    lines.push(`      parameters: {},`);
  } else {
    lines.push(`      parameters: parameters as Record<string, ExpressionOrValue>,`);
  }
  if (!hasParams) {
    lines.push(`      options,`);
  } else {
    lines.push(`      options,`);
  }
  lines.push(`    }) as ${returnType};`);
  lines.push(`  },`);
}

function renderIndexModule(
  entries: Array<{ namespaceName: string; moduleName: string; displayName: string; connectorId: string; opCount: number }>,
): string {
  const lines: string[] = [];
  lines.push("// AUTO-GENERATED. Do not edit by hand.");
  lines.push("");
  for (const entry of entries) {
    lines.push(`export { ${entry.namespaceName} } from "./${entry.moduleName}.js";`);
  }
  lines.push("");
  lines.push("export const CONNECTORS = [");
  for (const entry of entries) {
    lines.push(
      `  { connectorId: ${JSON.stringify(entry.connectorId)}, displayName: ${JSON.stringify(entry.displayName)}, operations: ${entry.opCount} },`,
    );
  }
  lines.push("] as const;");
  lines.push("");
  return lines.join("\n");
}

function camelCase(input: string): string {
  const parts = input.split(/[^a-zA-Z0-9]/).filter(Boolean);
  if (parts.length === 0) return input;
  return parts
    .map((part, idx) => (idx === 0 ? part[0]!.toLowerCase() + part.slice(1) : part[0]!.toUpperCase() + part.slice(1)))
    .join("");
}

function pascalCase(input: string): string {
  const parts = input.split(/[^a-zA-Z0-9]/).filter(Boolean);
  if (parts.length === 0) return input;
  return parts.map((part) => part[0]!.toUpperCase() + part.slice(1)).join("");
}

function uniqueIdentifier(name: string, seen: Map<string, number>): string {
  let candidate = name;
  if (RESERVED_TS_KEYWORDS.has(candidate)) candidate = `${candidate}_`;
  // Identifiers cannot start with a digit.
  if (/^[0-9]/.test(candidate)) candidate = `op${candidate[0]!.toUpperCase()}${candidate.slice(1)}`;
  const count = seen.get(candidate) ?? 0;
  seen.set(candidate, count + 1);
  if (count === 0) return candidate;
  return `${candidate}${count + 1}`;
}

function quoteKey(key: string): string {
  if (/^[a-zA-Z_$][a-zA-Z0-9_$]*$/.test(key) && !RESERVED_TS_KEYWORDS.has(key)) {
    return key;
  }
  return JSON.stringify(key);
}

function formatParamComment(
  p: NormalizedOperation["parameters"][number],
  required: boolean,
): string {
  const parts: string[] = [];
  parts.push(required ? "REQUIRED" : "optional");
  if (p.name && p.name !== p.key) parts.push(p.name);
  if (p.type) parts.push(p.type);
  if (p.description) parts.push(escapeJsDoc(p.description).slice(0, 120));
  return ` // ${parts.join(" — ")}`;
}

function escapeJsDoc(input: string): string {
  return input.replace(/\*\//g, "*\u200b/").replace(/\r?\n/g, " ").trim();
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
