from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path
from typing import Any

from .aliases import generate_aliases
from .context import write_context
from .index import build_index, package_summary
from .linting import lint_indexes
from .package import discover_export
from .rewrite import rewrite_export


def main(argv: list[str] | None = None) -> int:
    parser = _parser()
    args = parser.parse_args(argv)
    try:
        return args.func(args)
    except Exception as exc:  # pragma: no cover - exercised by CLI use
        print(f"vibeflow: error: {exc}", file=sys.stderr)
        return 1


def _parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(prog="vibeflow", description="Power Automate export tooling for AI-safe edits.")
    subcommands = parser.add_subparsers(dest="command", required=True)

    inspect = subcommands.add_parser("inspect", help="Summarize a Power Automate export.")
    inspect.add_argument("export", help="Export directory, flow directory, or definition.json")
    inspect.add_argument("--json", action="store_true", help="Emit machine-readable JSON.")
    inspect.set_defaults(func=_cmd_inspect)

    context = subcommands.add_parser("context", help="Generate AI-ready context files.")
    context.add_argument("export", help="Export directory, flow directory, or definition.json")
    context.add_argument("--out", required=True, help="Output directory for context files.")
    context.set_defaults(func=_cmd_context)

    lint = subcommands.add_parser("lint", help="Lint a Power Automate export.")
    lint.add_argument("export", help="Export directory, flow directory, or definition.json")
    lint.add_argument("--profile", default="balanced", choices=["balanced"], help="Lint profile.")
    lint.add_argument("--json", action="store_true", help="Emit machine-readable JSON.")
    lint.set_defaults(func=_cmd_lint)

    rewrite = subcommands.add_parser("rewrite", help="Rewrite an export into a generated output copy.")
    rewrite.add_argument("export", help="Export directory, flow directory, or definition.json")
    rewrite.add_argument("--aliases", required=True, help="aliases.json generated by vibeflow context.")
    rewrite.add_argument("--out", required=True, help="Output directory for the rewritten export copy.")
    rewrite.add_argument("--force", action="store_true", help="Replace the output directory if it already exists.")
    rewrite.set_defaults(func=_cmd_rewrite)

    aliases = subcommands.add_parser("aliases", help="Print aliases.json for an export.")
    aliases.add_argument("export", help="Export directory, flow directory, or definition.json")
    aliases.set_defaults(func=_cmd_aliases)
    return parser


def _indexes(export_path: str) -> list[Any]:
    package = discover_export(export_path)
    return [build_index(flow) for flow in package.flows]


def _cmd_inspect(args: argparse.Namespace) -> int:
    indexes = _indexes(args.export)
    summary = package_summary(indexes)
    if args.json:
        _print_json(summary)
    else:
        _print_human_summary(summary)
    return 0


def _cmd_context(args: argparse.Namespace) -> int:
    result = write_context(_indexes(args.export), args.out)
    _print_json(result)
    return 0


def _cmd_lint(args: argparse.Namespace) -> int:
    result = lint_indexes(_indexes(args.export), profile=args.profile)
    if args.json:
        _print_json(result)
    else:
        _print_human_lint(result)
    return 0 if result["severityCounts"].get("error", 0) == 0 else 2


def _cmd_rewrite(args: argparse.Namespace) -> int:
    report = rewrite_export(args.export, args.aliases, args.out, force=args.force)
    _print_json(report)
    return 0 if not any(flow["validationErrors"] for flow in report["flows"]) else 2


def _cmd_aliases(args: argparse.Namespace) -> int:
    _print_json(generate_aliases(_indexes(args.export)))
    return 0


def _print_json(value: Any) -> None:
    print(json.dumps(value, indent=2, ensure_ascii=False))


def _print_human_summary(summary: dict[str, Any]) -> None:
    print(f"Flows: {summary['flowCount']}")
    for flow in summary["flows"]:
        print(f"\n{flow['displayName']} ({flow['flowId']})")
        print(f"  Definition: {flow['definitionPath']}")
        print(f"  Triggers: {', '.join(flow['triggers']) or 'none'}")
        print(f"  Actions: {flow['totalActionCount']} total, {flow['topLevelActionCount']} top-level")
        print(f"  Types: {_short_counts(flow['actionTypes'])}")
        print(f"  Variables: {flow['variableCount']}")
        print(f"  Expressions: {flow['expressionCount']}")
        print(f"  Opaque form fields: {flow['formFieldIdCount']}")
        print(f"  Hard-coded constants: {flow['hardCodedConstantCount']}")
        print(f"  Metadata GUIDs: {flow['metadataGuidCount']}")


def _print_human_lint(result: dict[str, Any]) -> None:
    print(f"Profile: {result['profile']}")
    print(f"Issues: {result['issueCount']} ({_short_counts(result['severityCounts'])})")
    for flow in result["flows"]:
        print(f"\n{flow['displayName']} ({flow['flowId']})")
        for issue in flow["issues"]:
            print(f"  [{issue['severity']}] {issue['rule']} {issue['message']}")
            print(f"       {issue['suggestion']}")


def _short_counts(counts: dict[str, Any]) -> str:
    if not counts:
        return "none"
    return ", ".join(f"{key}={value}" for key, value in counts.items())
