// AUTO-GENERATED by packages/connectors/scripts/generate.ts.
// Do not edit by hand. Re-run `bun --filter @vibeflow/connectors generate`.
// Connector: shared_sharepointonline — SharePoint
// Source: https://learn.microsoft.com/en-us/connectors/sharepointonline/?accept=text/markdown

import { buildConnectorCall, type ActionSpec, type ConnectorCallOptions, type ExpressionOrValue, type TriggerSpec } from "../_runtime.js";

const API_ID = "/providers/Microsoft.PowerApps/apis/shared_sharepointonline";
const DEFAULT_CONNECTION_NAME = "shared_sharepointonline";

export const SharePoint = {
  /** Connector id (`shared_sharepointonline`). */
  connectorId: "shared_sharepointonline",
  /** Power Automate apiId for this connector. */
  apiId: API_ID,

  /**
   * Approve hub site join request
   * @returns Result object of ApproveHubSiteJoin action - Body - ApproveHubSiteJoinResponse
   * Operation id: `ApproveHubSiteJoin`
   */
  approveHubSiteJoin(
    parameters: {
      dataset?: ExpressionOrValue; // REQUIRED — Hub Site Address — string — Example: `https://contoso.sharepoint.com/sites/sitename`.
      joiningSiteId?: ExpressionOrValue; // REQUIRED — Requesting Site Id — string — Id of the requesting site.
    } & Record<string, ExpressionOrValue>,
    options?: ConnectorCallOptions,
  ): ActionSpec {
    return buildConnectorCall({
      kind: "action",
      apiId: API_ID,
      defaultConnectionName: DEFAULT_CONNECTION_NAME,
      operationId: "ApproveHubSiteJoin",
      parameters: parameters as Record<string, ExpressionOrValue>,
      options,
    }) as ActionSpec;
  },

  /**
   * Cancel hub site join request
   * Operation id: `CancelHubSiteJoinApproval`
   */
  cancelHubSiteJoinApproval(
    parameters: {
      dataset?: ExpressionOrValue; // REQUIRED — Requesting Site Address — string — Example: `https://contoso.sharepoint.com/sites/sitename`.
      approvalCorrelationId?: ExpressionOrValue; // optional — Approval Correlation Id — string — Approval correlation identifier for this request.
    } & Record<string, ExpressionOrValue>,
    options?: ConnectorCallOptions,
  ): ActionSpec {
    return buildConnectorCall({
      kind: "action",
      apiId: API_ID,
      defaultConnectionName: DEFAULT_CONNECTION_NAME,
      operationId: "CancelHubSiteJoinApproval",
      parameters: parameters as Record<string, ExpressionOrValue>,
      options,
    }) as ActionSpec;
  },

  /**
   * Check if the scheduled version of the item is published [DEPRECATED]
   * @deprecated Marked deprecated by Microsoft.
   * @returns Output object of the CheckIfFileIsPublished endpoint on the SPO Connector shim - Body - PublishedResult
   * Operation id: `CheckIfFileIsPublished`
   */
  checkIfFileIsPublished(
    parameters: {
      dataset?: ExpressionOrValue; // REQUIRED — Site Address — string — Example: `https://contoso.sharepoint.com/sites/sitename`.
      table?: ExpressionOrValue; // REQUIRED — Library Name — string — SharePoint library name.
      id?: ExpressionOrValue; // REQUIRED — Item ID — integer — Unique identifier of the file.
      scheduledVersion?: ExpressionOrValue; // REQUIRED — Scheduled Version — string — Version of file that was scheduled for publish.
    } & Record<string, ExpressionOrValue>,
    options?: ConnectorCallOptions,
  ): ActionSpec {
    return buildConnectorCall({
      kind: "action",
      apiId: API_ID,
      defaultConnectionName: DEFAULT_CONNECTION_NAME,
      operationId: "CheckIfFileIsPublished",
      parameters: parameters as Record<string, ExpressionOrValue>,
      options,
    }) as ActionSpec;
  },

  /**
   * Check in file
   * Operation id: `CheckInFile`
   */
  checkInFile(
    parameters: {
      dataset?: ExpressionOrValue; // REQUIRED — Site Address — string — Example: `https://contoso.sharepoint.com/sites/sitename`.
      table?: ExpressionOrValue; // REQUIRED — Library Name — string — SharePoint library name.
      id?: ExpressionOrValue; // REQUIRED — Id — integer — Id of the list item the file is attached to.
      comment?: ExpressionOrValue; // REQUIRED — Comments — string — Type comments describing what has changed in this version
      checkinType?: ExpressionOrValue; // REQUIRED — Check in type — integer — Select the type of version you would like to check in
    } & Record<string, ExpressionOrValue>,
    options?: ConnectorCallOptions,
  ): ActionSpec {
    return buildConnectorCall({
      kind: "action",
      apiId: API_ID,
      defaultConnectionName: DEFAULT_CONNECTION_NAME,
      operationId: "CheckInFile",
      parameters: parameters as Record<string, ExpressionOrValue>,
      options,
    }) as ActionSpec;
  },

  /**
   * Check out file
   * Operation id: `CheckOutFile`
   */
  checkOutFile(
    parameters: {
      dataset?: ExpressionOrValue; // REQUIRED — Site Address — string — Example: `https://contoso.sharepoint.com/sites/sitename`.
      table?: ExpressionOrValue; // REQUIRED — Library Name — string — SharePoint library name.
      id?: ExpressionOrValue; // REQUIRED — Id — integer — Id of the list item the file is attached to.
    } & Record<string, ExpressionOrValue>,
    options?: ConnectorCallOptions,
  ): ActionSpec {
    return buildConnectorCall({
      kind: "action",
      apiId: API_ID,
      defaultConnectionName: DEFAULT_CONNECTION_NAME,
      operationId: "CheckOutFile",
      parameters: parameters as Record<string, ExpressionOrValue>,
      options,
    }) as ActionSpec;
  },

  /**
   * Copy file (deprecated)
   * @returns Blob metadata - Body - BlobMetadata
   * Operation id: `CopyFile`
   */
  copyFile(
    parameters: {
      dataset?: ExpressionOrValue; // REQUIRED — Site Address — string — Example: `https://contoso.sharepoint.com/sites/sitename`.
      source?: ExpressionOrValue; // REQUIRED — Source File Path — string — Path to the source file.
      destination?: ExpressionOrValue; // REQUIRED — Destination File Path — string — Path to the destination file.
      overwrite?: ExpressionOrValue; // optional — Overwrite Flag — boolean — Whether or not to overwrite the destination file if it exists.
    } & Record<string, ExpressionOrValue>,
    options?: ConnectorCallOptions,
  ): ActionSpec {
    return buildConnectorCall({
      kind: "action",
      apiId: API_ID,
      defaultConnectionName: DEFAULT_CONNECTION_NAME,
      operationId: "CopyFile",
      parameters: parameters as Record<string, ExpressionOrValue>,
      options,
    }) as ActionSpec;
  },

  /**
   * Copy file
   * @returns The SharePoint version of the BlobMetadataResponse extends the object by adding some additional fields that we want serialized - Body - SPBlobMetadataResponse
   * Operation id: `CopyFileAsync`
   */
  copyFileAsync(
    parameters: {
      dataset?: ExpressionOrValue; // REQUIRED — Current Site Address — string — Example: `https://contoso.sharepoint.com/sites/sitename`.
      sourceFileId?: ExpressionOrValue; // REQUIRED — File to Copy — string — File Identifier
      destinationDataset?: ExpressionOrValue; // REQUIRED — Destination Site Address — string — Example: `https://contoso.sharepoint.com/sites/sitename`
      destinationFolderPath?: ExpressionOrValue; // REQUIRED — Destination Folder — string — Destination Folder
      nameConflictBehavior?: ExpressionOrValue; // REQUIRED — If another file is already there — integer — Pick one of the options available
    } & Record<string, ExpressionOrValue>,
    options?: ConnectorCallOptions,
  ): ActionSpec {
    return buildConnectorCall({
      kind: "action",
      apiId: API_ID,
      defaultConnectionName: DEFAULT_CONNECTION_NAME,
      operationId: "CopyFileAsync",
      parameters: parameters as Record<string, ExpressionOrValue>,
      options,
    }) as ActionSpec;
  },

  /**
   * Copy folder
   * @returns The SharePoint version of the BlobMetadataResponse extends the object by adding some additional fields that we want serialized - Body - SPBlobMetadataResponse
   * Operation id: `CopyFolderAsync`
   */
  copyFolderAsync(
    parameters: {
      dataset?: ExpressionOrValue; // REQUIRED — Current Site Address — string — Example: `https://contoso.sharepoint.com/sites/sitename`.
      sourceFolderId?: ExpressionOrValue; // REQUIRED — Folder to Copy — string — File Identifier
      destinationDataset?: ExpressionOrValue; // REQUIRED — Destination Site Address — string — Example: `https://contoso.sharepoint.com/sites/sitename`
      destinationFolderPath?: ExpressionOrValue; // REQUIRED — Destination Folder — string — Destination Folder
      nameConflictBehavior?: ExpressionOrValue; // REQUIRED — If another folder is already there — integer — Pick one of the options available
    } & Record<string, ExpressionOrValue>,
    options?: ConnectorCallOptions,
  ): ActionSpec {
    return buildConnectorCall({
      kind: "action",
      apiId: API_ID,
      defaultConnectionName: DEFAULT_CONNECTION_NAME,
      operationId: "CopyFolderAsync",
      parameters: parameters as Record<string, ExpressionOrValue>,
      options,
    }) as ActionSpec;
  },

  /**
   * Agreements Solution - Generate document within Agreements Solution workspace
   * @returns The SharePoint version of the BlobMetadataResponse extends the object by adding some additional fields that we want serialized - Body - SPBlobMetadataResponse
   * Operation id: `CreateAgreementsSolutionDocument`
   */
  createAgreementsSolutionDocument(
    parameters: {
      dataset?: ExpressionOrValue; // REQUIRED — Agreements Solution Workspace — string — Example: `https://contoso.sharepoint.com/sites/sitename`.
      template?: ExpressionOrValue; // REQUIRED — Agreements Solution Template — string — Agreements Solution template.
      item?: ExpressionOrValue; // REQUIRED — Fields — dynamic — Document placeholder values.
      documentName?: ExpressionOrValue; // optional — File Name — string — Document file name.
      table?: ExpressionOrValue; // optional — Table (no effect) — string — This parameter does nothing. Please do not use.
      view?: ExpressionOrValue; // optional — View (no effect) — string — This parameter does nothing. Please do not use.
    } & Record<string, ExpressionOrValue>,
    options?: ConnectorCallOptions,
  ): ActionSpec {
    return buildConnectorCall({
      kind: "action",
      apiId: API_ID,
      defaultConnectionName: DEFAULT_CONNECTION_NAME,
      operationId: "CreateAgreementsSolutionDocument",
      parameters: parameters as Record<string, ExpressionOrValue>,
      options,
    }) as ActionSpec;
  },

  /**
   * Create an approval request for an item or file
   * @returns Output object of the new approval request - Body - ApprovalData
   * Operation id: `CreateApprovalRequest`
   */
  createApprovalRequest(
    parameters: {
      dataset?: ExpressionOrValue; // REQUIRED — Site Address — string — Example: `https://contoso.sharepoint.com/sites/sitename`.
      table?: ExpressionOrValue; // REQUIRED — List or Library — string — SharePoint list or library name.
      id?: ExpressionOrValue; // REQUIRED — Id — integer — Id of the item the approval request is being created for.
      approvalType?: ExpressionOrValue; // REQUIRED — Approval Type — integer — Select an approval type.
      approvalSchema?: ExpressionOrValue; // REQUIRED — Approval Schema — dynamic — Schema for the selected approval type.
    } & Record<string, ExpressionOrValue>,
    options?: ConnectorCallOptions,
  ): ActionSpec {
    return buildConnectorCall({
      kind: "action",
      apiId: API_ID,
      defaultConnectionName: DEFAULT_CONNECTION_NAME,
      operationId: "CreateApprovalRequest",
      parameters: parameters as Record<string, ExpressionOrValue>,
      options,
    }) as ActionSpec;
  },

  /**
   * Add attachment
   * @returns SharePoint list item attachment - Body - SPListItemAttachment
   * Operation id: `CreateAttachment`
   */
  createAttachment(
    parameters: {
      dataset?: ExpressionOrValue; // REQUIRED — Site Address — string — Example: `https://contoso.sharepoint.com/sites/sitename`.
      table?: ExpressionOrValue; // REQUIRED — List Name — string — SharePoint list name.
      itemId?: ExpressionOrValue; // REQUIRED — Id — integer — Id of the list item to attach the file to.
      displayName?: ExpressionOrValue; // REQUIRED — File Name — string — File name.
      body?: ExpressionOrValue; // REQUIRED — File Content — binary — Content of the file.
    } & Record<string, ExpressionOrValue>,
    options?: ConnectorCallOptions,
  ): ActionSpec {
    return buildConnectorCall({
      kind: "action",
      apiId: API_ID,
      defaultConnectionName: DEFAULT_CONNECTION_NAME,
      operationId: "CreateAttachment",
      parameters: parameters as Record<string, ExpressionOrValue>,
      options,
    }) as ActionSpec;
  },

  /**
   * Generate document using Microsoft Syntex (preview)
   * @returns The SharePoint version of the BlobMetadataResponse extends the object by adding some additional fields that we want serialized - Body - SPBlobMetadataResponse
   * Operation id: `CreateContentAssemblyDocument`
   */
  createContentAssemblyDocument(
    parameters: {
      dataset?: ExpressionOrValue; // REQUIRED — Site Address — string — Example: `https://contoso.sharepoint.com/sites/sitename`.
      table?: ExpressionOrValue; // REQUIRED — Document Library Name — string — SharePoint document library name.
      template?: ExpressionOrValue; // REQUIRED — Document Template — string — Document template.
      item?: ExpressionOrValue; // REQUIRED — Placeholders — dynamic — Document placeholder values.
      folderPath?: ExpressionOrValue; // optional — Folder Path — string — Must start with an existing library.
      fileName?: ExpressionOrValue; // optional — File Name — string — Document file name.
      view?: ExpressionOrValue; // optional — View (no effect) — string — This parameter does nothing. Please do not use.
    } & Record<string, ExpressionOrValue>,
    options?: ConnectorCallOptions,
  ): ActionSpec {
    return buildConnectorCall({
      kind: "action",
      apiId: API_ID,
      defaultConnectionName: DEFAULT_CONNECTION_NAME,
      operationId: "CreateContentAssemblyDocument",
      parameters: parameters as Record<string, ExpressionOrValue>,
      options,
    }) as ActionSpec;
  },

  /**
   * Create file
   * @returns The SharePoint version of the BlobMetadataResponse extends the object by adding some additional fields that we want serialized - Body - SPBlobMetadataResponse
   * Operation id: `CreateFile`
   */
  createFile(
    parameters: {
      dataset?: ExpressionOrValue; // REQUIRED — Site Address — string — Example: `https://contoso.sharepoint.com/sites/sitename`.
      folderPath?: ExpressionOrValue; // REQUIRED — Folder Path — string — Must start with an existing library. Add folders if needed.
      name?: ExpressionOrValue; // REQUIRED — File Name — string — Name of the file.
      body?: ExpressionOrValue; // REQUIRED — File Content — binary — Content of the file.
    } & Record<string, ExpressionOrValue>,
    options?: ConnectorCallOptions,
  ): ActionSpec {
    return buildConnectorCall({
      kind: "action",
      apiId: API_ID,
      defaultConnectionName: DEFAULT_CONNECTION_NAME,
      operationId: "CreateFile",
      parameters: parameters as Record<string, ExpressionOrValue>,
      options,
    }) as ActionSpec;
  },

  /**
   * Create new document set
   * @returns The outputs of this operation are dynamic.
   * Operation id: `CreateNewDocumentSet`
   */
  createNewDocumentSet(
    parameters: {
      dataset?: ExpressionOrValue; // REQUIRED — Site Address — string — Example: `https://contoso.sharepoint.com/sites/sitename`.
      table?: ExpressionOrValue; // REQUIRED — Library — string — SharePoint library name.
      path?: ExpressionOrValue; // REQUIRED — Document Set Path — string — Example: folder1/folder2/dsName
      contentTypeId?: ExpressionOrValue; // REQUIRED — Content Type Id — string — Example: 0x0120D520
      DynamicProperties?: ExpressionOrValue; // optional — object
    } & Record<string, ExpressionOrValue>,
    options?: ConnectorCallOptions,
  ): ActionSpec {
    return buildConnectorCall({
      kind: "action",
      apiId: API_ID,
      defaultConnectionName: DEFAULT_CONNECTION_NAME,
      operationId: "CreateNewDocumentSet",
      parameters: parameters as Record<string, ExpressionOrValue>,
      options,
    }) as ActionSpec;
  },

  /**
   * Create new folder
   * @returns The outputs of this operation are dynamic.
   * Operation id: `CreateNewFolder`
   */
  createNewFolder(
    parameters: {
      dataset?: ExpressionOrValue; // REQUIRED — Site Address — string — Example: `https://contoso.sharepoint.com/sites/sitename`.
      table?: ExpressionOrValue; // REQUIRED — List or Library — string — SharePoint list or library name.
      path?: ExpressionOrValue; // REQUIRED — Folder Path — string — Example: folder1/folder2/folder3
      view?: ExpressionOrValue; // optional — Limit Columns by View — string — Avoid column threshold issues by only using columns defined in a view.
    } & Record<string, ExpressionOrValue>,
    options?: ConnectorCallOptions,
  ): ActionSpec {
    return buildConnectorCall({
      kind: "action",
      apiId: API_ID,
      defaultConnectionName: DEFAULT_CONNECTION_NAME,
      operationId: "CreateNewFolder",
      parameters: parameters as Record<string, ExpressionOrValue>,
      options,
    }) as ActionSpec;
  },

  /**
   * Create sharing link for a file or folder
   * @returns Internal structure for sharing links - Body - SharingLinkPermission
   * Operation id: `CreateSharingLink`
   */
  createSharingLink(
    parameters: {
      dataset?: ExpressionOrValue; // REQUIRED — Site Address — string — Example: `https://contoso.sharepoint.com/sites/sitename`.
      table?: ExpressionOrValue; // REQUIRED — Library Name — string — SharePoint library name.
      id?: ExpressionOrValue; // REQUIRED — Item Id — integer — Id of the file or folder item.
      "type"?: ExpressionOrValue; // REQUIRED — Link Type — string — The type of sharing link to create
      scope?: ExpressionOrValue; // REQUIRED — Link Scope — string — Choose who your sharing link gives access to. "Anyone" option will only work if your administrator has enabled it.
      expirationDateTime?: ExpressionOrValue; // optional — Link Expiration — date-time — The date after which the link will expire in yyyy-MM-dd format. Only applicable for anonymous links.
    } & Record<string, ExpressionOrValue>,
    options?: ConnectorCallOptions,
  ): ActionSpec {
    return buildConnectorCall({
      kind: "action",
      apiId: API_ID,
      defaultConnectionName: DEFAULT_CONNECTION_NAME,
      operationId: "CreateSharingLink",
      parameters: parameters as Record<string, ExpressionOrValue>,
      options,
    }) as ActionSpec;
  },

  /**
   * Delete attachment
   * Operation id: `DeleteAttachment`
   */
  deleteAttachment(
    parameters: {
      dataset?: ExpressionOrValue; // REQUIRED — Site Address — string — Example: `https://contoso.sharepoint.com/sites/sitename`.
      table?: ExpressionOrValue; // REQUIRED — List Name — string — SharePoint list name.
      itemId?: ExpressionOrValue; // REQUIRED — Id — integer — Id of the list item the file is attached to.
      attachmentId?: ExpressionOrValue; // REQUIRED — File Identifier — string — File identifier for the attachment.
    } & Record<string, ExpressionOrValue>,
    options?: ConnectorCallOptions,
  ): ActionSpec {
    return buildConnectorCall({
      kind: "action",
      apiId: API_ID,
      defaultConnectionName: DEFAULT_CONNECTION_NAME,
      operationId: "DeleteAttachment",
      parameters: parameters as Record<string, ExpressionOrValue>,
      options,
    }) as ActionSpec;
  },

  /**
   * Delete file
   * Operation id: `DeleteFile`
   */
  deleteFile(
    parameters: {
      dataset?: ExpressionOrValue; // REQUIRED — Site Address — string — Example: `https://contoso.sharepoint.com/sites/sitename`.
      id?: ExpressionOrValue; // REQUIRED — File Identifier — string — Select a file.
    } & Record<string, ExpressionOrValue>,
    options?: ConnectorCallOptions,
  ): ActionSpec {
    return buildConnectorCall({
      kind: "action",
      apiId: API_ID,
      defaultConnectionName: DEFAULT_CONNECTION_NAME,
      operationId: "DeleteFile",
      parameters: parameters as Record<string, ExpressionOrValue>,
      options,
    }) as ActionSpec;
  },

  /**
   * Delete item
   * Operation id: `DeleteItem`
   */
  deleteItem(
    parameters: {
      dataset?: ExpressionOrValue; // REQUIRED — Site Address — string — Example: `https://contoso.sharepoint.com/sites/sitename`
      table?: ExpressionOrValue; // REQUIRED — List Name — string — SharePoint list name
      id?: ExpressionOrValue; // REQUIRED — Id — integer — Unique identifier of item to be deleted
    } & Record<string, ExpressionOrValue>,
    options?: ConnectorCallOptions,
  ): ActionSpec {
    return buildConnectorCall({
      kind: "action",
      apiId: API_ID,
      defaultConnectionName: DEFAULT_CONNECTION_NAME,
      operationId: "DeleteItem",
      parameters: parameters as Record<string, ExpressionOrValue>,
      options,
    }) as ActionSpec;
  },

  /**
   * Discard check out
   * Operation id: `DiscardFileCheckOut`
   */
  discardFileCheckOut(
    parameters: {
      dataset?: ExpressionOrValue; // REQUIRED — Site Address — string — Example: `https://contoso.sharepoint.com/sites/sitename`.
      table?: ExpressionOrValue; // REQUIRED — Library Name — string — SharePoint library name.
      id?: ExpressionOrValue; // REQUIRED — Id — integer — Id of the list item the file is attached to.
    } & Record<string, ExpressionOrValue>,
    options?: ConnectorCallOptions,
  ): ActionSpec {
    return buildConnectorCall({
      kind: "action",
      apiId: API_ID,
      defaultConnectionName: DEFAULT_CONNECTION_NAME,
      operationId: "DiscardFileCheckOut",
      parameters: parameters as Record<string, ExpressionOrValue>,
      options,
    }) as ActionSpec;
  },

  /**
   * Extract folder
   * @returns - response - array of BlobMetadata
   * Operation id: `ExtractFolderV2`
   */
  extractFolderV2(
    parameters: {
      dataset?: ExpressionOrValue; // REQUIRED — Site Address — string — Example: `https://contoso.sharepoint.com/sites/sitename`.
      source?: ExpressionOrValue; // REQUIRED — Source File Path — string — Path to the source file.
      destination?: ExpressionOrValue; // REQUIRED — Destination Folder Path — string — Path to the destination folder.
      overwrite?: ExpressionOrValue; // optional — Overwrite Flag — boolean — Whether or not to overwrite the destination file if it exists.
    } & Record<string, ExpressionOrValue>,
    options?: ConnectorCallOptions,
  ): ActionSpec {
    return buildConnectorCall({
      kind: "action",
      apiId: API_ID,
      defaultConnectionName: DEFAULT_CONNECTION_NAME,
      operationId: "ExtractFolderV2",
      parameters: parameters as Record<string, ExpressionOrValue>,
      options,
    }) as ActionSpec;
  },

  /**
   * Get all lists and libraries
   * @returns Represents a list of tables. - Body - TablesList
   * Operation id: `GetAllTables`
   */
  getAllTables(
    parameters: {
      dataset?: ExpressionOrValue; // REQUIRED — Site Address — string — Example: `https://contoso.sharepoint.com/sites/sitename`.
    } & Record<string, ExpressionOrValue>,
    options?: ConnectorCallOptions,
  ): ActionSpec {
    return buildConnectorCall({
      kind: "action",
      apiId: API_ID,
      defaultConnectionName: DEFAULT_CONNECTION_NAME,
      operationId: "GetAllTables",
      parameters: parameters as Record<string, ExpressionOrValue>,
      options,
    }) as ActionSpec;
  },

  /**
   * Get attachment content
   * @returns The content of the attachment. - Attachment Content - binary
   * Operation id: `GetAttachmentContent`
   */
  getAttachmentContent(
    parameters: {
      dataset?: ExpressionOrValue; // REQUIRED — Site Address — string — Example: `https://contoso.sharepoint.com/sites/sitename`.
      table?: ExpressionOrValue; // REQUIRED — List Name — string — SharePoint list name.
      itemId?: ExpressionOrValue; // REQUIRED — Id — integer — Id of the list item the file is attached to.
      attachmentId?: ExpressionOrValue; // REQUIRED — File Identifier — string — File identifier for the attachment.
    } & Record<string, ExpressionOrValue>,
    options?: ConnectorCallOptions,
  ): ActionSpec {
    return buildConnectorCall({
      kind: "action",
      apiId: API_ID,
      defaultConnectionName: DEFAULT_CONNECTION_NAME,
      operationId: "GetAttachmentContent",
      parameters: parameters as Record<string, ExpressionOrValue>,
      options,
    }) as ActionSpec;
  },

  /**
   * Get file content
   * @returns The content of the file. - File Content - binary
   * Operation id: `GetFileContent`
   */
  getFileContent(
    parameters: {
      dataset?: ExpressionOrValue; // REQUIRED — Site Address — string — Example: `https://contoso.sharepoint.com/sites/sitename`.
      id?: ExpressionOrValue; // REQUIRED — File Identifier — string — Select a file.
      inferContentType?: ExpressionOrValue; // optional — Infer Content Type — boolean — Infer content-type based on extension.
    } & Record<string, ExpressionOrValue>,
    options?: ConnectorCallOptions,
  ): ActionSpec {
    return buildConnectorCall({
      kind: "action",
      apiId: API_ID,
      defaultConnectionName: DEFAULT_CONNECTION_NAME,
      operationId: "GetFileContent",
      parameters: parameters as Record<string, ExpressionOrValue>,
      options,
    }) as ActionSpec;
  },

  /**
   * Get file content using path
   * @returns The content of the file. - File Content - binary
   * Operation id: `GetFileContentByPath`
   */
  getFileContentByPath(
    parameters: {
      dataset?: ExpressionOrValue; // REQUIRED — Site Address — string — Example: `https://contoso.sharepoint.com/sites/sitename`.
      path?: ExpressionOrValue; // REQUIRED — File Path — string — Select a file.
      inferContentType?: ExpressionOrValue; // optional — Infer Content Type — boolean — Infer content-type based on extension.
    } & Record<string, ExpressionOrValue>,
    options?: ConnectorCallOptions,
  ): ActionSpec {
    return buildConnectorCall({
      kind: "action",
      apiId: API_ID,
      defaultConnectionName: DEFAULT_CONNECTION_NAME,
      operationId: "GetFileContentByPath",
      parameters: parameters as Record<string, ExpressionOrValue>,
      options,
    }) as ActionSpec;
  },

  /**
   * Get file properties
   * @returns The outputs of this operation are dynamic.
   * Operation id: `GetFileItem`
   */
  getFileItem(
    parameters: {
      dataset?: ExpressionOrValue; // REQUIRED — Site Address — string — Example: `https://contoso.sharepoint.com/sites/sitename`
      table?: ExpressionOrValue; // REQUIRED — Library Name — string — SharePoint library name
      id?: ExpressionOrValue; // REQUIRED — Id — integer — Unique identifier of item to be retrieved
      view?: ExpressionOrValue; // optional — Limit Columns by View — string — Avoid column threshold issues by only using columns defined in a view
    } & Record<string, ExpressionOrValue>,
    options?: ConnectorCallOptions,
  ): ActionSpec {
    return buildConnectorCall({
      kind: "action",
      apiId: API_ID,
      defaultConnectionName: DEFAULT_CONNECTION_NAME,
      operationId: "GetFileItem",
      parameters: parameters as Record<string, ExpressionOrValue>,
      options,
    }) as ActionSpec;
  },

  /**
   * Get files (properties only)
   * @returns The outputs of this operation are dynamic.
   * Operation id: `GetFileItems`
   */
  getFileItems(
    parameters: {
      dataset?: ExpressionOrValue; // REQUIRED — Site Address — string — Example: `https://contoso.sharepoint.com/sites/sitename`
      table?: ExpressionOrValue; // REQUIRED — Library Name — string — SharePoint library name
      $filter?: ExpressionOrValue; // optional — Filter Query — string — An ODATA filter query to restrict the entries returned (e.g. stringColumn eq 'string' OR numberColumn lt 123).
      $orderby?: ExpressionOrValue; // optional — Order By — string — An ODATA orderBy query for specifying the order of entries.
      $top?: ExpressionOrValue; // optional — Top Count — integer — Total number of entries to retrieve (default = all).
      folderPath?: ExpressionOrValue; // optional — Limit Entries to Folder — string — Select a folder, or leave blank for the whole library
      viewScopeOption?: ExpressionOrValue; // optional — Include Nested Items — string — Return entries contained in sub-folders (default = true)
      view?: ExpressionOrValue; // optional — Limit Columns by View — string — Avoid column threshold issues by only using columns defined in a view
    } & Record<string, ExpressionOrValue>,
    options?: ConnectorCallOptions,
  ): ActionSpec {
    return buildConnectorCall({
      kind: "action",
      apiId: API_ID,
      defaultConnectionName: DEFAULT_CONNECTION_NAME,
      operationId: "GetFileItems",
      parameters: parameters as Record<string, ExpressionOrValue>,
      options,
    }) as ActionSpec;
  },

  /**
   * Get file metadata
   * @returns The SharePoint version of the BlobMetadataResponse extends the object by adding some additional fields that we want serialized - Body - SPBlobMetadataResponse
   * Operation id: `GetFileMetadata`
   */
  getFileMetadata(
    parameters: {
      dataset?: ExpressionOrValue; // REQUIRED — Site Address — string — Example: `https://contoso.sharepoint.com/sites/sitename`.
      id?: ExpressionOrValue; // REQUIRED — File Identifier — string — Select a file.
    } & Record<string, ExpressionOrValue>,
    options?: ConnectorCallOptions,
  ): ActionSpec {
    return buildConnectorCall({
      kind: "action",
      apiId: API_ID,
      defaultConnectionName: DEFAULT_CONNECTION_NAME,
      operationId: "GetFileMetadata",
      parameters: parameters as Record<string, ExpressionOrValue>,
      options,
    }) as ActionSpec;
  },

  /**
   * Get file metadata using path
   * @returns The SharePoint version of the BlobMetadataResponse extends the object by adding some additional fields that we want serialized - Body - SPBlobMetadataResponse
   * Operation id: `GetFileMetadataByPath`
   */
  getFileMetadataByPath(
    parameters: {
      dataset?: ExpressionOrValue; // REQUIRED — Site Address — string — Example: `https://contoso.sharepoint.com/sites/sitename`.
      path?: ExpressionOrValue; // REQUIRED — File Path — string — Select a file.
    } & Record<string, ExpressionOrValue>,
    options?: ConnectorCallOptions,
  ): ActionSpec {
    return buildConnectorCall({
      kind: "action",
      apiId: API_ID,
      defaultConnectionName: DEFAULT_CONNECTION_NAME,
      operationId: "GetFileMetadataByPath",
      parameters: parameters as Record<string, ExpressionOrValue>,
      options,
    }) as ActionSpec;
  },

  /**
   * Get folder metadata
   * @returns The SharePoint version of the BlobMetadataResponse extends the object by adding some additional fields that we want serialized - Body - SPBlobMetadataResponse
   * Operation id: `GetFolderMetadata`
   */
  getFolderMetadata(
    parameters: {
      dataset?: ExpressionOrValue; // REQUIRED — Site Address — string — Example: `https://contoso.sharepoint.com/sites/sitename`.
      id?: ExpressionOrValue; // REQUIRED — File Identifier — string — Select a folder.
    } & Record<string, ExpressionOrValue>,
    options?: ConnectorCallOptions,
  ): ActionSpec {
    return buildConnectorCall({
      kind: "action",
      apiId: API_ID,
      defaultConnectionName: DEFAULT_CONNECTION_NAME,
      operationId: "GetFolderMetadata",
      parameters: parameters as Record<string, ExpressionOrValue>,
      options,
    }) as ActionSpec;
  },

  /**
   * Get folder metadata using path
   * @returns The SharePoint version of the BlobMetadataResponse extends the object by adding some additional fields that we want serialized - Body - SPBlobMetadataResponse
   * Operation id: `GetFolderMetadataByPath`
   */
  getFolderMetadataByPath(
    parameters: {
      dataset?: ExpressionOrValue; // REQUIRED — Site Address — string — Example: `https://contoso.sharepoint.com/sites/sitename`.
      path?: ExpressionOrValue; // REQUIRED — Folder Path — string — Select a folder.
    } & Record<string, ExpressionOrValue>,
    options?: ConnectorCallOptions,
  ): ActionSpec {
    return buildConnectorCall({
      kind: "action",
      apiId: API_ID,
      defaultConnectionName: DEFAULT_CONNECTION_NAME,
      operationId: "GetFolderMetadataByPath",
      parameters: parameters as Record<string, ExpressionOrValue>,
      options,
    }) as ActionSpec;
  },

  /**
   * Get item
   * @returns The outputs of this operation are dynamic.
   * Operation id: `GetItem`
   */
  getItem(
    parameters: {
      dataset?: ExpressionOrValue; // REQUIRED — Site Address — string — Example: `https://contoso.sharepoint.com/sites/sitename`
      table?: ExpressionOrValue; // REQUIRED — List Name — string — SharePoint list name
      id?: ExpressionOrValue; // REQUIRED — Id — integer — Unique identifier of item to be retrieved
      view?: ExpressionOrValue; // optional — Limit Columns by View — string — Avoid column threshold issues by only using columns defined in a view
    } & Record<string, ExpressionOrValue>,
    options?: ConnectorCallOptions,
  ): ActionSpec {
    return buildConnectorCall({
      kind: "action",
      apiId: API_ID,
      defaultConnectionName: DEFAULT_CONNECTION_NAME,
      operationId: "GetItem",
      parameters: parameters as Record<string, ExpressionOrValue>,
      options,
    }) as ActionSpec;
  },

  /**
   * Get attachments
   * @returns - response - array of SPListItemAttachment
   * Operation id: `GetItemAttachments`
   */
  getItemAttachments(
    parameters: {
      dataset?: ExpressionOrValue; // REQUIRED — Site Address — string — Example: `https://contoso.sharepoint.com/sites/sitename`.
      table?: ExpressionOrValue; // REQUIRED — List Name — string — SharePoint list name.
      itemId?: ExpressionOrValue; // REQUIRED — Id — string — Id of the list item to get attachments from.
    } & Record<string, ExpressionOrValue>,
    options?: ConnectorCallOptions,
  ): ActionSpec {
    return buildConnectorCall({
      kind: "action",
      apiId: API_ID,
      defaultConnectionName: DEFAULT_CONNECTION_NAME,
      operationId: "GetItemAttachments",
      parameters: parameters as Record<string, ExpressionOrValue>,
      options,
    }) as ActionSpec;
  },

  /**
   * Get changes for an item or a file (properties only)
   * @returns The outputs of this operation are dynamic.
   * Operation id: `GetItemChanges`
   */
  getItemChanges(
    parameters: {
      dataset?: ExpressionOrValue; // REQUIRED — Site Address — string — Example: `https://contoso.sharepoint.com/sites/sitename`.
      table?: ExpressionOrValue; // REQUIRED — List or Library Name — string — SharePoint list or library name.
      id?: ExpressionOrValue; // REQUIRED — Id — integer — Id of the item you want to fetch changes for.
      since?: ExpressionOrValue; // REQUIRED — Since — string — Trigger Window Start token or an item version label (ex: 3.0) or an ISO 8601 date (YYYY-MM-DDThh:mmZ).
      until?: ExpressionOrValue; // optional — Until — string — Trigger Window End token or an item version label (ex: 3.0) or an ISO 8601 date (YYYY-MM-DDThh:mmZ). If blank, defaults 
      includeDrafts?: ExpressionOrValue; // optional — Include Minor Versions — boolean — Boolean for whether to consider changes from minor (draft) versions.
      view?: ExpressionOrValue; // optional — Limit Columns by View — string — Returns only columns defined in a view.
    } & Record<string, ExpressionOrValue>,
    options?: ConnectorCallOptions,
  ): ActionSpec {
    return buildConnectorCall({
      kind: "action",
      apiId: API_ID,
      defaultConnectionName: DEFAULT_CONNECTION_NAME,
      operationId: "GetItemChanges",
      parameters: parameters as Record<string, ExpressionOrValue>,
      options,
    }) as ActionSpec;
  },

  /**
   * Get items
   * @returns The outputs of this operation are dynamic.
   * Operation id: `GetItems`
   */
  getItems(
    parameters: {
      dataset?: ExpressionOrValue; // REQUIRED — Site Address — string — Example: `https://contoso.sharepoint.com/sites/sitename`
      table?: ExpressionOrValue; // REQUIRED — List Name — string — SharePoint list name
      $filter?: ExpressionOrValue; // optional — Filter Query — string — An ODATA filter query to restrict the entries returned (e.g. stringColumn eq 'string' OR numberColumn lt 123).
      $orderby?: ExpressionOrValue; // optional — Order By — string — An ODATA orderBy query for specifying the order of entries.
      $top?: ExpressionOrValue; // optional — Top Count — integer — Total number of entries to retrieve (default = all).
      folderPath?: ExpressionOrValue; // optional — Limit Entries to Folder — string — Select a folder, or leave blank for the whole list
      viewScopeOption?: ExpressionOrValue; // optional — Include Nested Items — string — Return entries contained in sub-folders (default = true)
      view?: ExpressionOrValue; // optional — Limit Columns by View — string — Avoid column threshold issues by only using columns defined in a view
    } & Record<string, ExpressionOrValue>,
    options?: ConnectorCallOptions,
  ): ActionSpec {
    return buildConnectorCall({
      kind: "action",
      apiId: API_ID,
      defaultConnectionName: DEFAULT_CONNECTION_NAME,
      operationId: "GetItems",
      parameters: parameters as Record<string, ExpressionOrValue>,
      options,
    }) as ActionSpec;
  },

  /**
   * When an item or a file is modified
   * @remarks This is a trigger operation; pass it to flowBuilder.setTrigger().
   * @returns The outputs of this operation are dynamic.
   * Operation id: `GetOnChangedItems`
   */
  getOnChangedItems(
    parameters: {
      dataset?: ExpressionOrValue; // REQUIRED — Site Address — string — Example: `https://contoso.sharepoint.com/sites/sitename`
      table?: ExpressionOrValue; // REQUIRED — List or Library Name — string — SharePoint list name
      folderPath?: ExpressionOrValue; // optional — Folder — string — Select a folder, or leave blank for the whole library
      view?: ExpressionOrValue; // optional — Limit Columns by View — string — Avoid column threshold issues by only using columns defined in a view
    } & Record<string, ExpressionOrValue>,
    options?: ConnectorCallOptions,
  ): TriggerSpec {
    return buildConnectorCall({
      kind: "trigger",
      apiId: API_ID,
      defaultConnectionName: DEFAULT_CONNECTION_NAME,
      operationId: "GetOnChangedItems",
      parameters: parameters as Record<string, ExpressionOrValue>,
      options,
    }) as TriggerSpec;
  },

  /**
   * When a file is deleted
   * @remarks This is a trigger operation; pass it to flowBuilder.setTrigger().
   * @returns List of Deleted items - Body - DeletedItemList
   * Operation id: `GetOnDeletedFileItems`
   */
  getOnDeletedFileItems(
    parameters: {
      dataset?: ExpressionOrValue; // REQUIRED — Site Address — string — Example: `https://contoso.sharepoint.com/sites/sitename`
      table?: ExpressionOrValue; // REQUIRED — Library Name — string — SharePoint library name
      folderPath?: ExpressionOrValue; // optional — Folder — string — Select a folder, or leave blank for the whole library
    } & Record<string, ExpressionOrValue>,
    options?: ConnectorCallOptions,
  ): TriggerSpec {
    return buildConnectorCall({
      kind: "trigger",
      apiId: API_ID,
      defaultConnectionName: DEFAULT_CONNECTION_NAME,
      operationId: "GetOnDeletedFileItems",
      parameters: parameters as Record<string, ExpressionOrValue>,
      options,
    }) as TriggerSpec;
  },

  /**
   * When an item is deleted
   * @remarks This is a trigger operation; pass it to flowBuilder.setTrigger().
   * @returns List of Deleted items - Body - DeletedItemList
   * Operation id: `GetOnDeletedItems`
   */
  getOnDeletedItems(
    parameters: {
      dataset?: ExpressionOrValue; // REQUIRED — Site Address — string — Example: `https://contoso.sharepoint.com/sites/sitename`
      table?: ExpressionOrValue; // REQUIRED — List Name — string — SharePoint list name
    } & Record<string, ExpressionOrValue>,
    options?: ConnectorCallOptions,
  ): TriggerSpec {
    return buildConnectorCall({
      kind: "trigger",
      apiId: API_ID,
      defaultConnectionName: DEFAULT_CONNECTION_NAME,
      operationId: "GetOnDeletedItems",
      parameters: parameters as Record<string, ExpressionOrValue>,
      options,
    }) as TriggerSpec;
  },

  /**
   * When a file is created (properties only)
   * @remarks This is a trigger operation; pass it to flowBuilder.setTrigger().
   * @returns The outputs of this operation are dynamic.
   * Operation id: `GetOnNewFileItems`
   */
  getOnNewFileItems(
    parameters: {
      dataset?: ExpressionOrValue; // REQUIRED — Site Address — string — Example: `https://contoso.sharepoint.com/sites/sitename`
      table?: ExpressionOrValue; // REQUIRED — Library Name — string — SharePoint library name
      folderPath?: ExpressionOrValue; // optional — Folder — string — Select a folder, or leave blank for the whole library
      view?: ExpressionOrValue; // optional — Limit Columns by View — string — Avoid column threshold issues by only using columns defined in a view
    } & Record<string, ExpressionOrValue>,
    options?: ConnectorCallOptions,
  ): TriggerSpec {
    return buildConnectorCall({
      kind: "trigger",
      apiId: API_ID,
      defaultConnectionName: DEFAULT_CONNECTION_NAME,
      operationId: "GetOnNewFileItems",
      parameters: parameters as Record<string, ExpressionOrValue>,
      options,
    }) as TriggerSpec;
  },

  /**
   * When an item is created
   * @remarks This is a trigger operation; pass it to flowBuilder.setTrigger().
   * @returns The outputs of this operation are dynamic.
   * Operation id: `GetOnNewItems`
   */
  getOnNewItems(
    parameters: {
      dataset?: ExpressionOrValue; // REQUIRED — Site Address — string — Example: `https://contoso.sharepoint.com/sites/sitename`
      table?: ExpressionOrValue; // REQUIRED — List Name — string — SharePoint list name
      view?: ExpressionOrValue; // optional — Limit Columns by View — string — Avoid column threshold issues by only using columns defined in a view
    } & Record<string, ExpressionOrValue>,
    options?: ConnectorCallOptions,
  ): TriggerSpec {
    return buildConnectorCall({
      kind: "trigger",
      apiId: API_ID,
      defaultConnectionName: DEFAULT_CONNECTION_NAME,
      operationId: "GetOnNewItems",
      parameters: parameters as Record<string, ExpressionOrValue>,
      options,
    }) as TriggerSpec;
  },

  /**
   * When a form is submitted (preview)
   * @remarks This is a trigger operation; pass it to flowBuilder.setTrigger().
   * @returns The outputs of this operation are dynamic.
   * Operation id: `GetOnNewItemsFromForm`
   */
  getOnNewItemsFromForm(
    parameters: {
      dataset?: ExpressionOrValue; // REQUIRED — Site Address — string — Example: `https://contoso.sharepoint.com/sites/sitename`
      table?: ExpressionOrValue; // REQUIRED — List or Library Name — string — SharePoint list or library name
      form?: ExpressionOrValue; // REQUIRED — Form Name — string — Form identifier
      view?: ExpressionOrValue; // optional — Limit Columns by View — string — Avoid column threshold issues by only using columns defined in a view
    } & Record<string, ExpressionOrValue>,
    options?: ConnectorCallOptions,
  ): TriggerSpec {
    return buildConnectorCall({
      kind: "trigger",
      apiId: API_ID,
      defaultConnectionName: DEFAULT_CONNECTION_NAME,
      operationId: "GetOnNewItemsFromForm",
      parameters: parameters as Record<string, ExpressionOrValue>,
      options,
    }) as TriggerSpec;
  },

  /**
   * When a file is classified by a Microsoft Syntex model
   * @remarks This is a trigger operation; pass it to flowBuilder.setTrigger().
   * @returns The outputs of this operation are dynamic.
   * Operation id: `GetOnUpdatedFileClassifiedTimes`
   */
  getOnUpdatedFileClassifiedTimes(
    parameters: {
      dataset?: ExpressionOrValue; // REQUIRED — Site Address — string — Example: `https://contoso.sharepoint.com/sites/sitename`
      table?: ExpressionOrValue; // REQUIRED — Library Name — string — SharePoint library name
      folderPath?: ExpressionOrValue; // optional — Folder — string — Select a folder, or leave blank for the whole library
      view?: ExpressionOrValue; // optional — Limit Columns by View — string — Avoid column threshold issues by only using columns defined in a view
    } & Record<string, ExpressionOrValue>,
    options?: ConnectorCallOptions,
  ): TriggerSpec {
    return buildConnectorCall({
      kind: "trigger",
      apiId: API_ID,
      defaultConnectionName: DEFAULT_CONNECTION_NAME,
      operationId: "GetOnUpdatedFileClassifiedTimes",
      parameters: parameters as Record<string, ExpressionOrValue>,
      options,
    }) as TriggerSpec;
  },

  /**
   * When a file is created or modified (properties only)
   * @remarks This is a trigger operation; pass it to flowBuilder.setTrigger().
   * @returns The outputs of this operation are dynamic.
   * Operation id: `GetOnUpdatedFileItems`
   */
  getOnUpdatedFileItems(
    parameters: {
      dataset?: ExpressionOrValue; // REQUIRED — Site Address — string — Example: `https://contoso.sharepoint.com/sites/sitename`
      table?: ExpressionOrValue; // REQUIRED — Library Name — string — SharePoint library name
      folderPath?: ExpressionOrValue; // optional — Folder — string — Select a folder, or leave blank for the whole library
      view?: ExpressionOrValue; // optional — Limit Columns by View — string — Avoid column threshold issues by only using columns defined in a view
    } & Record<string, ExpressionOrValue>,
    options?: ConnectorCallOptions,
  ): TriggerSpec {
    return buildConnectorCall({
      kind: "trigger",
      apiId: API_ID,
      defaultConnectionName: DEFAULT_CONNECTION_NAME,
      operationId: "GetOnUpdatedFileItems",
      parameters: parameters as Record<string, ExpressionOrValue>,
      options,
    }) as TriggerSpec;
  },

  /**
   * When an item is created or modified
   * @remarks This is a trigger operation; pass it to flowBuilder.setTrigger().
   * @returns The outputs of this operation are dynamic.
   * Operation id: `GetOnUpdatedItems`
   */
  getOnUpdatedItems(
    parameters: {
      dataset?: ExpressionOrValue; // REQUIRED — Site Address — string — Example: `https://contoso.sharepoint.com/sites/sitename`
      table?: ExpressionOrValue; // REQUIRED — List Name — string — SharePoint list name
      view?: ExpressionOrValue; // optional — Limit Columns by View — string — Avoid column threshold issues by only using columns defined in a view
    } & Record<string, ExpressionOrValue>,
    options?: ConnectorCallOptions,
  ): TriggerSpec {
    return buildConnectorCall({
      kind: "trigger",
      apiId: API_ID,
      defaultConnectionName: DEFAULT_CONNECTION_NAME,
      operationId: "GetOnUpdatedItems",
      parameters: parameters as Record<string, ExpressionOrValue>,
      options,
    }) as TriggerSpec;
  },

  /**
   * Get form metadata (preview)
   * @returns Represents a table form with its metadata - Body - TableForm
   * Operation id: `GetTableForm`
   */
  getTableForm(
    parameters: {
      dataset?: ExpressionOrValue; // REQUIRED — Site Address — string — Example: `https://contoso.sharepoint.com/sites/sitename`.
      table?: ExpressionOrValue; // REQUIRED — List or Library Name — string — SharePoint list name.
      form?: ExpressionOrValue; // REQUIRED — Form Name — string — Form identifier.
    } & Record<string, ExpressionOrValue>,
    options?: ConnectorCallOptions,
  ): ActionSpec {
    return buildConnectorCall({
      kind: "action",
      apiId: API_ID,
      defaultConnectionName: DEFAULT_CONNECTION_NAME,
      operationId: "GetTableForm",
      parameters: parameters as Record<string, ExpressionOrValue>,
      options,
    }) as ActionSpec;
  },

  /**
   * Get list views
   * @returns - List of Tables - array of Table
   * Operation id: `GetTableViews`
   */
  getTableViews(
    parameters: {
      dataset?: ExpressionOrValue; // REQUIRED — Site Address — string — Example: `https://contoso.sharepoint.com/sites/sitename`.
      table?: ExpressionOrValue; // REQUIRED — List Name — string — SharePoint list name.
    } & Record<string, ExpressionOrValue>,
    options?: ConnectorCallOptions,
  ): ActionSpec {
    return buildConnectorCall({
      kind: "action",
      apiId: API_ID,
      defaultConnectionName: DEFAULT_CONNECTION_NAME,
      operationId: "GetTableViews",
      parameters: parameters as Record<string, ExpressionOrValue>,
      options,
    }) as ActionSpec;
  },

  /**
   * Get lists
   * @returns Represents a list of tables. - Body - TablesList
   * Operation id: `GetTables`
   */
  getTables(
    parameters: {
      dataset?: ExpressionOrValue; // REQUIRED — Site Address — string — Example: `https://contoso.sharepoint.com/sites/sitename`
    } & Record<string, ExpressionOrValue>,
    options?: ConnectorCallOptions,
  ): ActionSpec {
    return buildConnectorCall({
      kind: "action",
      apiId: API_ID,
      defaultConnectionName: DEFAULT_CONNECTION_NAME,
      operationId: "GetTables",
      parameters: parameters as Record<string, ExpressionOrValue>,
      options,
    }) as ActionSpec;
  },

  /**
   * Grant access to an item or a folder
   * Operation id: `GrantAccess`
   */
  grantAccess(
    parameters: {
      dataset?: ExpressionOrValue; // REQUIRED — Site Address — string — Example: `https://contoso.sharepoint.com/sites/sitename`.
      table?: ExpressionOrValue; // REQUIRED — List or Library Name — string — SharePoint list or library name.
      id?: ExpressionOrValue; // REQUIRED — Id — integer — Unique identifier of the item or folder you want to grant access to.
      recipients?: ExpressionOrValue; // REQUIRED — Recipients — email — A collection of recipients who will receive the sharing invitation
      roleValue?: ExpressionOrValue; // REQUIRED — Roles — string — Specify a role that is to be granted to the recipients
      emailBody?: ExpressionOrValue; // optional — Message — string — A plain text formatted message that is included in the sharing invitation
      sendEmail?: ExpressionOrValue; // optional — Notify Recipients — boolean — Specify whether recipients should receive an email notification message
    } & Record<string, ExpressionOrValue>,
    options?: ConnectorCallOptions,
  ): ActionSpec {
    return buildConnectorCall({
      kind: "action",
      apiId: API_ID,
      defaultConnectionName: DEFAULT_CONNECTION_NAME,
      operationId: "GrantAccess",
      parameters: parameters as Record<string, ExpressionOrValue>,
      options,
    }) as ActionSpec;
  },

  /**
   * Send an HTTP request to SharePoint
   * Operation id: `HttpRequest`
   */
  httpRequest(
    parameters: {
      dataset?: ExpressionOrValue; // REQUIRED — Site Address — string — Example: `https://contoso.sharepoint.com/sites/sitename`.
      method?: ExpressionOrValue; // REQUIRED — Method — string — Http Method
      uri?: ExpressionOrValue; // REQUIRED — Uri — string — Example: _api/web/lists/getbytitle('Documents')
      headers?: ExpressionOrValue; // optional — Headers — object — Enter JSON object of request headers
      body?: ExpressionOrValue; // optional — Body — string — Enter request content in JSON
    } & Record<string, ExpressionOrValue>,
    options?: ConnectorCallOptions,
  ): ActionSpec {
    return buildConnectorCall({
      kind: "action",
      apiId: API_ID,
      defaultConnectionName: DEFAULT_CONNECTION_NAME,
      operationId: "HttpRequest",
      parameters: parameters as Record<string, ExpressionOrValue>,
      options,
    }) as ActionSpec;
  },

  /**
   * Join hub site
   * Operation id: `JoinHubSite`
   */
  joinHubSite(
    parameters: {
      dataset?: ExpressionOrValue; // REQUIRED — Requesting Site Address — string — Example: `https://contoso.sharepoint.com/sites/sitename`.
      hubSiteId?: ExpressionOrValue; // REQUIRED — Hub Site Id — string — Id of the hub site.
      approvalToken?: ExpressionOrValue; // optional — Approval Token — string — Approval token for this request.
      approvalCorrelationId?: ExpressionOrValue; // optional — Approval Correlation Id — string — Approval correlation identifier for this request.
    } & Record<string, ExpressionOrValue>,
    options?: ConnectorCallOptions,
  ): ActionSpec {
    return buildConnectorCall({
      kind: "action",
      apiId: API_ID,
      defaultConnectionName: DEFAULT_CONNECTION_NAME,
      operationId: "JoinHubSite",
      parameters: parameters as Record<string, ExpressionOrValue>,
      options,
    }) as ActionSpec;
  },

  /**
   * List folder
   * @returns - response - array of BlobMetadata
   * Operation id: `ListFolder`
   */
  listFolder(
    parameters: {
      dataset?: ExpressionOrValue; // REQUIRED — Site Address — string — Example: `https://contoso.sharepoint.com/sites/sitename`.
      id?: ExpressionOrValue; // REQUIRED — File Identifier — string — Unique identifier of the folder.
    } & Record<string, ExpressionOrValue>,
    options?: ConnectorCallOptions,
  ): ActionSpec {
    return buildConnectorCall({
      kind: "action",
      apiId: API_ID,
      defaultConnectionName: DEFAULT_CONNECTION_NAME,
      operationId: "ListFolder",
      parameters: parameters as Record<string, ExpressionOrValue>,
      options,
    }) as ActionSpec;
  },

  /**
   * List root folder
   * @returns - response - array of BlobMetadata
   * Operation id: `ListRootFolder`
   */
  listRootFolder(
    parameters: {
      dataset?: ExpressionOrValue; // REQUIRED — Site Address — string — Example: `https://contoso.sharepoint.com/sites/sitename`.
    } & Record<string, ExpressionOrValue>,
    options?: ConnectorCallOptions,
  ): ActionSpec {
    return buildConnectorCall({
      kind: "action",
      apiId: API_ID,
      defaultConnectionName: DEFAULT_CONNECTION_NAME,
      operationId: "ListRootFolder",
      parameters: parameters as Record<string, ExpressionOrValue>,
      options,
    }) as ActionSpec;
  },

  /**
   * Move file
   * @returns The SharePoint version of the BlobMetadataResponse extends the object by adding some additional fields that we want serialized - Body - SPBlobMetadataResponse
   * Operation id: `MoveFileAsync`
   */
  moveFileAsync(
    parameters: {
      dataset?: ExpressionOrValue; // REQUIRED — Current Site Address — string — Example: `https://contoso.sharepoint.com/sites/sitename`.
      sourceFileId?: ExpressionOrValue; // REQUIRED — File to Move — string — File Identifier
      destinationDataset?: ExpressionOrValue; // REQUIRED — Destination Site Address — string — Example: `https://contoso.sharepoint.com/sites/sitename`
      destinationFolderPath?: ExpressionOrValue; // REQUIRED — Destination Folder — string — Destination Folder
      nameConflictBehavior?: ExpressionOrValue; // REQUIRED — If another file is already there — integer — Pick one of the options available
    } & Record<string, ExpressionOrValue>,
    options?: ConnectorCallOptions,
  ): ActionSpec {
    return buildConnectorCall({
      kind: "action",
      apiId: API_ID,
      defaultConnectionName: DEFAULT_CONNECTION_NAME,
      operationId: "MoveFileAsync",
      parameters: parameters as Record<string, ExpressionOrValue>,
      options,
    }) as ActionSpec;
  },

  /**
   * Move folder
   * @returns The SharePoint version of the BlobMetadataResponse extends the object by adding some additional fields that we want serialized - Body - SPBlobMetadataResponse
   * Operation id: `MoveFolderAsync`
   */
  moveFolderAsync(
    parameters: {
      dataset?: ExpressionOrValue; // REQUIRED — Current Site Address — string — Example: `https://contoso.sharepoint.com/sites/sitename`.
      sourceFolderId?: ExpressionOrValue; // REQUIRED — Folder to Move — string — File Identifier
      destinationDataset?: ExpressionOrValue; // REQUIRED — Destination Site Address — string — Example: `https://contoso.sharepoint.com/sites/sitename`
      destinationFolderPath?: ExpressionOrValue; // REQUIRED — Destination Folder — string — Destination Folder
      nameConflictBehavior?: ExpressionOrValue; // REQUIRED — If another folder is already there — integer — Pick one of the options available
    } & Record<string, ExpressionOrValue>,
    options?: ConnectorCallOptions,
  ): ActionSpec {
    return buildConnectorCall({
      kind: "action",
      apiId: API_ID,
      defaultConnectionName: DEFAULT_CONNECTION_NAME,
      operationId: "MoveFolderAsync",
      parameters: parameters as Record<string, ExpressionOrValue>,
      options,
    }) as ActionSpec;
  },

  /**
   * Set hub site join status to pending
   * Operation id: `NotifyHubSiteJoinApprovalStarted`
   */
  notifyHubSiteJoinApprovalStarted(
    parameters: {
      dataset?: ExpressionOrValue; // REQUIRED — Requesting Site Address — string — Example: `https://contoso.sharepoint.com/sites/sitename`.
      approvalCorrelationId?: ExpressionOrValue; // optional — Approval Correlation Id — string — Approval correlation identifier for this request.
    } & Record<string, ExpressionOrValue>,
    options?: ConnectorCallOptions,
  ): ActionSpec {
    return buildConnectorCall({
      kind: "action",
      apiId: API_ID,
      defaultConnectionName: DEFAULT_CONNECTION_NAME,
      operationId: "NotifyHubSiteJoinApprovalStarted",
      parameters: parameters as Record<string, ExpressionOrValue>,
      options,
    }) as ActionSpec;
  },

  /**
   * For a selected file
   * @remarks This is a trigger operation; pass it to flowBuilder.setTrigger().
   * @returns | Name | Path | Type | Description | | --- | --- | --- | --- | | rows | body.rows | array of object |  | | ID | body.rows.ID | integer | File Identifier |
   * Operation id: `OnFileSelected`
   */
  onFileSelected(
    parameters: {
      operationId?: ExpressionOrValue; // REQUIRED — string
      parameters?: ExpressionOrValue; // REQUIRED — object
      schema?: ExpressionOrValue; // REQUIRED — object
      host?: ExpressionOrValue; // optional — object
      headersSchema?: ExpressionOrValue; // optional — object
    } & Record<string, ExpressionOrValue>,
    options?: ConnectorCallOptions,
  ): TriggerSpec {
    return buildConnectorCall({
      kind: "trigger",
      apiId: API_ID,
      defaultConnectionName: DEFAULT_CONNECTION_NAME,
      operationId: "OnFileSelected",
      parameters: parameters as Record<string, ExpressionOrValue>,
      options,
    }) as TriggerSpec;
  },

  /**
   * When a site has requested to join a hub site
   * @remarks This is a trigger operation; pass it to flowBuilder.setTrigger().
   * @returns | Name | Path | Type | Description | | --- | --- | --- | --- | | rows | body.rows | array of object |  | | RequestingSiteUrl | body.rows.RequestingSiteUrl | string | Requesting Site Url |
   * Operation id: `OnHubSiteJoinApproval`
   */
  onHubSiteJoinApproval(
    parameters: {
      operationId?: ExpressionOrValue; // REQUIRED — string
      parameters?: ExpressionOrValue; // REQUIRED — object
      schema?: ExpressionOrValue; // REQUIRED — object
      host?: ExpressionOrValue; // optional — object
      headersSchema?: ExpressionOrValue; // optional — object
    } & Record<string, ExpressionOrValue>,
    options?: ConnectorCallOptions,
  ): TriggerSpec {
    return buildConnectorCall({
      kind: "trigger",
      apiId: API_ID,
      defaultConnectionName: DEFAULT_CONNECTION_NAME,
      operationId: "OnHubSiteJoinApproval",
      parameters: parameters as Record<string, ExpressionOrValue>,
      options,
    }) as TriggerSpec;
  },

  /**
   * For a selected item
   * @remarks This is a trigger operation; pass it to flowBuilder.setTrigger().
   * @returns | Name | Path | Type | Description | | --- | --- | --- | --- | | rows | body.rows | array of object |  | | ID | body.rows.ID | integer | File Identifier |
   * Operation id: `OnItemSelected`
   */
  onItemSelected(
    parameters: {
      operationId?: ExpressionOrValue; // REQUIRED — string
      parameters?: ExpressionOrValue; // REQUIRED — object
      schema?: ExpressionOrValue; // REQUIRED — object
      host?: ExpressionOrValue; // optional — object
      headersSchema?: ExpressionOrValue; // optional — object
    } & Record<string, ExpressionOrValue>,
    options?: ConnectorCallOptions,
  ): TriggerSpec {
    return buildConnectorCall({
      kind: "trigger",
      apiId: API_ID,
      defaultConnectionName: DEFAULT_CONNECTION_NAME,
      operationId: "OnItemSelected",
      parameters: parameters as Record<string, ExpressionOrValue>,
      options,
    }) as TriggerSpec;
  },

  /**
   * When a file is created in a folder (deprecated)
   * @remarks This is a trigger operation; pass it to flowBuilder.setTrigger().
   * @returns The content of the file. - File Content - binary
   * Operation id: `OnNewFile`
   */
  onNewFile(
    parameters: {
      dataset?: ExpressionOrValue; // REQUIRED — Site Address — string — Example: `https://contoso.sharepoint.com/sites/sitename`.
      folderId?: ExpressionOrValue; // REQUIRED — Folder Id — string — Select a folder.
      inferContentType?: ExpressionOrValue; // optional — Infer Content Type — boolean — Infer content-type based on extension.
    } & Record<string, ExpressionOrValue>,
    options?: ConnectorCallOptions,
  ): TriggerSpec {
    return buildConnectorCall({
      kind: "trigger",
      apiId: API_ID,
      defaultConnectionName: DEFAULT_CONNECTION_NAME,
      operationId: "OnNewFile",
      parameters: parameters as Record<string, ExpressionOrValue>,
      options,
    }) as TriggerSpec;
  },

  /**
   * When a file is created or modified in a folder (deprecated)
   * @remarks This is a trigger operation; pass it to flowBuilder.setTrigger().
   * @returns The content of the file. - File Content - binary
   * Operation id: `OnUpdatedFile`
   */
  onUpdatedFile(
    parameters: {
      dataset?: ExpressionOrValue; // REQUIRED — Site Address — string — Example: `https://contoso.sharepoint.com/sites/sitename`.
      folderId?: ExpressionOrValue; // REQUIRED — Folder Id — string — Select a folder.
      inferContentType?: ExpressionOrValue; // optional — Infer Content Type — boolean — Infer content-type based on extension.
    } & Record<string, ExpressionOrValue>,
    options?: ConnectorCallOptions,
  ): TriggerSpec {
    return buildConnectorCall({
      kind: "trigger",
      apiId: API_ID,
      defaultConnectionName: DEFAULT_CONNECTION_NAME,
      operationId: "OnUpdatedFile",
      parameters: parameters as Record<string, ExpressionOrValue>,
      options,
    }) as TriggerSpec;
  },

  /**
   * Update file properties
   * @returns The outputs of this operation are dynamic.
   * Operation id: `PatchFileItem`
   */
  patchFileItem(
    parameters: {
      dataset?: ExpressionOrValue; // REQUIRED — Site Address — string — Example: `https://contoso.sharepoint.com/sites/sitename`
      table?: ExpressionOrValue; // REQUIRED — Library Name — string — SharePoint library name
      id?: ExpressionOrValue; // REQUIRED — Id — integer — Unique identifier of item to be updated
      item?: ExpressionOrValue; // REQUIRED — Item — dynamic — Item with changed properties
      view?: ExpressionOrValue; // optional — Limit Columns by View — string — Avoid column threshold issues by only using columns defined in a view
    } & Record<string, ExpressionOrValue>,
    options?: ConnectorCallOptions,
  ): ActionSpec {
    return buildConnectorCall({
      kind: "action",
      apiId: API_ID,
      defaultConnectionName: DEFAULT_CONNECTION_NAME,
      operationId: "PatchFileItem",
      parameters: parameters as Record<string, ExpressionOrValue>,
      options,
    }) as ActionSpec;
  },

  /**
   * Update file properties using AI Builder model results
   * @returns The outputs of this operation are dynamic.
   * Operation id: `PatchFileItemWithPredictedValues`
   */
  patchFileItemWithPredictedValues(
    parameters: {
      dataset?: ExpressionOrValue; // REQUIRED — Site Address — string — Example: `https://contoso.sharepoint.com/sites/sitename`.
      table?: ExpressionOrValue; // REQUIRED — Library Name — string — Library Name.
      id?: ExpressionOrValue; // REQUIRED — Id — integer — Unique identifier of item to be updated.
      modelId?: ExpressionOrValue; // optional — ModelId — string — Enter modelId of the Model which is used for prediction
      predictResult?: ExpressionOrValue; // optional — PredictResult — string — Enter request content in JSON
    } & Record<string, ExpressionOrValue>,
    options?: ConnectorCallOptions,
  ): ActionSpec {
    return buildConnectorCall({
      kind: "action",
      apiId: API_ID,
      defaultConnectionName: DEFAULT_CONNECTION_NAME,
      operationId: "PatchFileItemWithPredictedValues",
      parameters: parameters as Record<string, ExpressionOrValue>,
      options,
    }) as ActionSpec;
  },

  /**
   * Update item
   * @returns The outputs of this operation are dynamic.
   * Operation id: `PatchItem`
   */
  patchItem(
    parameters: {
      dataset?: ExpressionOrValue; // REQUIRED — Site Address — string — Example: `https://contoso.sharepoint.com/sites/sitename`
      table?: ExpressionOrValue; // REQUIRED — List Name — string — SharePoint list name
      id?: ExpressionOrValue; // REQUIRED — Id — integer — Unique identifier of item to be updated
      item?: ExpressionOrValue; // REQUIRED — Item — dynamic — Item with changed properties
      view?: ExpressionOrValue; // optional — Limit Columns by View — string — Avoid column threshold issues by only using columns defined in a view
    } & Record<string, ExpressionOrValue>,
    options?: ConnectorCallOptions,
  ): ActionSpec {
    return buildConnectorCall({
      kind: "action",
      apiId: API_ID,
      defaultConnectionName: DEFAULT_CONNECTION_NAME,
      operationId: "PatchItem",
      parameters: parameters as Record<string, ExpressionOrValue>,
      options,
    }) as ActionSpec;
  },

  /**
   * Create item
   * @returns The outputs of this operation are dynamic.
   * Operation id: `PostItem`
   */
  postItem(
    parameters: {
      dataset?: ExpressionOrValue; // REQUIRED — Site Address — string — Example: `https://contoso.sharepoint.com/sites/sitename`
      table?: ExpressionOrValue; // REQUIRED — List Name — string — SharePoint list name
      item?: ExpressionOrValue; // REQUIRED — Item — dynamic — Item to create
      view?: ExpressionOrValue; // optional — Limit Columns by View — string — Avoid column threshold issues by only using columns defined in a view
    } & Record<string, ExpressionOrValue>,
    options?: ConnectorCallOptions,
  ): ActionSpec {
    return buildConnectorCall({
      kind: "action",
      apiId: API_ID,
      defaultConnectionName: DEFAULT_CONNECTION_NAME,
      operationId: "PostItem",
      parameters: parameters as Record<string, ExpressionOrValue>,
      options,
    }) as ActionSpec;
  },

  /**
   * Resolve person
   * @returns SharePoint expanded user field - Body - SPListExpandedUser
   * Operation id: `SearchForUser`
   */
  searchForUser(
    parameters: {
      dataset?: ExpressionOrValue; // REQUIRED — Site Address — string — Example: `https://contoso.sharepoint.com/sites/sitename`.
      table?: ExpressionOrValue; // REQUIRED — List or Library — string — Pick the list or library that the column is in.
      entityId?: ExpressionOrValue; // REQUIRED — Column — string — Pick the column you want to assign the value to.
      searchValue?: ExpressionOrValue; // REQUIRED — Email or name — string — Use the email address, or the full name of the user.
      view?: ExpressionOrValue; // optional — Limit Columns by View — string — Avoid column threshold issues by only using columns defined in a view.
    } & Record<string, ExpressionOrValue>,
    options?: ConnectorCallOptions,
  ): ActionSpec {
    return buildConnectorCall({
      kind: "action",
      apiId: API_ID,
      defaultConnectionName: DEFAULT_CONNECTION_NAME,
      operationId: "SearchForUser",
      parameters: parameters as Record<string, ExpressionOrValue>,
      options,
    }) as ActionSpec;
  },

  /**
   * Set content approval status
   * @returns SetApprovalStatus output - Body - SetApprovalStatusOutput
   * Operation id: `SetApprovalStatus`
   */
  setApprovalStatus(
    parameters: {
      dataset?: ExpressionOrValue; // REQUIRED — Site Address — string — Example: `https://contoso.sharepoint.com/sites/sitename`.
      table?: ExpressionOrValue; // REQUIRED — Library Name — string — SharePoint library name.
      id?: ExpressionOrValue; // REQUIRED — Id — integer — Id of the item you are setting the status of.
      approvalAction?: ExpressionOrValue; // REQUIRED — Action — string — Pick the approval action.
      comments?: ExpressionOrValue; // optional — Comments — string — Add the comments from the approver.
      entityTag?: ExpressionOrValue; // optional — ETag — string — Add an ETag (required for files and pages).
    } & Record<string, ExpressionOrValue>,
    options?: ConnectorCallOptions,
  ): ActionSpec {
    return buildConnectorCall({
      kind: "action",
      apiId: API_ID,
      defaultConnectionName: DEFAULT_CONNECTION_NAME,
      operationId: "SetApprovalStatus",
      parameters: parameters as Record<string, ExpressionOrValue>,
      options,
    }) as ActionSpec;
  },

  /**
   * Generate a document from a form (preview)
   * @returns The SharePoint version of the BlobMetadataResponse extends the object by adding some additional fields that we want serialized - Body - SPBlobMetadataResponse
   * Operation id: `SubmitDocGenForm`
   */
  submitDocGenForm(
    parameters: {
      dataset?: ExpressionOrValue; // REQUIRED — Site Address — string — Example: `https://contoso.sharepoint.com/sites/sitename`.
      table?: ExpressionOrValue; // REQUIRED — Document Library Name — string — SharePoint document library name.
      form?: ExpressionOrValue; // REQUIRED — Form Name — string — Form identifier.
      item?: ExpressionOrValue; // REQUIRED — Fields — dynamic — Form field values.
      view?: ExpressionOrValue; // optional — View (no effect) — string — This parameter does nothing. Please do not use.
    } & Record<string, ExpressionOrValue>,
    options?: ConnectorCallOptions,
  ): ActionSpec {
    return buildConnectorCall({
      kind: "action",
      apiId: API_ID,
      defaultConnectionName: DEFAULT_CONNECTION_NAME,
      operationId: "SubmitDocGenForm",
      parameters: parameters as Record<string, ExpressionOrValue>,
      options,
    }) as ActionSpec;
  },

  /**
   * Stop sharing an item or a file
   * Operation id: `UnshareItem`
   */
  unshareItem(
    parameters: {
      dataset?: ExpressionOrValue; // REQUIRED — Site Address — string — Example: `https://contoso.sharepoint.com/sites/sitename`.
      table?: ExpressionOrValue; // REQUIRED — List or Library Name — string — SharePoint list or library name.
      id?: ExpressionOrValue; // REQUIRED — Id — integer — Unique identifier of the item or file you want to stop sharing.
    } & Record<string, ExpressionOrValue>,
    options?: ConnectorCallOptions,
  ): ActionSpec {
    return buildConnectorCall({
      kind: "action",
      apiId: API_ID,
      defaultConnectionName: DEFAULT_CONNECTION_NAME,
      operationId: "UnshareItem",
      parameters: parameters as Record<string, ExpressionOrValue>,
      options,
    }) as ActionSpec;
  },

  /**
   * Update file
   * @returns Represents blob datasets metadata response - Body - BlobMetadataResponse
   * Operation id: `UpdateFile`
   */
  updateFile(
    parameters: {
      dataset?: ExpressionOrValue; // REQUIRED — Site Address — string — Example: `https://contoso.sharepoint.com/sites/sitename`.
      id?: ExpressionOrValue; // REQUIRED — File Identifier — string — Select a file.
      body?: ExpressionOrValue; // REQUIRED — File Content — binary — Content of the file.
    } & Record<string, ExpressionOrValue>,
    options?: ConnectorCallOptions,
  ): ActionSpec {
    return buildConnectorCall({
      kind: "action",
      apiId: API_ID,
      defaultConnectionName: DEFAULT_CONNECTION_NAME,
      operationId: "UpdateFile",
      parameters: parameters as Record<string, ExpressionOrValue>,
      options,
    }) as ActionSpec;
  },
} as const;
