// AUTO-GENERATED by packages/connectors/scripts/generate.ts.
// Do not edit by hand. Re-run `bun --filter @vibeflow/connectors generate`.
// Connector: shared_flowmanagement — Power Automate Management
// Source: https://learn.microsoft.com/en-us/connectors/flowmanagement/?accept=text/markdown

import { buildConnectorCall, type ActionSpec, type ConnectorCallOptions, type ExpressionOrValue, type TriggerSpec } from "../_runtime.js";

const API_ID = "/providers/Microsoft.PowerApps/apis/shared_flowmanagement";
const DEFAULT_CONNECTION_NAME = "shared_flowmanagement";

export const PowerAutomateManagement = {
  /** Connector id (`shared_flowmanagement`). */
  connectorId: "shared_flowmanagement",
  /** Power Automate apiId for this connector. */
  apiId: API_ID,

  /**
   * Get Flow as Admin
   * @returns - Body - AdminFlowWithConnectionReferences
   * Operation id: `AdminGetFlow`
   */
  adminGetFlow(
    parameters: {
      environmentName?: ExpressionOrValue; // REQUIRED — Environment — string — Select environment
      flowName?: ExpressionOrValue; // REQUIRED — Flow — string — Select flow
      includeFlowDefinition?: ExpressionOrValue; // optional — Include Flow Definition — boolean — Whether or not to include flow definition.
    } & Record<string, ExpressionOrValue>,
    options?: ConnectorCallOptions,
  ): ActionSpec {
    return buildConnectorCall({
      kind: "action",
      apiId: API_ID,
      defaultConnectionName: DEFAULT_CONNECTION_NAME,
      operationId: "AdminGetFlow",
      parameters: parameters as Record<string, ExpressionOrValue>,
      options,
    }) as ActionSpec;
  },

  /**
   * Modify Flow Owners as Admin
   * Operation id: `AdminModifyFlowOwners`
   */
  adminModifyFlowOwners(
    parameters: {
      environmentName?: ExpressionOrValue; // REQUIRED — Environment — string — Select environment
      flowName?: ExpressionOrValue; // REQUIRED — Flow — string — Select flow
      id?: ExpressionOrValue; // REQUIRED — Add User Object Id — string
      "type"?: ExpressionOrValue; // REQUIRED — Add User Type — string
    } & Record<string, ExpressionOrValue>,
    options?: ConnectorCallOptions,
  ): ActionSpec {
    return buildConnectorCall({
      kind: "action",
      apiId: API_ID,
      defaultConnectionName: DEFAULT_CONNECTION_NAME,
      operationId: "AdminModifyFlowOwners",
      parameters: parameters as Record<string, ExpressionOrValue>,
      options,
    }) as ActionSpec;
  },

  /**
   * Restore Deleted Flow as Admin
   * @returns - Body - AdminFlowWithConnectionReferences
   * Operation id: `AdminRestoreFlow`
   */
  adminRestoreFlow(
    parameters: {
      environmentName?: ExpressionOrValue; // REQUIRED — Environment — string — Select environment
      flowName?: ExpressionOrValue; // REQUIRED — Flow — string — Select flow
    } & Record<string, ExpressionOrValue>,
    options?: ConnectorCallOptions,
  ): ActionSpec {
    return buildConnectorCall({
      kind: "action",
      apiId: API_ID,
      defaultConnectionName: DEFAULT_CONNECTION_NAME,
      operationId: "AdminRestoreFlow",
      parameters: parameters as Record<string, ExpressionOrValue>,
      options,
    }) as ActionSpec;
  },

  /**
   * Cancel Flow Run
   * Operation id: `CancelFlowRun`
   */
  cancelFlowRun(
    parameters: {
      environmentName?: ExpressionOrValue; // REQUIRED — Environment — string — Select environment
      flowName?: ExpressionOrValue; // REQUIRED — Flow — string — Select flow
      runId?: ExpressionOrValue; // REQUIRED — Run ID — string — The ID of the flow run to resubmit.
    } & Record<string, ExpressionOrValue>,
    options?: ConnectorCallOptions,
  ): ActionSpec {
    return buildConnectorCall({
      kind: "action",
      apiId: API_ID,
      defaultConnectionName: DEFAULT_CONNECTION_NAME,
      operationId: "CancelFlowRun",
      parameters: parameters as Record<string, ExpressionOrValue>,
      options,
    }) as ActionSpec;
  },

  /**
   * Create Connection
   * @returns The outputs of this operation are dynamic.
   * Operation id: `CreateConnection`
   */
  createConnection(
    parameters: {
      environmentName?: ExpressionOrValue; // REQUIRED — Environment — string — Select environment
      apiName?: ExpressionOrValue; // REQUIRED — Connector — string — Select connector
      connection?: ExpressionOrValue; // optional — dynamic — Connection
    } & Record<string, ExpressionOrValue>,
    options?: ConnectorCallOptions,
  ): ActionSpec {
    return buildConnectorCall({
      kind: "action",
      apiId: API_ID,
      defaultConnectionName: DEFAULT_CONNECTION_NAME,
      operationId: "CreateConnection",
      parameters: parameters as Record<string, ExpressionOrValue>,
      options,
    }) as ActionSpec;
  },

  /**
   * Create Flow
   * @returns - Body - Flow
   * Operation id: `CreateFlow`
   */
  createFlow(
    parameters: {
      environmentName?: ExpressionOrValue; // REQUIRED — Environment — string — Select environment
      displayName?: ExpressionOrValue; // REQUIRED — Flow Display Name — string
      state?: ExpressionOrValue; // REQUIRED — Flow State — string
      id?: ExpressionOrValue; // REQUIRED — Connector Id — string
      tenantId?: ExpressionOrValue; // REQUIRED — Creator tenant ID — string
      userId?: ExpressionOrValue; // REQUIRED — Creator user ID — string
      userType?: ExpressionOrValue; // REQUIRED — Creator user type — string
      name?: ExpressionOrValue; // optional — Flow Name — string
      connectionName?: ExpressionOrValue; // optional — Connection Name — string
      source?: ExpressionOrValue; // optional — Either Embedded or Invoker connection — string
      connectionReferenceLogicalName?: ExpressionOrValue; // optional — Logical name of the connection reference — string
      createdTime?: ExpressionOrValue; // optional — Connection Created Time — date-time
      primaryRuntimeUrl?: ExpressionOrValue; // optional — Connector Runtime Url — string
      iconUri?: ExpressionOrValue; // optional — Connector Icon Url — string
      isCustomApi?: ExpressionOrValue; // optional — Connector is Custom Api — boolean
      tier?: ExpressionOrValue; // optional — Connector Tier — string
      lastModifiedTime?: ExpressionOrValue; // optional — Flow Modified Time — date-time
      templateName?: ExpressionOrValue; // optional — Flow Template Name — string
      flowTriggerUri?: ExpressionOrValue; // optional — Flow Trigger Uri — string
      installationStatus?: ExpressionOrValue; // optional — Flow Installation Status — string
      objectId?: ExpressionOrValue; // optional — Creator object ID — string
      "type"?: ExpressionOrValue; // optional — Flow trigger type — string
      kind?: ExpressionOrValue; // optional — Flow trigger kind — string
      swaggerOperationId?: ExpressionOrValue; // optional — Swagger operation Id — string
    } & Record<string, ExpressionOrValue>,
    options?: ConnectorCallOptions,
  ): ActionSpec {
    return buildConnectorCall({
      kind: "action",
      apiId: API_ID,
      defaultConnectionName: DEFAULT_CONNECTION_NAME,
      operationId: "CreateFlow",
      parameters: parameters as Record<string, ExpressionOrValue>,
      options,
    }) as ActionSpec;
  },

  /**
   * Delete Flow
   * Operation id: `DeleteFlow`
   */
  deleteFlow(
    parameters: {
      environmentName?: ExpressionOrValue; // REQUIRED — Environment — string — Select environment
      flowName?: ExpressionOrValue; // REQUIRED — Flow — string — Select flow
    } & Record<string, ExpressionOrValue>,
    options?: ConnectorCallOptions,
  ): ActionSpec {
    return buildConnectorCall({
      kind: "action",
      apiId: API_ID,
      defaultConnectionName: DEFAULT_CONNECTION_NAME,
      operationId: "DeleteFlow",
      parameters: parameters as Record<string, ExpressionOrValue>,
      options,
    }) as ActionSpec;
  },

  /**
   * Get Connector
   * @returns The outputs of this operation are dynamic.
   * Operation id: `GetApi`
   */
  getApi(
    parameters: {
      environmentName?: ExpressionOrValue; // REQUIRED — Environment — string — Select environment
      apiName?: ExpressionOrValue; // REQUIRED — Connector — string — Select connector
    } & Record<string, ExpressionOrValue>,
    options?: ConnectorCallOptions,
  ): ActionSpec {
    return buildConnectorCall({
      kind: "action",
      apiId: API_ID,
      defaultConnectionName: DEFAULT_CONNECTION_NAME,
      operationId: "GetApi",
      parameters: parameters as Record<string, ExpressionOrValue>,
      options,
    }) as ActionSpec;
  },

  /**
   * Get Flow
   * @returns - Body - FlowWithConnectionReferences
   * Operation id: `GetFlow`
   */
  getFlow(
    parameters: {
      environmentName?: ExpressionOrValue; // REQUIRED — Environment — string — Select environment
      flowName?: ExpressionOrValue; // REQUIRED — Flow — string — Select flow
    } & Record<string, ExpressionOrValue>,
    options?: ConnectorCallOptions,
  ): ActionSpec {
    return buildConnectorCall({
      kind: "action",
      apiId: API_ID,
      defaultConnectionName: DEFAULT_CONNECTION_NAME,
      operationId: "GetFlow",
      parameters: parameters as Record<string, ExpressionOrValue>,
      options,
    }) as ActionSpec;
  },

  /**
   * List Connectors
   * @returns - Body - ResourceArray[ApiWithoutConnectionParameters]
   * Operation id: `ListApis`
   */
  listApis(
    parameters: {
      environmentName?: ExpressionOrValue; // REQUIRED — Environment — string — Select environment
    } & Record<string, ExpressionOrValue>,
    options?: ConnectorCallOptions,
  ): ActionSpec {
    return buildConnectorCall({
      kind: "action",
      apiId: API_ID,
      defaultConnectionName: DEFAULT_CONNECTION_NAME,
      operationId: "ListApis",
      parameters: parameters as Record<string, ExpressionOrValue>,
      options,
    }) as ActionSpec;
  },

  /**
   * List Callback URL
   * @returns - Body - FlowListCallbackUrlResponse
   * Operation id: `ListCallbackUrl`
   */
  listCallbackUrl(
    parameters: {
      environmentName?: ExpressionOrValue; // REQUIRED — Environment — string — Select environment
      flowName?: ExpressionOrValue; // REQUIRED — Flow — string — Select flow
    } & Record<string, ExpressionOrValue>,
    options?: ConnectorCallOptions,
  ): ActionSpec {
    return buildConnectorCall({
      kind: "action",
      apiId: API_ID,
      defaultConnectionName: DEFAULT_CONNECTION_NAME,
      operationId: "ListCallbackUrl",
      parameters: parameters as Record<string, ExpressionOrValue>,
      options,
    }) as ActionSpec;
  },

  /**
   * List My Connections
   * @returns - Body - ResourceArray[ConnectionWithoutConnectionParameters]
   * Operation id: `ListConnections`
   */
  listConnections(
    parameters: {
      environmentName?: ExpressionOrValue; // REQUIRED — Environment — string — Select environment
    } & Record<string, ExpressionOrValue>,
    options?: ConnectorCallOptions,
  ): ActionSpec {
    return buildConnectorCall({
      kind: "action",
      apiId: API_ID,
      defaultConnectionName: DEFAULT_CONNECTION_NAME,
      operationId: "ListConnections",
      parameters: parameters as Record<string, ExpressionOrValue>,
      options,
    }) as ActionSpec;
  },

  /**
   * List Flow Owners
   * @returns - Body - ResourceArray[FlowPermission]
   * Operation id: `ListFlowOwners`
   */
  listFlowOwners(
    parameters: {
      environmentName?: ExpressionOrValue; // REQUIRED — Environment — string — Select environment
      flowName?: ExpressionOrValue; // REQUIRED — Flow — string — Select flow
    } & Record<string, ExpressionOrValue>,
    options?: ConnectorCallOptions,
  ): ActionSpec {
    return buildConnectorCall({
      kind: "action",
      apiId: API_ID,
      defaultConnectionName: DEFAULT_CONNECTION_NAME,
      operationId: "ListFlowOwners",
      parameters: parameters as Record<string, ExpressionOrValue>,
      options,
    }) as ActionSpec;
  },

  /**
   * List Flow Run-Only Users
   * @returns - Body - ResourceArray[FlowPermission]
   * Operation id: `ListFlowUsers`
   */
  listFlowUsers(
    parameters: {
      environmentName?: ExpressionOrValue; // REQUIRED — Environment — string — Select environment
      flowName?: ExpressionOrValue; // REQUIRED — Flow — string — Select flow
    } & Record<string, ExpressionOrValue>,
    options?: ConnectorCallOptions,
  ): ActionSpec {
    return buildConnectorCall({
      kind: "action",
      apiId: API_ID,
      defaultConnectionName: DEFAULT_CONNECTION_NAME,
      operationId: "ListFlowUsers",
      parameters: parameters as Record<string, ExpressionOrValue>,
      options,
    }) as ActionSpec;
  },

  /**
   * List Flows as Admin (V2)
   * @returns - Body - ResourceArray[AdminFlowWithoutDefinition]
   * Operation id: `ListFlowsInEnvironment_V2`
   */
  listFlowsInEnvironmentV2(
    parameters: {
      environmentName?: ExpressionOrValue; // REQUIRED — Environment — string — Select environment
      $top?: ExpressionOrValue; // optional — Top count — integer — Top count
      expandSuspensionInfo?: ExpressionOrValue; // optional — Expand Suspension Info — boolean — Expands the suspension information
      includeSoftDeletedFlows?: ExpressionOrValue; // optional — Include Soft-Deleted Flows — boolean — Whether or not to include soft-deleted flows.
    } & Record<string, ExpressionOrValue>,
    options?: ConnectorCallOptions,
  ): ActionSpec {
    return buildConnectorCall({
      kind: "action",
      apiId: API_ID,
      defaultConnectionName: DEFAULT_CONNECTION_NAME,
      operationId: "ListFlowsInEnvironment_V2",
      parameters: parameters as Record<string, ExpressionOrValue>,
      options,
    }) as ActionSpec;
  },

  /**
   * List My Flows
   * @returns - Body - ResourceArray[AdminFlow]
   * Operation id: `ListMyFlows`
   */
  listMyFlows(
    parameters: {
      environmentName?: ExpressionOrValue; // REQUIRED — Environment — string — Select environment
    } & Record<string, ExpressionOrValue>,
    options?: ConnectorCallOptions,
  ): ActionSpec {
    return buildConnectorCall({
      kind: "action",
      apiId: API_ID,
      defaultConnectionName: DEFAULT_CONNECTION_NAME,
      operationId: "ListMyFlows",
      parameters: parameters as Record<string, ExpressionOrValue>,
      options,
    }) as ActionSpec;
  },

  /**
   * List My Environments
   * @returns - Body - ResourceArray[Environment]
   * Operation id: `ListUserEnvironments`
   */
  listUserEnvironments(options?: ConnectorCallOptions): ActionSpec {
    return buildConnectorCall({
      kind: "action",
      apiId: API_ID,
      defaultConnectionName: DEFAULT_CONNECTION_NAME,
      operationId: "ListUserEnvironments",
      parameters: {},
      options,
    }) as ActionSpec;
  },

  /**
   * Modify Flow Owners
   * Operation id: `ModifyFlowOwners`
   */
  modifyFlowOwners(
    parameters: {
      environmentName?: ExpressionOrValue; // REQUIRED — Environment — string — Select environment
      flowName?: ExpressionOrValue; // REQUIRED — Flow — string — Select flow
      id?: ExpressionOrValue; // REQUIRED — Add User Object Id — string
      "type"?: ExpressionOrValue; // REQUIRED — Add User Type — string
    } & Record<string, ExpressionOrValue>,
    options?: ConnectorCallOptions,
  ): ActionSpec {
    return buildConnectorCall({
      kind: "action",
      apiId: API_ID,
      defaultConnectionName: DEFAULT_CONNECTION_NAME,
      operationId: "ModifyFlowOwners",
      parameters: parameters as Record<string, ExpressionOrValue>,
      options,
    }) as ActionSpec;
  },

  /**
   * Modify Run-Only Users
   * Operation id: `ModifyRunOnlyUsers`
   */
  modifyRunOnlyUsers(
    parameters: {
      environmentName?: ExpressionOrValue; // REQUIRED — Environment — string — Select environment
      flowName?: ExpressionOrValue; // REQUIRED — Flow — string — Select flow
      id?: ExpressionOrValue; // REQUIRED — Add User Object Id — string
      "type"?: ExpressionOrValue; // REQUIRED — Add User Type — string
    } & Record<string, ExpressionOrValue>,
    options?: ConnectorCallOptions,
  ): ActionSpec {
    return buildConnectorCall({
      kind: "action",
      apiId: API_ID,
      defaultConnectionName: DEFAULT_CONNECTION_NAME,
      operationId: "ModifyRunOnlyUsers",
      parameters: parameters as Record<string, ExpressionOrValue>,
      options,
    }) as ActionSpec;
  },

  /**
   * Resubmit Flow
   * Operation id: `ResubmitFlow`
   */
  resubmitFlow(
    parameters: {
      environmentName?: ExpressionOrValue; // REQUIRED — Environment — string — Select environment
      flowName?: ExpressionOrValue; // REQUIRED — Flow — string — Select flow
      triggerName?: ExpressionOrValue; // REQUIRED — Trigger Name — string — Name of the flow trigger to resubmit.
      runId?: ExpressionOrValue; // REQUIRED — Run ID — string — The ID of the flow run to resubmit.
    } & Record<string, ExpressionOrValue>,
    options?: ConnectorCallOptions,
  ): ActionSpec {
    return buildConnectorCall({
      kind: "action",
      apiId: API_ID,
      defaultConnectionName: DEFAULT_CONNECTION_NAME,
      operationId: "ResubmitFlow",
      parameters: parameters as Record<string, ExpressionOrValue>,
      options,
    }) as ActionSpec;
  },

  /**
   * Turn On Flow
   * Operation id: `StartFlow`
   */
  startFlow(
    parameters: {
      environmentName?: ExpressionOrValue; // REQUIRED — Environment — string — Select environment
      flowName?: ExpressionOrValue; // REQUIRED — Flow — string — Select flow
    } & Record<string, ExpressionOrValue>,
    options?: ConnectorCallOptions,
  ): ActionSpec {
    return buildConnectorCall({
      kind: "action",
      apiId: API_ID,
      defaultConnectionName: DEFAULT_CONNECTION_NAME,
      operationId: "StartFlow",
      parameters: parameters as Record<string, ExpressionOrValue>,
      options,
    }) as ActionSpec;
  },

  /**
   * Turn Off Flow
   * Operation id: `StopFlow`
   */
  stopFlow(
    parameters: {
      environmentName?: ExpressionOrValue; // REQUIRED — Environment — string — Select environment
      flowName?: ExpressionOrValue; // REQUIRED — Flow — string — Select flow
    } & Record<string, ExpressionOrValue>,
    options?: ConnectorCallOptions,
  ): ActionSpec {
    return buildConnectorCall({
      kind: "action",
      apiId: API_ID,
      defaultConnectionName: DEFAULT_CONNECTION_NAME,
      operationId: "StopFlow",
      parameters: parameters as Record<string, ExpressionOrValue>,
      options,
    }) as ActionSpec;
  },

  /**
   * Update Flow
   * @returns - Body - Flow
   * Operation id: `UpdateFlow`
   */
  updateFlow(
    parameters: {
      environmentName?: ExpressionOrValue; // REQUIRED — Environment — string — Select environment
      flowName?: ExpressionOrValue; // REQUIRED — Flow — string — Select flow
      displayName?: ExpressionOrValue; // REQUIRED — Flow Display Name — string
      state?: ExpressionOrValue; // REQUIRED — Flow State — string
      id?: ExpressionOrValue; // REQUIRED — Connector Id — string
      tenantId?: ExpressionOrValue; // REQUIRED — Creator tenant ID — string
      userId?: ExpressionOrValue; // REQUIRED — Creator user ID — string
      userType?: ExpressionOrValue; // REQUIRED — Creator user type — string
      name?: ExpressionOrValue; // optional — Flow Name — string
      connectionName?: ExpressionOrValue; // optional — Connection Name — string
      source?: ExpressionOrValue; // optional — Either Embedded or Invoker connection — string
      connectionReferenceLogicalName?: ExpressionOrValue; // optional — Logical name of the connection reference — string
      createdTime?: ExpressionOrValue; // optional — Connection Created Time — date-time
      primaryRuntimeUrl?: ExpressionOrValue; // optional — Connector Runtime Url — string
      iconUri?: ExpressionOrValue; // optional — Connector Icon Url — string
      isCustomApi?: ExpressionOrValue; // optional — Connector is Custom Api — boolean
      tier?: ExpressionOrValue; // optional — Connector Tier — string
      lastModifiedTime?: ExpressionOrValue; // optional — Flow Modified Time — date-time
      templateName?: ExpressionOrValue; // optional — Flow Template Name — string
      flowTriggerUri?: ExpressionOrValue; // optional — Flow Trigger Uri — string
      installationStatus?: ExpressionOrValue; // optional — Flow Installation Status — string
      objectId?: ExpressionOrValue; // optional — Creator object ID — string
      "type"?: ExpressionOrValue; // optional — Flow trigger type — string
      kind?: ExpressionOrValue; // optional — Flow trigger kind — string
      swaggerOperationId?: ExpressionOrValue; // optional — Swagger operation Id — string
    } & Record<string, ExpressionOrValue>,
    options?: ConnectorCallOptions,
  ): ActionSpec {
    return buildConnectorCall({
      kind: "action",
      apiId: API_ID,
      defaultConnectionName: DEFAULT_CONNECTION_NAME,
      operationId: "UpdateFlow",
      parameters: parameters as Record<string, ExpressionOrValue>,
      options,
    }) as ActionSpec;
  },
} as const;
