// AUTO-GENERATED by packages/connectors/scripts/generate.ts.
// Do not edit by hand. Re-run `bun --filter @vibeflow/connectors generate`.
// Connector: shared_webcontents — HTTP with Microsoft Entra ID (preauthorized)
// Source: https://learn.microsoft.com/en-us/connectors/webcontents/?accept=text/markdown

import { buildConnectorCall, type ActionSpec, type ConnectorCallOptions, type ExpressionOrValue, type TriggerSpec } from "../_runtime.js";

const API_ID = "/providers/Microsoft.PowerApps/apis/shared_webcontents";
const DEFAULT_CONNECTION_NAME = "shared_webcontents";

export const HTTPWithMicrosoftEntraIDPreauthorized = {
  /** Connector id (`shared_webcontents`). */
  connectorId: "shared_webcontents",
  /** Power Automate apiId for this connector. */
  apiId: API_ID,

  /**
   * Get web resource
   * @returns The content of the file. - File Content - binary
   * Operation id: `GetFileContent`
   */
  getFileContent(
    parameters: {
      path?: ExpressionOrValue; // REQUIRED — Resource path — string — File identifier
    } & Record<string, ExpressionOrValue>,
    options?: ConnectorCallOptions,
  ): ActionSpec {
    return buildConnectorCall({
      kind: "action",
      apiId: API_ID,
      defaultConnectionName: DEFAULT_CONNECTION_NAME,
      operationId: "GetFileContent",
      parameters: parameters as Record<string, ExpressionOrValue>,
      options,
    }) as ActionSpec;
  },

  /**
   * Invoke an HTTP request
   * @returns The content of the response. - Body - string
   * Operation id: `InvokeHttp`
   */
  invokeHttp(
    parameters: {
      method?: ExpressionOrValue; // REQUIRED — Method — string — One of the known HTTP verbs: GET, DELETE, PATCH, POST, PUT.
      url?: ExpressionOrValue; // REQUIRED — Url of the request — string — A full or relative URL to the resource. If it is a full URL , it must match the base resource URL set in the connection.
      headers?: ExpressionOrValue; // optional — Headers — object — The request headers.
      body?: ExpressionOrValue; // optional — Body of the request — string — Body of the request when the method requires it.
    } & Record<string, ExpressionOrValue>,
    options?: ConnectorCallOptions,
  ): ActionSpec {
    return buildConnectorCall({
      kind: "action",
      apiId: API_ID,
      defaultConnectionName: DEFAULT_CONNECTION_NAME,
      operationId: "InvokeHttp",
      parameters: parameters as Record<string, ExpressionOrValue>,
      options,
    }) as ActionSpec;
  },
} as const;
