// AUTO-GENERATED by packages/connectors/scripts/generate.ts.
// Do not edit by hand. Re-run `bun --filter @vibeflow/connectors generate`.
// Connector: shared_office365users — Office 365 Users
// Source: https://learn.microsoft.com/en-us/connectors/office365users/?accept=text/markdown

import { buildConnectorCall, type ActionSpec, type ConnectorCallOptions, type ExpressionOrValue, type TriggerSpec } from "../_runtime.js";

const API_ID = "/providers/Microsoft.PowerApps/apis/shared_office365users";
const DEFAULT_CONNECTION_NAME = "shared_office365users";

export const Office365Users = {
  /** Connector id (`shared_office365users`). */
  connectorId: "shared_office365users",
  /** Power Automate apiId for this connector. */
  apiId: API_ID,

  /**
   * Get direct reports (V1) [DEPRECATED]
   * @deprecated Marked deprecated by Microsoft.
   * @returns - response - array of User
   * Operation id: `DirectReports`
   */
  directReports(
    parameters: {
      userId?: ExpressionOrValue; // REQUIRED — User (UPN) — string — User principal name or id.
    } & Record<string, ExpressionOrValue>,
    options?: ConnectorCallOptions,
  ): ActionSpec {
    return buildConnectorCall({
      kind: "action",
      apiId: API_ID,
      defaultConnectionName: DEFAULT_CONNECTION_NAME,
      operationId: "DirectReports",
      parameters: parameters as Record<string, ExpressionOrValue>,
      options,
    }) as ActionSpec;
  },

  /**
   * Get direct reports (V2)
   * @returns | Name | Path | Type | Description | | --- | --- | --- | --- | | value | value | array of GraphUser_V1 | Value |
   * Operation id: `DirectReports_V2`
   */
  directReportsV2(
    parameters: {
      id?: ExpressionOrValue; // REQUIRED — User (UPN) — string — User principal name or id.
      $select?: ExpressionOrValue; // optional — Select fields — string — Comma separated list of fields to select. Example: surname, department, jobTitle
      $top?: ExpressionOrValue; // optional — Top — integer — Limit on the number of results to return. By default returns all entries.
    } & Record<string, ExpressionOrValue>,
    options?: ConnectorCallOptions,
  ): ActionSpec {
    return buildConnectorCall({
      kind: "action",
      apiId: API_ID,
      defaultConnectionName: DEFAULT_CONNECTION_NAME,
      operationId: "DirectReports_V2",
      parameters: parameters as Record<string, ExpressionOrValue>,
      options,
    }) as ActionSpec;
  },

  /**
   * Send an HTTP request
   * @returns - response - ObjectWithoutType
   * Operation id: `HttpRequest`
   */
  httpRequest(
    parameters: {
      Uri?: ExpressionOrValue; // REQUIRED — URI — string — The full or relative URI. Example: `https://graph.microsoft.com/{version}/{resource}`.
      Method?: ExpressionOrValue; // REQUIRED — string — The HTTP method (default is GET).
      Body?: ExpressionOrValue; // optional — binary — The request body content.
      ContentType?: ExpressionOrValue; // optional — Content-Type — string — The content-type header for the body (default is application/json).
      CustomHeader1?: ExpressionOrValue; // optional — string — Custom header 1. Specify in format: header-name: header-value
      CustomHeader2?: ExpressionOrValue; // optional — string — Custom header 2. Specify in format: header-name: header-value
      CustomHeader3?: ExpressionOrValue; // optional — string — Custom header 3. Specify in format: header-name: header-value
      CustomHeader4?: ExpressionOrValue; // optional — string — Custom header 4. Specify in format: header-name: header-value
      CustomHeader5?: ExpressionOrValue; // optional — string — Custom header 5. Specify in format: header-name: header-value
    } & Record<string, ExpressionOrValue>,
    options?: ConnectorCallOptions,
  ): ActionSpec {
    return buildConnectorCall({
      kind: "action",
      apiId: API_ID,
      defaultConnectionName: DEFAULT_CONNECTION_NAME,
      operationId: "HttpRequest",
      parameters: parameters as Record<string, ExpressionOrValue>,
      options,
    }) as ActionSpec;
  },

  /**
   * Get manager (V1) [DEPRECATED]
   * @deprecated Marked deprecated by Microsoft.
   * @returns Represents a User object in the directory - Body - User
   * Operation id: `Manager`
   */
  manager(
    parameters: {
      userId?: ExpressionOrValue; // REQUIRED — User (UPN) — string — User principal name or id.
    } & Record<string, ExpressionOrValue>,
    options?: ConnectorCallOptions,
  ): ActionSpec {
    return buildConnectorCall({
      kind: "action",
      apiId: API_ID,
      defaultConnectionName: DEFAULT_CONNECTION_NAME,
      operationId: "Manager",
      parameters: parameters as Record<string, ExpressionOrValue>,
      options,
    }) as ActionSpec;
  },

  /**
   * Get manager (V2)
   * @returns User from Graph API - Body - GraphUser_V1
   * Operation id: `Manager_V2`
   */
  managerV2(
    parameters: {
      id?: ExpressionOrValue; // REQUIRED — User (UPN) — string — User principal name or id.
      $select?: ExpressionOrValue; // optional — Select fields — string — Comma separated list of fields to select. Example: surname, department, jobTitle
    } & Record<string, ExpressionOrValue>,
    options?: ConnectorCallOptions,
  ): ActionSpec {
    return buildConnectorCall({
      kind: "action",
      apiId: API_ID,
      defaultConnectionName: DEFAULT_CONNECTION_NAME,
      operationId: "Manager_V2",
      parameters: parameters as Record<string, ExpressionOrValue>,
      options,
    }) as ActionSpec;
  },

  /**
   * Get my profile (V1) [DEPRECATED]
   * @deprecated Marked deprecated by Microsoft.
   * @returns Represents a User object in the directory - Body - User
   * Operation id: `MyProfile`
   */
  myProfile(options?: ConnectorCallOptions): ActionSpec {
    return buildConnectorCall({
      kind: "action",
      apiId: API_ID,
      defaultConnectionName: DEFAULT_CONNECTION_NAME,
      operationId: "MyProfile",
      parameters: {},
      options,
    }) as ActionSpec;
  },

  /**
   * Get my profile (V2)
   * @returns User from Graph API - Body - GraphUser_V1
   * Operation id: `MyProfile_V2`
   */
  myProfileV2(
    parameters: {
      $select?: ExpressionOrValue; // optional — Select fields — string — Comma separated list of fields to select. Example: surname, department, jobTitle
    } & Record<string, ExpressionOrValue>,
    options?: ConnectorCallOptions,
  ): ActionSpec {
    return buildConnectorCall({
      kind: "action",
      apiId: API_ID,
      defaultConnectionName: DEFAULT_CONNECTION_NAME,
      operationId: "MyProfile_V2",
      parameters: parameters as Record<string, ExpressionOrValue>,
      options,
    }) as ActionSpec;
  },

  /**
   * Get my trending documents
   * @returns | Name | Path | Type | Description | | --- | --- | --- | --- | | value | value | array of GraphTrending | value |
   * Operation id: `MyTrendingDocuments`
   */
  myTrendingDocuments(
    parameters: {
      $filter?: ExpressionOrValue; // optional — Filter query — string — An OData filter to filter the resources selected. Filter selected resources on ResourceVisualization/Type or ResourceVis
      extractSensitivityLabel?: ExpressionOrValue; // optional — Extract Sensitivity Label — boolean — Select if you want to extract Sensitivity label ( false, true).
      fetchSensitivityLabelMetadata?: ExpressionOrValue; // optional — Sensitivity Label Metadata — boolean — A boolean whether to fetch sensitivity label Metadata for associated LabelId.
    } & Record<string, ExpressionOrValue>,
    options?: ConnectorCallOptions,
  ): ActionSpec {
    return buildConnectorCall({
      kind: "action",
      apiId: API_ID,
      defaultConnectionName: DEFAULT_CONNECTION_NAME,
      operationId: "MyTrendingDocuments",
      parameters: parameters as Record<string, ExpressionOrValue>,
      options,
    }) as ActionSpec;
  },

  /**
   * Get relevant people
   * @returns Represents a list from the Graph API - Body - LinklessEntityListResponse[List[Person]]
   * Operation id: `RelevantPeople`
   */
  relevantPeople(
    parameters: {
      userId?: ExpressionOrValue; // REQUIRED — User (UPN) — string — User principal name or id.
    } & Record<string, ExpressionOrValue>,
    options?: ConnectorCallOptions,
  ): ActionSpec {
    return buildConnectorCall({
      kind: "action",
      apiId: API_ID,
      defaultConnectionName: DEFAULT_CONNECTION_NAME,
      operationId: "RelevantPeople",
      parameters: parameters as Record<string, ExpressionOrValue>,
      options,
    }) as ActionSpec;
  },

  /**
   * Search for users [DEPRECATED]
   * @deprecated Marked deprecated by Microsoft.
   * @returns - response - array of User
   * Operation id: `SearchUser`
   */
  searchUser(
    parameters: {
      searchTerm?: ExpressionOrValue; // optional — Search term — string — Search string (applies to: display name, given name, surname, mail, mail nickname and user principal name).
      top?: ExpressionOrValue; // optional — Top — integer — Limit on the number of results to return. By default returns all entries.
    } & Record<string, ExpressionOrValue>,
    options?: ConnectorCallOptions,
  ): ActionSpec {
    return buildConnectorCall({
      kind: "action",
      apiId: API_ID,
      defaultConnectionName: DEFAULT_CONNECTION_NAME,
      operationId: "SearchUser",
      parameters: parameters as Record<string, ExpressionOrValue>,
      options,
    }) as ActionSpec;
  },

  /**
   * Search for users (V2)
   * @returns Class representing entity list response from an Office API. - Body - EntityListResponse[IReadOnlyList[User]]
   * Operation id: `SearchUserV2`
   */
  searchUserV2(
    parameters: {
      searchTerm?: ExpressionOrValue; // optional — Search term — string — Search string (applies to: display name, given name, surname, mail, mail nickname and user principal name).
      top?: ExpressionOrValue; // optional — Top — integer — Limit on the number of results to return. Minimum value is 1. Default value is 1000.
      isSearchTermRequired?: ExpressionOrValue; // optional — Is search term required — boolean — If set to 'Yes' then no user profiles will be returned when the search term is empty. If set to 'No' then no filtering w
    } & Record<string, ExpressionOrValue>,
    options?: ConnectorCallOptions,
  ): ActionSpec {
    return buildConnectorCall({
      kind: "action",
      apiId: API_ID,
      defaultConnectionName: DEFAULT_CONNECTION_NAME,
      operationId: "SearchUserV2",
      parameters: parameters as Record<string, ExpressionOrValue>,
      options,
    }) as ActionSpec;
  },

  /**
   * Get trending documents
   * @returns | Name | Path | Type | Description | | --- | --- | --- | --- | | value | value | array of GraphTrending | value |
   * Operation id: `TrendingDocuments`
   */
  trendingDocuments(
    parameters: {
      id?: ExpressionOrValue; // REQUIRED — User (UPN) — string — User principal name or id.
      $filter?: ExpressionOrValue; // optional — Filter query — string — An OData filter to filter the resources selected. Filter selected resources on ResourceVisualization/Type or ResourceVis
      extractSensitivityLabel?: ExpressionOrValue; // optional — Extract Sensitivity Label — boolean — Select if you want to extract Sensitivity label ( false, true).
      fetchSensitivityLabelMetadata?: ExpressionOrValue; // optional — Sensitivity Label Metadata — boolean — A boolean whether to fetch sensitivity label Metadata for associated LabelId.
    } & Record<string, ExpressionOrValue>,
    options?: ConnectorCallOptions,
  ): ActionSpec {
    return buildConnectorCall({
      kind: "action",
      apiId: API_ID,
      defaultConnectionName: DEFAULT_CONNECTION_NAME,
      operationId: "TrendingDocuments",
      parameters: parameters as Record<string, ExpressionOrValue>,
      options,
    }) as ActionSpec;
  },

  /**
   * Update my profile photo
   * Operation id: `UpdateMyPhoto`
   */
  updateMyPhoto(
    parameters: {
      body?: ExpressionOrValue; // REQUIRED — Image content — binary — Image content
      "Content-Type"?: ExpressionOrValue; // REQUIRED — string — Image content type (like 'image/jpeg')
    } & Record<string, ExpressionOrValue>,
    options?: ConnectorCallOptions,
  ): ActionSpec {
    return buildConnectorCall({
      kind: "action",
      apiId: API_ID,
      defaultConnectionName: DEFAULT_CONNECTION_NAME,
      operationId: "UpdateMyPhoto",
      parameters: parameters as Record<string, ExpressionOrValue>,
      options,
    }) as ActionSpec;
  },

  /**
   * Update my profile
   * Operation id: `UpdateMyProfile`
   */
  updateMyProfile(
    parameters: {
      aboutMe?: ExpressionOrValue; // optional — About Me — string — About Me
      birthday?: ExpressionOrValue; // optional — Birthday — date-time — Birthday
      interests?: ExpressionOrValue; // optional — Interests — array of string — Interests
      mySite?: ExpressionOrValue; // optional — My Site — string — My Site
      pastProjects?: ExpressionOrValue; // optional — Past Projects — array of string — Past Projects
      schools?: ExpressionOrValue; // optional — Schools — array of string — Schools
      skills?: ExpressionOrValue; // optional — Skills — array of string — Skills
    } & Record<string, ExpressionOrValue>,
    options?: ConnectorCallOptions,
  ): ActionSpec {
    return buildConnectorCall({
      kind: "action",
      apiId: API_ID,
      defaultConnectionName: DEFAULT_CONNECTION_NAME,
      operationId: "UpdateMyProfile",
      parameters: parameters as Record<string, ExpressionOrValue>,
      options,
    }) as ActionSpec;
  },

  /**
   * Get user photo (V1) [DEPRECATED]
   * @deprecated Marked deprecated by Microsoft.
   * @returns - Image file content - binary
   * Operation id: `UserPhoto`
   */
  userPhoto(
    parameters: {
      userId?: ExpressionOrValue; // REQUIRED — User (UPN) — string — User principal name or id.
    } & Record<string, ExpressionOrValue>,
    options?: ConnectorCallOptions,
  ): ActionSpec {
    return buildConnectorCall({
      kind: "action",
      apiId: API_ID,
      defaultConnectionName: DEFAULT_CONNECTION_NAME,
      operationId: "UserPhoto",
      parameters: parameters as Record<string, ExpressionOrValue>,
      options,
    }) as ActionSpec;
  },

  /**
   * Get user photo metadata
   * @returns Photo Metadata class - Body - ClientPhotoMetadata
   * Operation id: `UserPhotoMetadata`
   */
  userPhotoMetadata(
    parameters: {
      userId?: ExpressionOrValue; // REQUIRED — User (UPN) — string — User principal name or id.
    } & Record<string, ExpressionOrValue>,
    options?: ConnectorCallOptions,
  ): ActionSpec {
    return buildConnectorCall({
      kind: "action",
      apiId: API_ID,
      defaultConnectionName: DEFAULT_CONNECTION_NAME,
      operationId: "UserPhotoMetadata",
      parameters: parameters as Record<string, ExpressionOrValue>,
      options,
    }) as ActionSpec;
  },

  /**
   * Get user photo (V2)
   * @returns - Image file content - binary
   * Operation id: `UserPhoto_V2`
   */
  userPhotoV2(
    parameters: {
      id?: ExpressionOrValue; // REQUIRED — User (UPN) — string — User principal name or id.
    } & Record<string, ExpressionOrValue>,
    options?: ConnectorCallOptions,
  ): ActionSpec {
    return buildConnectorCall({
      kind: "action",
      apiId: API_ID,
      defaultConnectionName: DEFAULT_CONNECTION_NAME,
      operationId: "UserPhoto_V2",
      parameters: parameters as Record<string, ExpressionOrValue>,
      options,
    }) as ActionSpec;
  },

  /**
   * Get user profile (V1) [DEPRECATED]
   * @deprecated Marked deprecated by Microsoft.
   * @returns Represents a User object in the directory - Body - User
   * Operation id: `UserProfile`
   */
  userProfile(
    parameters: {
      userId?: ExpressionOrValue; // REQUIRED — User (UPN) — string — User principal name or id.
    } & Record<string, ExpressionOrValue>,
    options?: ConnectorCallOptions,
  ): ActionSpec {
    return buildConnectorCall({
      kind: "action",
      apiId: API_ID,
      defaultConnectionName: DEFAULT_CONNECTION_NAME,
      operationId: "UserProfile",
      parameters: parameters as Record<string, ExpressionOrValue>,
      options,
    }) as ActionSpec;
  },

  /**
   * Get user profile (V2)
   * @returns User from Graph API - Body - GraphUser_V1
   * Operation id: `UserProfile_V2`
   */
  userProfileV2(
    parameters: {
      id?: ExpressionOrValue; // REQUIRED — User (UPN) — string — User principal name or id.
      $select?: ExpressionOrValue; // optional — Select fields — string — Comma separated list of fields to select. Example: surname, department, jobTitle
    } & Record<string, ExpressionOrValue>,
    options?: ConnectorCallOptions,
  ): ActionSpec {
    return buildConnectorCall({
      kind: "action",
      apiId: API_ID,
      defaultConnectionName: DEFAULT_CONNECTION_NAME,
      operationId: "UserProfile_V2",
      parameters: parameters as Record<string, ExpressionOrValue>,
      options,
    }) as ActionSpec;
  },
} as const;
