// AUTO-GENERATED by packages/connectors/scripts/generate.ts.
// Do not edit by hand. Re-run `bun --filter @vibeflow/connectors generate`.
// Connector: shared_documentdb — Azure Cosmos DB
// Source: https://learn.microsoft.com/en-us/connectors/documentdb/?accept=text/markdown

import { buildConnectorCall, type ActionSpec, type ConnectorCallOptions, type ExpressionOrValue, type TriggerSpec } from "../_runtime.js";

const API_ID = "/providers/Microsoft.PowerApps/apis/shared_documentdb";
const DEFAULT_CONNECTION_NAME = "shared_documentdb";

export const AzureCosmosDB = {
  /** Connector id (`shared_documentdb`). */
  connectorId: "shared_documentdb",
  /** Power Automate apiId for this connector. */
  apiId: API_ID,

  /**
   * Create or update document [DEPRECATED]
   * @deprecated Marked deprecated by Microsoft.
   * @returns - Body - postDocumentsResponse
   * Operation id: `CreateDocument`
   */
  createDocument(
    parameters: {
      databaseId?: ExpressionOrValue; // REQUIRED — Database ID — string — The name of the database.
      collectionId?: ExpressionOrValue; // REQUIRED — Collection ID — string — The name of the collection.
      "x-ms-documentdb-raw-partitionkey"?: ExpressionOrValue; // optional — Partition key value — string — The partition key value for the requested document or attachment operation.
      "x-ms-max-item-count"?: ExpressionOrValue; // optional — Max Item Count — number — An integer indicating the maximum number of items to be returned per page.
      "x-ms-continuation"?: ExpressionOrValue; // optional — Continuation Token — string — A string token returned for queries and read-feed operations if there are more results to be read.
      "x-ms-consistency-level"?: ExpressionOrValue; // optional — Consistency Level — string — This is the consistency level override. The valid values are: Strong, Bounded, Session, or Eventual (in order of stronge
      "x-ms-session-token"?: ExpressionOrValue; // optional — Session Token — string — A string token used with session level consistency.
      "x-ms-activity-id"?: ExpressionOrValue; // optional — Activity id — string — A client supplied identifier for the operation, which will be echoed in the server response.
      "x-ms-documentdb-is-upsert"?: ExpressionOrValue; // optional — IsUpsert — boolean — If set to true, the document will be replaced if it exists else created.
      "x-ms-documentdb-pre-trigger-include"?: ExpressionOrValue; // optional — Pre-Trigger — string — Comma-separated list of trigger names to run before the document operation is executed.
      "x-ms-documentdb-post-trigger-include"?: ExpressionOrValue; // optional — Post-Trigger — string — Comma-separated list of trigger names to run after the document operation is executed.
      "x-ms-version"?: ExpressionOrValue; // optional — API version — string — API version.
    } & Record<string, ExpressionOrValue>,
    options?: ConnectorCallOptions,
  ): ActionSpec {
    return buildConnectorCall({
      kind: "action",
      apiId: API_ID,
      defaultConnectionName: DEFAULT_CONNECTION_NAME,
      operationId: "CreateDocument",
      parameters: parameters as Record<string, ExpressionOrValue>,
      options,
    }) as ActionSpec;
  },

  /**
   * Create or update document (V2) [DEPRECATED]
   * @deprecated Marked deprecated by Microsoft.
   * @returns - Body - postDocumentsResponse
   * Operation id: `CreateDocumentV2`
   */
  createDocumentV2(
    parameters: {
      databaseId?: ExpressionOrValue; // REQUIRED — Database ID — string — The name of the database.
      collectionId?: ExpressionOrValue; // REQUIRED — Collection ID — string — The name of the collection.
      "x-ms-max-item-count"?: ExpressionOrValue; // optional — Max Item Count — number — An integer indicating the maximum number of items to be returned per page.
      "x-ms-continuation"?: ExpressionOrValue; // optional — Continuation Token — string — A string token returned for queries and read-feed operations if there are more results to be read.
      "x-ms-consistency-level"?: ExpressionOrValue; // optional — Consistency Level — string — This is the consistency level override. The valid values are: Strong, Bounded, Session, or Eventual (in order of stronge
      "x-ms-session-token"?: ExpressionOrValue; // optional — Session Token — string — A string token used with session level consistency.
      "x-ms-activity-id"?: ExpressionOrValue; // optional — Activity id — string — A client supplied identifier for the operation, which will be echoed in the server response.
      "x-ms-documentdb-is-upsert"?: ExpressionOrValue; // optional — IsUpsert — boolean — If set to true, the document will be replaced if it exists else created.
      "x-ms-documentdb-pre-trigger-include"?: ExpressionOrValue; // optional — Pre-Trigger — string — Comma-separated list of trigger names to run before the document operation is executed.
      "x-ms-documentdb-post-trigger-include"?: ExpressionOrValue; // optional — Post-Trigger — string — Comma-separated list of trigger names to run after the document operation is executed.
      "x-ms-version"?: ExpressionOrValue; // optional — API version — string — API version.
    } & Record<string, ExpressionOrValue>,
    options?: ConnectorCallOptions,
  ): ActionSpec {
    return buildConnectorCall({
      kind: "action",
      apiId: API_ID,
      defaultConnectionName: DEFAULT_CONNECTION_NAME,
      operationId: "CreateDocumentV2",
      parameters: parameters as Record<string, ExpressionOrValue>,
      options,
    }) as ActionSpec;
  },

  /**
   * Create or update document (V3)
   * @returns - Body - postDocumentsResponse
   * Operation id: `CreateDocument_V3`
   */
  createDocumentV3(
    parameters: {
      cosmosDbAccountName?: ExpressionOrValue; // REQUIRED — Azure Cosmos DB account name — string — The Azure Cosmos DB account name (without documents.azure.com).
      databaseId?: ExpressionOrValue; // REQUIRED — Database ID — string — The name of the database.
      collectionId?: ExpressionOrValue; // REQUIRED — Collection ID — string — The name of the collection.
      "x-ms-max-item-count"?: ExpressionOrValue; // optional — Max Item Count — number — An integer indicating the maximum number of items to be returned per page.
      "x-ms-continuation"?: ExpressionOrValue; // optional — Continuation Token — string — A string token returned for queries and read-feed operations if there are more results to be read.
      "x-ms-consistency-level"?: ExpressionOrValue; // optional — Consistency Level — string — This is the consistency level override. The valid values are: Strong, Bounded, Session, or Eventual (in order of stronge
      "x-ms-session-token"?: ExpressionOrValue; // optional — Session Token — string — A string token used with session level consistency.
      "x-ms-activity-id"?: ExpressionOrValue; // optional — Activity id — string — A client supplied identifier for the operation, which will be echoed in the server response.
      "x-ms-documentdb-is-upsert"?: ExpressionOrValue; // optional — IsUpsert — boolean — If set to true, the document will be replaced if it exists else created.
      "x-ms-documentdb-pre-trigger-include"?: ExpressionOrValue; // optional — Pre-Trigger — string — Comma-separated list of trigger names to run before the document operation is executed.
      "x-ms-documentdb-post-trigger-include"?: ExpressionOrValue; // optional — Post-Trigger — string — Comma-separated list of trigger names to run after the document operation is executed.
      "x-ms-version"?: ExpressionOrValue; // optional — API version — string — API version.
    } & Record<string, ExpressionOrValue>,
    options?: ConnectorCallOptions,
  ): ActionSpec {
    return buildConnectorCall({
      kind: "action",
      apiId: API_ID,
      defaultConnectionName: DEFAULT_CONNECTION_NAME,
      operationId: "CreateDocument_V3",
      parameters: parameters as Record<string, ExpressionOrValue>,
      options,
    }) as ActionSpec;
  },

  /**
   * Create stored procedure [DEPRECATED]
   * @deprecated Marked deprecated by Microsoft.
   * @returns - Body - createStoredProcedureResponse
   * Operation id: `CreateStoredProcedure`
   */
  createStoredProcedure(
    parameters: {
      databaseId?: ExpressionOrValue; // REQUIRED — Database ID — string — The name of the database.
      collectionId?: ExpressionOrValue; // REQUIRED — Collection ID — string — The name of the collection.
      body?: ExpressionOrValue; // optional — Function definition — string — Function that defines the stored procedure, e.g. 'function(params){ ... }'
      id?: ExpressionOrValue; // optional — string — New id of the stored procedure.
      "x-ms-version"?: ExpressionOrValue; // optional — API version — string — API version.
    } & Record<string, ExpressionOrValue>,
    options?: ConnectorCallOptions,
  ): ActionSpec {
    return buildConnectorCall({
      kind: "action",
      apiId: API_ID,
      defaultConnectionName: DEFAULT_CONNECTION_NAME,
      operationId: "CreateStoredProcedure",
      parameters: parameters as Record<string, ExpressionOrValue>,
      options,
    }) as ActionSpec;
  },

  /**
   * Create stored procedure (V2)
   * @returns - Body - createStoredProcedureResponse
   * Operation id: `CreateStoredProcedure_V2`
   */
  createStoredProcedureV2(
    parameters: {
      cosmosDbAccountName?: ExpressionOrValue; // REQUIRED — Azure Cosmos DB account name — string — The Azure Cosmos DB account name (without documents.azure.com).
      databaseId?: ExpressionOrValue; // REQUIRED — Database ID — string — The name of the database.
      collectionId?: ExpressionOrValue; // REQUIRED — Collection ID — string — The name of the collection.
      body?: ExpressionOrValue; // optional — Function definition — string — Function that defines the stored procedure, e.g. 'function(params){ ... }'
      id?: ExpressionOrValue; // optional — string — New id of the stored procedure.
      "x-ms-version"?: ExpressionOrValue; // optional — API version — string — API version.
    } & Record<string, ExpressionOrValue>,
    options?: ConnectorCallOptions,
  ): ActionSpec {
    return buildConnectorCall({
      kind: "action",
      apiId: API_ID,
      defaultConnectionName: DEFAULT_CONNECTION_NAME,
      operationId: "CreateStoredProcedure_V2",
      parameters: parameters as Record<string, ExpressionOrValue>,
      options,
    }) as ActionSpec;
  },

  /**
   * Delete a document [DEPRECATED]
   * @deprecated Marked deprecated by Microsoft.
   * Operation id: `DeleteDocument`
   */
  deleteDocument(
    parameters: {
      databaseId?: ExpressionOrValue; // REQUIRED — Database ID — string — The name of the database.
      collectionId?: ExpressionOrValue; // REQUIRED — Collection ID — string — The name of the collection.
      documentId?: ExpressionOrValue; // REQUIRED — Document ID — string — The identifier of the document.
      "x-ms-documentdb-raw-partitionkey"?: ExpressionOrValue; // optional — Partition key value — string — The partition key value for the requested document or attachment operation.
      "x-ms-max-item-count"?: ExpressionOrValue; // optional — Max Item Count — number — An integer indicating the maximum number of items to be returned per page.
      "x-ms-continuation"?: ExpressionOrValue; // optional — Continuation Token — string — A string token returned for queries and read-feed operations if there are more results to be read.
      "x-ms-consistency-level"?: ExpressionOrValue; // optional — Consistency Level — string — This is the consistency level override. The valid values are: Strong, Bounded, Session, or Eventual (in order of stronge
      "x-ms-session-token"?: ExpressionOrValue; // optional — Session Token — string — A string token used with session level consistency.
      "x-ms-activity-id"?: ExpressionOrValue; // optional — Activity id — string — A client supplied identifier for the operation, which will be echoed in the server response.
      "x-ms-documentdb-pre-trigger-include"?: ExpressionOrValue; // optional — Pre-Trigger — string — Comma-separated list of trigger names to run before the document operation is executed.
      "x-ms-documentdb-post-trigger-include"?: ExpressionOrValue; // optional — Post-Trigger — string — Comma-separated list of trigger names to run after the document operation is executed.
      "x-ms-version"?: ExpressionOrValue; // optional — API version — string — API version.
    } & Record<string, ExpressionOrValue>,
    options?: ConnectorCallOptions,
  ): ActionSpec {
    return buildConnectorCall({
      kind: "action",
      apiId: API_ID,
      defaultConnectionName: DEFAULT_CONNECTION_NAME,
      operationId: "DeleteDocument",
      parameters: parameters as Record<string, ExpressionOrValue>,
      options,
    }) as ActionSpec;
  },

  /**
   * Delete a document (V2)
   * Operation id: `DeleteDocument_V2`
   */
  deleteDocumentV2(
    parameters: {
      cosmosDbAccountName?: ExpressionOrValue; // REQUIRED — Azure Cosmos DB account name — string — The Azure Cosmos DB account name (without documents.azure.com).
      databaseId?: ExpressionOrValue; // REQUIRED — Database ID — string — The name of the database.
      collectionId?: ExpressionOrValue; // REQUIRED — Collection ID — string — The name of the collection.
      documentId?: ExpressionOrValue; // REQUIRED — Document ID — string — The identifier of the document.
      "x-ms-documentdb-raw-partitionkey"?: ExpressionOrValue; // optional — Partition key value — string — The partition key value for the requested document or attachment operation.
      "x-ms-max-item-count"?: ExpressionOrValue; // optional — Max Item Count — number — An integer indicating the maximum number of items to be returned per page.
      "x-ms-continuation"?: ExpressionOrValue; // optional — Continuation Token — string — A string token returned for queries and read-feed operations if there are more results to be read.
      "x-ms-consistency-level"?: ExpressionOrValue; // optional — Consistency Level — string — This is the consistency level override. The valid values are: Strong, Bounded, Session, or Eventual (in order of stronge
      "x-ms-session-token"?: ExpressionOrValue; // optional — Session Token — string — A string token used with session level consistency.
      "x-ms-activity-id"?: ExpressionOrValue; // optional — Activity id — string — A client supplied identifier for the operation, which will be echoed in the server response.
      "x-ms-documentdb-pre-trigger-include"?: ExpressionOrValue; // optional — Pre-Trigger — string — Comma-separated list of trigger names to run before the document operation is executed.
      "x-ms-documentdb-post-trigger-include"?: ExpressionOrValue; // optional — Post-Trigger — string — Comma-separated list of trigger names to run after the document operation is executed.
      "x-ms-version"?: ExpressionOrValue; // optional — API version — string — API version.
    } & Record<string, ExpressionOrValue>,
    options?: ConnectorCallOptions,
  ): ActionSpec {
    return buildConnectorCall({
      kind: "action",
      apiId: API_ID,
      defaultConnectionName: DEFAULT_CONNECTION_NAME,
      operationId: "DeleteDocument_V2",
      parameters: parameters as Record<string, ExpressionOrValue>,
      options,
    }) as ActionSpec;
  },

  /**
   * Delete stored procedure [DEPRECATED]
   * @deprecated Marked deprecated by Microsoft.
   * @returns - response - string
   * Operation id: `DeleteStoredProcedure`
   */
  deleteStoredProcedure(
    parameters: {
      databaseId?: ExpressionOrValue; // REQUIRED — Database ID — string — The name of the database.
      collectionId?: ExpressionOrValue; // REQUIRED — Collection ID — string — The name of the collection.
      sprocId?: ExpressionOrValue; // REQUIRED — Sproc ID — string — The name of the stored procedure.
      "x-ms-version"?: ExpressionOrValue; // optional — API version — string — API version.
    } & Record<string, ExpressionOrValue>,
    options?: ConnectorCallOptions,
  ): ActionSpec {
    return buildConnectorCall({
      kind: "action",
      apiId: API_ID,
      defaultConnectionName: DEFAULT_CONNECTION_NAME,
      operationId: "DeleteStoredProcedure",
      parameters: parameters as Record<string, ExpressionOrValue>,
      options,
    }) as ActionSpec;
  },

  /**
   * Delete stored procedure (V2)
   * @returns - response - string
   * Operation id: `DeleteStoredProcedure_V2`
   */
  deleteStoredProcedureV2(
    parameters: {
      cosmosDbAccountName?: ExpressionOrValue; // REQUIRED — Azure Cosmos DB account name — string — The Azure Cosmos DB account name (without documents.azure.com).
      databaseId?: ExpressionOrValue; // REQUIRED — Database ID — string — The name of the database.
      collectionId?: ExpressionOrValue; // REQUIRED — Collection ID — string — The name of the collection.
      sprocId?: ExpressionOrValue; // REQUIRED — Sproc ID — string — The name of the stored procedure.
      "x-ms-version"?: ExpressionOrValue; // optional — API version — string — API version.
    } & Record<string, ExpressionOrValue>,
    options?: ConnectorCallOptions,
  ): ActionSpec {
    return buildConnectorCall({
      kind: "action",
      apiId: API_ID,
      defaultConnectionName: DEFAULT_CONNECTION_NAME,
      operationId: "DeleteStoredProcedure_V2",
      parameters: parameters as Record<string, ExpressionOrValue>,
      options,
    }) as ActionSpec;
  },

  /**
   * Execute stored procedure [DEPRECATED]
   * @deprecated Marked deprecated by Microsoft.
   * @returns - response - ObjectWithoutType
   * Operation id: `ExecuteStoredProcedure`
   */
  executeStoredProcedure(
    parameters: {
      databaseId?: ExpressionOrValue; // REQUIRED — Database ID — string — The name of the database.
      collectionId?: ExpressionOrValue; // REQUIRED — Collection ID — string — The name of the collection.
      sprocId?: ExpressionOrValue; // REQUIRED — Sproc ID — string — The name of the stored procedure.
      "x-ms-documentdb-raw-partitionkey"?: ExpressionOrValue; // optional — Partition key value — string — The partition key value for the requested document or attachment operation.
      parameters?: ExpressionOrValue; // optional — Parameters for the stored procedure — string — Specify valid JSON for the parameters of the stored procedure, e.g. ["param1", "param2"].
      "x-ms-version"?: ExpressionOrValue; // optional — API version — string — API version.
    } & Record<string, ExpressionOrValue>,
    options?: ConnectorCallOptions,
  ): ActionSpec {
    return buildConnectorCall({
      kind: "action",
      apiId: API_ID,
      defaultConnectionName: DEFAULT_CONNECTION_NAME,
      operationId: "ExecuteStoredProcedure",
      parameters: parameters as Record<string, ExpressionOrValue>,
      options,
    }) as ActionSpec;
  },

  /**
   * Execute stored procedure (V2)
   * @returns - response - ObjectWithoutType
   * Operation id: `ExecuteStoredProcedure_V2`
   */
  executeStoredProcedureV2(
    parameters: {
      cosmosDbAccountName?: ExpressionOrValue; // REQUIRED — Azure Cosmos DB account name — string — The Azure Cosmos DB account name (without documents.azure.com).
      databaseId?: ExpressionOrValue; // REQUIRED — Database ID — string — The name of the database.
      collectionId?: ExpressionOrValue; // REQUIRED — Collection ID — string — The name of the collection.
      sprocId?: ExpressionOrValue; // REQUIRED — Sproc ID — string — The name of the stored procedure.
      "x-ms-documentdb-raw-partitionkey"?: ExpressionOrValue; // optional — Partition key value — string — The partition key value for the requested document or attachment operation.
      parameters?: ExpressionOrValue; // optional — Parameters for the stored procedure — string — Specify valid JSON for the parameters of the stored procedure, e.g. ["param1", "param2"].
      "x-ms-version"?: ExpressionOrValue; // optional — API version — string — API version.
    } & Record<string, ExpressionOrValue>,
    options?: ConnectorCallOptions,
  ): ActionSpec {
    return buildConnectorCall({
      kind: "action",
      apiId: API_ID,
      defaultConnectionName: DEFAULT_CONNECTION_NAME,
      operationId: "ExecuteStoredProcedure_V2",
      parameters: parameters as Record<string, ExpressionOrValue>,
      options,
    }) as ActionSpec;
  },

  /**
   * Get a document [DEPRECATED]
   * @deprecated Marked deprecated by Microsoft.
   * @returns - response - object
   * Operation id: `GetDocument`
   */
  getDocument(
    parameters: {
      databaseId?: ExpressionOrValue; // REQUIRED — Database ID — string — The name of the database.
      collectionId?: ExpressionOrValue; // REQUIRED — Collection ID — string — The name of the collection.
      documentId?: ExpressionOrValue; // REQUIRED — Document ID — string — The identifier for the document.
      "x-ms-documentdb-raw-partitionkey"?: ExpressionOrValue; // optional — Partition key value — string — The partition key value for the requested document or attachment operation.
      "x-ms-max-item-count"?: ExpressionOrValue; // optional — Max Item Count — number — An integer indicating the maximum number of items to be returned per page.
      "x-ms-continuation"?: ExpressionOrValue; // optional — Continuation Token — string — A string token returned for queries and read-feed operations if there are more results to be read.
      "x-ms-consistency-level"?: ExpressionOrValue; // optional — Consistency Level — string — This is the consistency level override. The valid values are: Strong, Bounded, Session, or Eventual (in order of stronge
      "x-ms-session-token"?: ExpressionOrValue; // optional — Session Token — string — A string token used with session level consistency.
      "x-ms-activity-id"?: ExpressionOrValue; // optional — Activity id — string — A client supplied identifier for the operation, which will be echoed in the server response.
      "x-ms-version"?: ExpressionOrValue; // optional — API version — string — API version.
    } & Record<string, ExpressionOrValue>,
    options?: ConnectorCallOptions,
  ): ActionSpec {
    return buildConnectorCall({
      kind: "action",
      apiId: API_ID,
      defaultConnectionName: DEFAULT_CONNECTION_NAME,
      operationId: "GetDocument",
      parameters: parameters as Record<string, ExpressionOrValue>,
      options,
    }) as ActionSpec;
  },

  /**
   * Get a document (V2)
   * @returns - response - object
   * Operation id: `GetDocument_V2`
   */
  getDocumentV2(
    parameters: {
      cosmosDbAccountName?: ExpressionOrValue; // REQUIRED — Azure Cosmos DB account name — string — The Azure Cosmos DB account name (without documents.azure.com).
      databaseId?: ExpressionOrValue; // REQUIRED — Database ID — string — The name of the database.
      collectionId?: ExpressionOrValue; // REQUIRED — Collection ID — string — The name of the collection.
      documentId?: ExpressionOrValue; // REQUIRED — Document ID — string — The identifier for the document.
      "x-ms-documentdb-raw-partitionkey"?: ExpressionOrValue; // optional — Partition key value — string — The partition key value for the requested document or attachment operation.
      "x-ms-max-item-count"?: ExpressionOrValue; // optional — Max Item Count — number — An integer indicating the maximum number of items to be returned per page.
      "x-ms-continuation"?: ExpressionOrValue; // optional — Continuation Token — string — A string token returned for queries and read-feed operations if there are more results to be read.
      "x-ms-consistency-level"?: ExpressionOrValue; // optional — Consistency Level — string — This is the consistency level override. The valid values are: Strong, Bounded, Session, or Eventual (in order of stronge
      "x-ms-session-token"?: ExpressionOrValue; // optional — Session Token — string — A string token used with session level consistency.
      "x-ms-activity-id"?: ExpressionOrValue; // optional — Activity id — string — A client supplied identifier for the operation, which will be echoed in the server response.
      "x-ms-version"?: ExpressionOrValue; // optional — API version — string — API version.
    } & Record<string, ExpressionOrValue>,
    options?: ConnectorCallOptions,
  ): ActionSpec {
    return buildConnectorCall({
      kind: "action",
      apiId: API_ID,
      defaultConnectionName: DEFAULT_CONNECTION_NAME,
      operationId: "GetDocument_V2",
      parameters: parameters as Record<string, ExpressionOrValue>,
      options,
    }) as ActionSpec;
  },

  /**
   * Get all documents [DEPRECATED]
   * @deprecated Marked deprecated by Microsoft.
   * @returns - Body - getDocumentsResponse
   * Operation id: `GetDocuments`
   */
  getDocuments(
    parameters: {
      databaseId?: ExpressionOrValue; // REQUIRED — Database ID — string — The name of the database.
      collectionId?: ExpressionOrValue; // REQUIRED — Collection ID — string — The name of the collection.
      "x-ms-documentdb-raw-partitionkey"?: ExpressionOrValue; // optional — Partition key value — string — The partition key value for the requested document or attachment operation.
      "x-ms-max-item-count"?: ExpressionOrValue; // optional — Max Item Count — number — An integer indicating the maximum number of items to be returned per page.
      "x-ms-continuation"?: ExpressionOrValue; // optional — Continuation Token — string — A string token returned for queries and read-feed operations if there are more results to be read.
      "x-ms-consistency-level"?: ExpressionOrValue; // optional — Consistency Level — string — This is the consistency level override. The valid values are: Strong, Bounded, Session, or Eventual (in order of stronge
      "x-ms-session-token"?: ExpressionOrValue; // optional — Session Token — string — A string token used with session level consistency.
      "x-ms-activity-id"?: ExpressionOrValue; // optional — Activity id — string — A client supplied identifier for the operation, which will be echoed in the server response.
      "x-ms-version"?: ExpressionOrValue; // optional — API version — string — API version.
    } & Record<string, ExpressionOrValue>,
    options?: ConnectorCallOptions,
  ): ActionSpec {
    return buildConnectorCall({
      kind: "action",
      apiId: API_ID,
      defaultConnectionName: DEFAULT_CONNECTION_NAME,
      operationId: "GetDocuments",
      parameters: parameters as Record<string, ExpressionOrValue>,
      options,
    }) as ActionSpec;
  },

  /**
   * Get all documents V2 [DEPRECATED]
   * @deprecated Marked deprecated by Microsoft.
   * @returns Array of documents that match the requested query and the related metadata. - Body - DocumentsCollection
   * Operation id: `GetDocumentsV2`
   */
  getDocumentsV2(
    parameters: {
      databaseId?: ExpressionOrValue; // REQUIRED — Database ID — string — The name of the database.
      collectionId?: ExpressionOrValue; // REQUIRED — Collection ID — string — The name of the collection.
      partitionKey?: ExpressionOrValue; // optional — Partition key value — string — If empty, all partitions will be used to search for documents.
      maxItemCount?: ExpressionOrValue; // optional — Max Item Count — integer — An integer indicating the maximum number of items to be returned per page.
      continuationToken?: ExpressionOrValue; // optional — Continuation Token — string — A token to fetch additional results.
      consistencyLevel?: ExpressionOrValue; // optional — Consistency Level — string — Consistency level required for the feed (query/read feed) operation.
      sessionToken?: ExpressionOrValue; // optional — Session Token — string — The session token for use with session consistency.
    } & Record<string, ExpressionOrValue>,
    options?: ConnectorCallOptions,
  ): ActionSpec {
    return buildConnectorCall({
      kind: "action",
      apiId: API_ID,
      defaultConnectionName: DEFAULT_CONNECTION_NAME,
      operationId: "GetDocumentsV2",
      parameters: parameters as Record<string, ExpressionOrValue>,
      options,
    }) as ActionSpec;
  },

  /**
   * Get all documents (V3)
   * @returns - Body - getDocumentsResponse
   * Operation id: `GetDocuments_V3`
   */
  getDocumentsV3(
    parameters: {
      cosmosDbAccountName?: ExpressionOrValue; // REQUIRED — Azure Cosmos DB account name — string — The Azure Cosmos DB account name (without documents.azure.com).
      databaseId?: ExpressionOrValue; // REQUIRED — Database ID — string — The name of the database.
      collectionId?: ExpressionOrValue; // REQUIRED — Collection ID — string — The name of the collection.
      "x-ms-documentdb-raw-partitionkey"?: ExpressionOrValue; // optional — Partition key value — string — The partition key value for the requested document or attachment operation.
      "x-ms-max-item-count"?: ExpressionOrValue; // optional — Max Item Count — number — An integer indicating the maximum number of items to be returned per page.
      "x-ms-continuation"?: ExpressionOrValue; // optional — Continuation Token — string — A string token returned for queries and read-feed operations if there are more results to be read.
      "x-ms-consistency-level"?: ExpressionOrValue; // optional — Consistency Level — string — This is the consistency level override. The valid values are: Strong, Bounded, Session, or Eventual (in order of stronge
      "x-ms-session-token"?: ExpressionOrValue; // optional — Session Token — string — A string token used with session level consistency.
      "x-ms-activity-id"?: ExpressionOrValue; // optional — Activity id — string — A client supplied identifier for the operation, which will be echoed in the server response.
      "x-ms-version"?: ExpressionOrValue; // optional — API version — string — API version.
    } & Record<string, ExpressionOrValue>,
    options?: ConnectorCallOptions,
  ): ActionSpec {
    return buildConnectorCall({
      kind: "action",
      apiId: API_ID,
      defaultConnectionName: DEFAULT_CONNECTION_NAME,
      operationId: "GetDocuments_V3",
      parameters: parameters as Record<string, ExpressionOrValue>,
      options,
    }) as ActionSpec;
  },

  /**
   * Get stored procedures [DEPRECATED]
   * @deprecated Marked deprecated by Microsoft.
   * @returns - Body - getStoredProceduresResponse
   * Operation id: `GetStoredProcedures`
   */
  getStoredProcedures(
    parameters: {
      databaseId?: ExpressionOrValue; // REQUIRED — Database ID — string — The name of the database.
      collectionId?: ExpressionOrValue; // REQUIRED — Collection ID — string — The name of the collection.
      "x-ms-version"?: ExpressionOrValue; // optional — API version — string — API version.
    } & Record<string, ExpressionOrValue>,
    options?: ConnectorCallOptions,
  ): ActionSpec {
    return buildConnectorCall({
      kind: "action",
      apiId: API_ID,
      defaultConnectionName: DEFAULT_CONNECTION_NAME,
      operationId: "GetStoredProcedures",
      parameters: parameters as Record<string, ExpressionOrValue>,
      options,
    }) as ActionSpec;
  },

  /**
   * Get stored procedures (V2)
   * @returns - Body - getStoredProceduresResponse
   * Operation id: `GetStoredProcedures_V2`
   */
  getStoredProceduresV2(
    parameters: {
      cosmosDbAccountName?: ExpressionOrValue; // REQUIRED — Azure Cosmos DB account name — string — The Azure Cosmos DB account name (without documents.azure.com).
      databaseId?: ExpressionOrValue; // REQUIRED — Database ID — string — The name of the database.
      collectionId?: ExpressionOrValue; // REQUIRED — Collection ID — string — The name of the collection.
      "x-ms-version"?: ExpressionOrValue; // optional — API version — string — API version.
    } & Record<string, ExpressionOrValue>,
    options?: ConnectorCallOptions,
  ): ActionSpec {
    return buildConnectorCall({
      kind: "action",
      apiId: API_ID,
      defaultConnectionName: DEFAULT_CONNECTION_NAME,
      operationId: "GetStoredProcedures_V2",
      parameters: parameters as Record<string, ExpressionOrValue>,
      options,
    }) as ActionSpec;
  },

  /**
   * Query documents [DEPRECATED]
   * @deprecated Marked deprecated by Microsoft.
   * @returns - Body - queryResponse
   * Operation id: `QueryDocuments`
   */
  queryDocuments(
    parameters: {
      databaseId?: ExpressionOrValue; // REQUIRED — Database ID — string — The name of the database.
      collectionId?: ExpressionOrValue; // REQUIRED — Collection ID — string — The name of the collection.
      "x-ms-documentdb-raw-partitionkey"?: ExpressionOrValue; // optional — Partition key value — string — The partition key value for the requested document or attachment operation.
      "x-ms-max-item-count"?: ExpressionOrValue; // optional — Max Item Count — number — An integer indicating the maximum number of items to be returned per page.
      "x-ms-continuation"?: ExpressionOrValue; // optional — Continuation Token — string — A string token returned for queries and read-feed operations if there are more results to be read.
      "x-ms-documentdb-query-enablecrosspartition"?: ExpressionOrValue; // optional — Enable Cross Partition — boolean — If the collection is partitioned, this must be set to True to allow execution across multiple partitions.
      "x-ms-consistency-level"?: ExpressionOrValue; // optional — Consistency Level — string — This is the consistency level override. The valid values are: Strong, Bounded, Session, or Eventual (in order of stronge
      "x-ms-session-token"?: ExpressionOrValue; // optional — Session Token — string — A string token used with session level consistency.
      "x-ms-activity-id"?: ExpressionOrValue; // optional — Activity id — string — A client supplied identifier for the operation, which will be echoed in the server response.
      query?: ExpressionOrValue; // optional — string
    } & Record<string, ExpressionOrValue>,
    options?: ConnectorCallOptions,
  ): ActionSpec {
    return buildConnectorCall({
      kind: "action",
      apiId: API_ID,
      defaultConnectionName: DEFAULT_CONNECTION_NAME,
      operationId: "QueryDocuments",
      parameters: parameters as Record<string, ExpressionOrValue>,
      options,
    }) as ActionSpec;
  },

  /**
   * Query documents V2 [DEPRECATED]
   * @deprecated Marked deprecated by Microsoft.
   * @returns Array of documents that match the requested query and the related metadata. - Body - QueryDocumentsResponse
   * Operation id: `QueryDocumentsV2`
   */
  queryDocumentsV2(
    parameters: {
      databaseId?: ExpressionOrValue; // REQUIRED — Database ID — string — The name of the database.
      collectionId?: ExpressionOrValue; // REQUIRED — Collection ID — string — The name of the collection.
      QueryText?: ExpressionOrValue; // optional — string — SQL Syntax Query over documents
      partitionKey?: ExpressionOrValue; // optional — Partition key value — string — Partition key value.
      continuationToken?: ExpressionOrValue; // optional — Continuation Token — string — A token to fetch additional results from the operation.
    } & Record<string, ExpressionOrValue>,
    options?: ConnectorCallOptions,
  ): ActionSpec {
    return buildConnectorCall({
      kind: "action",
      apiId: API_ID,
      defaultConnectionName: DEFAULT_CONNECTION_NAME,
      operationId: "QueryDocumentsV2",
      parameters: parameters as Record<string, ExpressionOrValue>,
      options,
    }) as ActionSpec;
  },

  /**
   * Query documents V3 [DEPRECATED]
   * @deprecated Marked deprecated by Microsoft.
   * @returns Array of documents that match the requested query and the related metadata. - Body - DocumentsCollection
   * Operation id: `QueryDocumentsV3`
   */
  queryDocumentsV3(
    parameters: {
      databaseId?: ExpressionOrValue; // REQUIRED — Database ID — string — The name of the database.
      collectionId?: ExpressionOrValue; // REQUIRED — Collection ID — string — The name of the collection.
      queryText?: ExpressionOrValue; // REQUIRED — SQL Syntax Query — string — SQL query.
      partitionKey?: ExpressionOrValue; // optional — Partition key value — string — If empty, all partitions will be used to search for documents.
      maxItemCount?: ExpressionOrValue; // optional — Max Item Count — integer — An integer indicating the maximum number of items to be returned per page.
      continuationToken?: ExpressionOrValue; // optional — Continuation Token — string — A token to fetch additional results.
      enableCrossPartition?: ExpressionOrValue; // optional — Enable Cross Partition — boolean — Indicates whether user are enabled to send more than one request to execute the query.
      consistencyLevel?: ExpressionOrValue; // optional — Consistency Level — string — Consistency level required for the feed (query/read feed) operation.
      sessionToken?: ExpressionOrValue; // optional — Session Token — string — The session token for use with session consistency.
    } & Record<string, ExpressionOrValue>,
    options?: ConnectorCallOptions,
  ): ActionSpec {
    return buildConnectorCall({
      kind: "action",
      apiId: API_ID,
      defaultConnectionName: DEFAULT_CONNECTION_NAME,
      operationId: "QueryDocumentsV3",
      parameters: parameters as Record<string, ExpressionOrValue>,
      options,
    }) as ActionSpec;
  },

  /**
   * Query documents V4 [DEPRECATED]
   * @deprecated Marked deprecated by Microsoft.
   * @returns Array of documents that match the requested query and the related metadata. - Body - DocumentsCollection
   * Operation id: `QueryDocumentsV4`
   */
  queryDocumentsV4(
    parameters: {
      databaseId?: ExpressionOrValue; // REQUIRED — Database ID — string — The name of the database.
      containerId?: ExpressionOrValue; // REQUIRED — Container ID — string — The name of the container.
      queryText?: ExpressionOrValue; // optional — SQL Syntax Query — string — SQL query. If empty, will return all documents.
      partitionKey?: ExpressionOrValue; // optional — Partition key value — string — If empty, all partitions will be used to search for documents.
      maxItemCount?: ExpressionOrValue; // optional — Max Item Count — integer — An integer indicating the maximum number of items to be returned per page.
      continuationToken?: ExpressionOrValue; // optional — Continuation Token — string — A token to fetch additional results.
      consistencyLevel?: ExpressionOrValue; // optional — Consistency Level — string — Consistency level required for the feed (query/read feed) operation.
      sessionToken?: ExpressionOrValue; // optional — Session Token — string — The session token for use with session consistency.
    } & Record<string, ExpressionOrValue>,
    options?: ConnectorCallOptions,
  ): ActionSpec {
    return buildConnectorCall({
      kind: "action",
      apiId: API_ID,
      defaultConnectionName: DEFAULT_CONNECTION_NAME,
      operationId: "QueryDocumentsV4",
      parameters: parameters as Record<string, ExpressionOrValue>,
      options,
    }) as ActionSpec;
  },

  /**
   * Query documents V5
   * @returns Array of documents that match the requested query and the related metadata. - Body - DocumentsCollection
   * Operation id: `QueryDocuments_V5`
   */
  queryDocumentsV5(
    parameters: {
      cosmosDbAccountName?: ExpressionOrValue; // REQUIRED — Azure Cosmos DB account name — string — The Azure Cosmos DB account name (without documents.azure.com).
      databaseId?: ExpressionOrValue; // REQUIRED — Database ID — string — The name of the database.
      containerId?: ExpressionOrValue; // REQUIRED — Container ID — string — The name of the container.
      queryText?: ExpressionOrValue; // optional — SQL Syntax Query — string — SQL query. If empty, will return all documents.
      partitionKey?: ExpressionOrValue; // optional — Partition key value — string — Value must be provided according to its type ("string", 42, 0.5). If empty, all partitions will be used to search for do
      maxItemCount?: ExpressionOrValue; // optional — Max Item Count — integer — An integer indicating the maximum number of items to be returned per page.
      continuationToken?: ExpressionOrValue; // optional — Continuation Token — string — A token to fetch additional results.
      consistencyLevel?: ExpressionOrValue; // optional — Consistency Level — string — Consistency level required for the feed (query/read feed) operation.
      sessionToken?: ExpressionOrValue; // optional — Session Token — string — The session token for use with session consistency.
    } & Record<string, ExpressionOrValue>,
    options?: ConnectorCallOptions,
  ): ActionSpec {
    return buildConnectorCall({
      kind: "action",
      apiId: API_ID,
      defaultConnectionName: DEFAULT_CONNECTION_NAME,
      operationId: "QueryDocuments_V5",
      parameters: parameters as Record<string, ExpressionOrValue>,
      options,
    }) as ActionSpec;
  },

  /**
   * Replace a document [DEPRECATED]
   * @deprecated Marked deprecated by Microsoft.
   * @returns - Body - putDocumentResponse
   * Operation id: `ReplaceDocument`
   */
  replaceDocument(
    parameters: {
      databaseId?: ExpressionOrValue; // REQUIRED — Database ID — string — The name of the database.
      collectionId?: ExpressionOrValue; // REQUIRED — Collection ID — string — The name of the collection.
      documentId?: ExpressionOrValue; // REQUIRED — Document ID — string — The identifier of the document.
      "x-ms-documentdb-raw-partitionkey"?: ExpressionOrValue; // optional — Partition key value — string — The partition key value for the requested document or attachment operation.
      "x-ms-max-item-count"?: ExpressionOrValue; // optional — Max Item Count — number — An integer indicating the maximum number of items to be returned per page.
      "x-ms-continuation"?: ExpressionOrValue; // optional — Continuation Token — string — A string token returned for queries and read-feed operations if there are more results to be read.
      "x-ms-consistency-level"?: ExpressionOrValue; // optional — Consistency Level — string — This is the consistency level override. The valid values are: Strong, Bounded, Session, or Eventual (in order of stronge
      "x-ms-session-token"?: ExpressionOrValue; // optional — Session Token — string — A string token used with session level consistency.
      "x-ms-activity-id"?: ExpressionOrValue; // optional — Activity id — string — A client supplied identifier for the operation, which will be echoed in the server response.
      "x-ms-documentdb-pre-trigger-include"?: ExpressionOrValue; // optional — Pre-Trigger — string — Comma-separated list of trigger names to run before the document operation is executed.
      "x-ms-documentdb-post-trigger-include"?: ExpressionOrValue; // optional — Post-Trigger — string — Comma-separated list of trigger names to run after the document operation is executed.
      "x-ms-version"?: ExpressionOrValue; // optional — API version — string — API version.
    } & Record<string, ExpressionOrValue>,
    options?: ConnectorCallOptions,
  ): ActionSpec {
    return buildConnectorCall({
      kind: "action",
      apiId: API_ID,
      defaultConnectionName: DEFAULT_CONNECTION_NAME,
      operationId: "ReplaceDocument",
      parameters: parameters as Record<string, ExpressionOrValue>,
      options,
    }) as ActionSpec;
  },

  /**
   * Replace a document (V2)
   * @returns - Body - putDocumentResponse
   * Operation id: `ReplaceDocument_V2`
   */
  replaceDocumentV2(
    parameters: {
      cosmosDbAccountName?: ExpressionOrValue; // REQUIRED — Azure Cosmos DB account name — string — The Azure Cosmos DB account name (without documents.azure.com).
      databaseId?: ExpressionOrValue; // REQUIRED — Database ID — string — The name of the database.
      collectionId?: ExpressionOrValue; // REQUIRED — Collection ID — string — The name of the collection.
      documentId?: ExpressionOrValue; // REQUIRED — Document ID — string — The identifier of the document.
      "x-ms-documentdb-raw-partitionkey"?: ExpressionOrValue; // optional — Partition key value — string — The partition key value for the requested document or attachment operation.
      "x-ms-max-item-count"?: ExpressionOrValue; // optional — Max Item Count — number — An integer indicating the maximum number of items to be returned per page.
      "x-ms-continuation"?: ExpressionOrValue; // optional — Continuation Token — string — A string token returned for queries and read-feed operations if there are more results to be read.
      "x-ms-consistency-level"?: ExpressionOrValue; // optional — Consistency Level — string — This is the consistency level override. The valid values are: Strong, Bounded, Session, or Eventual (in order of stronge
      "x-ms-session-token"?: ExpressionOrValue; // optional — Session Token — string — A string token used with session level consistency.
      "x-ms-activity-id"?: ExpressionOrValue; // optional — Activity id — string — A client supplied identifier for the operation, which will be echoed in the server response.
      "x-ms-documentdb-pre-trigger-include"?: ExpressionOrValue; // optional — Pre-Trigger — string — Comma-separated list of trigger names to run before the document operation is executed.
      "x-ms-documentdb-post-trigger-include"?: ExpressionOrValue; // optional — Post-Trigger — string — Comma-separated list of trigger names to run after the document operation is executed.
      "x-ms-version"?: ExpressionOrValue; // optional — API version — string — API version.
    } & Record<string, ExpressionOrValue>,
    options?: ConnectorCallOptions,
  ): ActionSpec {
    return buildConnectorCall({
      kind: "action",
      apiId: API_ID,
      defaultConnectionName: DEFAULT_CONNECTION_NAME,
      operationId: "ReplaceDocument_V2",
      parameters: parameters as Record<string, ExpressionOrValue>,
      options,
    }) as ActionSpec;
  },

  /**
   * Replace stored procedure [DEPRECATED]
   * @deprecated Marked deprecated by Microsoft.
   * @returns - Body - createStoredProcedureResponse
   * Operation id: `ReplaceStoredProcedure`
   */
  replaceStoredProcedure(
    parameters: {
      databaseId?: ExpressionOrValue; // REQUIRED — Database ID — string — The name of the database.
      collectionId?: ExpressionOrValue; // REQUIRED — Collection ID — string — The name of the collection.
      sprocId?: ExpressionOrValue; // REQUIRED — Sproc ID — string — The name of the stored procedure.
      body?: ExpressionOrValue; // optional — Function definition — string — Function that defines the stored procedure, e.g. 'function(params){ ... }'
      id?: ExpressionOrValue; // optional — string — Id of the existing stored procedure.
      "x-ms-version"?: ExpressionOrValue; // optional — API version — string — API version.
    } & Record<string, ExpressionOrValue>,
    options?: ConnectorCallOptions,
  ): ActionSpec {
    return buildConnectorCall({
      kind: "action",
      apiId: API_ID,
      defaultConnectionName: DEFAULT_CONNECTION_NAME,
      operationId: "ReplaceStoredProcedure",
      parameters: parameters as Record<string, ExpressionOrValue>,
      options,
    }) as ActionSpec;
  },

  /**
   * Replace stored procedure (V2)
   * @returns - Body - createStoredProcedureResponse
   * Operation id: `ReplaceStoredProcedure_V2`
   */
  replaceStoredProcedureV2(
    parameters: {
      cosmosDbAccountName?: ExpressionOrValue; // REQUIRED — Azure Cosmos DB account name — string — The Azure Cosmos DB account name (without documents.azure.com).
      databaseId?: ExpressionOrValue; // REQUIRED — Database ID — string — The name of the database.
      collectionId?: ExpressionOrValue; // REQUIRED — Collection ID — string — The name of the collection.
      sprocId?: ExpressionOrValue; // REQUIRED — Sproc ID — string — The name of the stored procedure.
      body?: ExpressionOrValue; // optional — Function definition — string — Function that defines the stored procedure, e.g. 'function(params){ ... }'
      id?: ExpressionOrValue; // optional — string — Id of the existing stored procedure.
      "x-ms-version"?: ExpressionOrValue; // optional — API version — string — API version.
    } & Record<string, ExpressionOrValue>,
    options?: ConnectorCallOptions,
  ): ActionSpec {
    return buildConnectorCall({
      kind: "action",
      apiId: API_ID,
      defaultConnectionName: DEFAULT_CONNECTION_NAME,
      operationId: "ReplaceStoredProcedure_V2",
      parameters: parameters as Record<string, ExpressionOrValue>,
      options,
    }) as ActionSpec;
  },
} as const;
