// AUTO-GENERATED by packages/connectors/scripts/generate.ts.
// Do not edit by hand. Re-run `bun --filter @vibeflow/connectors generate`.
// Connector: shared_azurefile — Azure File Storage
// Source: https://learn.microsoft.com/en-us/connectors/azurefile/?accept=text/markdown

import { buildConnectorCall, type ActionSpec, type ConnectorCallOptions, type ExpressionOrValue, type TriggerSpec } from "../_runtime.js";

const API_ID = "/providers/Microsoft.PowerApps/apis/shared_azurefile";
const DEFAULT_CONNECTION_NAME = "shared_azurefile";

export const AzureFileStorage = {
  /** Connector id (`shared_azurefile`). */
  connectorId: "shared_azurefile",
  /** Power Automate apiId for this connector. */
  apiId: API_ID,

  /**
   * Copy file
   * @returns Blob metadata - Body - BlobMetadata
   * Operation id: `CopyFile`
   */
  copyFile(
    parameters: {
      source?: ExpressionOrValue; // REQUIRED — Source url — string — Specify the Url to source file
      destination?: ExpressionOrValue; // REQUIRED — Destination file path — string — Specify the destination file path, including target filename
      overwrite?: ExpressionOrValue; // optional — Overwrite? — boolean — Should the destination file be overwritten (true/false)?
    } & Record<string, ExpressionOrValue>,
    options?: ConnectorCallOptions,
  ): ActionSpec {
    return buildConnectorCall({
      kind: "action",
      apiId: API_ID,
      defaultConnectionName: DEFAULT_CONNECTION_NAME,
      operationId: "CopyFile",
      parameters: parameters as Record<string, ExpressionOrValue>,
      options,
    }) as ActionSpec;
  },

  /**
   * Create file
   * @returns Blob metadata - Body - BlobMetadata
   * Operation id: `CreateFile`
   */
  createFile(
    parameters: {
      folderPath?: ExpressionOrValue; // REQUIRED — Folder path — string — Specify folder path to upload
      name?: ExpressionOrValue; // REQUIRED — File name — string — Specify name of the file to create
      body?: ExpressionOrValue; // REQUIRED — File content — binary — Specify content of the file to upload
    } & Record<string, ExpressionOrValue>,
    options?: ConnectorCallOptions,
  ): ActionSpec {
    return buildConnectorCall({
      kind: "action",
      apiId: API_ID,
      defaultConnectionName: DEFAULT_CONNECTION_NAME,
      operationId: "CreateFile",
      parameters: parameters as Record<string, ExpressionOrValue>,
      options,
    }) as ActionSpec;
  },

  /**
   * Delete file
   * Operation id: `DeleteFile`
   */
  deleteFile(
    parameters: {
      id?: ExpressionOrValue; // REQUIRED — File — string — Specify the file to delete
    } & Record<string, ExpressionOrValue>,
    options?: ConnectorCallOptions,
  ): ActionSpec {
    return buildConnectorCall({
      kind: "action",
      apiId: API_ID,
      defaultConnectionName: DEFAULT_CONNECTION_NAME,
      operationId: "DeleteFile",
      parameters: parameters as Record<string, ExpressionOrValue>,
      options,
    }) as ActionSpec;
  },

  /**
   * Extract archive to folder
   * @returns - response - array of BlobMetadata
   * Operation id: `ExtractFolderV2`
   */
  extractFolderV2(
    parameters: {
      source?: ExpressionOrValue; // REQUIRED — Source archive file path — string — Specify the path to the archive file
      destination?: ExpressionOrValue; // REQUIRED — Destination folder path — string — Specify the path in Azure File Storage to extract the archive contents
      overwrite?: ExpressionOrValue; // optional — Overwrite? — boolean — Should destination file be overwritten (true/false)?
    } & Record<string, ExpressionOrValue>,
    options?: ConnectorCallOptions,
  ): ActionSpec {
    return buildConnectorCall({
      kind: "action",
      apiId: API_ID,
      defaultConnectionName: DEFAULT_CONNECTION_NAME,
      operationId: "ExtractFolderV2",
      parameters: parameters as Record<string, ExpressionOrValue>,
      options,
    }) as ActionSpec;
  },

  /**
   * Get file content
   * @returns The content of the file. - File Content - binary
   * Operation id: `GetFileContent`
   */
  getFileContent(
    parameters: {
      id?: ExpressionOrValue; // REQUIRED — File — string — Specify the file to get contents
      inferContentType?: ExpressionOrValue; // optional — Infer Content Type — boolean — Infer content-type based on extension
    } & Record<string, ExpressionOrValue>,
    options?: ConnectorCallOptions,
  ): ActionSpec {
    return buildConnectorCall({
      kind: "action",
      apiId: API_ID,
      defaultConnectionName: DEFAULT_CONNECTION_NAME,
      operationId: "GetFileContent",
      parameters: parameters as Record<string, ExpressionOrValue>,
      options,
    }) as ActionSpec;
  },

  /**
   * Get file content using path
   * @returns The content of the file. - File Content - binary
   * Operation id: `GetFileContentByPath`
   */
  getFileContentByPath(
    parameters: {
      path?: ExpressionOrValue; // REQUIRED — File path — string — Specify unique path to the file
      inferContentType?: ExpressionOrValue; // optional — Infer Content Type — boolean — Infer content-type based on extension
    } & Record<string, ExpressionOrValue>,
    options?: ConnectorCallOptions,
  ): ActionSpec {
    return buildConnectorCall({
      kind: "action",
      apiId: API_ID,
      defaultConnectionName: DEFAULT_CONNECTION_NAME,
      operationId: "GetFileContentByPath",
      parameters: parameters as Record<string, ExpressionOrValue>,
      options,
    }) as ActionSpec;
  },

  /**
   * Get file metadata
   * @returns Blob metadata - Body - BlobMetadata
   * Operation id: `GetFileMetadata`
   */
  getFileMetadata(
    parameters: {
      id?: ExpressionOrValue; // REQUIRED — File — string — Specify the file to get metadata
    } & Record<string, ExpressionOrValue>,
    options?: ConnectorCallOptions,
  ): ActionSpec {
    return buildConnectorCall({
      kind: "action",
      apiId: API_ID,
      defaultConnectionName: DEFAULT_CONNECTION_NAME,
      operationId: "GetFileMetadata",
      parameters: parameters as Record<string, ExpressionOrValue>,
      options,
    }) as ActionSpec;
  },

  /**
   * Get file metadata using path
   * @returns Blob metadata - Body - BlobMetadata
   * Operation id: `GetFileMetadataByPath`
   */
  getFileMetadataByPath(
    parameters: {
      path?: ExpressionOrValue; // REQUIRED — File path — string — Specify unique path to the file
    } & Record<string, ExpressionOrValue>,
    options?: ConnectorCallOptions,
  ): ActionSpec {
    return buildConnectorCall({
      kind: "action",
      apiId: API_ID,
      defaultConnectionName: DEFAULT_CONNECTION_NAME,
      operationId: "GetFileMetadataByPath",
      parameters: parameters as Record<string, ExpressionOrValue>,
      options,
    }) as ActionSpec;
  },

  /**
   * List files
   * @returns Represents a page of blob metadata. - Body - BlobMetadataPage
   * Operation id: `ListFolderV2`
   */
  listFolderV2(
    parameters: {
      id?: ExpressionOrValue; // REQUIRED — Folder — string — Specify the folder
    } & Record<string, ExpressionOrValue>,
    options?: ConnectorCallOptions,
  ): ActionSpec {
    return buildConnectorCall({
      kind: "action",
      apiId: API_ID,
      defaultConnectionName: DEFAULT_CONNECTION_NAME,
      operationId: "ListFolderV2",
      parameters: parameters as Record<string, ExpressionOrValue>,
      options,
    }) as ActionSpec;
  },

  /**
   * Update file
   * @returns Blob metadata - Body - BlobMetadata
   * Operation id: `UpdateFile`
   */
  updateFile(
    parameters: {
      id?: ExpressionOrValue; // REQUIRED — File — string — Specify the file to update
      body?: ExpressionOrValue; // REQUIRED — File content — binary — Specify the content to update the file with
    } & Record<string, ExpressionOrValue>,
    options?: ConnectorCallOptions,
  ): ActionSpec {
    return buildConnectorCall({
      kind: "action",
      apiId: API_ID,
      defaultConnectionName: DEFAULT_CONNECTION_NAME,
      operationId: "UpdateFile",
      parameters: parameters as Record<string, ExpressionOrValue>,
      options,
    }) as ActionSpec;
  },
} as const;
