// AUTO-GENERATED by packages/connectors/scripts/generate.ts.
// Do not edit by hand. Re-run `bun --filter @vibeflow/connectors generate`.
// Connector: shared_onenote — OneNote (Business)
// Source: https://learn.microsoft.com/en-us/connectors/onenote/?accept=text/markdown

import { buildConnectorCall, type ActionSpec, type ConnectorCallOptions, type ExpressionOrValue, type TriggerSpec } from "../_runtime.js";

const API_ID = "/providers/Microsoft.PowerApps/apis/shared_onenote";
const DEFAULT_CONNECTION_NAME = "shared_onenote";

export const OneNoteBusiness = {
  /** Connector id (`shared_onenote`). */
  connectorId: "shared_onenote",
  /** Power Automate apiId for this connector. */
  apiId: API_ID,

  /**
   * Create a page in Quick Notes
   * @returns - Body - Page
   * Operation id: `CreatePageInQuickNotes`
   */
  createPageInQuickNotes(
    parameters: {
      pageContent?: ExpressionOrValue; // REQUIRED — Page Content — html — Page content.
    } & Record<string, ExpressionOrValue>,
    options?: ConnectorCallOptions,
  ): ActionSpec {
    return buildConnectorCall({
      kind: "action",
      apiId: API_ID,
      defaultConnectionName: DEFAULT_CONNECTION_NAME,
      operationId: "CreatePageInQuickNotes",
      parameters: parameters as Record<string, ExpressionOrValue>,
      options,
    }) as ActionSpec;
  },

  /**
   * Create page in a section
   * @returns - Body - Page
   * Operation id: `CreatePageInSection`
   */
  createPageInSection(
    parameters: {
      notebookKey?: ExpressionOrValue; // REQUIRED — Notebook Key — string — A key identifying the notebook. Note this is specific to the API and cannot be hand-typed.
      sectionId?: ExpressionOrValue; // REQUIRED — Notebook section — string — API URL of the section pages.
      pageContent?: ExpressionOrValue; // REQUIRED — Page Content — html — Page content.
    } & Record<string, ExpressionOrValue>,
    options?: ConnectorCallOptions,
  ): ActionSpec {
    return buildConnectorCall({
      kind: "action",
      apiId: API_ID,
      defaultConnectionName: DEFAULT_CONNECTION_NAME,
      operationId: "CreatePageInSection",
      parameters: parameters as Record<string, ExpressionOrValue>,
      options,
    }) as ActionSpec;
  },

  /**
   * Create section in a notebook
   * @returns - Body - CreateSectionInNotebookResponse
   * Operation id: `CreateSectionInNotebook`
   */
  createSectionInNotebook(
    parameters: {
      notebookKey?: ExpressionOrValue; // REQUIRED — Notebook Key — string — A key identifying the notebook. Note this is specific to the API and cannot be hand-typed.
      name?: ExpressionOrValue; // REQUIRED — Name of the new section — string — The name of the new section.
    } & Record<string, ExpressionOrValue>,
    options?: ConnectorCallOptions,
  ): ActionSpec {
    return buildConnectorCall({
      kind: "action",
      apiId: API_ID,
      defaultConnectionName: DEFAULT_CONNECTION_NAME,
      operationId: "CreateSectionInNotebook",
      parameters: parameters as Record<string, ExpressionOrValue>,
      options,
    }) as ActionSpec;
  },

  /**
   * Delete a page
   * Operation id: `DeletePage`
   */
  deletePage(
    parameters: {
      notebookKey?: ExpressionOrValue; // REQUIRED — Notebook Key — string — A key identifying the notebook. Note this is specific to the API and cannot be hand-typed.
      sectionId?: ExpressionOrValue; // REQUIRED — Notebook section — string — API URL of the section pages.
      pageId?: ExpressionOrValue; // REQUIRED — Page Id — string — Unique id of the page.
    } & Record<string, ExpressionOrValue>,
    options?: ConnectorCallOptions,
  ): ActionSpec {
    return buildConnectorCall({
      kind: "action",
      apiId: API_ID,
      defaultConnectionName: DEFAULT_CONNECTION_NAME,
      operationId: "DeletePage",
      parameters: parameters as Record<string, ExpressionOrValue>,
      options,
    }) as ActionSpec;
  },

  /**
   * Get recent notebooks
   * @returns - response - array of Notebook
   * Operation id: `GetNotebooks`
   */
  getNotebooks(options?: ConnectorCallOptions): ActionSpec {
    return buildConnectorCall({
      kind: "action",
      apiId: API_ID,
      defaultConnectionName: DEFAULT_CONNECTION_NAME,
      operationId: "GetNotebooks",
      parameters: {},
      options,
    }) as ActionSpec;
  },

  /**
   * Get page content
   * @returns The page HTML content - response - string
   * Operation id: `GetPageContent`
   */
  getPageContent(
    parameters: {
      notebookKey?: ExpressionOrValue; // REQUIRED — Notebook Key — string — A key identifying the notebook. Note this is specific to the API and cannot be hand-typed.
      sectionId?: ExpressionOrValue; // REQUIRED — Notebook section — string — API URL of the section pages.
      pageId?: ExpressionOrValue; // REQUIRED — Page Id — string — Unique id of the page.
    } & Record<string, ExpressionOrValue>,
    options?: ConnectorCallOptions,
  ): ActionSpec {
    return buildConnectorCall({
      kind: "action",
      apiId: API_ID,
      defaultConnectionName: DEFAULT_CONNECTION_NAME,
      operationId: "GetPageContent",
      parameters: parameters as Record<string, ExpressionOrValue>,
      options,
    }) as ActionSpec;
  },

  /**
   * Get pages for a specific section
   * @returns - Body - GetPagesInSectionResponse
   * Operation id: `GetPagesInSection`
   */
  getPagesInSection(
    parameters: {
      notebookKey?: ExpressionOrValue; // REQUIRED — Notebook Key — string — A key identifying the notebook. Note this is specific to the API and cannot be hand-typed.
      sectionId?: ExpressionOrValue; // REQUIRED — Notebook section — string — API URL of the section pages.
    } & Record<string, ExpressionOrValue>,
    options?: ConnectorCallOptions,
  ): ActionSpec {
    return buildConnectorCall({
      kind: "action",
      apiId: API_ID,
      defaultConnectionName: DEFAULT_CONNECTION_NAME,
      operationId: "GetPagesInSection",
      parameters: parameters as Record<string, ExpressionOrValue>,
      options,
    }) as ActionSpec;
  },

  /**
   * Get sections in notebook
   * @returns | Name | Path | Type | Description | | --- | --- | --- | --- | | value | value | array of SectionListItem |  |
   * Operation id: `GetSectionsInNotebook`
   */
  getSectionsInNotebook(
    parameters: {
      notebookKey?: ExpressionOrValue; // REQUIRED — Notebook Key — string — A key identifying the notebook. Note this is specific to the API and cannot be hand-typed.
    } & Record<string, ExpressionOrValue>,
    options?: ConnectorCallOptions,
  ): ActionSpec {
    return buildConnectorCall({
      kind: "action",
      apiId: API_ID,
      defaultConnectionName: DEFAULT_CONNECTION_NAME,
      operationId: "GetSectionsInNotebook",
      parameters: parameters as Record<string, ExpressionOrValue>,
      options,
    }) as ActionSpec;
  },

  /**
   * When a new page is created in a section
   * @remarks This is a trigger operation; pass it to flowBuilder.setTrigger().
   * @returns Response for a new page. - Body - NewPageResponse
   * Operation id: `OnNewPageInSection`
   */
  onNewPageInSection(
    parameters: {
      notebookKey?: ExpressionOrValue; // REQUIRED — Notebook Key — string — A key identifying the notebook. Note this is specific to the API and cannot be hand-typed.
      sectionId?: ExpressionOrValue; // REQUIRED — Notebook section — string — API URL of the section pages.
    } & Record<string, ExpressionOrValue>,
    options?: ConnectorCallOptions,
  ): TriggerSpec {
    return buildConnectorCall({
      kind: "trigger",
      apiId: API_ID,
      defaultConnectionName: DEFAULT_CONNECTION_NAME,
      operationId: "OnNewPageInSection",
      parameters: parameters as Record<string, ExpressionOrValue>,
      options,
    }) as TriggerSpec;
  },

  /**
   * When a new section group is created
   * @remarks This is a trigger operation; pass it to flowBuilder.setTrigger().
   * @returns Response for a new section group. - Body - NewSectionGroupResponse
   * Operation id: `OnNewSectionGroupInNotebook`
   */
  onNewSectionGroupInNotebook(
    parameters: {
      notebookKey?: ExpressionOrValue; // REQUIRED — Notebook Key — string — A key identifying the notebook. Note this is specific to the API and cannot be hand-typed.
    } & Record<string, ExpressionOrValue>,
    options?: ConnectorCallOptions,
  ): TriggerSpec {
    return buildConnectorCall({
      kind: "trigger",
      apiId: API_ID,
      defaultConnectionName: DEFAULT_CONNECTION_NAME,
      operationId: "OnNewSectionGroupInNotebook",
      parameters: parameters as Record<string, ExpressionOrValue>,
      options,
    }) as TriggerSpec;
  },

  /**
   * When a new section is created
   * @remarks This is a trigger operation; pass it to flowBuilder.setTrigger().
   * @returns Response for a new section. - Body - NewSectionResponse
   * Operation id: `OnNewSectionInNotebook`
   */
  onNewSectionInNotebook(
    parameters: {
      notebookKey?: ExpressionOrValue; // REQUIRED — Notebook Key — string — A key identifying the notebook. Note this is specific to the API and cannot be hand-typed.
    } & Record<string, ExpressionOrValue>,
    options?: ConnectorCallOptions,
  ): TriggerSpec {
    return buildConnectorCall({
      kind: "trigger",
      apiId: API_ID,
      defaultConnectionName: DEFAULT_CONNECTION_NAME,
      operationId: "OnNewSectionInNotebook",
      parameters: parameters as Record<string, ExpressionOrValue>,
      options,
    }) as TriggerSpec;
  },

  /**
   * Update page content
   * @returns The page HTML content - response - string
   * Operation id: `UpdatePageContent`
   */
  updatePageContent(
    parameters: {
      notebookKey?: ExpressionOrValue; // REQUIRED — Notebook Key — string — A key identifying the notebook. Note this is specific to the API and cannot be hand-typed.
      sectionId?: ExpressionOrValue; // REQUIRED — Notebook section — string — API URL of the section pages.
      pageId?: ExpressionOrValue; // REQUIRED — Page Id — string — Unique id of the page.
      target?: ExpressionOrValue; // optional — Target — string — The element to update.
      action?: ExpressionOrValue; // optional — Action — string — The action to perform on the target element.
      position?: ExpressionOrValue; // optional — Location — string — The location to add the supplied content.
      content?: ExpressionOrValue; // optional — Content — html — The new content.
    } & Record<string, ExpressionOrValue>,
    options?: ConnectorCallOptions,
  ): ActionSpec {
    return buildConnectorCall({
      kind: "action",
      apiId: API_ID,
      defaultConnectionName: DEFAULT_CONNECTION_NAME,
      operationId: "UpdatePageContent",
      parameters: parameters as Record<string, ExpressionOrValue>,
      options,
    }) as ActionSpec;
  },
} as const;
