// AUTO-GENERATED by packages/connectors/scripts/generate.ts.
// Do not edit by hand. Re-run `bun --filter @vibeflow/connectors generate`.
// Connector: shared_excelonlinebusiness — Excel Online (Business)
// Source: https://learn.microsoft.com/en-us/connectors/excelonlinebusiness/?accept=text/markdown

import { buildConnectorCall, type ActionSpec, type ConnectorCallOptions, type ExpressionOrValue, type TriggerSpec } from "../_runtime.js";

const API_ID = "/providers/Microsoft.PowerApps/apis/shared_excelonlinebusiness";
const DEFAULT_CONNECTION_NAME = "shared_excelonlinebusiness";

export const ExcelOnlineBusiness = {
  /** Connector id (`shared_excelonlinebusiness`). */
  connectorId: "shared_excelonlinebusiness",
  /** Power Automate apiId for this connector. */
  apiId: API_ID,

  /**
   * Add a row into a table [DEPRECATED]
   * @deprecated Marked deprecated by Microsoft.
   * Operation id: `AddRow`
   */
  addRow(
    parameters: {
      source?: ExpressionOrValue; // REQUIRED — Location — string — Select from the drop-down or specify one of the following: - "me" - "SharePoint Site URL" - "users/someone's UPN" - "gro
      drive?: ExpressionOrValue; // REQUIRED — Document Library — string — Select a document library from the drop-down.
      file?: ExpressionOrValue; // REQUIRED — File — string — Select an Excel file through File Browse.
      table?: ExpressionOrValue; // REQUIRED — Table — string — Select a table from the drop-down.
      item?: ExpressionOrValue; // REQUIRED — Row — dynamic — Row to insert into the specified Excel table.
    } & Record<string, ExpressionOrValue>,
    options?: ConnectorCallOptions,
  ): ActionSpec {
    return buildConnectorCall({
      kind: "action",
      apiId: API_ID,
      defaultConnectionName: DEFAULT_CONNECTION_NAME,
      operationId: "AddRow",
      parameters: parameters as Record<string, ExpressionOrValue>,
      options,
    }) as ActionSpec;
  },

  /**
   * Add a row into a table
   * @returns The outputs of this operation are dynamic.
   * Operation id: `AddRowV2`
   */
  addRowV2(
    parameters: {
      source?: ExpressionOrValue; // REQUIRED — Location — string — Select from the drop-down or specify one of the following: - "me" - "SharePoint Site URL" - "users/someone's UPN" - "gro
      drive?: ExpressionOrValue; // REQUIRED — Document Library — string — Select a document library from the drop-down.
      file?: ExpressionOrValue; // REQUIRED — File — string — Select an Excel file through File Browse.
      table?: ExpressionOrValue; // REQUIRED — Table — string — Select a table from the drop-down.
      item?: ExpressionOrValue; // REQUIRED — Row — dynamic — Row to add into the specified Excel table.
      dateTimeFormat?: ExpressionOrValue; // optional — DateTime Format — string — DateTime Format.
    } & Record<string, ExpressionOrValue>,
    options?: ConnectorCallOptions,
  ): ActionSpec {
    return buildConnectorCall({
      kind: "action",
      apiId: API_ID,
      defaultConnectionName: DEFAULT_CONNECTION_NAME,
      operationId: "AddRowV2",
      parameters: parameters as Record<string, ExpressionOrValue>,
      options,
    }) as ActionSpec;
  },

  /**
   * Add a key column to a table
   * Operation id: `CreateIdColumn`
   */
  createIdColumn(
    parameters: {
      source?: ExpressionOrValue; // REQUIRED — Location — string — Select from the drop-down or specify one of the following: - "me" - "SharePoint Site URL" - "users/someone's UPN" - "gro
      drive?: ExpressionOrValue; // REQUIRED — Document Library — string — Select a document library from the drop-down.
      file?: ExpressionOrValue; // REQUIRED — File — string — Select an Excel file through File Browse.
      table?: ExpressionOrValue; // REQUIRED — Table — string — Select a table from the drop-down.
      idColumn?: ExpressionOrValue; // optional — Key Column — string — Provide the key column name.
    } & Record<string, ExpressionOrValue>,
    options?: ConnectorCallOptions,
  ): ActionSpec {
    return buildConnectorCall({
      kind: "action",
      apiId: API_ID,
      defaultConnectionName: DEFAULT_CONNECTION_NAME,
      operationId: "CreateIdColumn",
      parameters: parameters as Record<string, ExpressionOrValue>,
      options,
    }) as ActionSpec;
  },

  /**
   * Create table
   * @returns Table metadata - Body - TableMetadata
   * Operation id: `CreateTable`
   */
  createTable(
    parameters: {
      source?: ExpressionOrValue; // REQUIRED — Location — string — Select from the drop-down or specify one of the following: - "me" - "SharePoint Site URL" - "users/someone's UPN" - "gro
      drive?: ExpressionOrValue; // REQUIRED — Document Library — string — Select a document library from the drop-down.
      file?: ExpressionOrValue; // REQUIRED — File — string — Select an Excel file through File Browse.
      Range?: ExpressionOrValue; // REQUIRED — Table range — string — Enter the table address using A1 notation.
      TableName?: ExpressionOrValue; // optional — Table name — string — Enter the Excel table name.
      ColumnsNames?: ExpressionOrValue; // optional — Columns names — string — Enter the columns names separated by ';' or ','.
    } & Record<string, ExpressionOrValue>,
    options?: ConnectorCallOptions,
  ): ActionSpec {
    return buildConnectorCall({
      kind: "action",
      apiId: API_ID,
      defaultConnectionName: DEFAULT_CONNECTION_NAME,
      operationId: "CreateTable",
      parameters: parameters as Record<string, ExpressionOrValue>,
      options,
    }) as ActionSpec;
  },

  /**
   * Create worksheet
   * @returns - Body - WorksheetMetadata
   * Operation id: `CreateWorksheet`
   */
  createWorksheet(
    parameters: {
      source?: ExpressionOrValue; // REQUIRED — Location — string — Select from the drop-down or specify one of the following: - "me" - "SharePoint Site URL" - "users/someone's UPN" - "gro
      drive?: ExpressionOrValue; // REQUIRED — Document Library — string — Select a document library from the drop-down.
      file?: ExpressionOrValue; // REQUIRED — File — string — Select an Excel file through File Browse.
      name?: ExpressionOrValue; // optional — Name — string — Worksheet name.
    } & Record<string, ExpressionOrValue>,
    options?: ConnectorCallOptions,
  ): ActionSpec {
    return buildConnectorCall({
      kind: "action",
      apiId: API_ID,
      defaultConnectionName: DEFAULT_CONNECTION_NAME,
      operationId: "CreateWorksheet",
      parameters: parameters as Record<string, ExpressionOrValue>,
      options,
    }) as ActionSpec;
  },

  /**
   * Delete a row
   * Operation id: `DeleteItem`
   */
  deleteItem(
    parameters: {
      source?: ExpressionOrValue; // REQUIRED — Location — string — Select from the drop-down or specify one of the following: - "me" - "SharePoint Site URL" - "users/someone's UPN" - "gro
      drive?: ExpressionOrValue; // REQUIRED — Document Library — string — Select a document library from the drop-down.
      file?: ExpressionOrValue; // REQUIRED — File — string — Select an Excel file through File Browse.
      table?: ExpressionOrValue; // REQUIRED — Table — string — Select a table from the drop-down.
      idColumn?: ExpressionOrValue; // REQUIRED — Key Column — string — Select a column from the drop-down.
      id?: ExpressionOrValue; // REQUIRED — Key Value — string — Enter the key value.
    } & Record<string, ExpressionOrValue>,
    options?: ConnectorCallOptions,
  ): ActionSpec {
    return buildConnectorCall({
      kind: "action",
      apiId: API_ID,
      defaultConnectionName: DEFAULT_CONNECTION_NAME,
      operationId: "DeleteItem",
      parameters: parameters as Record<string, ExpressionOrValue>,
      options,
    }) as ActionSpec;
  },

  /**
   * Get worksheets
   * @returns | Name | Path | Type | Description | | --- | --- | --- | --- | | value | value | array of WorksheetMetadata |  | | sensitivityLabelInfo | sensitivityLabelInfo | array of SensitivityLabelMetadata |  |
   * Operation id: `GetAllWorksheets`
   */
  getAllWorksheets(
    parameters: {
      source?: ExpressionOrValue; // REQUIRED — Location — string — Select from the drop-down or specify one of the following: - "me" - "SharePoint Site URL" - "users/someone's UPN" - "gro
      drive?: ExpressionOrValue; // REQUIRED — Document Library — string — Select a document library from the drop-down.
      file?: ExpressionOrValue; // REQUIRED — File — string — Select an Excel file through File Browse.
      extractSensitivityLabel?: ExpressionOrValue; // optional — Extract Sensitivity Label — boolean — A boolean whether to extract sensitivity label Id for associated artefact.
      fetchSensitivityLabelMetadata?: ExpressionOrValue; // optional — Sensitivity Label Metadata — boolean — A boolean whether to fetch sensitivity label Metadata for associated LabelId.
    } & Record<string, ExpressionOrValue>,
    options?: ConnectorCallOptions,
  ): ActionSpec {
    return buildConnectorCall({
      kind: "action",
      apiId: API_ID,
      defaultConnectionName: DEFAULT_CONNECTION_NAME,
      operationId: "GetAllWorksheets",
      parameters: parameters as Record<string, ExpressionOrValue>,
      options,
    }) as ActionSpec;
  },

  /**
   * Get a row
   * @returns The outputs of this operation are dynamic.
   * Operation id: `GetItem`
   */
  getItem(
    parameters: {
      source?: ExpressionOrValue; // REQUIRED — Location — string — Select from the drop-down or specify one of the following: - "me" - "SharePoint Site URL" - "users/someone's UPN" - "gro
      drive?: ExpressionOrValue; // REQUIRED — Document Library — string — Select a document library from the drop-down.
      file?: ExpressionOrValue; // REQUIRED — File — string — Select an Excel file through File Browse.
      table?: ExpressionOrValue; // REQUIRED — Table — string — Select a table from the drop-down.
      idColumn?: ExpressionOrValue; // REQUIRED — Key Column — string — Select a column from the drop-down.
      id?: ExpressionOrValue; // REQUIRED — Key Value — string — Enter the key value.
      dateTimeFormat?: ExpressionOrValue; // optional — DateTime Format — string — DateTime Format.
      extractSensitivityLabel?: ExpressionOrValue; // optional — Extract Sensitivity Label — boolean — A boolean whether to extract sensitivity label Id for associated artefact.
      fetchSensitivityLabelMetadata?: ExpressionOrValue; // optional — Sensitivity Label Metadata — boolean — A boolean whether to fetch sensitivity label Metadata for associated LabelId.
    } & Record<string, ExpressionOrValue>,
    options?: ConnectorCallOptions,
  ): ActionSpec {
    return buildConnectorCall({
      kind: "action",
      apiId: API_ID,
      defaultConnectionName: DEFAULT_CONNECTION_NAME,
      operationId: "GetItem",
      parameters: parameters as Record<string, ExpressionOrValue>,
      options,
    }) as ActionSpec;
  },

  /**
   * List rows present in a table
   * @returns The outputs of this operation are dynamic.
   * Operation id: `GetItems`
   */
  getItems(
    parameters: {
      source?: ExpressionOrValue; // REQUIRED — Location — string — Select from the drop-down or specify one of the following: - "me" - "SharePoint Site URL" - "users/someone's UPN" - "gro
      drive?: ExpressionOrValue; // REQUIRED — Document Library — string — Select a document library from the drop-down.
      file?: ExpressionOrValue; // REQUIRED — File — string — Select an Excel file through File Browse.
      table?: ExpressionOrValue; // REQUIRED — Table — string — Select a table from the drop-down.
      $filter?: ExpressionOrValue; // optional — Filter Query — string — An ODATA filter query to restrict the entries returned.
      $orderby?: ExpressionOrValue; // optional — Order By — string — An ODATA orderBy query for specifying the order of entries.
      $top?: ExpressionOrValue; // optional — Top Count — integer — Total number of entries to retrieve (default = all).
      $skip?: ExpressionOrValue; // optional — Skip Count — integer — The number of entries to skip (default = 0).
      $select?: ExpressionOrValue; // optional — Select Query — string — Comma-separated list of columns to retrieve (first 500 by default).
      dateTimeFormat?: ExpressionOrValue; // optional — DateTime Format — string — DateTime Format.
      extractSensitivityLabel?: ExpressionOrValue; // optional — Extract Sensitivity Label — boolean — A boolean whether to extract sensitivity label Id for associated artefact.
      fetchSensitivityLabelMetadata?: ExpressionOrValue; // optional — Sensitivity Label Metadata — boolean — A boolean whether to fetch sensitivity label Metadata for associated LabelId.
    } & Record<string, ExpressionOrValue>,
    options?: ConnectorCallOptions,
  ): ActionSpec {
    return buildConnectorCall({
      kind: "action",
      apiId: API_ID,
      defaultConnectionName: DEFAULT_CONNECTION_NAME,
      operationId: "GetItems",
      parameters: parameters as Record<string, ExpressionOrValue>,
      options,
    }) as ActionSpec;
  },

  /**
   * Get tables
   * @returns | Name | Path | Type | Description | | --- | --- | --- | --- | | value | value | array of object |  | | Id | value.id | string | Table Id. |
   * Operation id: `GetTables`
   */
  getTables(
    parameters: {
      source?: ExpressionOrValue; // REQUIRED — Location — string — Select from the drop-down or specify one of the following: - "me" - "SharePoint Site URL" - "users/someone's UPN" - "gro
      drive?: ExpressionOrValue; // REQUIRED — Document Library — string — Select a document library from the drop-down.
      file?: ExpressionOrValue; // REQUIRED — File — string — Select an Excel file through File Browse.
      extractSensitivityLabel?: ExpressionOrValue; // optional — Extract Sensitivity Label — boolean — A boolean whether to extract sensitivity label Id for associated artefact.
      fetchSensitivityLabelMetadata?: ExpressionOrValue; // optional — Sensitivity Label Metadata — boolean — A boolean whether to fetch sensitivity label Metadata for associated LabelId.
    } & Record<string, ExpressionOrValue>,
    options?: ConnectorCallOptions,
  ): ActionSpec {
    return buildConnectorCall({
      kind: "action",
      apiId: API_ID,
      defaultConnectionName: DEFAULT_CONNECTION_NAME,
      operationId: "GetTables",
      parameters: parameters as Record<string, ExpressionOrValue>,
      options,
    }) as ActionSpec;
  },

  /**
   * For a selected row
   * @remarks This is a trigger operation; pass it to flowBuilder.setTrigger().
   * @returns | Name | Path | Type | Description | | --- | --- | --- | --- | | rows | body.rows | array of object |  | | items | body.rows | object |  |
   * Operation id: `OnRowSelected`
   */
  onRowSelected(
    parameters: {
      operationId?: ExpressionOrValue; // REQUIRED — string
      parameters?: ExpressionOrValue; // REQUIRED — object
      schema?: ExpressionOrValue; // REQUIRED — object
      host?: ExpressionOrValue; // optional — object
      headersSchema?: ExpressionOrValue; // optional — object
    } & Record<string, ExpressionOrValue>,
    options?: ConnectorCallOptions,
  ): TriggerSpec {
    return buildConnectorCall({
      kind: "trigger",
      apiId: API_ID,
      defaultConnectionName: DEFAULT_CONNECTION_NAME,
      operationId: "OnRowSelected",
      parameters: parameters as Record<string, ExpressionOrValue>,
      options,
    }) as TriggerSpec;
  },

  /**
   * Update a row
   * @returns The outputs of this operation are dynamic.
   * Operation id: `PatchItem`
   */
  patchItem(
    parameters: {
      source?: ExpressionOrValue; // REQUIRED — Location — string — Select from the drop-down or specify one of the following: - "me" - "SharePoint Site URL" - "users/someone's UPN" - "gro
      drive?: ExpressionOrValue; // REQUIRED — Document Library — string — Select a document library from the drop-down.
      file?: ExpressionOrValue; // REQUIRED — File — string — Select an Excel file through File Browse.
      table?: ExpressionOrValue; // REQUIRED — Table — string — Select a table from the drop-down.
      idColumn?: ExpressionOrValue; // REQUIRED — Key Column — string — Select a column from the drop-down.
      id?: ExpressionOrValue; // REQUIRED — Key Value — string — Enter the key value.
      item?: ExpressionOrValue; // REQUIRED — Provide the item properties — dynamic — Provide the item properties.
      dateTimeFormat?: ExpressionOrValue; // optional — DateTime Format — string — DateTime Format.
    } & Record<string, ExpressionOrValue>,
    options?: ConnectorCallOptions,
  ): ActionSpec {
    return buildConnectorCall({
      kind: "action",
      apiId: API_ID,
      defaultConnectionName: DEFAULT_CONNECTION_NAME,
      operationId: "PatchItem",
      parameters: parameters as Record<string, ExpressionOrValue>,
      options,
    }) as ActionSpec;
  },

  /**
   * Run script
   * @returns The outputs of this operation are dynamic.
   * Operation id: `RunScriptProd`
   */
  runScriptProd(
    parameters: {
      source?: ExpressionOrValue; // REQUIRED — Location — string — Select from the drop-down or specify one of the following: - "me" - "SharePoint Site URL" - "users/someone's UPN" - "gro
      drive?: ExpressionOrValue; // REQUIRED — Document Library — string — Select a document library from the drop-down.
      file?: ExpressionOrValue; // REQUIRED — File — string — Select an Excel file through File Browse.
      scriptId?: ExpressionOrValue; // REQUIRED — Script — string — Select the Office Script you want to run from the drop-down.
      ScriptParameters?: ExpressionOrValue; // REQUIRED — dynamic — Provide the Office Script's parameters.
    } & Record<string, ExpressionOrValue>,
    options?: ConnectorCallOptions,
  ): ActionSpec {
    return buildConnectorCall({
      kind: "action",
      apiId: API_ID,
      defaultConnectionName: DEFAULT_CONNECTION_NAME,
      operationId: "RunScriptProd",
      parameters: parameters as Record<string, ExpressionOrValue>,
      options,
    }) as ActionSpec;
  },

  /**
   * Run script from SharePoint library
   * @returns The outputs of this operation are dynamic.
   * Operation id: `RunScriptProdV2`
   */
  runScriptProdV2(
    parameters: {
      source?: ExpressionOrValue; // REQUIRED — Workbook Location — string — Select from the drop-down or specify one of the following: - "me" - "SharePoint Site URL" - "users/someone's UPN" - "gro
      drive?: ExpressionOrValue; // REQUIRED — Workbook Library — string — Select a document library from the drop-down.
      file?: ExpressionOrValue; // REQUIRED — Workbook — string — Select an Excel workbook through File Browse.
      scriptSource?: ExpressionOrValue; // REQUIRED — Script Location — string — Select from the drop-down or specify one of the following: - "me" - "SharePoint Site URL" - "users/someone's UPN" - "gro
      scriptDrive?: ExpressionOrValue; // REQUIRED — Script Library — string — Select the SharePoint library of your Office Script file (.osts) from the drop-down.
      scriptId?: ExpressionOrValue; // REQUIRED — Script — string — Select an Office Script file (.osts) in a SharePoint library from the drop-down.
      ScriptParameters?: ExpressionOrValue; // REQUIRED — dynamic — Provide parameters for the Office Script.
    } & Record<string, ExpressionOrValue>,
    options?: ConnectorCallOptions,
  ): ActionSpec {
    return buildConnectorCall({
      kind: "action",
      apiId: API_ID,
      defaultConnectionName: DEFAULT_CONNECTION_NAME,
      operationId: "RunScriptProdV2",
      parameters: parameters as Record<string, ExpressionOrValue>,
      options,
    }) as ActionSpec;
  },
} as const;
