// AUTO-GENERATED by packages/connectors/scripts/generate.ts.
// Do not edit by hand. Re-run `bun --filter @vibeflow/connectors generate`.
// Connector: shared_bingsearch — Bing Search
// Source: https://learn.microsoft.com/en-us/connectors/bingsearch/?accept=text/markdown

import { buildConnectorCall, type ActionSpec, type ConnectorCallOptions, type ExpressionOrValue, type TriggerSpec } from "../_runtime.js";

const API_ID = "/providers/Microsoft.PowerApps/apis/shared_bingsearch";
const DEFAULT_CONNECTION_NAME = "shared_bingsearch";

export const BingSearch = {
  /** Connector id (`shared_bingsearch`). */
  connectorId: "shared_bingsearch",
  /** Power Automate apiId for this connector. */
  apiId: API_ID,

  /**
   * List news by query
   * @returns - Items - BingNewsBatch
   * Operation id: `GetNews`
   */
  getNews(
    parameters: {
      q?: ExpressionOrValue; // REQUIRED — Search Query — string — The search query string.
      mkt?: ExpressionOrValue; // optional — Market — string — The market where the results come from. Typically, this is the country where the user is making the request from; howeve
      safeSearch?: ExpressionOrValue; // optional — Safe Search — string — A filter used to filter results for adult content.
      count?: ExpressionOrValue; // optional — Count — string — The number of search results to return in the response. The actual number delivered may be less than requested.
      offset?: ExpressionOrValue; // optional — Offset — string — The zero-based offset that indicates the number of search results to skip before returning results.
    } & Record<string, ExpressionOrValue>,
    options?: ConnectorCallOptions,
  ): ActionSpec {
    return buildConnectorCall({
      kind: "action",
      apiId: API_ID,
      defaultConnectionName: DEFAULT_CONNECTION_NAME,
      operationId: "GetNews",
      parameters: parameters as Record<string, ExpressionOrValue>,
      options,
    }) as ActionSpec;
  },

  /**
   * On new news article
   * @remarks This is a trigger operation; pass it to flowBuilder.setTrigger().
   * @returns - Body - NewsArticle
   * Operation id: `TrigNewNews`
   */
  trigNewNews(
    parameters: {
      q?: ExpressionOrValue; // REQUIRED — Search Query — string — The search query string.
      mkt?: ExpressionOrValue; // optional — Market — string — The market where the results come from. Typically, this is the country where the user is making the request from; howeve
      safeSearch?: ExpressionOrValue; // optional — Safe Search — string — A filter used to filter results for adult content.
      count?: ExpressionOrValue; // optional — Count — string — The number of search results to return in the response. The actual number delivered may be less than requested.
      offset?: ExpressionOrValue; // optional — Offset — string — The zero-based offset that indicates the number of search results to skip before returning results.
    } & Record<string, ExpressionOrValue>,
    options?: ConnectorCallOptions,
  ): TriggerSpec {
    return buildConnectorCall({
      kind: "trigger",
      apiId: API_ID,
      defaultConnectionName: DEFAULT_CONNECTION_NAME,
      operationId: "TrigNewNews",
      parameters: parameters as Record<string, ExpressionOrValue>,
      options,
    }) as TriggerSpec;
  },
} as const;
