// AUTO-GENERATED by packages/connectors/scripts/generate.ts.
// Do not edit by hand. Re-run `bun --filter @vibeflow/connectors generate`.
// Connector: shared_powerappsforadmins — Power Apps for Admins
// Source: https://learn.microsoft.com/en-us/connectors/powerappsforadmins/?accept=text/markdown

import { buildConnectorCall, type ActionSpec, type ConnectorCallOptions, type ExpressionOrValue, type TriggerSpec } from "../_runtime.js";

const API_ID = "/providers/Microsoft.PowerApps/apis/shared_powerappsforadmins";
const DEFAULT_CONNECTION_NAME = "shared_powerappsforadmins";

export const PowerAppsForAdmins = {
  /** Connector id (`shared_powerappsforadmins`). */
  connectorId: "shared_powerappsforadmins",
  /** Power Automate apiId for this connector. */
  apiId: API_ID,

  /**
   * Edit App Role Assignment as Admin
   * @returns | Name | Path | Type | Description | | --- | --- | --- | --- | | put | put | array of object | App Role Assignment put object. | | id | put.id | string | App Role Assignment ID field. |
   * Operation id: `Edit-AdminAppRoleAssignment`
   */
  editAdminAppRoleAssignment(
    parameters: {
      environment?: ExpressionOrValue; // REQUIRED — Environment Name — string — Name field of the Environment.
      app?: ExpressionOrValue; // REQUIRED — PowerApp Name — string — Name field of the PowerApp.
      "api-version"?: ExpressionOrValue; // optional — API Version — string — The date value of the API version.
      $filter?: ExpressionOrValue; // optional — Filter Query — string — A filter query parameter.
      roleName?: ExpressionOrValue; // optional — Role Name — string — The name of the permission role. Choose from CanView, CanViewWithShare, and CanEdit.
      capabilities?: ExpressionOrValue; // optional — array of string — capabilities
      NotifyShareTargetOption?: ExpressionOrValue; // optional — Notify Share Target Option — string — Notifies the new user if provided the string value 'Notify'.
      email?: ExpressionOrValue; // optional — Principal Email — string — The principal email of the user.
      id?: ExpressionOrValue; // optional — Principal Object ID — string — The principal object ID of the user.
      "type"?: ExpressionOrValue; // optional — Principal Type — string — The principal type of the user.
      tenantId?: ExpressionOrValue; // optional — Tenant ID — string — The principal tenant ID of the user.
    } & Record<string, ExpressionOrValue>,
    options?: ConnectorCallOptions,
  ): ActionSpec {
    return buildConnectorCall({
      kind: "action",
      apiId: API_ID,
      defaultConnectionName: DEFAULT_CONNECTION_NAME,
      operationId: "Edit-AdminAppRoleAssignment",
      parameters: parameters as Record<string, ExpressionOrValue>,
      options,
    }) as ActionSpec;
  },

  /**
   * Edit Connection Role Assignment as Admin
   * Operation id: `Edit-AdminConnectionRoleAssignment`
   */
  editAdminConnectionRoleAssignment(
    parameters: {
      environment?: ExpressionOrValue; // REQUIRED — Environment Name — string — Name field of the Environment.
      connector?: ExpressionOrValue; // REQUIRED — Connector Name — string — Name field of the Connector.
      connection?: ExpressionOrValue; // REQUIRED — Connection Name — string — Name field of the Connection.
      "api-version"?: ExpressionOrValue; // optional — API Version — string — The date value of the API version.
      "Content-Type"?: ExpressionOrValue; // optional — Field Content Type — string — The content type of the API request.
      id?: ExpressionOrValue; // optional — Role ID — string — The ID field of the Role Assignment.
      roleName?: ExpressionOrValue; // optional — Role Name — string — The name of the permission role.
    } & Record<string, ExpressionOrValue>,
    options?: ConnectorCallOptions,
  ): ActionSpec {
    return buildConnectorCall({
      kind: "action",
      apiId: API_ID,
      defaultConnectionName: DEFAULT_CONNECTION_NAME,
      operationId: "Edit-AdminConnectionRoleAssignment",
      parameters: parameters as Record<string, ExpressionOrValue>,
      options,
    }) as ActionSpec;
  },

  /**
   * Edit Connector Role Assignment as Admin
   * Operation id: `Edit-AdminConnectorRoleAssignment`
   */
  editAdminConnectorRoleAssignment(
    parameters: {
      environment?: ExpressionOrValue; // REQUIRED — Environment Name — string — Name field of the Environment.
      connectorName?: ExpressionOrValue; // REQUIRED — Connector Name — string — Name field of the Connector.
      "api-version"?: ExpressionOrValue; // optional — API Version — string — The date value of the API version.
      "Content-Type"?: ExpressionOrValue; // optional — Field Content Type — string — The content type of the API request.
      id?: ExpressionOrValue; // optional — Role ID — string — The ID field of the Role Assignment.
      roleName?: ExpressionOrValue; // optional — Role Name — string — The name of the role.
    } & Record<string, ExpressionOrValue>,
    options?: ConnectorCallOptions,
  ): ActionSpec {
    return buildConnectorCall({
      kind: "action",
      apiId: API_ID,
      defaultConnectionName: DEFAULT_CONNECTION_NAME,
      operationId: "Edit-AdminConnectorRoleAssignment",
      parameters: parameters as Record<string, ExpressionOrValue>,
      options,
    }) as ActionSpec;
  },

  /**
   * Get App as Admin
   * @returns - Body - PowerApp
   * Operation id: `Get-AdminApp`
   */
  getAdminApp(
    parameters: {
      environment?: ExpressionOrValue; // REQUIRED — Environment Name — string — Name field of the Environment.
      app?: ExpressionOrValue; // REQUIRED — PowerApp Name — string — Name field of the PowerApp.
      "api-version"?: ExpressionOrValue; // optional — API Version — string — The date value of the API version.
    } & Record<string, ExpressionOrValue>,
    options?: ConnectorCallOptions,
  ): ActionSpec {
    return buildConnectorCall({
      kind: "action",
      apiId: API_ID,
      defaultConnectionName: DEFAULT_CONNECTION_NAME,
      operationId: "Get-AdminApp",
      parameters: parameters as Record<string, ExpressionOrValue>,
      options,
    }) as ActionSpec;
  },

  /**
   * Get App Role Assignments as Admin
   * @returns | Name | Path | Type | Description | | --- | --- | --- | --- | | value | value | array of object | PowerApp Role Assignment value array. | | Name | value.name | string | PowerApp Role Assignment name field. |
   * Operation id: `Get-AdminAppRoleAssignment`
   */
  getAdminAppRoleAssignment(
    parameters: {
      environment?: ExpressionOrValue; // REQUIRED — Environment Name — string — Name field of the Environment.
      app?: ExpressionOrValue; // REQUIRED — PowerApp Name — string — Name field of the PowerApp.
      "api-version"?: ExpressionOrValue; // optional — API Version — string — The date value of the API version.
      $top?: ExpressionOrValue; // optional — Page size — integer — Number of App Role Assignments in the response.
    } & Record<string, ExpressionOrValue>,
    options?: ConnectorCallOptions,
  ): ActionSpec {
    return buildConnectorCall({
      kind: "action",
      apiId: API_ID,
      defaultConnectionName: DEFAULT_CONNECTION_NAME,
      operationId: "Get-AdminAppRoleAssignment",
      parameters: parameters as Record<string, ExpressionOrValue>,
      options,
    }) as ActionSpec;
  },

  /**
   * Get Apps as Admin
   * @returns - Body - ResourceArray[PowerApp]
   * Operation id: `Get-AdminApps`
   */
  getAdminApps(
    parameters: {
      environment?: ExpressionOrValue; // REQUIRED — Environment Name — string — Name field of the Environment.
      "api-version"?: ExpressionOrValue; // optional — API Version — string — The date value of the API version.
      $top?: ExpressionOrValue; // optional — Page size — integer — Number of Apps in the response.
      $skiptoken?: ExpressionOrValue; // optional — Skip token — string — Used to get next page of responses.
    } & Record<string, ExpressionOrValue>,
    options?: ConnectorCallOptions,
  ): ActionSpec {
    return buildConnectorCall({
      kind: "action",
      apiId: API_ID,
      defaultConnectionName: DEFAULT_CONNECTION_NAME,
      operationId: "Get-AdminApps",
      parameters: parameters as Record<string, ExpressionOrValue>,
      options,
    }) as ActionSpec;
  },

  /**
   * Get Connection Role Assignments as Admin
   * @returns | Name | Path | Type | Description | | --- | --- | --- | --- | | value | value | array of object | Connection Role Assignment value array. | | name | value.name | string | Connection Role Assignment name field. |
   * Operation id: `Get-AdminConnectionRoleAssignment`
   */
  getAdminConnectionRoleAssignment(
    parameters: {
      environment?: ExpressionOrValue; // REQUIRED — Environment Name — string — Name field of the Environment.
      connectorName?: ExpressionOrValue; // REQUIRED — Connector Name — string — Name field of the Connector.
      connectionName?: ExpressionOrValue; // REQUIRED — Connection Name — string — Name field of the Connection.
      "api-version"?: ExpressionOrValue; // optional — API Version — string — The date value of the API version.
      $top?: ExpressionOrValue; // optional — Page size — integer — Number of Connection Role Assignments in the response.
    } & Record<string, ExpressionOrValue>,
    options?: ConnectorCallOptions,
  ): ActionSpec {
    return buildConnectorCall({
      kind: "action",
      apiId: API_ID,
      defaultConnectionName: DEFAULT_CONNECTION_NAME,
      operationId: "Get-AdminConnectionRoleAssignment",
      parameters: parameters as Record<string, ExpressionOrValue>,
      options,
    }) as ActionSpec;
  },

  /**
   * Get Connections as Admin
   * @returns | Name | Path | Type | Description | | --- | --- | --- | --- | | value | value | array of object | Connection value array. | | name | value.name | string | Connection name field. |
   * Operation id: `Get-AdminConnections`
   */
  getAdminConnections(
    parameters: {
      environment?: ExpressionOrValue; // REQUIRED — Environment Name — string — Name field of the Environment.
      "api-version"?: ExpressionOrValue; // optional — API Version — string — The date value of the API version.
      $top?: ExpressionOrValue; // optional — Page size — integer — Number of Connections in the response.
    } & Record<string, ExpressionOrValue>,
    options?: ConnectorCallOptions,
  ): ActionSpec {
    return buildConnectorCall({
      kind: "action",
      apiId: API_ID,
      defaultConnectionName: DEFAULT_CONNECTION_NAME,
      operationId: "Get-AdminConnections",
      parameters: parameters as Record<string, ExpressionOrValue>,
      options,
    }) as ActionSpec;
  },

  /**
   * Get Connector Role Assignments as Admin
   * @returns | Name | Path | Type | Description | | --- | --- | --- | --- | | value | value | array of object | value | | name | value.name | string | Connector Role Assignment name field. |
   * Operation id: `Get-AdminConnectorRoleAssignment`
   */
  getAdminConnectorRoleAssignment(
    parameters: {
      environment?: ExpressionOrValue; // REQUIRED — Environment Name — string — Name field of the Environment.
      connectorName?: ExpressionOrValue; // REQUIRED — Connector Name — string — Name field of the Connector.
      "api-version"?: ExpressionOrValue; // optional — API Version — string — The date value of the API version.
      $top?: ExpressionOrValue; // optional — Page size — integer — Number of Connector Role Assignments in the response.
    } & Record<string, ExpressionOrValue>,
    options?: ConnectorCallOptions,
  ): ActionSpec {
    return buildConnectorCall({
      kind: "action",
      apiId: API_ID,
      defaultConnectionName: DEFAULT_CONNECTION_NAME,
      operationId: "Get-AdminConnectorRoleAssignment",
      parameters: parameters as Record<string, ExpressionOrValue>,
      options,
    }) as ActionSpec;
  },

  /**
   * Get Custom Connectors as Admin
   * @returns | Name | Path | Type | Description | | --- | --- | --- | --- | | value | value | array of object | value | | name | value.name | string | Connector name field. |
   * Operation id: `Get-AdminConnectors`
   */
  getAdminConnectors(
    parameters: {
      environment?: ExpressionOrValue; // REQUIRED — Environment Name — string — Name field of the Environment.
      "api-version"?: ExpressionOrValue; // optional — API Version — string — The date value of the API version.
      $top?: ExpressionOrValue; // optional — Page size — integer — Number of Custom Connectors in the response.
    } & Record<string, ExpressionOrValue>,
    options?: ConnectorCallOptions,
  ): ActionSpec {
    return buildConnectorCall({
      kind: "action",
      apiId: API_ID,
      defaultConnectionName: DEFAULT_CONNECTION_NAME,
      operationId: "Get-AdminConnectors",
      parameters: parameters as Record<string, ExpressionOrValue>,
      options,
    }) as ActionSpec;
  },

  /**
   * Get PowerApp Conditional Access
   * @returns | Name | Path | Type | Description | | --- | --- | --- | --- | |  |  | array of string | Conditional Access Properties. |
   * Operation id: `Get-PowerAppConditionalAccess`
   */
  getPowerAppConditionalAccess(
    parameters: {
      environment?: ExpressionOrValue; // REQUIRED — Environment Name — string — Name field of the Environment.
      app?: ExpressionOrValue; // REQUIRED — PowerApp Name — string — Name field of the PowerApp.
      "api-version"?: ExpressionOrValue; // optional — API Version — string — The date value of the API version.
    } & Record<string, ExpressionOrValue>,
    options?: ConnectorCallOptions,
  ): ActionSpec {
    return buildConnectorCall({
      kind: "action",
      apiId: API_ID,
      defaultConnectionName: DEFAULT_CONNECTION_NAME,
      operationId: "Get-PowerAppConditionalAccess",
      parameters: parameters as Record<string, ExpressionOrValue>,
      options,
    }) as ActionSpec;
  },

  /**
   * Remove App as Admin
   * Operation id: `Remove-AdminApp`
   */
  removeAdminApp(
    parameters: {
      environment?: ExpressionOrValue; // REQUIRED — Environment Name — string — Name field of the Environment.
      app?: ExpressionOrValue; // REQUIRED — PowerApp Name — string — Name field of the PowerApp.
      "api-version"?: ExpressionOrValue; // optional — API Version — string — The date value of the API version.
    } & Record<string, ExpressionOrValue>,
    options?: ConnectorCallOptions,
  ): ActionSpec {
    return buildConnectorCall({
      kind: "action",
      apiId: API_ID,
      defaultConnectionName: DEFAULT_CONNECTION_NAME,
      operationId: "Remove-AdminApp",
      parameters: parameters as Record<string, ExpressionOrValue>,
      options,
    }) as ActionSpec;
  },

  /**
   * Remove Connection as Admin
   * Operation id: `Remove-AdminConnection`
   */
  removeAdminConnection(
    parameters: {
      environment?: ExpressionOrValue; // REQUIRED — Environment Name — string — Name field of the Environment.
      connectorName?: ExpressionOrValue; // REQUIRED — Connector Name — string — Name field of the Connector.
      connectionName?: ExpressionOrValue; // REQUIRED — Connection Name — string — Name field of the Connection.
      "api-version"?: ExpressionOrValue; // optional — API Version — string — The date value of the API version.
    } & Record<string, ExpressionOrValue>,
    options?: ConnectorCallOptions,
  ): ActionSpec {
    return buildConnectorCall({
      kind: "action",
      apiId: API_ID,
      defaultConnectionName: DEFAULT_CONNECTION_NAME,
      operationId: "Remove-AdminConnection",
      parameters: parameters as Record<string, ExpressionOrValue>,
      options,
    }) as ActionSpec;
  },

  /**
   * Set App Owner
   * Operation id: `Set-AdminAppOwner`
   */
  setAdminAppOwner(
    parameters: {
      environment?: ExpressionOrValue; // REQUIRED — Environment Name — string — Name field of the Environment.
      app?: ExpressionOrValue; // REQUIRED — PowerApp Name — string — Name field of the PowerApp.
      "api-version"?: ExpressionOrValue; // optional — API Version — string — The date value of the API version.
      "Content-Type"?: ExpressionOrValue; // optional — Content Type — string — The content type of the API request.
      roleForOldAppOwner?: ExpressionOrValue; // optional — Role For Old App Owner — string — The role name for the old app owner. Choose from CanView, CanViewWithShare, or CanEdit.
      newAppOwner?: ExpressionOrValue; // optional — New PowerApp Owner — string — The principal object ID of the new owner.
    } & Record<string, ExpressionOrValue>,
    options?: ConnectorCallOptions,
  ): ActionSpec {
    return buildConnectorCall({
      kind: "action",
      apiId: API_ID,
      defaultConnectionName: DEFAULT_CONNECTION_NAME,
      operationId: "Set-AdminAppOwner",
      parameters: parameters as Record<string, ExpressionOrValue>,
      options,
    }) as ActionSpec;
  },

  /**
   * Set App Quarantine State
   * Operation id: `Set-AppQuarantineState`
   */
  setAppQuarantineState(
    parameters: {
      environment?: ExpressionOrValue; // REQUIRED — Environment Name — string — Name field of the Environment.
      app?: ExpressionOrValue; // REQUIRED — PowerApp Name — string — Name field of the PowerApp.
      "api-version"?: ExpressionOrValue; // optional — API Version — string — The date value of the API version.
      "Content-Type"?: ExpressionOrValue; // optional — Content Type — string — The content type of the API request.
      quarantineStatus?: ExpressionOrValue; // optional — Quarantine Status — string — The quarantine status of the app. Choose from NotSpecified, Quarantined, or Unquarantined.
    } & Record<string, ExpressionOrValue>,
    options?: ConnectorCallOptions,
  ): ActionSpec {
    return buildConnectorCall({
      kind: "action",
      apiId: API_ID,
      defaultConnectionName: DEFAULT_CONNECTION_NAME,
      operationId: "Set-AppQuarantineState",
      parameters: parameters as Record<string, ExpressionOrValue>,
      options,
    }) as ActionSpec;
  },

  /**
   * Set PowerApp Conditional Access
   * Operation id: `Set-PowerAppConditionalAccess`
   */
  setPowerAppConditionalAccess(
    parameters: {
      environment?: ExpressionOrValue; // REQUIRED — Environment Name — string — Name field of the Environment.
      app?: ExpressionOrValue; // REQUIRED — PowerApp Name — string — Name field of the PowerApp.
      "api-version"?: ExpressionOrValue; // optional — API Version — string — The date value of the API version.
      "Content-Type"?: ExpressionOrValue; // optional — Content Type — string — The content type of the API request.
      authContextIds?: ExpressionOrValue; // optional — Auth Context Ids — array of string
    } & Record<string, ExpressionOrValue>,
    options?: ConnectorCallOptions,
  ): ActionSpec {
    return buildConnectorCall({
      kind: "action",
      apiId: API_ID,
      defaultConnectionName: DEFAULT_CONNECTION_NAME,
      operationId: "Set-PowerAppConditionalAccess",
      parameters: parameters as Record<string, ExpressionOrValue>,
      options,
    }) as ActionSpec;
  },
} as const;
