// AUTO-GENERATED by packages/connectors/scripts/generate.ts.
// Do not edit by hand. Re-run `bun --filter @vibeflow/connectors generate`.
// Connector: shared_bingmaps — Bing Maps
// Source: https://learn.microsoft.com/en-us/connectors/bingmaps/?accept=text/markdown

import { buildConnectorCall, type ActionSpec, type ConnectorCallOptions, type ExpressionOrValue, type TriggerSpec } from "../_runtime.js";

const API_ID = "/providers/Microsoft.PowerApps/apis/shared_bingmaps";
const DEFAULT_CONNECTION_NAME = "shared_bingmaps";

export const BingMaps = {
  /** Connector id (`shared_bingmaps`). */
  connectorId: "shared_bingmaps",
  /** Power Automate apiId for this connector. */
  apiId: API_ID,

  /**
   * Get location by address
   * @returns - Body - GetLocation_Response
   * Operation id: `GetLocationByAddress`
   */
  getLocationByAddress(
    parameters: {
      addressLine?: ExpressionOrValue; // optional — Address line — string — A string specifying the street line of an address (not including city, country region, etc).
      locality?: ExpressionOrValue; // optional — Locality (City) — string — A string that contains the locality, such as a US city.
      adminDistrict?: ExpressionOrValue; // optional — Admin district (State) — string — A string that contains a subdivision, such as the abbreviation of a US state.
      postalCode?: ExpressionOrValue; // optional — Postal code — string — A string that contains the postal code, such as a US ZIP Code.
      countryRegion?: ExpressionOrValue; // optional — Country region — string — A string specifying the ISO country code.
    } & Record<string, ExpressionOrValue>,
    options?: ConnectorCallOptions,
  ): ActionSpec {
    return buildConnectorCall({
      kind: "action",
      apiId: API_ID,
      defaultConnectionName: DEFAULT_CONNECTION_NAME,
      operationId: "GetLocationByAddress",
      parameters: parameters as Record<string, ExpressionOrValue>,
      options,
    }) as ActionSpec;
  },

  /**
   * Get location by point
   * @returns - Body - GetLocation_Response
   * Operation id: `GetLocationByPoint`
   */
  getLocationByPoint(
    parameters: {
      latitude?: ExpressionOrValue; // REQUIRED — Point Latitude — double — The latitude coordinate you want to reverse geocode. Example: 47.64054
      longitude?: ExpressionOrValue; // REQUIRED — Point Longitude — double — The longitude coordinate you want to reverse geocode. Example: -122.12934
      includeEntityTypes?: ExpressionOrValue; // optional — Include Entity Types — string — The entity types that you want to return in the response.
      includeNeighborhood?: ExpressionOrValue; // optional — Include Neighborhood — boolean — A value determining whether or not to include the neighborhood in the response when it is available. 0 or 1
      include?: ExpressionOrValue; // optional — Include Country Code — boolean — A value determining whether or not to include the two-letter ISO country code. ciso2
    } & Record<string, ExpressionOrValue>,
    options?: ConnectorCallOptions,
  ): ActionSpec {
    return buildConnectorCall({
      kind: "action",
      apiId: API_ID,
      defaultConnectionName: DEFAULT_CONNECTION_NAME,
      operationId: "GetLocationByPoint",
      parameters: parameters as Record<string, ExpressionOrValue>,
      options,
    }) as ActionSpec;
  },

  /**
   * Get static map [DEPRECATED]
   * @deprecated Marked deprecated by Microsoft.
   * @returns - response - GetMap_Response
   * Operation id: `GetMap`
   */
  getMap(
    parameters: {
      latitude?: ExpressionOrValue; // REQUIRED — Point latitude — string — The latitude coordinate you want to reverse geocode. Example: 47.64054
      longitude?: ExpressionOrValue; // REQUIRED — Point longitude — string — The longitude coordinate you want to reverse geocode. Example: -122.12934
      imagerySet?: ExpressionOrValue; // REQUIRED — Imagery set — string — The type of imagery.
      zoomLevel?: ExpressionOrValue; // REQUIRED — Zoom level — string — The level of zoom to display between 0 and 21. Default 10
      format?: ExpressionOrValue; // optional — Image format — string — The image format to use for the static map.
      mapSize?: ExpressionOrValue; // optional — Map size — string — The width and height in pixels of the static map output. Example: 1000,600.
      pushpin?: ExpressionOrValue; // optional — Pushpin — string — Point value (latitude and longitude) with options to add a label of up to three (3) characters and to specify an icon st
    } & Record<string, ExpressionOrValue>,
    options?: ConnectorCallOptions,
  ): ActionSpec {
    return buildConnectorCall({
      kind: "action",
      apiId: API_ID,
      defaultConnectionName: DEFAULT_CONNECTION_NAME,
      operationId: "GetMap",
      parameters: parameters as Record<string, ExpressionOrValue>,
      options,
    }) as ActionSpec;
  },

  /**
   * Get static map
   * @returns - response - GetMap_Response
   * Operation id: `GetMapV2`
   */
  getMapV2(
    parameters: {
      latitude?: ExpressionOrValue; // REQUIRED — Point latitude — double — The latitude coordinate you want to reverse geocode. Example: 47.64054
      longitude?: ExpressionOrValue; // REQUIRED — Point longitude — double — The longitude coordinate you want to reverse geocode. Example: -122.12934
      imagerySet?: ExpressionOrValue; // REQUIRED — Imagery set — string — The type of imagery.
      zoomLevel?: ExpressionOrValue; // REQUIRED — Zoom level — string — The level of zoom to display between 0 and 21. Default 10
      format?: ExpressionOrValue; // optional — Image format — string — The image format to use for the static map.
      mapSize?: ExpressionOrValue; // optional — Map size — string — The width and height in pixels of the static map output. Example: 1000,600.
      pushpinLatitude?: ExpressionOrValue; // optional — Pushpin latitude — double — Specify pushpin latitude (more information https://aka.ms/u8b8aq).
      pushpinLongitude?: ExpressionOrValue; // optional — Pushpin longitude — double — Specify pushpin longitude (more information https://aka.ms/u8b8aq).
      pushpinIconStyle?: ExpressionOrValue; // optional — Pushpin icon style — integer — Specify pushpin icon style (more information https://aka.ms/u8b8aq).
      pushpinLabel?: ExpressionOrValue; // optional — Pushpin label — string — Specify a label of up to three (3) characters (more information https://aka.ms/u8b8aq).
    } & Record<string, ExpressionOrValue>,
    options?: ConnectorCallOptions,
  ): ActionSpec {
    return buildConnectorCall({
      kind: "action",
      apiId: API_ID,
      defaultConnectionName: DEFAULT_CONNECTION_NAME,
      operationId: "GetMapV2",
      parameters: parameters as Record<string, ExpressionOrValue>,
      options,
    }) as ActionSpec;
  },

  /**
   * Get route [DEPRECATED]
   * @deprecated Marked deprecated by Microsoft.
   * @returns - Body - GetRoute_Response
   * Operation id: `GetRoute`
   */
  getRoute(
    parameters: {
      "wp.0"?: ExpressionOrValue; // REQUIRED — Waypoint 1 — string — Specified as a point, landmark, or address. (47.610,-122.107 or Seattle, WA)
      "wp.1"?: ExpressionOrValue; // REQUIRED — Waypoint 2 — string — Specified as a point, landmark, or address. (47.610,-122.107 or Seattle, WA)
      avoid?: ExpressionOrValue; // optional — Avoid — string — A comma-separated list of values from the following list (highways, tolls, minimizeHighways, minimizeTolls).
      optimize?: ExpressionOrValue; // optional — Optimize — string — Specifies what parameters to use to optimize the route.
      distanceUnit?: ExpressionOrValue; // optional — Distance unit — string — The units to use for distance in the response. Default: Kilometer
      travelMode?: ExpressionOrValue; // optional — Travel mode — string — The mode of travel for the route. Default: Driving
      dateTime?: ExpressionOrValue; // optional — Transit Date-Time — string — Required when the travel mode is transit. Identifies the desired transit time, such as arrival time or departure time.
      timeType?: ExpressionOrValue; // optional — Transit Date-Time Type — string — Required when the travel mode is transit. Specifies how to interpret the transit date-time value.
    } & Record<string, ExpressionOrValue>,
    options?: ConnectorCallOptions,
  ): ActionSpec {
    return buildConnectorCall({
      kind: "action",
      apiId: API_ID,
      defaultConnectionName: DEFAULT_CONNECTION_NAME,
      operationId: "GetRoute",
      parameters: parameters as Record<string, ExpressionOrValue>,
      options,
    }) as ActionSpec;
  },

  /**
   * Get route [DEPRECATED]
   * @deprecated Marked deprecated by Microsoft.
   * @returns - Body - GetRoute_Response
   * Operation id: `GetRouteV2`
   */
  getRouteV2(
    parameters: {
      "wp.0"?: ExpressionOrValue; // REQUIRED — Waypoint 1 — string — Specified as a point, landmark, or address. (47.610,-122.107 or Seattle, WA)
      "wp.1"?: ExpressionOrValue; // REQUIRED — Waypoint 2 — string — Specified as a point, landmark, or address. (47.610,-122.107 or Seattle, WA)
      avoid_highways?: ExpressionOrValue; // optional — Avoid highways — boolean — Avoids the use of highways in the route.
      avoid_tolls?: ExpressionOrValue; // optional — Avoid tolls — boolean — Avoids the use of toll roads in the route.
      avoid_ferry?: ExpressionOrValue; // optional — Avoid ferries — boolean — Avoids the use of ferries in the route.
      avoid_minimizeHighways?: ExpressionOrValue; // optional — Minimize the use of highways — boolean — Minimizes (tries to avoid) the use of highways in the route.
      avoid_minimizeTolls?: ExpressionOrValue; // optional — Minimize the use of toll roads — boolean — Minimizes (tries to avoid) the use of toll roads in the route.
      avoid_borderCrossing?: ExpressionOrValue; // optional — Avoid crossing country borders — boolean — Avoids crossing country borders in the route.
      optimize?: ExpressionOrValue; // optional — Optimize — string — Specifies what parameters to use to optimize the route.
      distanceUnit?: ExpressionOrValue; // optional — Distance unit — string — The units to use for distance in the response. Default: Kilometer
      travelMode?: ExpressionOrValue; // optional — Travel mode — string — The mode of travel for the route. Default: Driving
      dateTime?: ExpressionOrValue; // optional — Transit Date-Time — string — Required when the travel mode is transit. Identifies the desired transit time, such as arrival time or departure time.
      timeType?: ExpressionOrValue; // optional — Transit Date-Time Type — string — Required when the travel mode is transit. Specifies how to interpret the transit date-time value.
    } & Record<string, ExpressionOrValue>,
    options?: ConnectorCallOptions,
  ): ActionSpec {
    return buildConnectorCall({
      kind: "action",
      apiId: API_ID,
      defaultConnectionName: DEFAULT_CONNECTION_NAME,
      operationId: "GetRouteV2",
      parameters: parameters as Record<string, ExpressionOrValue>,
      options,
    }) as ActionSpec;
  },

  /**
   * Get route
   * @returns - Body - GetRoute_Response
   * Operation id: `GetRouteV3`
   */
  getRouteV3(
    parameters: {
      "wp.0"?: ExpressionOrValue; // REQUIRED — Waypoint 1 — string — Specified as a point, landmark, or address. (47.610,-122.107 or Seattle, WA)
      "wp.1"?: ExpressionOrValue; // REQUIRED — Waypoint 2 — string — Specified as a point, landmark, or address. (47.610,-122.107 or Seattle, WA)
      travelMode?: ExpressionOrValue; // REQUIRED — Travel mode — string — The mode of travel for the route. Default: Driving
      avoid_highways?: ExpressionOrValue; // optional — Avoid highways — boolean — Avoids the use of highways in the route.
      avoid_tolls?: ExpressionOrValue; // optional — Avoid tolls — boolean — Avoids the use of toll roads in the route.
      avoid_ferry?: ExpressionOrValue; // optional — Avoid ferries — boolean — Avoids the use of ferries in the route.
      avoid_minimizeHighways?: ExpressionOrValue; // optional — Minimize the use of highways — boolean — Minimizes (tries to avoid) the use of highways in the route.
      avoid_minimizeTolls?: ExpressionOrValue; // optional — Minimize the use of toll roads — boolean — Minimizes (tries to avoid) the use of toll roads in the route.
      avoid_borderCrossing?: ExpressionOrValue; // optional — Avoid crossing country borders — boolean — Avoids crossing country borders in the route.
      optimize?: ExpressionOrValue; // optional — Optimize — string — Specifies what parameters to use to optimize the route.
      distanceUnit?: ExpressionOrValue; // optional — Distance unit — string — The units to use for distance in the response. Default: Kilometer
      dateTime?: ExpressionOrValue; // optional — Transit Date-Time — string — Required when the travel mode is transit. Identifies the desired transit time, such as arrival time or departure time.
      timeType?: ExpressionOrValue; // optional — Transit Date-Time Type — string — Required when the travel mode is transit. Specifies how to interpret the transit date-time value.
    } & Record<string, ExpressionOrValue>,
    options?: ConnectorCallOptions,
  ): ActionSpec {
    return buildConnectorCall({
      kind: "action",
      apiId: API_ID,
      defaultConnectionName: DEFAULT_CONNECTION_NAME,
      operationId: "GetRouteV3",
      parameters: parameters as Record<string, ExpressionOrValue>,
      options,
    }) as ActionSpec;
  },
} as const;
