// AUTO-GENERATED by packages/connectors/scripts/generate.ts.
// Do not edit by hand. Re-run `bun --filter @vibeflow/connectors generate`.
// Connector: shared_powerappsnotification — Power Apps Notification
// Source: https://learn.microsoft.com/en-us/connectors/powerappsnotification/?accept=text/markdown

import { buildConnectorCall, type ActionSpec, type ConnectorCallOptions, type ExpressionOrValue, type TriggerSpec } from "../_runtime.js";

const API_ID = "/providers/Microsoft.PowerApps/apis/shared_powerappsnotification";
const DEFAULT_CONNECTION_NAME = "shared_powerappsnotification";

export const PowerAppsNotification = {
  /** Connector id (`shared_powerappsnotification`). */
  connectorId: "shared_powerappsnotification",
  /** Power Automate apiId for this connector. */
  apiId: API_ID,

  /**
   * Send push notification
   * Operation id: `SendPushNotification`
   */
  sendPushNotification(
    parameters: {
      recipients?: ExpressionOrValue; // optional — Recipients — array of string — List of user emails or user principle identifiers.
      message?: ExpressionOrValue; // optional — Message — string — Message body for the push notification.
      openApp?: ExpressionOrValue; // optional — Open App — boolean — Whether to open or not the app when user taps on the push notification.
      params?: ExpressionOrValue; // optional — Parameters — object — Key value parameters to pass with the notification.
    } & Record<string, ExpressionOrValue>,
    options?: ConnectorCallOptions,
  ): ActionSpec {
    return buildConnectorCall({
      kind: "action",
      apiId: API_ID,
      defaultConnectionName: DEFAULT_CONNECTION_NAME,
      operationId: "SendPushNotification",
      parameters: parameters as Record<string, ExpressionOrValue>,
      options,
    }) as ActionSpec;
  },
} as const;
