// AUTO-GENERATED by packages/connectors/scripts/generate.ts.
// Do not edit by hand. Re-run `bun --filter @vibeflow/connectors generate`.
// Connector: shared_filesystem — File System
// Source: https://learn.microsoft.com/en-us/connectors/filesystem/?accept=text/markdown

import { buildConnectorCall, type ActionSpec, type ConnectorCallOptions, type ExpressionOrValue, type TriggerSpec } from "../_runtime.js";

const API_ID = "/providers/Microsoft.PowerApps/apis/shared_filesystem";
const DEFAULT_CONNECTION_NAME = "shared_filesystem";

export const FileSystem = {
  /** Connector id (`shared_filesystem`). */
  connectorId: "shared_filesystem",
  /** Power Automate apiId for this connector. */
  apiId: API_ID,

  /**
   * Append file
   * @returns Blob metadata - Body - BlobMetadata
   * Operation id: `AppendFile`
   */
  appendFile(
    parameters: {
      id?: ExpressionOrValue; // REQUIRED — File — string — Select a file
      body?: ExpressionOrValue; // REQUIRED — File content — binary — Content to add to the file
    } & Record<string, ExpressionOrValue>,
    options?: ConnectorCallOptions,
  ): ActionSpec {
    return buildConnectorCall({
      kind: "action",
      apiId: API_ID,
      defaultConnectionName: DEFAULT_CONNECTION_NAME,
      operationId: "AppendFile",
      parameters: parameters as Record<string, ExpressionOrValue>,
      options,
    }) as ActionSpec;
  },

  /**
   * Copy file
   * @returns Blob metadata - Body - BlobMetadata
   * Operation id: `CopyFile`
   */
  copyFile(
    parameters: {
      source?: ExpressionOrValue; // REQUIRED — Source path — string — Path to source file
      destination?: ExpressionOrValue; // REQUIRED — Destination file path — string — Destination file path, including target filename
      overwrite?: ExpressionOrValue; // optional — Overwrite? — boolean — Overwrites the destination file if set to 'true
    } & Record<string, ExpressionOrValue>,
    options?: ConnectorCallOptions,
  ): ActionSpec {
    return buildConnectorCall({
      kind: "action",
      apiId: API_ID,
      defaultConnectionName: DEFAULT_CONNECTION_NAME,
      operationId: "CopyFile",
      parameters: parameters as Record<string, ExpressionOrValue>,
      options,
    }) as ActionSpec;
  },

  /**
   * Create file
   * @returns Blob metadata - Body - BlobMetadata
   * Operation id: `CreateFile`
   */
  createFile(
    parameters: {
      folderPath?: ExpressionOrValue; // REQUIRED — Folder path — string — Select a folder
      name?: ExpressionOrValue; // REQUIRED — File name — string — Name of the file
      body?: ExpressionOrValue; // REQUIRED — File content — binary — Content of the file
    } & Record<string, ExpressionOrValue>,
    options?: ConnectorCallOptions,
  ): ActionSpec {
    return buildConnectorCall({
      kind: "action",
      apiId: API_ID,
      defaultConnectionName: DEFAULT_CONNECTION_NAME,
      operationId: "CreateFile",
      parameters: parameters as Record<string, ExpressionOrValue>,
      options,
    }) as ActionSpec;
  },

  /**
   * Delete file
   * Operation id: `DeleteFile`
   */
  deleteFile(
    parameters: {
      id?: ExpressionOrValue; // REQUIRED — File — string — Select a file
    } & Record<string, ExpressionOrValue>,
    options?: ConnectorCallOptions,
  ): ActionSpec {
    return buildConnectorCall({
      kind: "action",
      apiId: API_ID,
      defaultConnectionName: DEFAULT_CONNECTION_NAME,
      operationId: "DeleteFile",
      parameters: parameters as Record<string, ExpressionOrValue>,
      options,
    }) as ActionSpec;
  },

  /**
   * Extract archive to folder
   * @returns - response - array of BlobMetadata
   * Operation id: `ExtractFolderV2`
   */
  extractFolderV2(
    parameters: {
      source?: ExpressionOrValue; // REQUIRED — Source archive file path — string — Path to the archive file
      destination?: ExpressionOrValue; // REQUIRED — Destination folder path — string — Path to the destination folder
      overwrite?: ExpressionOrValue; // optional — Overwrite? — boolean — Overwrites the destination files if set to 'true'
    } & Record<string, ExpressionOrValue>,
    options?: ConnectorCallOptions,
  ): ActionSpec {
    return buildConnectorCall({
      kind: "action",
      apiId: API_ID,
      defaultConnectionName: DEFAULT_CONNECTION_NAME,
      operationId: "ExtractFolderV2",
      parameters: parameters as Record<string, ExpressionOrValue>,
      options,
    }) as ActionSpec;
  },

  /**
   * Get file content
   * @returns The content of the file. - File Content - binary
   * Operation id: `GetFileContent`
   */
  getFileContent(
    parameters: {
      id?: ExpressionOrValue; // REQUIRED — File — string — Select a file
      inferContentType?: ExpressionOrValue; // optional — Infer Content Type — boolean — Infer content-type based on extension
    } & Record<string, ExpressionOrValue>,
    options?: ConnectorCallOptions,
  ): ActionSpec {
    return buildConnectorCall({
      kind: "action",
      apiId: API_ID,
      defaultConnectionName: DEFAULT_CONNECTION_NAME,
      operationId: "GetFileContent",
      parameters: parameters as Record<string, ExpressionOrValue>,
      options,
    }) as ActionSpec;
  },

  /**
   * Get file content using path
   * @returns The content of the file. - File Content - binary
   * Operation id: `GetFileContentByPath`
   */
  getFileContentByPath(
    parameters: {
      path?: ExpressionOrValue; // REQUIRED — File path — string — Select a file
      inferContentType?: ExpressionOrValue; // optional — Infer Content Type — boolean — Infer content-type based on extension
    } & Record<string, ExpressionOrValue>,
    options?: ConnectorCallOptions,
  ): ActionSpec {
    return buildConnectorCall({
      kind: "action",
      apiId: API_ID,
      defaultConnectionName: DEFAULT_CONNECTION_NAME,
      operationId: "GetFileContentByPath",
      parameters: parameters as Record<string, ExpressionOrValue>,
      options,
    }) as ActionSpec;
  },

  /**
   * Get file metadata
   * @returns Blob metadata - Body - BlobMetadata
   * Operation id: `GetFileMetadata`
   */
  getFileMetadata(
    parameters: {
      id?: ExpressionOrValue; // REQUIRED — File — string — Select a file
    } & Record<string, ExpressionOrValue>,
    options?: ConnectorCallOptions,
  ): ActionSpec {
    return buildConnectorCall({
      kind: "action",
      apiId: API_ID,
      defaultConnectionName: DEFAULT_CONNECTION_NAME,
      operationId: "GetFileMetadata",
      parameters: parameters as Record<string, ExpressionOrValue>,
      options,
    }) as ActionSpec;
  },

  /**
   * Get file metadata using path
   * @returns Blob metadata - Body - BlobMetadata
   * Operation id: `GetFileMetadataByPath`
   */
  getFileMetadataByPath(
    parameters: {
      path?: ExpressionOrValue; // REQUIRED — File path — string — Select a file
    } & Record<string, ExpressionOrValue>,
    options?: ConnectorCallOptions,
  ): ActionSpec {
    return buildConnectorCall({
      kind: "action",
      apiId: API_ID,
      defaultConnectionName: DEFAULT_CONNECTION_NAME,
      operationId: "GetFileMetadataByPath",
      parameters: parameters as Record<string, ExpressionOrValue>,
      options,
    }) as ActionSpec;
  },

  /**
   * List files in folder
   * @returns - response - array of BlobMetadata
   * Operation id: `ListFolder`
   */
  listFolder(
    parameters: {
      id?: ExpressionOrValue; // REQUIRED — Folder — string — Select a folder
    } & Record<string, ExpressionOrValue>,
    options?: ConnectorCallOptions,
  ): ActionSpec {
    return buildConnectorCall({
      kind: "action",
      apiId: API_ID,
      defaultConnectionName: DEFAULT_CONNECTION_NAME,
      operationId: "ListFolder",
      parameters: parameters as Record<string, ExpressionOrValue>,
      options,
    }) as ActionSpec;
  },

  /**
   * List files in root folder
   * @returns - response - array of BlobMetadata
   * Operation id: `ListRootFolder`
   */
  listRootFolder(options?: ConnectorCallOptions): ActionSpec {
    return buildConnectorCall({
      kind: "action",
      apiId: API_ID,
      defaultConnectionName: DEFAULT_CONNECTION_NAME,
      operationId: "ListRootFolder",
      parameters: {},
      options,
    }) as ActionSpec;
  },

  /**
   * When a file is created (properties only)
   * @remarks This is a trigger operation; pass it to flowBuilder.setTrigger().
   * @returns Blob metadata - List of Files - BlobMetadata
   * Operation id: `OnNewFiles`
   */
  onNewFiles(
    parameters: {
      folderId?: ExpressionOrValue; // REQUIRED — Folder — string — Select a folder
      maxFileCount?: ExpressionOrValue; // optional — Number of files to return — integer — Maximum number of files to return by single trigger run (1-100). Note that 'Split On' setting can force trigger to proce
    } & Record<string, ExpressionOrValue>,
    options?: ConnectorCallOptions,
  ): TriggerSpec {
    return buildConnectorCall({
      kind: "trigger",
      apiId: API_ID,
      defaultConnectionName: DEFAULT_CONNECTION_NAME,
      operationId: "OnNewFiles",
      parameters: parameters as Record<string, ExpressionOrValue>,
      options,
    }) as TriggerSpec;
  },

  /**
   * When a file is added or modified (properties only)
   * @remarks This is a trigger operation; pass it to flowBuilder.setTrigger().
   * @returns Blob metadata - List of Files - BlobMetadata
   * Operation id: `OnUpdatedFiles`
   */
  onUpdatedFiles(
    parameters: {
      folderId?: ExpressionOrValue; // REQUIRED — Folder — string — Select a folder
      maxFileCount?: ExpressionOrValue; // optional — Number of files to return — integer — Maximum number of files to return by single trigger run (1-100). Note that 'Split On' setting can force trigger to proce
      checkBothCreatedAndModifiedDateTime?: ExpressionOrValue; // optional — Check Created and Modified Time — boolean — If the flag is set to true, the trigger will check the file's created date and time and the file's last modified date an
    } & Record<string, ExpressionOrValue>,
    options?: ConnectorCallOptions,
  ): TriggerSpec {
    return buildConnectorCall({
      kind: "trigger",
      apiId: API_ID,
      defaultConnectionName: DEFAULT_CONNECTION_NAME,
      operationId: "OnUpdatedFiles",
      parameters: parameters as Record<string, ExpressionOrValue>,
      options,
    }) as TriggerSpec;
  },

  /**
   * Rename File
   * @returns Represents blob datasets metadata response - Body - BlobMetadataResponse
   * Operation id: `RenameFile`
   */
  renameFile(
    parameters: {
      id?: ExpressionOrValue; // REQUIRED — File — string — Select a file
      newName?: ExpressionOrValue; // REQUIRED — New name — string — New name for the file
    } & Record<string, ExpressionOrValue>,
    options?: ConnectorCallOptions,
  ): ActionSpec {
    return buildConnectorCall({
      kind: "action",
      apiId: API_ID,
      defaultConnectionName: DEFAULT_CONNECTION_NAME,
      operationId: "RenameFile",
      parameters: parameters as Record<string, ExpressionOrValue>,
      options,
    }) as ActionSpec;
  },

  /**
   * Update file
   * @returns Blob metadata - Body - BlobMetadata
   * Operation id: `UpdateFile`
   */
  updateFile(
    parameters: {
      id?: ExpressionOrValue; // REQUIRED — File — string — Select a file
      body?: ExpressionOrValue; // REQUIRED — File content — binary — Content of the file
    } & Record<string, ExpressionOrValue>,
    options?: ConnectorCallOptions,
  ): ActionSpec {
    return buildConnectorCall({
      kind: "action",
      apiId: API_ID,
      defaultConnectionName: DEFAULT_CONNECTION_NAME,
      operationId: "UpdateFile",
      parameters: parameters as Record<string, ExpressionOrValue>,
      options,
    }) as ActionSpec;
  },
} as const;
