// AUTO-GENERATED by packages/connectors/scripts/generate.ts.
// Do not edit by hand. Re-run `bun --filter @vibeflow/connectors generate`.
// Connector: shared_azureeventgrid — Azure Event Grid
// Source: https://learn.microsoft.com/en-us/connectors/azureeventgrid/?accept=text/markdown

import { buildConnectorCall, type ActionSpec, type ConnectorCallOptions, type ExpressionOrValue, type TriggerSpec } from "../_runtime.js";

const API_ID = "/providers/Microsoft.PowerApps/apis/shared_azureeventgrid";
const DEFAULT_CONNECTION_NAME = "shared_azureeventgrid";

export const AzureEventGrid = {
  /** Connector id (`shared_azureeventgrid`). */
  connectorId: "shared_azureeventgrid",
  /** Power Automate apiId for this connector. */
  apiId: API_ID,

  /**
   * When a resource event occurs
   * @remarks This is a trigger operation; pass it to flowBuilder.setTrigger().
   * @returns | Name | Path | Type | Description | | --- | --- | --- | --- | | Event data | data |  | Contains the data from the event. | | Event Time | eventTime | date-time | Time of the event. |
   * Operation id: `CreateSubscription`
   */
  createSubscription(
    parameters: {
      subscriptionId?: ExpressionOrValue; // REQUIRED — Subscription — string — The unique identifier for the Microsoft Azure subscription. The subscription ID forms part of the ID for every Azure res
      resourceType?: ExpressionOrValue; // REQUIRED — Resource Type — string — Type of resource to create event subscription on.
      topic?: ExpressionOrValue; // REQUIRED — Resource Name — string — Name of the resource to listen to for events.
      subscriptionName?: ExpressionOrValue; // optional — Subscription Name — string — Name to use for the new Event Grid subscription.
      subjectBeginsWith?: ExpressionOrValue; // optional — Prefix Filter — string — A filter like: Sample-workitems/{name}
      subjectEndsWith?: ExpressionOrValue; // optional — Suffix Filter — string — A filter like: .jpg
      includedEventTypes?: ExpressionOrValue; // optional — Event Type — array of string — Type of event to listen for.
    } & Record<string, ExpressionOrValue>,
    options?: ConnectorCallOptions,
  ): TriggerSpec {
    return buildConnectorCall({
      kind: "trigger",
      apiId: API_ID,
      defaultConnectionName: DEFAULT_CONNECTION_NAME,
      operationId: "CreateSubscription",
      parameters: parameters as Record<string, ExpressionOrValue>,
      options,
    }) as TriggerSpec;
  },
} as const;
