// AUTO-GENERATED by packages/connectors/scripts/generate.ts.
// Do not edit by hand. Re-run `bun --filter @vibeflow/connectors generate`.
// Connector: shared_azurequeues — Azure Queues
// Source: https://learn.microsoft.com/en-us/connectors/azurequeues/?accept=text/markdown

import { buildConnectorCall, type ActionSpec, type ConnectorCallOptions, type ExpressionOrValue, type TriggerSpec } from "../_runtime.js";

const API_ID = "/providers/Microsoft.PowerApps/apis/shared_azurequeues";
const DEFAULT_CONNECTION_NAME = "shared_azurequeues";

export const AzureQueues = {
  /** Connector id (`shared_azurequeues`). */
  connectorId: "shared_azurequeues",
  /** Power Automate apiId for this connector. */
  apiId: API_ID,

  /**
   * Delete message [DEPRECATED]
   * @deprecated Marked deprecated by Microsoft.
   * Operation id: `DeleteMessage`
   */
  deleteMessage(
    parameters: {
      queueName?: ExpressionOrValue; // REQUIRED — Queue Name — string — The queue to delete a message from.
      messageId?: ExpressionOrValue; // REQUIRED — Message ID — string — The ID of the message to delete.
      popreceipt?: ExpressionOrValue; // REQUIRED — Pop Receipt — string — A valid pop receipt value returned from an earlier call to the Get Messages.
    } & Record<string, ExpressionOrValue>,
    options?: ConnectorCallOptions,
  ): ActionSpec {
    return buildConnectorCall({
      kind: "action",
      apiId: API_ID,
      defaultConnectionName: DEFAULT_CONNECTION_NAME,
      operationId: "DeleteMessage",
      parameters: parameters as Record<string, ExpressionOrValue>,
      options,
    }) as ActionSpec;
  },

  /**
   * Delete message (V2)
   * Operation id: `DeleteMessage_V2`
   */
  deleteMessageV2(
    parameters: {
      storageAccountName?: ExpressionOrValue; // REQUIRED — Storage account name or queue endpoint — string — Azure Storage account name or queue endpoint.
      queueName?: ExpressionOrValue; // REQUIRED — Queue Name — string — The queue to delete a message from.
      messageId?: ExpressionOrValue; // REQUIRED — Message ID — string — The ID of the message to delete.
      popreceipt?: ExpressionOrValue; // REQUIRED — Pop Receipt — string — A valid pop receipt value returned from an earlier call to the Get Messages.
    } & Record<string, ExpressionOrValue>,
    options?: ConnectorCallOptions,
  ): ActionSpec {
    return buildConnectorCall({
      kind: "action",
      apiId: API_ID,
      defaultConnectionName: DEFAULT_CONNECTION_NAME,
      operationId: "DeleteMessage_V2",
      parameters: parameters as Record<string, ExpressionOrValue>,
      options,
    }) as ActionSpec;
  },

  /**
   * Get messages [DEPRECATED]
   * @deprecated Marked deprecated by Microsoft.
   * @returns - Body - Messages
   * Operation id: `GetMessages`
   */
  getMessages(
    parameters: {
      queueName?: ExpressionOrValue; // REQUIRED — Queue Name — string — The queue to get Messages from.
      numofmessages?: ExpressionOrValue; // optional — Number of Messages — string — The number of messages to grab from the queue (default 1).
      visibilitytimeout?: ExpressionOrValue; // optional — Visibility Timeout — string — The time in seconds that messages will be invisible to other consumers (default 30).
    } & Record<string, ExpressionOrValue>,
    options?: ConnectorCallOptions,
  ): ActionSpec {
    return buildConnectorCall({
      kind: "action",
      apiId: API_ID,
      defaultConnectionName: DEFAULT_CONNECTION_NAME,
      operationId: "GetMessages",
      parameters: parameters as Record<string, ExpressionOrValue>,
      options,
    }) as ActionSpec;
  },

  /**
   * Get messages (V2)
   * @returns - Body - Messages
   * Operation id: `GetMessages_V2`
   */
  getMessagesV2(
    parameters: {
      storageAccountName?: ExpressionOrValue; // REQUIRED — Storage account name or queue endpoint — string — Azure Storage account name or queue endpoint.
      queueName?: ExpressionOrValue; // REQUIRED — Queue Name — string — The queue to get Messages from.
      numofmessages?: ExpressionOrValue; // optional — Number of Messages — string — The number of messages to grab from the queue (default 1).
      visibilitytimeout?: ExpressionOrValue; // optional — Visibility Timeout — string — The time in seconds that messages will be invisible to other consumers (default 30).
    } & Record<string, ExpressionOrValue>,
    options?: ConnectorCallOptions,
  ): ActionSpec {
    return buildConnectorCall({
      kind: "action",
      apiId: API_ID,
      defaultConnectionName: DEFAULT_CONNECTION_NAME,
      operationId: "GetMessages_V2",
      parameters: parameters as Record<string, ExpressionOrValue>,
      options,
    }) as ActionSpec;
  },

  /**
   * List queues [DEPRECATED]
   * @deprecated Marked deprecated by Microsoft.
   * @returns - Items - QueueArray
   * Operation id: `ListQueues`
   */
  listQueues(options?: ConnectorCallOptions): ActionSpec {
    return buildConnectorCall({
      kind: "action",
      apiId: API_ID,
      defaultConnectionName: DEFAULT_CONNECTION_NAME,
      operationId: "ListQueues",
      parameters: {},
      options,
    }) as ActionSpec;
  },

  /**
   * List queues (V2)
   * @returns - Items - QueueArray
   * Operation id: `ListQueues_V2`
   */
  listQueuesV2(
    parameters: {
      storageAccountName?: ExpressionOrValue; // REQUIRED — Storage account name or queue endpoint — string — Azure Storage account name or queue endpoint.
    } & Record<string, ExpressionOrValue>,
    options?: ConnectorCallOptions,
  ): ActionSpec {
    return buildConnectorCall({
      kind: "action",
      apiId: API_ID,
      defaultConnectionName: DEFAULT_CONNECTION_NAME,
      operationId: "ListQueues_V2",
      parameters: parameters as Record<string, ExpressionOrValue>,
      options,
    }) as ActionSpec;
  },

  /**
   * When a specified number of messages are in a given queue [DEPRECATED]
   * @deprecated Marked deprecated by Microsoft.
   * @remarks This is a trigger operation; pass it to flowBuilder.setTrigger().
   * @returns - response - string
   * Operation id: `OnMessageThresholdReached`
   */
  onMessageThresholdReached(
    parameters: {
      queueName?: ExpressionOrValue; // REQUIRED — Queue Name — string — The queue to check for messages.
      threshold?: ExpressionOrValue; // REQUIRED — Threshold — integer — The number of messages to wait for to fire the trigger.
    } & Record<string, ExpressionOrValue>,
    options?: ConnectorCallOptions,
  ): TriggerSpec {
    return buildConnectorCall({
      kind: "trigger",
      apiId: API_ID,
      defaultConnectionName: DEFAULT_CONNECTION_NAME,
      operationId: "OnMessageThresholdReached",
      parameters: parameters as Record<string, ExpressionOrValue>,
      options,
    }) as TriggerSpec;
  },

  /**
   * When a specified number of messages are in a given queue (V2)
   * @remarks This is a trigger operation; pass it to flowBuilder.setTrigger().
   * @returns - response - string
   * Operation id: `OnMessageThresholdReached_V2`
   */
  onMessageThresholdReachedV2(
    parameters: {
      storageAccountName?: ExpressionOrValue; // REQUIRED — Storage account name or queue endpoint — string — Azure Storage account name or queue endpoint.
      queueName?: ExpressionOrValue; // REQUIRED — Queue Name — string — The queue to check for messages.
      threshold?: ExpressionOrValue; // REQUIRED — Threshold — integer — The number of messages to wait for to fire the trigger.
    } & Record<string, ExpressionOrValue>,
    options?: ConnectorCallOptions,
  ): TriggerSpec {
    return buildConnectorCall({
      kind: "trigger",
      apiId: API_ID,
      defaultConnectionName: DEFAULT_CONNECTION_NAME,
      operationId: "OnMessageThresholdReached_V2",
      parameters: parameters as Record<string, ExpressionOrValue>,
      options,
    }) as TriggerSpec;
  },

  /**
   * When there are messages in a queue [DEPRECATED]
   * @deprecated Marked deprecated by Microsoft.
   * @remarks This is a trigger operation; pass it to flowBuilder.setTrigger().
   * @returns - Body - Messages
   * Operation id: `OnMessages`
   */
  onMessages(
    parameters: {
      queueName?: ExpressionOrValue; // REQUIRED — Queue Name — string — The queue to check for messages
      visibilitytimeout?: ExpressionOrValue; // optional — Visibility Timeout — string — The time in seconds that messages will be invisible to other consumers (default 30)
    } & Record<string, ExpressionOrValue>,
    options?: ConnectorCallOptions,
  ): TriggerSpec {
    return buildConnectorCall({
      kind: "trigger",
      apiId: API_ID,
      defaultConnectionName: DEFAULT_CONNECTION_NAME,
      operationId: "OnMessages",
      parameters: parameters as Record<string, ExpressionOrValue>,
      options,
    }) as TriggerSpec;
  },

  /**
   * When there are messages in a queue (V2)
   * @remarks This is a trigger operation; pass it to flowBuilder.setTrigger().
   * @returns - Body - Messages
   * Operation id: `OnMessages_V2`
   */
  onMessagesV2(
    parameters: {
      storageAccountName?: ExpressionOrValue; // REQUIRED — Storage account name or queue endpoint — string — Azure Storage account name or queue endpoint.
      queueName?: ExpressionOrValue; // REQUIRED — Queue Name — string — The queue to check for messages
      visibilitytimeout?: ExpressionOrValue; // optional — Visibility Timeout — string — The time in seconds that messages will be invisible to other consumers (default 30)
    } & Record<string, ExpressionOrValue>,
    options?: ConnectorCallOptions,
  ): TriggerSpec {
    return buildConnectorCall({
      kind: "trigger",
      apiId: API_ID,
      defaultConnectionName: DEFAULT_CONNECTION_NAME,
      operationId: "OnMessages_V2",
      parameters: parameters as Record<string, ExpressionOrValue>,
      options,
    }) as TriggerSpec;
  },

  /**
   * Put a message on a queue [DEPRECATED]
   * @deprecated Marked deprecated by Microsoft.
   * Operation id: `PutMessage`
   */
  putMessage(
    parameters: {
      queueName?: ExpressionOrValue; // REQUIRED — Queue Name — string — The queue to put a message to.
      message?: ExpressionOrValue; // REQUIRED — Message — string — The message content to post to the queue.
    } & Record<string, ExpressionOrValue>,
    options?: ConnectorCallOptions,
  ): ActionSpec {
    return buildConnectorCall({
      kind: "action",
      apiId: API_ID,
      defaultConnectionName: DEFAULT_CONNECTION_NAME,
      operationId: "PutMessage",
      parameters: parameters as Record<string, ExpressionOrValue>,
      options,
    }) as ActionSpec;
  },

  /**
   * Put a message on a queue (V2)
   * Operation id: `PutMessage_V2`
   */
  putMessageV2(
    parameters: {
      storageAccountName?: ExpressionOrValue; // REQUIRED — Storage account name or queue endpoint — string — Azure Storage account name or queue endpoint.
      queueName?: ExpressionOrValue; // REQUIRED — Queue Name — string — The queue to put a message to.
      message?: ExpressionOrValue; // REQUIRED — Message — string — The message content to post to the queue.
    } & Record<string, ExpressionOrValue>,
    options?: ConnectorCallOptions,
  ): ActionSpec {
    return buildConnectorCall({
      kind: "action",
      apiId: API_ID,
      defaultConnectionName: DEFAULT_CONNECTION_NAME,
      operationId: "PutMessage_V2",
      parameters: parameters as Record<string, ExpressionOrValue>,
      options,
    }) as ActionSpec;
  },

  /**
   * Create a new queue [DEPRECATED]
   * @deprecated Marked deprecated by Microsoft.
   * @returns - response - string
   * Operation id: `PutQueue`
   */
  putQueue(
    parameters: {
      queueName?: ExpressionOrValue; // REQUIRED — Queue Name — string — The name of the queue to create.
    } & Record<string, ExpressionOrValue>,
    options?: ConnectorCallOptions,
  ): ActionSpec {
    return buildConnectorCall({
      kind: "action",
      apiId: API_ID,
      defaultConnectionName: DEFAULT_CONNECTION_NAME,
      operationId: "PutQueue",
      parameters: parameters as Record<string, ExpressionOrValue>,
      options,
    }) as ActionSpec;
  },

  /**
   * Create a new queue (V2)
   * @returns - response - string
   * Operation id: `PutQueue_V2`
   */
  putQueueV2(
    parameters: {
      storageAccountName?: ExpressionOrValue; // REQUIRED — Storage account name or queue endpoint — string — Azure Storage account name or queue endpoint.
      queueName?: ExpressionOrValue; // REQUIRED — Queue Name — string — The name of the queue to create.
    } & Record<string, ExpressionOrValue>,
    options?: ConnectorCallOptions,
  ): ActionSpec {
    return buildConnectorCall({
      kind: "action",
      apiId: API_ID,
      defaultConnectionName: DEFAULT_CONNECTION_NAME,
      operationId: "PutQueue_V2",
      parameters: parameters as Record<string, ExpressionOrValue>,
      options,
    }) as ActionSpec;
  },
} as const;
