// AUTO-GENERATED by packages/connectors/scripts/generate.ts.
// Do not edit by hand. Re-run `bun --filter @vibeflow/connectors generate`.
// Connector: shared_sftpwithssh — SFTP - SSH
// Source: https://learn.microsoft.com/en-us/connectors/sftpwithssh/?accept=text/markdown

import { buildConnectorCall, type ActionSpec, type ConnectorCallOptions, type ExpressionOrValue, type TriggerSpec } from "../_runtime.js";

const API_ID = "/providers/Microsoft.PowerApps/apis/shared_sftpwithssh";
const DEFAULT_CONNECTION_NAME = "shared_sftpwithssh";

export const SFTPSSH = {
  /** Connector id (`shared_sftpwithssh`). */
  connectorId: "shared_sftpwithssh",
  /** Power Automate apiId for this connector. */
  apiId: API_ID,

  /**
   * Copy file
   * @returns Blob metadata - Body - BlobMetadata
   * Operation id: `CopyFile`
   */
  copyFile(
    parameters: {
      source?: ExpressionOrValue; // REQUIRED — Source file path — string — Path to the source file
      destination?: ExpressionOrValue; // REQUIRED — Destination file path — string — Path to the destination file, including file name
      overwrite?: ExpressionOrValue; // optional — Overwrite? — boolean — Overwrites the destination file if set to 'true'
      ReadFileMetadataFromServer?: ExpressionOrValue; // optional — Get all file metadata — boolean — Get all file metadata from the SFTP server after file creation is complete. If this is false, some metadata properties m
    } & Record<string, ExpressionOrValue>,
    options?: ConnectorCallOptions,
  ): ActionSpec {
    return buildConnectorCall({
      kind: "action",
      apiId: API_ID,
      defaultConnectionName: DEFAULT_CONNECTION_NAME,
      operationId: "CopyFile",
      parameters: parameters as Record<string, ExpressionOrValue>,
      options,
    }) as ActionSpec;
  },

  /**
   * Create file
   * @returns Blob metadata - Body - BlobMetadata
   * Operation id: `CreateFile`
   */
  createFile(
    parameters: {
      folderPath?: ExpressionOrValue; // REQUIRED — Folder path — string — Unique path of the folder
      name?: ExpressionOrValue; // REQUIRED — File name — string — Name of the file
      body?: ExpressionOrValue; // REQUIRED — File content — binary — Content of the file to create
      ReadFileMetadataFromServer?: ExpressionOrValue; // optional — Get all file metadata — boolean — Get all file metadata from the SFTP server after file creation is complete. If this is false, some metadata properties m
    } & Record<string, ExpressionOrValue>,
    options?: ConnectorCallOptions,
  ): ActionSpec {
    return buildConnectorCall({
      kind: "action",
      apiId: API_ID,
      defaultConnectionName: DEFAULT_CONNECTION_NAME,
      operationId: "CreateFile",
      parameters: parameters as Record<string, ExpressionOrValue>,
      options,
    }) as ActionSpec;
  },

  /**
   * Create folder
   * @returns Blob metadata - Body - BlobMetadata
   * Operation id: `CreateFolder`
   */
  createFolder(
    parameters: {
      folderPath?: ExpressionOrValue; // REQUIRED — Folder — string — Select a folder
      name?: ExpressionOrValue; // REQUIRED — Name — string — Name of the folder
    } & Record<string, ExpressionOrValue>,
    options?: ConnectorCallOptions,
  ): ActionSpec {
    return buildConnectorCall({
      kind: "action",
      apiId: API_ID,
      defaultConnectionName: DEFAULT_CONNECTION_NAME,
      operationId: "CreateFolder",
      parameters: parameters as Record<string, ExpressionOrValue>,
      options,
    }) as ActionSpec;
  },

  /**
   * Delete file
   * Operation id: `DeleteFile`
   */
  deleteFile(
    parameters: {
      id?: ExpressionOrValue; // REQUIRED — File — string — Specify the file
      SkipDeleteIfFileNotFoundOnServer?: ExpressionOrValue; // optional — Skip delete if file not found — boolean — Skips deletion if a file is not found without failing action.
    } & Record<string, ExpressionOrValue>,
    options?: ConnectorCallOptions,
  ): ActionSpec {
    return buildConnectorCall({
      kind: "action",
      apiId: API_ID,
      defaultConnectionName: DEFAULT_CONNECTION_NAME,
      operationId: "DeleteFile",
      parameters: parameters as Record<string, ExpressionOrValue>,
      options,
    }) as ActionSpec;
  },

  /**
   * Extract archive to folder
   * @returns - response - array of BlobMetadata
   * Operation id: `ExtractFolderV2`
   */
  extractFolderV2(
    parameters: {
      source?: ExpressionOrValue; // REQUIRED — Source archive file path — string — Path to the archive file
      destination?: ExpressionOrValue; // REQUIRED — Destination folder path — string — Path to the destination folder
      overwrite?: ExpressionOrValue; // optional — Overwrite? — boolean — Overwrites the destination files if set to 'true'
    } & Record<string, ExpressionOrValue>,
    options?: ConnectorCallOptions,
  ): ActionSpec {
    return buildConnectorCall({
      kind: "action",
      apiId: API_ID,
      defaultConnectionName: DEFAULT_CONNECTION_NAME,
      operationId: "ExtractFolderV2",
      parameters: parameters as Record<string, ExpressionOrValue>,
      options,
    }) as ActionSpec;
  },

  /**
   * Get file content
   * @returns The content of the file. - File Content - binary
   * Operation id: `GetFileContent`
   */
  getFileContent(
    parameters: {
      id?: ExpressionOrValue; // REQUIRED — File — string — Specify the file id
      inferContentType?: ExpressionOrValue; // optional — Infer Content Type — boolean — Infer content-type based on extension
    } & Record<string, ExpressionOrValue>,
    options?: ConnectorCallOptions,
  ): ActionSpec {
    return buildConnectorCall({
      kind: "action",
      apiId: API_ID,
      defaultConnectionName: DEFAULT_CONNECTION_NAME,
      operationId: "GetFileContent",
      parameters: parameters as Record<string, ExpressionOrValue>,
      options,
    }) as ActionSpec;
  },

  /**
   * Get file content using path
   * @returns The content of the file. - File Content - binary
   * Operation id: `GetFileContentByPath`
   */
  getFileContentByPath(
    parameters: {
      path?: ExpressionOrValue; // REQUIRED — File path — string — Unique path of the file
      inferContentType?: ExpressionOrValue; // optional — Infer Content Type — boolean — Infer content-type based on extension
    } & Record<string, ExpressionOrValue>,
    options?: ConnectorCallOptions,
  ): ActionSpec {
    return buildConnectorCall({
      kind: "action",
      apiId: API_ID,
      defaultConnectionName: DEFAULT_CONNECTION_NAME,
      operationId: "GetFileContentByPath",
      parameters: parameters as Record<string, ExpressionOrValue>,
      options,
    }) as ActionSpec;
  },

  /**
   * Get file metadata
   * @returns Blob metadata - Body - BlobMetadata
   * Operation id: `GetFileMetadata`
   */
  getFileMetadata(
    parameters: {
      id?: ExpressionOrValue; // REQUIRED — File — string — Specify the file id
    } & Record<string, ExpressionOrValue>,
    options?: ConnectorCallOptions,
  ): ActionSpec {
    return buildConnectorCall({
      kind: "action",
      apiId: API_ID,
      defaultConnectionName: DEFAULT_CONNECTION_NAME,
      operationId: "GetFileMetadata",
      parameters: parameters as Record<string, ExpressionOrValue>,
      options,
    }) as ActionSpec;
  },

  /**
   * Get file metadata using path
   * @returns Blob metadata - Body - BlobMetadata
   * Operation id: `GetFileMetadataByPath`
   */
  getFileMetadataByPath(
    parameters: {
      path?: ExpressionOrValue; // REQUIRED — File path — string — Unique path of the file
    } & Record<string, ExpressionOrValue>,
    options?: ConnectorCallOptions,
  ): ActionSpec {
    return buildConnectorCall({
      kind: "action",
      apiId: API_ID,
      defaultConnectionName: DEFAULT_CONNECTION_NAME,
      operationId: "GetFileMetadataByPath",
      parameters: parameters as Record<string, ExpressionOrValue>,
      options,
    }) as ActionSpec;
  },

  /**
   * List files in folder
   * @returns - response - array of BlobMetadata
   * Operation id: `ListFolder`
   */
  listFolder(
    parameters: {
      id?: ExpressionOrValue; // REQUIRED — Folder — string — Specify the folder
    } & Record<string, ExpressionOrValue>,
    options?: ConnectorCallOptions,
  ): ActionSpec {
    return buildConnectorCall({
      kind: "action",
      apiId: API_ID,
      defaultConnectionName: DEFAULT_CONNECTION_NAME,
      operationId: "ListFolder",
      parameters: parameters as Record<string, ExpressionOrValue>,
      options,
    }) as ActionSpec;
  },

  /**
   * List files in root folder
   * @returns - response - array of BlobMetadata
   * Operation id: `ListRootFolder`
   */
  listRootFolder(options?: ConnectorCallOptions): ActionSpec {
    return buildConnectorCall({
      kind: "action",
      apiId: API_ID,
      defaultConnectionName: DEFAULT_CONNECTION_NAME,
      operationId: "ListRootFolder",
      parameters: {},
      options,
    }) as ActionSpec;
  },

  /**
   * When a file is added or modified
   * @remarks This is a trigger operation; pass it to flowBuilder.setTrigger().
   * @returns The content of the file. - File Content - binary
   * Operation id: `OnUpdatedFile`
   */
  onUpdatedFile(
    parameters: {
      folderId?: ExpressionOrValue; // REQUIRED — Folder — string — Specify a folder
      includeFileContent?: ExpressionOrValue; // optional — Include file content — boolean — If set to true, file content will also be retrieved along with the trigger response
      inferContentType?: ExpressionOrValue; // optional — Infer Content Type — boolean — Infer content-type based on extension
    } & Record<string, ExpressionOrValue>,
    options?: ConnectorCallOptions,
  ): TriggerSpec {
    return buildConnectorCall({
      kind: "trigger",
      apiId: API_ID,
      defaultConnectionName: DEFAULT_CONNECTION_NAME,
      operationId: "OnUpdatedFile",
      parameters: parameters as Record<string, ExpressionOrValue>,
      options,
    }) as TriggerSpec;
  },

  /**
   * When files are added or modified (properties only)
   * @remarks This is a trigger operation; pass it to flowBuilder.setTrigger().
   * @returns Blob metadata - List of Files - BlobMetadata
   * Operation id: `OnUpdatedFiles`
   */
  onUpdatedFiles(
    parameters: {
      folderId?: ExpressionOrValue; // REQUIRED — Folder — string — Select a folder
      maxFileCount?: ExpressionOrValue; // optional — Number of files to return — integer — Number of files returned from the trigger (1-100)
    } & Record<string, ExpressionOrValue>,
    options?: ConnectorCallOptions,
  ): TriggerSpec {
    return buildConnectorCall({
      kind: "trigger",
      apiId: API_ID,
      defaultConnectionName: DEFAULT_CONNECTION_NAME,
      operationId: "OnUpdatedFiles",
      parameters: parameters as Record<string, ExpressionOrValue>,
      options,
    }) as TriggerSpec;
  },

  /**
   * Rename File
   * @returns Represents blob datasets metadata response - Body - BlobMetadataResponse
   * Operation id: `RenameFile`
   */
  renameFile(
    parameters: {
      id?: ExpressionOrValue; // REQUIRED — File — string — Select a file
      newName?: ExpressionOrValue; // REQUIRED — New name — string — New name for the file
      ReadFileMetadataFromServer?: ExpressionOrValue; // optional — Get all file metadata — boolean — Get all file metadata from the SFTP server after file creation is complete. If this is false, some metadata properties m
    } & Record<string, ExpressionOrValue>,
    options?: ConnectorCallOptions,
  ): ActionSpec {
    return buildConnectorCall({
      kind: "action",
      apiId: API_ID,
      defaultConnectionName: DEFAULT_CONNECTION_NAME,
      operationId: "RenameFile",
      parameters: parameters as Record<string, ExpressionOrValue>,
      options,
    }) as ActionSpec;
  },

  /**
   * Update file
   * @returns Blob metadata - Body - BlobMetadata
   * Operation id: `UpdateFile`
   */
  updateFile(
    parameters: {
      id?: ExpressionOrValue; // REQUIRED — File — string — Specify the file
      body?: ExpressionOrValue; // REQUIRED — File content — binary — Content of the file to update
      ReadFileMetadataFromServer?: ExpressionOrValue; // optional — Get all file metadata — boolean — Get all file metadata from the SFTP server after file creation is complete. If this is false, some metadata properties m
    } & Record<string, ExpressionOrValue>,
    options?: ConnectorCallOptions,
  ): ActionSpec {
    return buildConnectorCall({
      kind: "action",
      apiId: API_ID,
      defaultConnectionName: DEFAULT_CONNECTION_NAME,
      operationId: "UpdateFile",
      parameters: parameters as Record<string, ExpressionOrValue>,
      options,
    }) as ActionSpec;
  },
} as const;
