// AUTO-GENERATED by packages/connectors/scripts/generate.ts.
// Do not edit by hand. Re-run `bun --filter @vibeflow/connectors generate`.
// Connector: shared_outlook — Outlook.com
// Source: https://learn.microsoft.com/en-us/connectors/outlook/?accept=text/markdown

import { buildConnectorCall, type ActionSpec, type ConnectorCallOptions, type ExpressionOrValue, type TriggerSpec } from "../_runtime.js";

const API_ID = "/providers/Microsoft.PowerApps/apis/shared_outlook";
const DEFAULT_CONNECTION_NAME = "shared_outlook";

export const OutlookCom = {
  /** Connector id (`shared_outlook`). */
  connectorId: "shared_outlook",
  /** Power Automate apiId for this connector. */
  apiId: API_ID,

  /**
   * Delete event
   * Operation id: `CalendarDeleteItem`
   */
  calendarDeleteItem(
    parameters: {
      table?: ExpressionOrValue; // REQUIRED — Calendar id — string — Select a calendar
      id?: ExpressionOrValue; // REQUIRED — Id — string — Select an event
    } & Record<string, ExpressionOrValue>,
    options?: ConnectorCallOptions,
  ): ActionSpec {
    return buildConnectorCall({
      kind: "action",
      apiId: API_ID,
      defaultConnectionName: DEFAULT_CONNECTION_NAME,
      operationId: "CalendarDeleteItem",
      parameters: parameters as Record<string, ExpressionOrValue>,
      options,
    }) as ActionSpec;
  },

  /**
   * Get event (V1) [DEPRECATED]
   * @deprecated Marked deprecated by Microsoft.
   * @returns Connector specific calendar event model class for the backend - Body - CalendarEventBackend
   * Operation id: `CalendarGetItem`
   */
  calendarGetItem(
    parameters: {
      table?: ExpressionOrValue; // REQUIRED — Calendar id — string — Select a calendar
      id?: ExpressionOrValue; // REQUIRED — Item id — string — Select an event
    } & Record<string, ExpressionOrValue>,
    options?: ConnectorCallOptions,
  ): ActionSpec {
    return buildConnectorCall({
      kind: "action",
      apiId: API_ID,
      defaultConnectionName: DEFAULT_CONNECTION_NAME,
      operationId: "CalendarGetItem",
      parameters: parameters as Record<string, ExpressionOrValue>,
      options,
    }) as ActionSpec;
  },

  /**
   * Get events (V1) [DEPRECATED]
   * @deprecated Marked deprecated by Microsoft.
   * @returns Entity list response - Body - EntityListResponse[CalendarEventBackend]
   * Operation id: `CalendarGetItems`
   */
  calendarGetItems(
    parameters: {
      table?: ExpressionOrValue; // REQUIRED — Calendar id — string — Select a calendar
      $orderby?: ExpressionOrValue; // optional — Order By — string — An ODATA orderBy query for specifying the order of entries.
      $top?: ExpressionOrValue; // optional — Top Count — integer — Total number of entries to retrieve (default = all).
      $skip?: ExpressionOrValue; // optional — Skip Count — integer — The number of entries to skip (default = 0).
    } & Record<string, ExpressionOrValue>,
    options?: ConnectorCallOptions,
  ): ActionSpec {
    return buildConnectorCall({
      kind: "action",
      apiId: API_ID,
      defaultConnectionName: DEFAULT_CONNECTION_NAME,
      operationId: "CalendarGetItems",
      parameters: parameters as Record<string, ExpressionOrValue>,
      options,
    }) as ActionSpec;
  },

  /**
   * When an event is added, updated or deleted [DEPRECATED]
   * @deprecated Marked deprecated by Microsoft.
   * @remarks This is a trigger operation; pass it to flowBuilder.setTrigger().
   * @returns The list of calendar items with action type - Body - CalendarEventListWithActionType
   * Operation id: `CalendarGetOnChangedItems`
   */
  calendarGetOnChangedItems(
    parameters: {
      table?: ExpressionOrValue; // REQUIRED — Calendar id — string — Select a calendar
      incomingDays?: ExpressionOrValue; // optional — Incoming Days Tracked — integer — Number of incoming days in calendar to be tracked
      pastDays?: ExpressionOrValue; // optional — Past Days Tracked — integer — Number of past days in calendar to be tracked
    } & Record<string, ExpressionOrValue>,
    options?: ConnectorCallOptions,
  ): TriggerSpec {
    return buildConnectorCall({
      kind: "trigger",
      apiId: API_ID,
      defaultConnectionName: DEFAULT_CONNECTION_NAME,
      operationId: "CalendarGetOnChangedItems",
      parameters: parameters as Record<string, ExpressionOrValue>,
      options,
    }) as TriggerSpec;
  },

  /**
   * When an event is added, updated or deleted (V2)
   * @remarks This is a trigger operation; pass it to flowBuilder.setTrigger().
   * @returns The list of calendar items with action type - Body - CalendarEventListWithActionType
   * Operation id: `CalendarGetOnChangedItemsV2`
   */
  calendarGetOnChangedItemsV2(
    parameters: {
      table?: ExpressionOrValue; // REQUIRED — Calendar id — string — Select a calendar
      incomingDays?: ExpressionOrValue; // optional — Incoming Days Tracked — integer — Number of incoming days in calendar to be tracked
      pastDays?: ExpressionOrValue; // optional — Past Days Tracked — integer — Number of past days in calendar to be tracked
    } & Record<string, ExpressionOrValue>,
    options?: ConnectorCallOptions,
  ): TriggerSpec {
    return buildConnectorCall({
      kind: "trigger",
      apiId: API_ID,
      defaultConnectionName: DEFAULT_CONNECTION_NAME,
      operationId: "CalendarGetOnChangedItemsV2",
      parameters: parameters as Record<string, ExpressionOrValue>,
      options,
    }) as TriggerSpec;
  },

  /**
   * When a new event is created (V1) [DEPRECATED]
   * @deprecated Marked deprecated by Microsoft.
   * @remarks This is a trigger operation; pass it to flowBuilder.setTrigger().
   * @returns The list of calendar items - Body - CalendarEventList
   * Operation id: `CalendarGetOnNewItems`
   */
  calendarGetOnNewItems(
    parameters: {
      table?: ExpressionOrValue; // REQUIRED — Calendar id — string — Select a calendar
      $orderby?: ExpressionOrValue; // optional — Order By — string — An ODATA orderBy query for specifying the order of entries.
      $top?: ExpressionOrValue; // optional — Top Count — integer — Total number of entries to retrieve (default = all).
      $skip?: ExpressionOrValue; // optional — Skip Count — integer — The number of entries to skip (default = 0).
    } & Record<string, ExpressionOrValue>,
    options?: ConnectorCallOptions,
  ): TriggerSpec {
    return buildConnectorCall({
      kind: "trigger",
      apiId: API_ID,
      defaultConnectionName: DEFAULT_CONNECTION_NAME,
      operationId: "CalendarGetOnNewItems",
      parameters: parameters as Record<string, ExpressionOrValue>,
      options,
    }) as TriggerSpec;
  },

  /**
   * When a new event is created (V2)
   * @remarks This is a trigger operation; pass it to flowBuilder.setTrigger().
   * @returns The list of calendar items - Body - CalendarEventListClientReceive
   * Operation id: `CalendarGetOnNewItemsV2`
   */
  calendarGetOnNewItemsV2(
    parameters: {
      table?: ExpressionOrValue; // REQUIRED — Calendar id — string — Select a calendar
      $orderby?: ExpressionOrValue; // optional — Order By — string — An ODATA orderBy query for specifying the order of entries.
      $top?: ExpressionOrValue; // optional — Top Count — integer — Total number of entries to retrieve (default = all).
      $skip?: ExpressionOrValue; // optional — Skip Count — integer — The number of entries to skip (default = 0).
    } & Record<string, ExpressionOrValue>,
    options?: ConnectorCallOptions,
  ): TriggerSpec {
    return buildConnectorCall({
      kind: "trigger",
      apiId: API_ID,
      defaultConnectionName: DEFAULT_CONNECTION_NAME,
      operationId: "CalendarGetOnNewItemsV2",
      parameters: parameters as Record<string, ExpressionOrValue>,
      options,
    }) as TriggerSpec;
  },

  /**
   * When an event is modified (V1) [DEPRECATED]
   * @deprecated Marked deprecated by Microsoft.
   * @remarks This is a trigger operation; pass it to flowBuilder.setTrigger().
   * @returns The list of calendar items - Body - CalendarEventList
   * Operation id: `CalendarGetOnUpdatedItems`
   */
  calendarGetOnUpdatedItems(
    parameters: {
      table?: ExpressionOrValue; // REQUIRED — Calendar id — string — Select a calendar
      $orderby?: ExpressionOrValue; // optional — Order By — string — An ODATA orderBy query for specifying the order of entries.
      $top?: ExpressionOrValue; // optional — Top Count — integer — Total number of entries to retrieve (default = all).
      $skip?: ExpressionOrValue; // optional — Skip Count — integer — The number of entries to skip (default = 0).
    } & Record<string, ExpressionOrValue>,
    options?: ConnectorCallOptions,
  ): TriggerSpec {
    return buildConnectorCall({
      kind: "trigger",
      apiId: API_ID,
      defaultConnectionName: DEFAULT_CONNECTION_NAME,
      operationId: "CalendarGetOnUpdatedItems",
      parameters: parameters as Record<string, ExpressionOrValue>,
      options,
    }) as TriggerSpec;
  },

  /**
   * When an event is modified (V2)
   * @remarks This is a trigger operation; pass it to flowBuilder.setTrigger().
   * @returns The list of calendar items - Body - CalendarEventListClientReceive
   * Operation id: `CalendarGetOnUpdatedItemsV2`
   */
  calendarGetOnUpdatedItemsV2(
    parameters: {
      table?: ExpressionOrValue; // REQUIRED — Calendar id — string — Select a calendar
      $orderby?: ExpressionOrValue; // optional — Order By — string — An ODATA orderBy query for specifying the order of entries.
      $top?: ExpressionOrValue; // optional — Top Count — integer — Total number of entries to retrieve (default = all).
      $skip?: ExpressionOrValue; // optional — Skip Count — integer — The number of entries to skip (default = 0).
    } & Record<string, ExpressionOrValue>,
    options?: ConnectorCallOptions,
  ): TriggerSpec {
    return buildConnectorCall({
      kind: "trigger",
      apiId: API_ID,
      defaultConnectionName: DEFAULT_CONNECTION_NAME,
      operationId: "CalendarGetOnUpdatedItemsV2",
      parameters: parameters as Record<string, ExpressionOrValue>,
      options,
    }) as TriggerSpec;
  },

  /**
   * Get calendars
   * @returns Entity list response - Body - EntityListResponse[Table]
   * Operation id: `CalendarGetTables`
   */
  calendarGetTables(options?: ConnectorCallOptions): ActionSpec {
    return buildConnectorCall({
      kind: "action",
      apiId: API_ID,
      defaultConnectionName: DEFAULT_CONNECTION_NAME,
      operationId: "CalendarGetTables",
      parameters: {},
      options,
    }) as ActionSpec;
  },

  /**
   * Update event (V1) [DEPRECATED]
   * @deprecated Marked deprecated by Microsoft.
   * @returns Connector specific calendar event model class for the backend - Body - CalendarEventBackend
   * Operation id: `CalendarPatchItem`
   */
  calendarPatchItem(
    parameters: {
      table?: ExpressionOrValue; // REQUIRED — Calendar id — string — Select a calendar
      id?: ExpressionOrValue; // REQUIRED — Id — string — Select an event
      End?: ExpressionOrValue; // REQUIRED — End time — date-time — The end time of the event
      Start?: ExpressionOrValue; // REQUIRED — Start time — date-time — The start time of the event
      Subject?: ExpressionOrValue; // REQUIRED — string — Event subject
      Id?: ExpressionOrValue; // optional — string — The Event's unique identifier
      Response?: ExpressionOrValue; // optional — string
      Time?: ExpressionOrValue; // optional — date-time
      Type?: ExpressionOrValue; // optional — string
      Name?: ExpressionOrValue; // optional — string
      Address?: ExpressionOrValue; // optional — email
      ContentType?: ExpressionOrValue; // optional — string
      Content?: ExpressionOrValue; // optional — string
      BodyPreview?: ExpressionOrValue; // optional — Body preview — string — The preview of the message associated with the event
      Categories?: ExpressionOrValue; // optional — array of string — The categories associated with the event
      ChangeKey?: ExpressionOrValue; // optional — Change key — string — This property identifies the version of the event object. Every time the event is changed, ChangeKey changes as well.
      DateTimeCreated?: ExpressionOrValue; // optional — Created time — date-time — The date and time that the event was created
      DateTimeLastModified?: ExpressionOrValue; // optional — Last modified time — date-time — The date and time that the event was last modified
      EndTimeZone?: ExpressionOrValue; // optional — End time zone — string — This property specifies the time zone of the meeting end time. The value must be as defined in Windows (example: 'Pacifi
      HasAttachments?: ExpressionOrValue; // optional — Has attachments? — boolean — Set to true if the event has attachments
      ICalUId?: ExpressionOrValue; // optional — Event Unique ID — string — A unique identifier that is shared by all instances of an event across different calendars
      Importance?: ExpressionOrValue; // optional — string — The importance of the event: Low, Normal, or High
      IsAllDay?: ExpressionOrValue; // optional — Is all day event? — boolean — Set to true if the event lasts all day
      IsCancelled?: ExpressionOrValue; // optional — Is cancelled? — boolean — Set to true if the event has been canceled
      IsOrganizer?: ExpressionOrValue; // optional — Is Organizer — boolean — Set to true if the message sender is also the organizer
      DisplayName?: ExpressionOrValue; // optional — string
      Street?: ExpressionOrValue; // optional — string
      City?: ExpressionOrValue; // optional — string
      State?: ExpressionOrValue; // optional — string
      CountryOrRegion?: ExpressionOrValue; // optional — string
      PostalCode?: ExpressionOrValue; // optional — string
      Altitude?: ExpressionOrValue; // optional — double
      Latitude?: ExpressionOrValue; // optional — double
      Longitude?: ExpressionOrValue; // optional — double
      Accuracy?: ExpressionOrValue; // optional — double
      AltitudeAccuracy?: ExpressionOrValue; // optional — double
      Interval?: ExpressionOrValue; // optional — integer
      Month?: ExpressionOrValue; // optional — integer
      DayOfMonth?: ExpressionOrValue; // optional — integer
      DaysOfWeek?: ExpressionOrValue; // optional — array of string
      FirstDayOfWeek?: ExpressionOrValue; // optional — string
      Index?: ExpressionOrValue; // optional — string
      StartDate?: ExpressionOrValue; // optional — date-time
      EndDate?: ExpressionOrValue; // optional — date-time
      NumberOfOccurrences?: ExpressionOrValue; // optional — integer
      Reminder?: ExpressionOrValue; // optional — integer — Time in minutes before event start to remind
      ResponseRequested?: ExpressionOrValue; // optional — Response requested — boolean — Set to true if the sender would like a response when the event is accepted or declined
      SeriesMasterId?: ExpressionOrValue; // optional — Series master id — string — Unique identifier for Series Master event type
      ShowAs?: ExpressionOrValue; // optional — Show as — string — Shows as free or busy
      StartTimeZone?: ExpressionOrValue; // optional — Start time zone — string — This property specifies the time zone of the meeting start time. The value must be as defined in Windows (example: 'Paci
      WebLink?: ExpressionOrValue; // optional — Web link — uri — The preview of the message associated with the event
      Reason?: ExpressionOrValue; // optional — string — The reason property used by O365 sync events protocol, will be 'deleted' if its a deleted event.
    } & Record<string, ExpressionOrValue>,
    options?: ConnectorCallOptions,
  ): ActionSpec {
    return buildConnectorCall({
      kind: "action",
      apiId: API_ID,
      defaultConnectionName: DEFAULT_CONNECTION_NAME,
      operationId: "CalendarPatchItem",
      parameters: parameters as Record<string, ExpressionOrValue>,
      options,
    }) as ActionSpec;
  },

  /**
   * Create event (V1) [DEPRECATED]
   * @deprecated Marked deprecated by Microsoft.
   * @returns Connector specific calendar event model class for the backend - Body - CalendarEventBackend
   * Operation id: `CalendarPostItem`
   */
  calendarPostItem(
    parameters: {
      table?: ExpressionOrValue; // REQUIRED — Calendar id — string — Select a calendar
      End?: ExpressionOrValue; // REQUIRED — End time — date-time — The end time of the event
      Start?: ExpressionOrValue; // REQUIRED — Start time — date-time — The start time of the event
      Subject?: ExpressionOrValue; // REQUIRED — string — Event subject
      Id?: ExpressionOrValue; // optional — string — The Event's unique identifier
      Response?: ExpressionOrValue; // optional — string
      Time?: ExpressionOrValue; // optional — date-time
      Type?: ExpressionOrValue; // optional — string
      Name?: ExpressionOrValue; // optional — string
      Address?: ExpressionOrValue; // optional — email
      ContentType?: ExpressionOrValue; // optional — string
      Content?: ExpressionOrValue; // optional — string
      BodyPreview?: ExpressionOrValue; // optional — Body preview — string — The preview of the message associated with the event
      Categories?: ExpressionOrValue; // optional — array of string — The categories associated with the event
      ChangeKey?: ExpressionOrValue; // optional — Change key — string — This property identifies the version of the event object. Every time the event is changed, ChangeKey changes as well.
      DateTimeCreated?: ExpressionOrValue; // optional — Created time — date-time — The date and time that the event was created
      DateTimeLastModified?: ExpressionOrValue; // optional — Last modified time — date-time — The date and time that the event was last modified
      EndTimeZone?: ExpressionOrValue; // optional — End time zone — string — This property specifies the time zone of the meeting end time. The value must be as defined in Windows (example: 'Pacifi
      HasAttachments?: ExpressionOrValue; // optional — Has attachments? — boolean — Set to true if the event has attachments
      ICalUId?: ExpressionOrValue; // optional — Event Unique ID — string — A unique identifier that is shared by all instances of an event across different calendars
      Importance?: ExpressionOrValue; // optional — string — The importance of the event: Low, Normal, or High
      IsAllDay?: ExpressionOrValue; // optional — Is all day event? — boolean — Set to true if the event lasts all day
      IsCancelled?: ExpressionOrValue; // optional — Is cancelled? — boolean — Set to true if the event has been canceled
      IsOrganizer?: ExpressionOrValue; // optional — Is Organizer — boolean — Set to true if the message sender is also the organizer
      DisplayName?: ExpressionOrValue; // optional — string
      Street?: ExpressionOrValue; // optional — string
      City?: ExpressionOrValue; // optional — string
      State?: ExpressionOrValue; // optional — string
      CountryOrRegion?: ExpressionOrValue; // optional — string
      PostalCode?: ExpressionOrValue; // optional — string
      Altitude?: ExpressionOrValue; // optional — double
      Latitude?: ExpressionOrValue; // optional — double
      Longitude?: ExpressionOrValue; // optional — double
      Accuracy?: ExpressionOrValue; // optional — double
      AltitudeAccuracy?: ExpressionOrValue; // optional — double
      Interval?: ExpressionOrValue; // optional — integer
      Month?: ExpressionOrValue; // optional — integer
      DayOfMonth?: ExpressionOrValue; // optional — integer
      DaysOfWeek?: ExpressionOrValue; // optional — array of string
      FirstDayOfWeek?: ExpressionOrValue; // optional — string
      Index?: ExpressionOrValue; // optional — string
      StartDate?: ExpressionOrValue; // optional — date-time
      EndDate?: ExpressionOrValue; // optional — date-time
      NumberOfOccurrences?: ExpressionOrValue; // optional — integer
      Reminder?: ExpressionOrValue; // optional — integer — Time in minutes before event start to remind
      ResponseRequested?: ExpressionOrValue; // optional — Response requested — boolean — Set to true if the sender would like a response when the event is accepted or declined
      SeriesMasterId?: ExpressionOrValue; // optional — Series master id — string — Unique identifier for Series Master event type
      ShowAs?: ExpressionOrValue; // optional — Show as — string — Shows as free or busy
      StartTimeZone?: ExpressionOrValue; // optional — Start time zone — string — This property specifies the time zone of the meeting start time. The value must be as defined in Windows (example: 'Paci
      WebLink?: ExpressionOrValue; // optional — Web link — uri — The preview of the message associated with the event
      Reason?: ExpressionOrValue; // optional — string — The reason property used by O365 sync events protocol, will be 'deleted' if its a deleted event.
    } & Record<string, ExpressionOrValue>,
    options?: ConnectorCallOptions,
  ): ActionSpec {
    return buildConnectorCall({
      kind: "action",
      apiId: API_ID,
      defaultConnectionName: DEFAULT_CONNECTION_NAME,
      operationId: "CalendarPostItem",
      parameters: parameters as Record<string, ExpressionOrValue>,
      options,
    }) as ActionSpec;
  },

  /**
   * Delete contact
   * Operation id: `ContactDeleteItem`
   */
  contactDeleteItem(
    parameters: {
      table?: ExpressionOrValue; // REQUIRED — Folder id — string — Select a contacts folder
      id?: ExpressionOrValue; // REQUIRED — Id — string — Unique identifier of contact to delete
    } & Record<string, ExpressionOrValue>,
    options?: ConnectorCallOptions,
  ): ActionSpec {
    return buildConnectorCall({
      kind: "action",
      apiId: API_ID,
      defaultConnectionName: DEFAULT_CONNECTION_NAME,
      operationId: "ContactDeleteItem",
      parameters: parameters as Record<string, ExpressionOrValue>,
      options,
    }) as ActionSpec;
  },

  /**
   * Get contact
   * @returns Contact response - Body - ContactResponse
   * Operation id: `ContactGetItem`
   */
  contactGetItem(
    parameters: {
      table?: ExpressionOrValue; // REQUIRED — Folder id — string — Select a contacts folder
      id?: ExpressionOrValue; // REQUIRED — Item id — string — Unique identifier of a contact to retrieve
    } & Record<string, ExpressionOrValue>,
    options?: ConnectorCallOptions,
  ): ActionSpec {
    return buildConnectorCall({
      kind: "action",
      apiId: API_ID,
      defaultConnectionName: DEFAULT_CONNECTION_NAME,
      operationId: "ContactGetItem",
      parameters: parameters as Record<string, ExpressionOrValue>,
      options,
    }) as ActionSpec;
  },

  /**
   * Get contacts
   * @returns Entity list response - Body - EntityListResponse[ContactResponse]
   * Operation id: `ContactGetItems`
   */
  contactGetItems(
    parameters: {
      table?: ExpressionOrValue; // REQUIRED — Folder id — string — Unique identifier of the contacts folder to retrieve
      $filter?: ExpressionOrValue; // optional — Filter Query — string — An ODATA filter query to restrict the entries returned (e.g. stringColumn eq 'string' OR numberColumn lt 123).
      $orderby?: ExpressionOrValue; // optional — Order By — string — An ODATA orderBy query for specifying the order of entries.
      $top?: ExpressionOrValue; // optional — Top Count — integer — Total number of entries to retrieve (default = all).
      $skip?: ExpressionOrValue; // optional — Skip Count — integer — The number of entries to skip (default = 0).
    } & Record<string, ExpressionOrValue>,
    options?: ConnectorCallOptions,
  ): ActionSpec {
    return buildConnectorCall({
      kind: "action",
      apiId: API_ID,
      defaultConnectionName: DEFAULT_CONNECTION_NAME,
      operationId: "ContactGetItems",
      parameters: parameters as Record<string, ExpressionOrValue>,
      options,
    }) as ActionSpec;
  },

  /**
   * Get contact folders
   * @returns Entity list response - Body - EntityListResponse[Table]
   * Operation id: `ContactGetTables`
   */
  contactGetTables(options?: ConnectorCallOptions): ActionSpec {
    return buildConnectorCall({
      kind: "action",
      apiId: API_ID,
      defaultConnectionName: DEFAULT_CONNECTION_NAME,
      operationId: "ContactGetTables",
      parameters: {},
      options,
    }) as ActionSpec;
  },

  /**
   * Update contact
   * @returns Contact response - Body - ContactResponse
   * Operation id: `ContactPatchItem`
   */
  contactPatchItem(
    parameters: {
      table?: ExpressionOrValue; // REQUIRED — Folder id — string — Select a contacts folder
      id?: ExpressionOrValue; // REQUIRED — Id — string — Unique identifier of contact to update
      GivenName?: ExpressionOrValue; // REQUIRED — Given name — string — The contact's given name
      HomePhones?: ExpressionOrValue; // REQUIRED — Home phones — array of string — The contact's home phone numbers
      Id?: ExpressionOrValue; // optional — string — The contact's unique identifier.
      ParentFolderId?: ExpressionOrValue; // optional — Parent folder id — string — The ID of the contact's parent folder
      Birthday?: ExpressionOrValue; // optional — date-time — The contact's birthday
      FileAs?: ExpressionOrValue; // optional — File as — string — The name the contact is filed under
      DisplayName?: ExpressionOrValue; // optional — Display Name — string — The contact's display name
      Initials?: ExpressionOrValue; // optional — string — The contact's initials
      MiddleName?: ExpressionOrValue; // optional — Middle name — string — The contact's middle name
      NickName?: ExpressionOrValue; // optional — Nickname — string — The contact's nickname
      Surname?: ExpressionOrValue; // optional — string — The contact's surname
      Title?: ExpressionOrValue; // optional — string — The contact's title
      Generation?: ExpressionOrValue; // optional — string — The contact's generation
      Name?: ExpressionOrValue; // optional — string
      Address?: ExpressionOrValue; // optional — email
      ImAddresses?: ExpressionOrValue; // optional — IM addresses — array of string — The contact's instant messaging (IM) addresses
      JobTitle?: ExpressionOrValue; // optional — string — The contact's job title
      CompanyName?: ExpressionOrValue; // optional — Company name — string — The name of the contact's company
      Department?: ExpressionOrValue; // optional — string — The contact's department
      OfficeLocation?: ExpressionOrValue; // optional — Office location — string — The location of the contact's office
      Profession?: ExpressionOrValue; // optional — string — The contact's profession
      BusinessHomePage?: ExpressionOrValue; // optional — Business home page — string — The business home page of the contact
      AssistantName?: ExpressionOrValue; // optional — Assistant name — string — The name of the contact's assistant
      Manager?: ExpressionOrValue; // optional — string — The name of the contact's manager
      BusinessPhones?: ExpressionOrValue; // optional — Business phones — array of string — The contact's business phone numbers
      MobilePhone1?: ExpressionOrValue; // optional — Mobile phone — string — The contact's mobile phone number
      Street?: ExpressionOrValue; // optional — string
      City?: ExpressionOrValue; // optional — string
      State?: ExpressionOrValue; // optional — string
      CountryOrRegion?: ExpressionOrValue; // optional — string
      PostalCode?: ExpressionOrValue; // optional — string
      YomiCompanyName?: ExpressionOrValue; // optional — Yomi company name — string — The phonetic Japanese company name of the contact
      YomiGivenName?: ExpressionOrValue; // optional — Yomi given name — string — The phonetic Japanese given name (first name) of the contact
      YomiSurname?: ExpressionOrValue; // optional — Yomi surname — string — The phonetic Japanese surname (last name) of the contact
      Categories?: ExpressionOrValue; // optional — array of string — The categories associated with the contact
      ChangeKey?: ExpressionOrValue; // optional — Change key — string — Identifies the version of the event object
      DateTimeCreated?: ExpressionOrValue; // optional — Created time — date-time — The time the contact was created
      DateTimeLastModified?: ExpressionOrValue; // optional — Last modified time — date-time — The time the contact was modified
    } & Record<string, ExpressionOrValue>,
    options?: ConnectorCallOptions,
  ): ActionSpec {
    return buildConnectorCall({
      kind: "action",
      apiId: API_ID,
      defaultConnectionName: DEFAULT_CONNECTION_NAME,
      operationId: "ContactPatchItem",
      parameters: parameters as Record<string, ExpressionOrValue>,
      options,
    }) as ActionSpec;
  },

  /**
   * Create contact
   * @returns Contact response - Body - ContactResponse
   * Operation id: `ContactPostItem`
   */
  contactPostItem(
    parameters: {
      table?: ExpressionOrValue; // REQUIRED — Folder id — string — Select a contacts folder
      GivenName?: ExpressionOrValue; // REQUIRED — Given name — string — The contact's given name
      HomePhones?: ExpressionOrValue; // REQUIRED — Home phones — array of string — The contact's home phone numbers
      Id?: ExpressionOrValue; // optional — string — The contact's unique identifier.
      ParentFolderId?: ExpressionOrValue; // optional — Parent folder id — string — The ID of the contact's parent folder
      Birthday?: ExpressionOrValue; // optional — date-time — The contact's birthday
      FileAs?: ExpressionOrValue; // optional — File as — string — The name the contact is filed under
      DisplayName?: ExpressionOrValue; // optional — Display Name — string — The contact's display name
      Initials?: ExpressionOrValue; // optional — string — The contact's initials
      MiddleName?: ExpressionOrValue; // optional — Middle name — string — The contact's middle name
      NickName?: ExpressionOrValue; // optional — Nickname — string — The contact's nickname
      Surname?: ExpressionOrValue; // optional — string — The contact's surname
      Title?: ExpressionOrValue; // optional — string — The contact's title
      Generation?: ExpressionOrValue; // optional — string — The contact's generation
      Name?: ExpressionOrValue; // optional — string
      Address?: ExpressionOrValue; // optional — email
      ImAddresses?: ExpressionOrValue; // optional — IM addresses — array of string — The contact's instant messaging (IM) addresses
      JobTitle?: ExpressionOrValue; // optional — string — The contact's job title
      CompanyName?: ExpressionOrValue; // optional — Company name — string — The name of the contact's company
      Department?: ExpressionOrValue; // optional — string — The contact's department
      OfficeLocation?: ExpressionOrValue; // optional — Office location — string — The location of the contact's office
      Profession?: ExpressionOrValue; // optional — string — The contact's profession
      BusinessHomePage?: ExpressionOrValue; // optional — Business home page — string — The business home page of the contact
      AssistantName?: ExpressionOrValue; // optional — Assistant name — string — The name of the contact's assistant
      Manager?: ExpressionOrValue; // optional — string — The name of the contact's manager
      BusinessPhones?: ExpressionOrValue; // optional — Business phones — array of string — The contact's business phone numbers
      MobilePhone1?: ExpressionOrValue; // optional — Mobile phone — string — The contact's mobile phone number
      Street?: ExpressionOrValue; // optional — string
      City?: ExpressionOrValue; // optional — string
      State?: ExpressionOrValue; // optional — string
      CountryOrRegion?: ExpressionOrValue; // optional — string
      PostalCode?: ExpressionOrValue; // optional — string
      YomiCompanyName?: ExpressionOrValue; // optional — Yomi company name — string — The phonetic Japanese company name of the contact
      YomiGivenName?: ExpressionOrValue; // optional — Yomi given name — string — The phonetic Japanese given name (first name) of the contact
      YomiSurname?: ExpressionOrValue; // optional — Yomi surname — string — The phonetic Japanese surname (last name) of the contact
      Categories?: ExpressionOrValue; // optional — array of string — The categories associated with the contact
      ChangeKey?: ExpressionOrValue; // optional — Change key — string — Identifies the version of the event object
      DateTimeCreated?: ExpressionOrValue; // optional — Created time — date-time — The time the contact was created
      DateTimeLastModified?: ExpressionOrValue; // optional — Last modified time — date-time — The time the contact was modified
    } & Record<string, ExpressionOrValue>,
    options?: ConnectorCallOptions,
  ): ActionSpec {
    return buildConnectorCall({
      kind: "action",
      apiId: API_ID,
      defaultConnectionName: DEFAULT_CONNECTION_NAME,
      operationId: "ContactPostItem",
      parameters: parameters as Record<string, ExpressionOrValue>,
      options,
    }) as ActionSpec;
  },

  /**
   * Delete email
   * Operation id: `DeleteEmail`
   */
  deleteEmail(
    parameters: {
      messageId?: ExpressionOrValue; // REQUIRED — Message Id — string — Id of the email to delete.
    } & Record<string, ExpressionOrValue>,
    options?: ConnectorCallOptions,
  ): ActionSpec {
    return buildConnectorCall({
      kind: "action",
      apiId: API_ID,
      defaultConnectionName: DEFAULT_CONNECTION_NAME,
      operationId: "DeleteEmail",
      parameters: parameters as Record<string, ExpressionOrValue>,
      options,
    }) as ActionSpec;
  },

  /**
   * Flag email
   * Operation id: `Flag`
   */
  flag(
    parameters: {
      messageId?: ExpressionOrValue; // REQUIRED — Message Id — string — Id of the email to be flagged.
    } & Record<string, ExpressionOrValue>,
    options?: ConnectorCallOptions,
  ): ActionSpec {
    return buildConnectorCall({
      kind: "action",
      apiId: API_ID,
      defaultConnectionName: DEFAULT_CONNECTION_NAME,
      operationId: "Flag",
      parameters: parameters as Record<string, ExpressionOrValue>,
      options,
    }) as ActionSpec;
  },

  /**
   * Forward an email
   * Operation id: `ForwardEmail`
   */
  forwardEmail(
    parameters: {
      message_id?: ExpressionOrValue; // REQUIRED — Message Id — string — Id of the message to forward.
      ToRecipients?: ExpressionOrValue; // REQUIRED — To — string — Semicolon separated list of recipients to forward the message to
      Comment?: ExpressionOrValue; // optional — string — Comment
    } & Record<string, ExpressionOrValue>,
    options?: ConnectorCallOptions,
  ): ActionSpec {
    return buildConnectorCall({
      kind: "action",
      apiId: API_ID,
      defaultConnectionName: DEFAULT_CONNECTION_NAME,
      operationId: "ForwardEmail",
      parameters: parameters as Record<string, ExpressionOrValue>,
      options,
    }) as ActionSpec;
  },

  /**
   * Get attachment
   * @returns - response - binary
   * Operation id: `GetAttachment`
   */
  getAttachment(
    parameters: {
      messageId?: ExpressionOrValue; // REQUIRED — Message Id — string — Id of the email.
      attachmentId?: ExpressionOrValue; // REQUIRED — Attachment Id — string — Id of the attachment to download.
    } & Record<string, ExpressionOrValue>,
    options?: ConnectorCallOptions,
  ): ActionSpec {
    return buildConnectorCall({
      kind: "action",
      apiId: API_ID,
      defaultConnectionName: DEFAULT_CONNECTION_NAME,
      operationId: "GetAttachment",
      parameters: parameters as Record<string, ExpressionOrValue>,
      options,
    }) as ActionSpec;
  },

  /**
   * Get email
   * @returns Receive Email Message - Body - ClientReceiveMessage
   * Operation id: `GetEmail`
   */
  getEmail(
    parameters: {
      messageId?: ExpressionOrValue; // REQUIRED — Message Id — string — Id of the email.
      includeAttachments?: ExpressionOrValue; // optional — Include Attachments — boolean — If set to true, attachments content will also be retrieved along with the email.
      internetMessageId?: ExpressionOrValue; // optional — Internet Message Id — string — Internet Message Id.
    } & Record<string, ExpressionOrValue>,
    options?: ConnectorCallOptions,
  ): ActionSpec {
    return buildConnectorCall({
      kind: "action",
      apiId: API_ID,
      defaultConnectionName: DEFAULT_CONNECTION_NAME,
      operationId: "GetEmail",
      parameters: parameters as Record<string, ExpressionOrValue>,
      options,
    }) as ActionSpec;
  },

  /**
   * Get emails [DEPRECATED]
   * @deprecated Marked deprecated by Microsoft.
   * @returns - response - array of ClientReceiveMessageStringEnums
   * Operation id: `GetEmails`
   */
  getEmails(
    parameters: {
      folderPath?: ExpressionOrValue; // optional — Folder — string — Mail folder to retrieve emails from (default: 'Inbox').
      fetchOnlyUnread?: ExpressionOrValue; // optional — Fetch Only Unread Messages — boolean — Retrieve only unread emails?.
      includeAttachments?: ExpressionOrValue; // optional — Include Attachments — boolean — If set to true, attachments content will also be retrieved along with the email.
      searchQuery?: ExpressionOrValue; // optional — Search Query — string — Search query (like in the Outlook client) to filter emails.
      top?: ExpressionOrValue; // optional — Top — integer — Number of emails to retrieve (default: 10).
    } & Record<string, ExpressionOrValue>,
    options?: ConnectorCallOptions,
  ): ActionSpec {
    return buildConnectorCall({
      kind: "action",
      apiId: API_ID,
      defaultConnectionName: DEFAULT_CONNECTION_NAME,
      operationId: "GetEmails",
      parameters: parameters as Record<string, ExpressionOrValue>,
      options,
    }) as ActionSpec;
  },

  /**
   * Get emails (V2)
   * @returns Represents a wrapper object for batch response - Body - BatchResponse[ClientReceiveMessage]
   * Operation id: `GetEmailsV2`
   */
  getEmailsV2(
    parameters: {
      folderPath?: ExpressionOrValue; // optional — Folder — string — Mail folder to retrieve emails from (default: 'Inbox').
      to?: ExpressionOrValue; // optional — To — email — Recipient email addresses separated by semicolons (If any match, the trigger will run).
      cc?: ExpressionOrValue; // optional — CC — email — CC recipient email addresses separated by semicolons (If any match, the trigger will run).
      toOrCc?: ExpressionOrValue; // optional — To or CC — email — To or CC recipient email addresses separated by semicolons (If any match, the trigger will run).
      "from"?: ExpressionOrValue; // optional — From — email — Sender email addresses separated by semicolons (If any match, the trigger will run).
      importance?: ExpressionOrValue; // optional — Importance — string — Importance of the email (Any, High, Normal, Low).
      fetchOnlyWithAttachment?: ExpressionOrValue; // optional — Only with Attachments — boolean — If set to true, only emails with an attachment will be retrieved. Emails without any attachments will be skipped. If set
      subjectFilter?: ExpressionOrValue; // optional — Subject Filter — string — String to look for in the subject line.
      fetchOnlyUnread?: ExpressionOrValue; // optional — Fetch Only Unread Messages — boolean — Retrieve only unread emails?.
      includeAttachments?: ExpressionOrValue; // optional — Include Attachments — boolean — If set to true, attachments content will also be retrieved along with the email.
      searchQuery?: ExpressionOrValue; // optional — Search Query — string — Search query to filter emails. How to use '$search' parameter please refer to: https://docs.microsoft.com/previous-versi
      top?: ExpressionOrValue; // optional — Top — integer — Number of emails to retrieve (default: 10).
    } & Record<string, ExpressionOrValue>,
    options?: ConnectorCallOptions,
  ): ActionSpec {
    return buildConnectorCall({
      kind: "action",
      apiId: API_ID,
      defaultConnectionName: DEFAULT_CONNECTION_NAME,
      operationId: "GetEmailsV2",
      parameters: parameters as Record<string, ExpressionOrValue>,
      options,
    }) as ActionSpec;
  },

  /**
   * Get calendar view of events [DEPRECATED]
   * @deprecated Marked deprecated by Microsoft.
   * @returns Response containing a list and next link - Body - PaginatedListResponse[CalendarEventClientReceiveStringEnums]
   * Operation id: `GetEventsCalendarView`
   */
  getEventsCalendarView(
    parameters: {
      calendarId?: ExpressionOrValue; // REQUIRED — Calendar Id — string — Select a calendar.
      startDateTimeOffset?: ExpressionOrValue; // REQUIRED — Start Time — string — Start time (example: '2017-01-01T08:00:00-07:00').
      endDateTimeOffset?: ExpressionOrValue; // REQUIRED — End Time — string — End time (example: '2017-02-01T08:00:00-07:00').
    } & Record<string, ExpressionOrValue>,
    options?: ConnectorCallOptions,
  ): ActionSpec {
    return buildConnectorCall({
      kind: "action",
      apiId: API_ID,
      defaultConnectionName: DEFAULT_CONNECTION_NAME,
      operationId: "GetEventsCalendarView",
      parameters: parameters as Record<string, ExpressionOrValue>,
      options,
    }) as ActionSpec;
  },

  /**
   * Get calendar view of events (V2)
   * @returns Entity list response - Body - EntityListResponse[CalendarEventClientReceiveStringEnums]
   * Operation id: `GetEventsCalendarViewV2`
   */
  getEventsCalendarViewV2(
    parameters: {
      calendarId?: ExpressionOrValue; // REQUIRED — Calendar Id — string — Select a calendar
      startDateTimeOffset?: ExpressionOrValue; // REQUIRED — Start Time — string — Start time (example: '2017-01-01T08:00:00-07:00')
      endDateTimeOffset?: ExpressionOrValue; // REQUIRED — End Time — string — End time (example: '2017-02-01T08:00:00-07:00')
      $filter?: ExpressionOrValue; // optional — Filter Query — string — An ODATA filter query to restrict the entries returned (e.g. stringColumn eq 'string' OR numberColumn lt 123).
      $orderby?: ExpressionOrValue; // optional — Order By — string — An ODATA orderBy query for specifying the order of entries.
      $top?: ExpressionOrValue; // optional — Top Count — integer — Total number of entries to retrieve (default = all).
      $skip?: ExpressionOrValue; // optional — Skip Count — integer — The number of entries to skip (default = 0).
      search?: ExpressionOrValue; // optional — Search — string — Search text for matching event body and subject
    } & Record<string, ExpressionOrValue>,
    options?: ConnectorCallOptions,
  ): ActionSpec {
    return buildConnectorCall({
      kind: "action",
      apiId: API_ID,
      defaultConnectionName: DEFAULT_CONNECTION_NAME,
      operationId: "GetEventsCalendarViewV2",
      parameters: parameters as Record<string, ExpressionOrValue>,
      options,
    }) as ActionSpec;
  },

  /**
   * Mark as read
   * Operation id: `MarkAsRead`
   */
  markAsRead(
    parameters: {
      messageId?: ExpressionOrValue; // REQUIRED — Message Id — string — Id of the email to be marked as read.
    } & Record<string, ExpressionOrValue>,
    options?: ConnectorCallOptions,
  ): ActionSpec {
    return buildConnectorCall({
      kind: "action",
      apiId: API_ID,
      defaultConnectionName: DEFAULT_CONNECTION_NAME,
      operationId: "MarkAsRead",
      parameters: parameters as Record<string, ExpressionOrValue>,
      options,
    }) as ActionSpec;
  },

  /**
   * Move email
   * @returns Receive Email Message - Body - ClientReceiveMessageStringEnums
   * Operation id: `Move`
   */
  move(
    parameters: {
      messageId?: ExpressionOrValue; // REQUIRED — Message Id — string — Id of the email to be moved.
      folderPath?: ExpressionOrValue; // REQUIRED — Folder — string — Mail folder to move the email to.
    } & Record<string, ExpressionOrValue>,
    options?: ConnectorCallOptions,
  ): ActionSpec {
    return buildConnectorCall({
      kind: "action",
      apiId: API_ID,
      defaultConnectionName: DEFAULT_CONNECTION_NAME,
      operationId: "Move",
      parameters: parameters as Record<string, ExpressionOrValue>,
      options,
    }) as ActionSpec;
  },

  /**
   * When an email is flagged [DEPRECATED]
   * @deprecated Marked deprecated by Microsoft.
   * @remarks This is a trigger operation; pass it to flowBuilder.setTrigger().
   * @returns Represents a wrapper object for batch trigger response - Body - TriggerBatchResponse[ClientReceiveMessage]
   * Operation id: `OnFlaggedEmail`
   */
  onFlaggedEmail(
    parameters: {
      folderPath?: ExpressionOrValue; // optional — Folder — string — Mail folder to check for new emails.
      to?: ExpressionOrValue; // optional — To — email — Recipient email addresses separated by semicolons (If any match, the trigger will run).
      cc?: ExpressionOrValue; // optional — CC — email — CC recipient email addresses separated by semicolons (If any match, the trigger will run).
      toOrCc?: ExpressionOrValue; // optional — To or CC — email — To or CC recipient email addresses separated by semicolons (If any match, the trigger will run).
      "from"?: ExpressionOrValue; // optional — From — email — Sender email addresses separated by semicolons (If any match, the trigger will run).
      importance?: ExpressionOrValue; // optional — Importance — string — Importance of the email (Any, High, Normal, Low).
      fetchOnlyWithAttachment?: ExpressionOrValue; // optional — Only with Attachments — boolean — If set to true, only emails with an attachment will be retrieved. Emails without any attachments will be skipped. If set
      includeAttachments?: ExpressionOrValue; // optional — Include Attachments — boolean — Should the response of the trigger include the attachments content.
      subjectFilter?: ExpressionOrValue; // optional — Subject Filter — string — String to look for in the subject line.
    } & Record<string, ExpressionOrValue>,
    options?: ConnectorCallOptions,
  ): TriggerSpec {
    return buildConnectorCall({
      kind: "trigger",
      apiId: API_ID,
      defaultConnectionName: DEFAULT_CONNECTION_NAME,
      operationId: "OnFlaggedEmail",
      parameters: parameters as Record<string, ExpressionOrValue>,
      options,
    }) as TriggerSpec;
  },

  /**
   * When an email is flagged (V2)
   * @remarks This is a trigger operation; pass it to flowBuilder.setTrigger().
   * @returns Represents a wrapper object for batch trigger response - Body - TriggerBatchResponse[ClientReceiveMessage]
   * Operation id: `OnFlaggedEmailV2`
   */
  onFlaggedEmailV2(
    parameters: {
      folderPath?: ExpressionOrValue; // optional — Folder — string — Mail folder to check for new emails.
      to?: ExpressionOrValue; // optional — To — email — Recipient email addresses separated by semicolons (If any match, the trigger will run).
      cc?: ExpressionOrValue; // optional — CC — email — CC recipient email addresses separated by semicolons (If any match, the trigger will run).
      toOrCc?: ExpressionOrValue; // optional — To or CC — email — To or CC recipient email addresses separated by semicolons (If any match, the trigger will run).
      "from"?: ExpressionOrValue; // optional — From — email — Sender email addresses separated by semicolons (If any match, the trigger will run).
      importance?: ExpressionOrValue; // optional — Importance — string — Importance of the email (Any, High, Normal, Low).
      fetchOnlyWithAttachment?: ExpressionOrValue; // optional — Only with Attachments — boolean — If set to true, only emails with an attachment will be retrieved. Emails without any attachments will be skipped. If set
      includeAttachments?: ExpressionOrValue; // optional — Include Attachments — boolean — Should the response of the trigger include the attachments content.
      subjectFilter?: ExpressionOrValue; // optional — Subject Filter — string — String to look for in the subject line.
    } & Record<string, ExpressionOrValue>,
    options?: ConnectorCallOptions,
  ): TriggerSpec {
    return buildConnectorCall({
      kind: "trigger",
      apiId: API_ID,
      defaultConnectionName: DEFAULT_CONNECTION_NAME,
      operationId: "OnFlaggedEmailV2",
      parameters: parameters as Record<string, ExpressionOrValue>,
      options,
    }) as TriggerSpec;
  },

  /**
   * When a new email arrives [DEPRECATED]
   * @deprecated Marked deprecated by Microsoft.
   * @remarks This is a trigger operation; pass it to flowBuilder.setTrigger().
   * @returns Represents a wrapper object for batch trigger response - Body - TriggerBatchResponse[ClientReceiveMessage]
   * Operation id: `OnNewEmail`
   */
  onNewEmail(
    parameters: {
      folderPath?: ExpressionOrValue; // optional — Folder — string — Mail folder to check for new emails.
      to?: ExpressionOrValue; // optional — To — email — Recipient email addresses separated by semicolons (If any match, the trigger will run).
      cc?: ExpressionOrValue; // optional — CC — email — CC recipient email addresses separated by semicolons (If any match, the trigger will run).
      toOrCc?: ExpressionOrValue; // optional — To or CC — email — To or CC recipient email addresses separated by semicolons (If any match, the trigger will run).
      "from"?: ExpressionOrValue; // optional — From — email — Sender email addresses separated by semicolons (If any match, the trigger will run).
      importance?: ExpressionOrValue; // optional — Importance — string — Importance of the email (Any, High, Normal, Low).
      fetchOnlyWithAttachment?: ExpressionOrValue; // optional — Only with Attachments — boolean — If set to true, only emails with an attachment will be retrieved. Emails without any attachments will be skipped. If set
      includeAttachments?: ExpressionOrValue; // optional — Include Attachments — boolean — Should the response of the trigger include the attachments content.
      subjectFilter?: ExpressionOrValue; // optional — Subject Filter — string — String to look for in the subject line.
    } & Record<string, ExpressionOrValue>,
    options?: ConnectorCallOptions,
  ): TriggerSpec {
    return buildConnectorCall({
      kind: "trigger",
      apiId: API_ID,
      defaultConnectionName: DEFAULT_CONNECTION_NAME,
      operationId: "OnNewEmail",
      parameters: parameters as Record<string, ExpressionOrValue>,
      options,
    }) as TriggerSpec;
  },

  /**
   * When a new email arrives (V2)
   * @remarks This is a trigger operation; pass it to flowBuilder.setTrigger().
   * @returns Represents a wrapper object for batch trigger response - Body - TriggerBatchResponse[ClientReceiveMessage]
   * Operation id: `OnNewEmailV2`
   */
  onNewEmailV2(
    parameters: {
      folderPath?: ExpressionOrValue; // optional — Folder — string — Mail folder to check for new emails.
      to?: ExpressionOrValue; // optional — To — email — Recipient email addresses separated by semicolons (If any match, the trigger will run).
      cc?: ExpressionOrValue; // optional — CC — email — CC recipient email addresses separated by semicolons (If any match, the trigger will run).
      toOrCc?: ExpressionOrValue; // optional — To or CC — email — To or CC recipient email addresses separated by semicolons (If any match, the trigger will run).
      "from"?: ExpressionOrValue; // optional — From — email — Sender email addresses separated by semicolons (If any match, the trigger will run).
      importance?: ExpressionOrValue; // optional — Importance — string — Importance of the email (Any, High, Normal, Low).
      fetchOnlyWithAttachment?: ExpressionOrValue; // optional — Only with Attachments — boolean — If set to true, only emails with an attachment will be retrieved. Emails without any attachments will be skipped. If set
      includeAttachments?: ExpressionOrValue; // optional — Include Attachments — boolean — Should the response of the trigger include the attachments content.
      subjectFilter?: ExpressionOrValue; // optional — Subject Filter — string — String to look for in the subject line.
    } & Record<string, ExpressionOrValue>,
    options?: ConnectorCallOptions,
  ): TriggerSpec {
    return buildConnectorCall({
      kind: "trigger",
      apiId: API_ID,
      defaultConnectionName: DEFAULT_CONNECTION_NAME,
      operationId: "OnNewEmailV2",
      parameters: parameters as Record<string, ExpressionOrValue>,
      options,
    }) as TriggerSpec;
  },

  /**
   * When a new email mentioning me arrives [DEPRECATED]
   * @deprecated Marked deprecated by Microsoft.
   * @remarks This is a trigger operation; pass it to flowBuilder.setTrigger().
   * @returns Represents a wrapper object for batch trigger response - Body - TriggerBatchResponse[ClientReceiveMessage]
   * Operation id: `OnNewMentionMeEmail`
   */
  onNewMentionMeEmail(
    parameters: {
      folderPath?: ExpressionOrValue; // optional — Folder — string — Mail folder to check for new emails.
      to?: ExpressionOrValue; // optional — To — email — Recipient email addresses separated by semicolons (If any match, the trigger will run).
      cc?: ExpressionOrValue; // optional — CC — email — CC recipient email addresses separated by semicolons (If any match, the trigger will run).
      toOrCc?: ExpressionOrValue; // optional — To or CC — email — To or CC recipient email addresses separated by semicolons (If any match, the trigger will run).
      "from"?: ExpressionOrValue; // optional — From — email — Sender email addresses separated by semicolons (If any match, the trigger will run).
      importance?: ExpressionOrValue; // optional — Importance — string — Importance of the email (Any, High, Normal, Low).
      fetchOnlyWithAttachment?: ExpressionOrValue; // optional — Only with Attachments — boolean — If set to true, only emails with an attachment will be retrieved. Emails without any attachments will be skipped. If set
      includeAttachments?: ExpressionOrValue; // optional — Include Attachments — boolean — Should the response of the trigger include the attachments content.
      subjectFilter?: ExpressionOrValue; // optional — Subject Filter — string — String to look for in the subject line.
    } & Record<string, ExpressionOrValue>,
    options?: ConnectorCallOptions,
  ): TriggerSpec {
    return buildConnectorCall({
      kind: "trigger",
      apiId: API_ID,
      defaultConnectionName: DEFAULT_CONNECTION_NAME,
      operationId: "OnNewMentionMeEmail",
      parameters: parameters as Record<string, ExpressionOrValue>,
      options,
    }) as TriggerSpec;
  },

  /**
   * When a new email mentioning me arrives (V2)
   * @remarks This is a trigger operation; pass it to flowBuilder.setTrigger().
   * @returns Represents a wrapper object for batch trigger response - Body - TriggerBatchResponse[ClientReceiveMessage]
   * Operation id: `OnNewMentionMeEmailV2`
   */
  onNewMentionMeEmailV2(
    parameters: {
      folderPath?: ExpressionOrValue; // optional — Folder — string — Mail folder to check for new emails.
      to?: ExpressionOrValue; // optional — To — email — Recipient email addresses separated by semicolons (If any match, the trigger will run).
      cc?: ExpressionOrValue; // optional — CC — email — CC recipient email addresses separated by semicolons (If any match, the trigger will run).
      toOrCc?: ExpressionOrValue; // optional — To or CC — email — To or CC recipient email addresses separated by semicolons (If any match, the trigger will run).
      "from"?: ExpressionOrValue; // optional — From — email — Sender email addresses separated by semicolons (If any match, the trigger will run).
      importance?: ExpressionOrValue; // optional — Importance — string — Importance of the email (Any, High, Normal, Low).
      fetchOnlyWithAttachment?: ExpressionOrValue; // optional — Only with Attachments — boolean — If set to true, only emails with an attachment will be retrieved. Emails without any attachments will be skipped. If set
      includeAttachments?: ExpressionOrValue; // optional — Include Attachments — boolean — Should the response of the trigger include the attachments content.
      subjectFilter?: ExpressionOrValue; // optional — Subject Filter — string — String to look for in the subject line.
    } & Record<string, ExpressionOrValue>,
    options?: ConnectorCallOptions,
  ): TriggerSpec {
    return buildConnectorCall({
      kind: "trigger",
      apiId: API_ID,
      defaultConnectionName: DEFAULT_CONNECTION_NAME,
      operationId: "OnNewMentionMeEmailV2",
      parameters: parameters as Record<string, ExpressionOrValue>,
      options,
    }) as TriggerSpec;
  },

  /**
   * When an upcoming event is starting soon [DEPRECATED]
   * @deprecated Marked deprecated by Microsoft.
   * @remarks This is a trigger operation; pass it to flowBuilder.setTrigger().
   * @returns The list of calendar items - Body - CalendarEventList
   * Operation id: `OnUpcomingEvents`
   */
  onUpcomingEvents(
    parameters: {
      table?: ExpressionOrValue; // REQUIRED — Calendar Id — string — Unique identifier of the calendar.
      lookAheadTimeInMinutes?: ExpressionOrValue; // optional — Look-Ahead Time — integer — Time (in minutes) to look ahead for upcoming events.
    } & Record<string, ExpressionOrValue>,
    options?: ConnectorCallOptions,
  ): TriggerSpec {
    return buildConnectorCall({
      kind: "trigger",
      apiId: API_ID,
      defaultConnectionName: DEFAULT_CONNECTION_NAME,
      operationId: "OnUpcomingEvents",
      parameters: parameters as Record<string, ExpressionOrValue>,
      options,
    }) as TriggerSpec;
  },

  /**
   * When an upcoming event is starting soon (V2)
   * @remarks This is a trigger operation; pass it to flowBuilder.setTrigger().
   * @returns The list of calendar items - Body - CalendarEventListClientReceive
   * Operation id: `OnUpcomingEventsV2`
   */
  onUpcomingEventsV2(
    parameters: {
      table?: ExpressionOrValue; // REQUIRED — Calendar Id — string — Unique identifier of the calendar.
      lookAheadTimeInMinutes?: ExpressionOrValue; // optional — Look-Ahead Time — integer — Time (in minutes) to look ahead for upcoming events.
    } & Record<string, ExpressionOrValue>,
    options?: ConnectorCallOptions,
  ): TriggerSpec {
    return buildConnectorCall({
      kind: "trigger",
      apiId: API_ID,
      defaultConnectionName: DEFAULT_CONNECTION_NAME,
      operationId: "OnUpcomingEventsV2",
      parameters: parameters as Record<string, ExpressionOrValue>,
      options,
    }) as TriggerSpec;
  },

  /**
   * Reply to email [DEPRECATED]
   * @deprecated Marked deprecated by Microsoft.
   * Operation id: `ReplyTo`
   */
  replyTo(
    parameters: {
      messageId?: ExpressionOrValue; // REQUIRED — Message Id — string — Id of the email to reply to.
      comment?: ExpressionOrValue; // REQUIRED — Comment — string — Reply comment.
      replyAll?: ExpressionOrValue; // optional — Reply All — boolean — Reply to all recipients.
    } & Record<string, ExpressionOrValue>,
    options?: ConnectorCallOptions,
  ): ActionSpec {
    return buildConnectorCall({
      kind: "action",
      apiId: API_ID,
      defaultConnectionName: DEFAULT_CONNECTION_NAME,
      operationId: "ReplyTo",
      parameters: parameters as Record<string, ExpressionOrValue>,
      options,
    }) as ActionSpec;
  },

  /**
   * Reply to email (V2) [DEPRECATED]
   * @deprecated Marked deprecated by Microsoft.
   * Operation id: `ReplyToV2`
   */
  replyToV2(
    parameters: {
      messageId?: ExpressionOrValue; // REQUIRED — Message Id — string — Id of the email to reply to.
      Name?: ExpressionOrValue; // REQUIRED — string — Attachment name
      ContentBytes?: ExpressionOrValue; // REQUIRED — Content — byte — Attachment content
      To?: ExpressionOrValue; // optional — email — Example: recipient1@domain.com; recipient2@domain.com
      Cc?: ExpressionOrValue; // optional — CC — email — Example: recipient1@domain.com; recipient2@domain.com
      Bcc?: ExpressionOrValue; // optional — BCC — email — Example: recipient1@domain.com; recipient2@domain.com
      Subject?: ExpressionOrValue; // optional — string — Email subject (if empty, the original subject used).
      Body?: ExpressionOrValue; // optional — string — Content of the email.
      ReplyAll?: ExpressionOrValue; // optional — Reply All — boolean — True to reply to all recipients. (default: False)
      IsHtml?: ExpressionOrValue; // optional — Is HTML — boolean — True to send the reply as HTML. (default: True)
      Importance?: ExpressionOrValue; // optional — string — Pick an importance. (default: Low)
    } & Record<string, ExpressionOrValue>,
    options?: ConnectorCallOptions,
  ): ActionSpec {
    return buildConnectorCall({
      kind: "action",
      apiId: API_ID,
      defaultConnectionName: DEFAULT_CONNECTION_NAME,
      operationId: "ReplyToV2",
      parameters: parameters as Record<string, ExpressionOrValue>,
      options,
    }) as ActionSpec;
  },

  /**
   * Reply to email (V3)
   * Operation id: `ReplyToV3`
   */
  replyToV3(
    parameters: {
      messageId?: ExpressionOrValue; // REQUIRED — Message Id — string — Id of the email to reply to.
      Name?: ExpressionOrValue; // REQUIRED — string — Attachment name
      ContentBytes?: ExpressionOrValue; // REQUIRED — Content — byte — Attachment content
      To?: ExpressionOrValue; // optional — email — Example: recipient1@domain.com; recipient2@domain.com
      Cc?: ExpressionOrValue; // optional — CC — email — Example: recipient1@domain.com; recipient2@domain.com
      Bcc?: ExpressionOrValue; // optional — BCC — email — Example: recipient1@domain.com; recipient2@domain.com
      Subject?: ExpressionOrValue; // optional — string — Email subject (if empty, the original subject used).
      Body?: ExpressionOrValue; // optional — html — Content of the email.
      ReplyAll?: ExpressionOrValue; // optional — Reply All — boolean — True to reply to all recipients. (default: False)
      Importance?: ExpressionOrValue; // optional — string — Pick an importance. (default: Low)
    } & Record<string, ExpressionOrValue>,
    options?: ConnectorCallOptions,
  ): ActionSpec {
    return buildConnectorCall({
      kind: "action",
      apiId: API_ID,
      defaultConnectionName: DEFAULT_CONNECTION_NAME,
      operationId: "ReplyToV3",
      parameters: parameters as Record<string, ExpressionOrValue>,
      options,
    }) as ActionSpec;
  },

  /**
   * Respond to an event invite
   * Operation id: `RespondToEvent`
   */
  respondToEvent(
    parameters: {
      event_id?: ExpressionOrValue; // REQUIRED — Event Id — string — Id of the event to respond to.
      response?: ExpressionOrValue; // REQUIRED — Response — string — Response for the event invite
      Comment?: ExpressionOrValue; // optional — string — Comment
      SendResponse?: ExpressionOrValue; // optional — Send response? — boolean — Send response to organizer?
    } & Record<string, ExpressionOrValue>,
    options?: ConnectorCallOptions,
  ): ActionSpec {
    return buildConnectorCall({
      kind: "action",
      apiId: API_ID,
      defaultConnectionName: DEFAULT_CONNECTION_NAME,
      operationId: "RespondToEvent",
      parameters: parameters as Record<string, ExpressionOrValue>,
      options,
    }) as ActionSpec;
  },

  /**
   * Send approval email
   * @returns Approval Email Response - Body - ApprovalEmailResponse
   * Operation id: `SendApprovalMail`
   */
  sendApprovalMail(
    parameters: {
      To?: ExpressionOrValue; // REQUIRED — email — Specify email addresses separated by semicolons like someone@contoso.com
      Name?: ExpressionOrValue; // REQUIRED — string — Attachment name
      ContentBytes?: ExpressionOrValue; // REQUIRED — Content — byte — Attachment content
      Subject?: ExpressionOrValue; // optional — string — Subject
      Options?: ExpressionOrValue; // optional — User Options — string — User Options
      HeaderText?: ExpressionOrValue; // optional — Header Text — string — Header text for email body
      SelectionText?: ExpressionOrValue; // optional — Selection Text — string — Header text for users options selection
      Body?: ExpressionOrValue; // optional — string — Body
      Importance?: ExpressionOrValue; // optional — string — Importance
      UseOnlyHTMLMessage?: ExpressionOrValue; // optional — Use only HTML message — boolean — Use only HTML message
      HideHTMLMessage?: ExpressionOrValue; // optional — Hide HTML message — boolean — If set to Yes, then the email body is hidden and only message card is displayed. Email clients which do not support acti
      ShowHTMLConfirmationDialog?: ExpressionOrValue; // optional — Show HTML confirmation dialog — boolean — If set to Yes then a dialog wil be shown to confirm selected option of HTML message
    } & Record<string, ExpressionOrValue>,
    options?: ConnectorCallOptions,
  ): ActionSpec {
    return buildConnectorCall({
      kind: "action",
      apiId: API_ID,
      defaultConnectionName: DEFAULT_CONNECTION_NAME,
      operationId: "SendApprovalMail",
      parameters: parameters as Record<string, ExpressionOrValue>,
      options,
    }) as ActionSpec;
  },

  /**
   * Send an email [DEPRECATED]
   * @deprecated Marked deprecated by Microsoft.
   * Operation id: `SendEmail`
   */
  sendEmail(
    parameters: {
      To?: ExpressionOrValue; // REQUIRED — email — Specify email addresses separated by semicolons like someone@contoso.com
      Subject?: ExpressionOrValue; // REQUIRED — string — Specify the subject of the mail
      Body?: ExpressionOrValue; // REQUIRED — string — Specify the body of the mail
      Name?: ExpressionOrValue; // REQUIRED — string — Attachment name
      ContentBytes?: ExpressionOrValue; // REQUIRED — Content — byte — Attachment content
      Cc?: ExpressionOrValue; // optional — CC — email — Specify email addresses separated by semicolons like someone@contoso.com
      Bcc?: ExpressionOrValue; // optional — BCC — email — Specify email addresses separated by semicolons like someone@contoso.com
      ReplyTo?: ExpressionOrValue; // optional — Reply To — email — The email addresses to use when replying
      Importance?: ExpressionOrValue; // optional — string — Importance
      IsHtml?: ExpressionOrValue; // optional — Is HTML — boolean — Is Html?
    } & Record<string, ExpressionOrValue>,
    options?: ConnectorCallOptions,
  ): ActionSpec {
    return buildConnectorCall({
      kind: "action",
      apiId: API_ID,
      defaultConnectionName: DEFAULT_CONNECTION_NAME,
      operationId: "SendEmail",
      parameters: parameters as Record<string, ExpressionOrValue>,
      options,
    }) as ActionSpec;
  },

  /**
   * Send an email (V2)
   * Operation id: `SendEmailV2`
   */
  sendEmailV2(
    parameters: {
      To?: ExpressionOrValue; // REQUIRED — email — Specify email addresses separated by semicolons like someone@contoso.com
      Subject?: ExpressionOrValue; // REQUIRED — string — Specify the subject of the mail
      Body?: ExpressionOrValue; // REQUIRED — html — Specify the body of the mail
      Name?: ExpressionOrValue; // REQUIRED — string — Attachment name
      ContentBytes?: ExpressionOrValue; // REQUIRED — Content — byte — Attachment content
      From?: ExpressionOrValue; // optional — From (Send as) — email — Email address to send mail from (requires "Send as" or "Send on behalf of" permission for that mailbox). For more info o
      Cc?: ExpressionOrValue; // optional — CC — email — Specify email addresses separated by semicolons like someone@contoso.com
      Bcc?: ExpressionOrValue; // optional — BCC — email — Specify email addresses separated by semicolons like someone@contoso.com
      ReplyTo?: ExpressionOrValue; // optional — Reply To — email — The email addresses to use when replying
      Importance?: ExpressionOrValue; // optional — string — Importance
    } & Record<string, ExpressionOrValue>,
    options?: ConnectorCallOptions,
  ): ActionSpec {
    return buildConnectorCall({
      kind: "action",
      apiId: API_ID,
      defaultConnectionName: DEFAULT_CONNECTION_NAME,
      operationId: "SendEmailV2",
      parameters: parameters as Record<string, ExpressionOrValue>,
      options,
    }) as ActionSpec;
  },

  /**
   * Send email with options
   * @returns Approval Email Response - Body - ApprovalEmailResponse
   * Operation id: `SendMailWithOptions`
   */
  sendMailWithOptions(
    parameters: {
      To?: ExpressionOrValue; // REQUIRED — email — Specify email addresses separated by semicolons like someone@contoso.com
      Name?: ExpressionOrValue; // REQUIRED — string — Attachment name
      ContentBytes?: ExpressionOrValue; // REQUIRED — Content — byte — Attachment content
      Subject?: ExpressionOrValue; // optional — string — Subject of the email
      Options?: ExpressionOrValue; // optional — User Options — string — List of comma separated options for the email response
      HeaderText?: ExpressionOrValue; // optional — Header Text — string — Header text for email body
      SelectionText?: ExpressionOrValue; // optional — Selection Text — string — Header text for users options selection
      Body?: ExpressionOrValue; // optional — string — Body of the email
      Importance?: ExpressionOrValue; // optional — string — Importance
      UseOnlyHTMLMessage?: ExpressionOrValue; // optional — Use only HTML message — boolean — Use only HTML message
      HideHTMLMessage?: ExpressionOrValue; // optional — Hide HTML message — boolean — If set to Yes, then the email body is hidden and only message card is displayed. Email clients which do not support acti
      ShowHTMLConfirmationDialog?: ExpressionOrValue; // optional — Show HTML confirmation dialog — boolean — If set to Yes then a dialog wil be shown to confirm selected option of HTML message
    } & Record<string, ExpressionOrValue>,
    options?: ConnectorCallOptions,
  ): ActionSpec {
    return buildConnectorCall({
      kind: "action",
      apiId: API_ID,
      defaultConnectionName: DEFAULT_CONNECTION_NAME,
      operationId: "SendMailWithOptions",
      parameters: parameters as Record<string, ExpressionOrValue>,
      options,
    }) as ActionSpec;
  },

  /**
   * Get event (V2)
   * @returns Connector specific calendar event model class for the client - Body - CalendarEventClientReceiveStringEnums
   * Operation id: `V2CalendarGetItem`
   */
  v2CalendarGetItem(
    parameters: {
      table?: ExpressionOrValue; // REQUIRED — Calendar id — string — Select a calendar
      id?: ExpressionOrValue; // REQUIRED — Item id — string — Select an event
    } & Record<string, ExpressionOrValue>,
    options?: ConnectorCallOptions,
  ): ActionSpec {
    return buildConnectorCall({
      kind: "action",
      apiId: API_ID,
      defaultConnectionName: DEFAULT_CONNECTION_NAME,
      operationId: "V2CalendarGetItem",
      parameters: parameters as Record<string, ExpressionOrValue>,
      options,
    }) as ActionSpec;
  },

  /**
   * Get events (V2) [DEPRECATED]
   * @deprecated Marked deprecated by Microsoft.
   * @returns Entity list response - Body - EntityListResponse[CalendarEventClientReceiveStringEnums]
   * Operation id: `V2CalendarGetItems`
   */
  v2CalendarGetItems(
    parameters: {
      table?: ExpressionOrValue; // REQUIRED — Calendar id — string — Select a calendar
      $filter?: ExpressionOrValue; // optional — Filter Query — string — An ODATA filter query to restrict the entries returned (e.g. stringColumn eq 'string' OR numberColumn lt 123).
      $orderby?: ExpressionOrValue; // optional — Order By — string — An ODATA orderBy query for specifying the order of entries.
      $top?: ExpressionOrValue; // optional — Top Count — integer — Total number of entries to retrieve (default = all).
      $skip?: ExpressionOrValue; // optional — Skip Count — integer — The number of entries to skip (default = 0).
    } & Record<string, ExpressionOrValue>,
    options?: ConnectorCallOptions,
  ): ActionSpec {
    return buildConnectorCall({
      kind: "action",
      apiId: API_ID,
      defaultConnectionName: DEFAULT_CONNECTION_NAME,
      operationId: "V2CalendarGetItems",
      parameters: parameters as Record<string, ExpressionOrValue>,
      options,
    }) as ActionSpec;
  },

  /**
   * Update event (V2) [DEPRECATED]
   * @deprecated Marked deprecated by Microsoft.
   * @returns Connector specific calendar event model class for the client - Body - CalendarEventClientReceiveStringEnums
   * Operation id: `V2CalendarPatchItem`
   */
  v2CalendarPatchItem(
    parameters: {
      table?: ExpressionOrValue; // REQUIRED — Calendar id — string — Select a calendar
      id?: ExpressionOrValue; // REQUIRED — Id — string — Select an event
      Subject?: ExpressionOrValue; // REQUIRED — string — Event subject
      Start?: ExpressionOrValue; // REQUIRED — Start time — date-time — Start time of the event (example: '2016-11-01T14:30:00Z')
      End?: ExpressionOrValue; // REQUIRED — End time — date-time — End time of the event (example: '2016-11-01T15:30:00Z')
      TimeZone?: ExpressionOrValue; // optional — Time zone — string — Time zone of the event
      RequiredAttendees?: ExpressionOrValue; // optional — Required attendees — email — Required attendees for the event separated by semicolons
      OptionalAttendees?: ExpressionOrValue; // optional — Optional attendees — email — Optional attendees for the event separated by semicolons
      ResourceAttendees?: ExpressionOrValue; // optional — Resource attendees — string — Resource attendees for the event separated by semicolons
      Body?: ExpressionOrValue; // optional — string — Body of the message associated with the event
      IsHtml?: ExpressionOrValue; // optional — Is HTML — boolean — Set to true if the body is Html
      Location?: ExpressionOrValue; // optional — string — Location of the event
      Importance?: ExpressionOrValue; // optional — string — The importance of the event: Low, Normal, or High
      IsAllDay?: ExpressionOrValue; // optional — Is all day event? — boolean — Set to true if the event lasts all day
      Recurrence?: ExpressionOrValue; // optional — string — The recurrence pattern for the event
      RecurrenceEnd?: ExpressionOrValue; // optional — Recurrence end time — date-time — End time of the recurrence
      NumberOfOccurrences?: ExpressionOrValue; // optional — Number of occurrences — integer — How many times to repeat the event
      Reminder?: ExpressionOrValue; // optional — integer — Time in minutes before event start to remind
      ShowAs?: ExpressionOrValue; // optional — Show as — string — Status to show during the event
      ResponseRequested?: ExpressionOrValue; // optional — Response requested — boolean — Set to true if the sender would like a response when the event is accepted or declined
    } & Record<string, ExpressionOrValue>,
    options?: ConnectorCallOptions,
  ): ActionSpec {
    return buildConnectorCall({
      kind: "action",
      apiId: API_ID,
      defaultConnectionName: DEFAULT_CONNECTION_NAME,
      operationId: "V2CalendarPatchItem",
      parameters: parameters as Record<string, ExpressionOrValue>,
      options,
    }) as ActionSpec;
  },

  /**
   * Create event (V2) [DEPRECATED]
   * @deprecated Marked deprecated by Microsoft.
   * @returns Connector specific calendar event model class for the client - Body - CalendarEventClientReceiveStringEnums
   * Operation id: `V2CalendarPostItem`
   */
  v2CalendarPostItem(
    parameters: {
      table?: ExpressionOrValue; // REQUIRED — Calendar id — string — Select a calendar
      Subject?: ExpressionOrValue; // REQUIRED — string — Event subject
      Start?: ExpressionOrValue; // REQUIRED — Start time — date-time — Start time of the event (example: '2016-11-01T14:30:00Z')
      End?: ExpressionOrValue; // REQUIRED — End time — date-time — End time of the event (example: '2016-11-01T15:30:00Z')
      TimeZone?: ExpressionOrValue; // optional — Time zone — string — Time zone of the event
      RequiredAttendees?: ExpressionOrValue; // optional — Required attendees — email — Required attendees for the event separated by semicolons
      OptionalAttendees?: ExpressionOrValue; // optional — Optional attendees — email — Optional attendees for the event separated by semicolons
      ResourceAttendees?: ExpressionOrValue; // optional — Resource attendees — string — Resource attendees for the event separated by semicolons
      Body?: ExpressionOrValue; // optional — string — Body of the message associated with the event
      IsHtml?: ExpressionOrValue; // optional — Is HTML — boolean — Set to true if the body is Html
      Location?: ExpressionOrValue; // optional — string — Location of the event
      Importance?: ExpressionOrValue; // optional — string — The importance of the event: Low, Normal, or High
      IsAllDay?: ExpressionOrValue; // optional — Is all day event? — boolean — Set to true if the event lasts all day
      Recurrence?: ExpressionOrValue; // optional — string — The recurrence pattern for the event
      RecurrenceEnd?: ExpressionOrValue; // optional — Recurrence end time — date-time — End time of the recurrence
      NumberOfOccurrences?: ExpressionOrValue; // optional — Number of occurrences — integer — How many times to repeat the event
      Reminder?: ExpressionOrValue; // optional — integer — Time in minutes before event start to remind
      ShowAs?: ExpressionOrValue; // optional — Show as — string — Status to show during the event
      ResponseRequested?: ExpressionOrValue; // optional — Response requested — boolean — Set to true if the sender would like a response when the event is accepted or declined
    } & Record<string, ExpressionOrValue>,
    options?: ConnectorCallOptions,
  ): ActionSpec {
    return buildConnectorCall({
      kind: "action",
      apiId: API_ID,
      defaultConnectionName: DEFAULT_CONNECTION_NAME,
      operationId: "V2CalendarPostItem",
      parameters: parameters as Record<string, ExpressionOrValue>,
      options,
    }) as ActionSpec;
  },

  /**
   * Get events (V3)
   * @returns The list of calendar items - Body - CalendarEventListClientReceive
   * Operation id: `V3CalendarGetItems`
   */
  v3CalendarGetItems(
    parameters: {
      table?: ExpressionOrValue; // REQUIRED — Calendar id — string — Select a calendar
      $filter?: ExpressionOrValue; // optional — Filter Query — string — An ODATA filter query to restrict the entries returned (e.g. stringColumn eq 'string' OR numberColumn lt 123).
      $orderby?: ExpressionOrValue; // optional — Order By — string — An ODATA orderBy query for specifying the order of entries.
      $top?: ExpressionOrValue; // optional — Top Count — integer — Total number of entries to retrieve (default = all).
      $skip?: ExpressionOrValue; // optional — Skip Count — integer — The number of entries to skip (default = 0).
    } & Record<string, ExpressionOrValue>,
    options?: ConnectorCallOptions,
  ): ActionSpec {
    return buildConnectorCall({
      kind: "action",
      apiId: API_ID,
      defaultConnectionName: DEFAULT_CONNECTION_NAME,
      operationId: "V3CalendarGetItems",
      parameters: parameters as Record<string, ExpressionOrValue>,
      options,
    }) as ActionSpec;
  },

  /**
   * Update event (V3)
   * @returns Connector specific calendar event model class for the client - Body - CalendarEventClientReceiveStringEnums
   * Operation id: `V3CalendarPatchItem`
   */
  v3CalendarPatchItem(
    parameters: {
      table?: ExpressionOrValue; // REQUIRED — Calendar id — string — Select a calendar
      id?: ExpressionOrValue; // REQUIRED — Id — string — Select an event
      Subject?: ExpressionOrValue; // REQUIRED — string — Event subject
      Start?: ExpressionOrValue; // REQUIRED — Start time — date-time — Start time of the event (example: '2016-11-01T14:30:00Z')
      End?: ExpressionOrValue; // REQUIRED — End time — date-time — End time of the event (example: '2016-11-01T15:30:00Z')
      TimeZone?: ExpressionOrValue; // optional — Time zone — string — Time zone of the event
      RequiredAttendees?: ExpressionOrValue; // optional — Required attendees — email — Required attendees for the event separated by semicolons
      OptionalAttendees?: ExpressionOrValue; // optional — Optional attendees — email — Optional attendees for the event separated by semicolons
      ResourceAttendees?: ExpressionOrValue; // optional — Resource attendees — string — Resource attendees for the event separated by semicolons
      Body?: ExpressionOrValue; // optional — html — Body of the message associated with the event
      Location?: ExpressionOrValue; // optional — string — Location of the event
      Importance?: ExpressionOrValue; // optional — string — The importance of the event: Low, Normal, or High
      IsAllDay?: ExpressionOrValue; // optional — Is all day event? — boolean — Set to true if the event lasts all day
      Recurrence?: ExpressionOrValue; // optional — string — The recurrence pattern for the event
      RecurrenceEnd?: ExpressionOrValue; // optional — Recurrence end time — date-time — End time of the recurrence
      NumberOfOccurrences?: ExpressionOrValue; // optional — Number of occurrences — integer — How many times to repeat the event
      Reminder?: ExpressionOrValue; // optional — integer — Time in minutes before event start to remind
      ShowAs?: ExpressionOrValue; // optional — Show as — string — Status to show during the event
      ResponseRequested?: ExpressionOrValue; // optional — Response requested — boolean — Set to true if the sender would like a response when the event is accepted or declined
    } & Record<string, ExpressionOrValue>,
    options?: ConnectorCallOptions,
  ): ActionSpec {
    return buildConnectorCall({
      kind: "action",
      apiId: API_ID,
      defaultConnectionName: DEFAULT_CONNECTION_NAME,
      operationId: "V3CalendarPatchItem",
      parameters: parameters as Record<string, ExpressionOrValue>,
      options,
    }) as ActionSpec;
  },

  /**
   * Create event (V3)
   * @returns Connector specific calendar event model class for the client - Body - CalendarEventClientReceiveStringEnums
   * Operation id: `V3CalendarPostItem`
   */
  v3CalendarPostItem(
    parameters: {
      table?: ExpressionOrValue; // REQUIRED — Calendar id — string — Select a calendar
      Subject?: ExpressionOrValue; // REQUIRED — string — Event subject
      Start?: ExpressionOrValue; // REQUIRED — Start time — date-time — Start time of the event (example: '2016-11-01T14:30:00Z')
      End?: ExpressionOrValue; // REQUIRED — End time — date-time — End time of the event (example: '2016-11-01T15:30:00Z')
      TimeZone?: ExpressionOrValue; // optional — Time zone — string — Time zone of the event
      RequiredAttendees?: ExpressionOrValue; // optional — Required attendees — email — Required attendees for the event separated by semicolons
      OptionalAttendees?: ExpressionOrValue; // optional — Optional attendees — email — Optional attendees for the event separated by semicolons
      ResourceAttendees?: ExpressionOrValue; // optional — Resource attendees — string — Resource attendees for the event separated by semicolons
      Body?: ExpressionOrValue; // optional — html — Body of the message associated with the event
      Location?: ExpressionOrValue; // optional — string — Location of the event
      Importance?: ExpressionOrValue; // optional — string — The importance of the event: Low, Normal, or High
      IsAllDay?: ExpressionOrValue; // optional — Is all day event? — boolean — Set to true if the event lasts all day
      Recurrence?: ExpressionOrValue; // optional — string — The recurrence pattern for the event
      RecurrenceEnd?: ExpressionOrValue; // optional — Recurrence end time — date-time — End time of the recurrence
      NumberOfOccurrences?: ExpressionOrValue; // optional — Number of occurrences — integer — How many times to repeat the event
      Reminder?: ExpressionOrValue; // optional — integer — Time in minutes before event start to remind
      ShowAs?: ExpressionOrValue; // optional — Show as — string — Status to show during the event
      ResponseRequested?: ExpressionOrValue; // optional — Response requested — boolean — Set to true if the sender would like a response when the event is accepted or declined
    } & Record<string, ExpressionOrValue>,
    options?: ConnectorCallOptions,
  ): ActionSpec {
    return buildConnectorCall({
      kind: "action",
      apiId: API_ID,
      defaultConnectionName: DEFAULT_CONNECTION_NAME,
      operationId: "V3CalendarPostItem",
      parameters: parameters as Record<string, ExpressionOrValue>,
      options,
    }) as ActionSpec;
  },
} as const;
