// AUTO-GENERATED by packages/connectors/scripts/generate.ts.
// Do not edit by hand. Re-run `bun --filter @vibeflow/connectors generate`.
// Connector: shared_powerbi — Power BI
// Source: https://learn.microsoft.com/en-us/connectors/powerbi/?accept=text/markdown

import { buildConnectorCall, type ActionSpec, type ConnectorCallOptions, type ExpressionOrValue, type TriggerSpec } from "../_runtime.js";

const API_ID = "/providers/Microsoft.PowerApps/apis/shared_powerbi";
const DEFAULT_CONNECTION_NAME = "shared_powerbi";

export const PowerBI = {
  /** Connector id (`shared_powerbi`). */
  connectorId: "shared_powerbi",
  /** Power Automate apiId for this connector. */
  apiId: API_ID,

  /**
   * Add rows to a dataset
   * Operation id: `AddRows`
   */
  addRows(
    parameters: {
      groupid?: ExpressionOrValue; // REQUIRED — Workspace — string — The unique identifier of the workspace.
      datasetid?: ExpressionOrValue; // REQUIRED — Dataset — string — The unique identifier of the dataset.
      tablename?: ExpressionOrValue; // REQUIRED — Table — string — The name of the table.
      Payload?: ExpressionOrValue; // optional — Payload to send — dynamic
    } & Record<string, ExpressionOrValue>,
    options?: ConnectorCallOptions,
  ): ActionSpec {
    return buildConnectorCall({
      kind: "action",
      apiId: API_ID,
      defaultConnectionName: DEFAULT_CONNECTION_NAME,
      operationId: "AddRows",
      parameters: parameters as Record<string, ExpressionOrValue>,
      options,
    }) as ActionSpec;
  },

  /**
   * When a data driven alert is triggered
   * @remarks This is a trigger operation; pass it to flowBuilder.setTrigger().
   * @returns - Body - EvaluatedAlert
   * Operation id: `CheckAlertStatus`
   */
  checkAlertStatus(
    parameters: {
      alertId?: ExpressionOrValue; // REQUIRED — Alert Id — string — The alert id to track.
    } & Record<string, ExpressionOrValue>,
    options?: ConnectorCallOptions,
  ): TriggerSpec {
    return buildConnectorCall({
      kind: "trigger",
      apiId: API_ID,
      defaultConnectionName: DEFAULT_CONNECTION_NAME,
      operationId: "CheckAlertStatus",
      parameters: parameters as Record<string, ExpressionOrValue>,
      options,
    }) as TriggerSpec;
  },

  /**
   * Create a goal (Preview)
   * @returns | Name | Path | Type | Description | | --- | --- | --- | --- | | Id | id | string | The unique identifier of the goal. |
   * Operation id: `CreateGoal`
   */
  createGoal(
    parameters: {
      groupid?: ExpressionOrValue; // REQUIRED — Workspace — string — The unique identifier of the workspace.
      scorecardId?: ExpressionOrValue; // REQUIRED — Scorecard id — string — The unique identifier of the scorecard.
      name?: ExpressionOrValue; // REQUIRED — Name — string — The name of the goal.
      owner?: ExpressionOrValue; // optional — Owner — email — The email address of the goal's owner. Example: foo@bar.com
      value?: ExpressionOrValue; // optional — Current value — string — The current value of the goal being tracked.
      target?: ExpressionOrValue; // optional — Target value — string — The target value of the goal.
      status?: ExpressionOrValue; // optional — Status — string — The current status the goal.
      startDate?: ExpressionOrValue; // optional — Start date — date — The start date for the goal. Example: 2021-07-15.
      completionDate?: ExpressionOrValue; // optional — Completion date — date — The date for the goal to be completed by. Example: 2021-07-29.
      note?: ExpressionOrValue; // optional — Note — string — Note to attach to the initial check-in on goal creation. Can be multiline text
      parentId?: ExpressionOrValue; // optional — Parent goal id — string — If this goal is a subgoal, the unique id of its parent goal.
    } & Record<string, ExpressionOrValue>,
    options?: ConnectorCallOptions,
  ): ActionSpec {
    return buildConnectorCall({
      kind: "action",
      apiId: API_ID,
      defaultConnectionName: DEFAULT_CONNECTION_NAME,
      operationId: "CreateGoal",
      parameters: parameters as Record<string, ExpressionOrValue>,
      options,
    }) as ActionSpec;
  },

  /**
   * Create a scorecard (Preview)
   * @returns Created scorecard. - Created scorecard - CreatedScorecard
   * Operation id: `CreateScorecard`
   */
  createScorecard(
    parameters: {
      groupid?: ExpressionOrValue; // REQUIRED — Workspace — string — The unique identifier of the workspace.
      name?: ExpressionOrValue; // REQUIRED — Name — string — Scorecard name
      description?: ExpressionOrValue; // optional — Description — string — Scorecard description
    } & Record<string, ExpressionOrValue>,
    options?: ConnectorCallOptions,
  ): ActionSpec {
    return buildConnectorCall({
      kind: "action",
      apiId: API_ID,
      defaultConnectionName: DEFAULT_CONNECTION_NAME,
      operationId: "CreateScorecard",
      parameters: parameters as Record<string, ExpressionOrValue>,
      options,
    }) as ActionSpec;
  },

  /**
   * Run a json query against a dataset
   * @returns - response - object
   * Operation id: `ExecuteDatasetQueriesJson`
   */
  executeDatasetQueriesJson(
    parameters: {
      groupid?: ExpressionOrValue; // REQUIRED — Workspace — string — The unique identifier of the workspace.
      datasetid?: ExpressionOrValue; // REQUIRED — Dataset — string — The unique identifier of the dataset.
    } & Record<string, ExpressionOrValue>,
    options?: ConnectorCallOptions,
  ): ActionSpec {
    return buildConnectorCall({
      kind: "action",
      apiId: API_ID,
      defaultConnectionName: DEFAULT_CONNECTION_NAME,
      operationId: "ExecuteDatasetQueriesJson",
      parameters: parameters as Record<string, ExpressionOrValue>,
      options,
    }) as ActionSpec;
  },

  /**
   * Run a query against a dataset
   * @returns Results of query execution. - Body - QueryExecutionResults
   * Operation id: `ExecuteDatasetQuery`
   */
  executeDatasetQuery(
    parameters: {
      groupid?: ExpressionOrValue; // REQUIRED — Workspace — string — The unique identifier of the workspace.
      datasetid?: ExpressionOrValue; // REQUIRED — Dataset — string — The unique identifier of the dataset.
      query?: ExpressionOrValue; // REQUIRED — Query text — string — The text of the query. Can be multiline text.
      includeNulls?: ExpressionOrValue; // optional — Nulls included — boolean — Should null values be included in the results. Default is No.
      impersonatedUserName?: ExpressionOrValue; // optional — Impersonate user — string — A user identity in UPN format to run the query as another user.
    } & Record<string, ExpressionOrValue>,
    options?: ConnectorCallOptions,
  ): ActionSpec {
    return buildConnectorCall({
      kind: "action",
      apiId: API_ID,
      defaultConnectionName: DEFAULT_CONNECTION_NAME,
      operationId: "ExecuteDatasetQuery",
      parameters: parameters as Record<string, ExpressionOrValue>,
      options,
    }) as ActionSpec;
  },

  /**
   * Get a goal (Preview)
   * @returns Goal information. - Goal - FetchedGoal
   * Operation id: `GetGoal`
   */
  getGoal(
    parameters: {
      groupid?: ExpressionOrValue; // REQUIRED — Workspace — string — The unique identifier of the workspace.
      scorecardId?: ExpressionOrValue; // REQUIRED — Scorecard id — string — The unique identifier of the scorecard.
      goalId?: ExpressionOrValue; // REQUIRED — Goal id — string — The unique identifier of the goal.
    } & Record<string, ExpressionOrValue>,
    options?: ConnectorCallOptions,
  ): ActionSpec {
    return buildConnectorCall({
      kind: "action",
      apiId: API_ID,
      defaultConnectionName: DEFAULT_CONNECTION_NAME,
      operationId: "GetGoal",
      parameters: parameters as Record<string, ExpressionOrValue>,
      options,
    }) as ActionSpec;
  },

  /**
   * Get a goal check-in (Preview)
   * @returns | Name | Path | Type | Description | | --- | --- | --- | --- | | Date | timestamp | date | The date that the check-in was made. | | Value | value | number | The value at the time of check in, if set. |
   * Operation id: `GetGoalCheckin`
   */
  getGoalCheckin(
    parameters: {
      groupid?: ExpressionOrValue; // REQUIRED — Workspace — string — The unique identifier of the workspace.
      scorecardId?: ExpressionOrValue; // REQUIRED — Scorecard id — string — The unique identifier of the scorecard.
      goalId?: ExpressionOrValue; // REQUIRED — Goal id — string — The unique identifier of the goal.
      goalCheckin?: ExpressionOrValue; // REQUIRED — Check-in date — date — Example: 2021-07-21
    } & Record<string, ExpressionOrValue>,
    options?: ConnectorCallOptions,
  ): ActionSpec {
    return buildConnectorCall({
      kind: "action",
      apiId: API_ID,
      defaultConnectionName: DEFAULT_CONNECTION_NAME,
      operationId: "GetGoalCheckin",
      parameters: parameters as Record<string, ExpressionOrValue>,
      options,
    }) as ActionSpec;
  },

  /**
   * Get goal check-ins (Preview)
   * @returns | Name | Path | Type | Description | | --- | --- | --- | --- | | Check-ins | value | array of object | List of check-ins. | | Date | value.timestamp | datetime | The date that the check-in was made. |
   * Operation id: `GetGoalCheckins`
   */
  getGoalCheckins(
    parameters: {
      groupid?: ExpressionOrValue; // REQUIRED — Workspace — string — The unique identifier of the workspace.
      scorecardId?: ExpressionOrValue; // REQUIRED — Scorecard id — string — The unique identifier of the scorecard.
      goalId?: ExpressionOrValue; // REQUIRED — Goal id — string — The unique identifier of the goal.
    } & Record<string, ExpressionOrValue>,
    options?: ConnectorCallOptions,
  ): ActionSpec {
    return buildConnectorCall({
      kind: "action",
      apiId: API_ID,
      defaultConnectionName: DEFAULT_CONNECTION_NAME,
      operationId: "GetGoalCheckins",
      parameters: parameters as Record<string, ExpressionOrValue>,
      options,
    }) as ActionSpec;
  },

  /**
   * Get multiple goals (Preview)
   * @returns Entire response body. - Retrieved - FetchedGoals
   * Operation id: `GetMultipleGoals`
   */
  getMultipleGoals(
    parameters: {
      groupid?: ExpressionOrValue; // REQUIRED — Workspace — string — The unique identifier of the workspace.
      scorecardId?: ExpressionOrValue; // REQUIRED — Scorecard id — string — The unique identifier of the scorecard.
    } & Record<string, ExpressionOrValue>,
    options?: ConnectorCallOptions,
  ): ActionSpec {
    return buildConnectorCall({
      kind: "action",
      apiId: API_ID,
      defaultConnectionName: DEFAULT_CONNECTION_NAME,
      operationId: "GetMultipleGoals",
      parameters: parameters as Record<string, ExpressionOrValue>,
      options,
    }) as ActionSpec;
  },

  /**
   * Get scorecards (Preview)
   * @returns Entire response body. - Retrieved - ListedScorecards
   * Operation id: `GetScorecards`
   */
  getScorecards(
    parameters: {
      groupid?: ExpressionOrValue; // REQUIRED — Workspace — string — The unique identifier of the workspace.
    } & Record<string, ExpressionOrValue>,
    options?: ConnectorCallOptions,
  ): ActionSpec {
    return buildConnectorCall({
      kind: "action",
      apiId: API_ID,
      defaultConnectionName: DEFAULT_CONNECTION_NAME,
      operationId: "GetScorecards",
      parameters: parameters as Record<string, ExpressionOrValue>,
      options,
    }) as ActionSpec;
  },

  /**
   * When a goal changes (Preview)
   * @remarks This is a trigger operation; pass it to flowBuilder.setTrigger().
   * @returns Changed goal properties. - Changed goal - GoalChanged
   * Operation id: `GoalChangeTrigger`
   */
  goalChangeTrigger(
    parameters: {
      groupid?: ExpressionOrValue; // REQUIRED — Workspace — string — The unique identifier of the workspace.
      scorecardId?: ExpressionOrValue; // REQUIRED — Scorecard id — string — The unique identifier of the scorecard.
      goalId?: ExpressionOrValue; // REQUIRED — Goal id — string — The unique identifier of the goal.
      pollingInterval?: ExpressionOrValue; // REQUIRED — Polling interval (sec) — number — Number of seconds between checks for new data. Minimum is 300.
    } & Record<string, ExpressionOrValue>,
    options?: ConnectorCallOptions,
  ): TriggerSpec {
    return buildConnectorCall({
      kind: "trigger",
      apiId: API_ID,
      defaultConnectionName: DEFAULT_CONNECTION_NAME,
      operationId: "GoalChangeTrigger",
      parameters: parameters as Record<string, ExpressionOrValue>,
      options,
    }) as TriggerSpec;
  },

  /**
   * When a data refresh for a goal fails (Preview)
   * @remarks This is a trigger operation; pass it to flowBuilder.setTrigger().
   * @returns Goal refresh failure issues. - Refresh failure - GoalRefreshIssues
   * Operation id: `GoalRefreshFailedTrigger`
   */
  goalRefreshFailedTrigger(
    parameters: {
      groupid?: ExpressionOrValue; // REQUIRED — Workspace — string — The unique identifier of the workspace.
      scorecardId?: ExpressionOrValue; // REQUIRED — Scorecard id — string — The unique identifier of the scorecard.
      goalId?: ExpressionOrValue; // REQUIRED — Goal id — string — The unique identifier of the goal.
      trackTargetSource?: ExpressionOrValue; // REQUIRED — Track target source — string — Will track the link for the goal's target.
      trackValueSource?: ExpressionOrValue; // REQUIRED — Track value source — string — Will track the link for the goal's value.
      pollingInterval?: ExpressionOrValue; // REQUIRED — Polling interval (sec) — number — Number of seconds between checks for new data. Minimum is 300.
    } & Record<string, ExpressionOrValue>,
    options?: ConnectorCallOptions,
  ): TriggerSpec {
    return buildConnectorCall({
      kind: "trigger",
      apiId: API_ID,
      defaultConnectionName: DEFAULT_CONNECTION_NAME,
      operationId: "GoalRefreshFailedTrigger",
      parameters: parameters as Record<string, ExpressionOrValue>,
      options,
    }) as TriggerSpec;
  },

  /**
   * When status of a goal changes (Preview)
   * @remarks This is a trigger operation; pass it to flowBuilder.setTrigger().
   * @returns Changed goal properties. - Changed goal - GoalStatusChanged
   * Operation id: `GoalStatusChangeTrigger`
   */
  goalStatusChangeTrigger(
    parameters: {
      groupid?: ExpressionOrValue; // REQUIRED — Workspace — string — The unique identifier of the workspace.
      scorecardId?: ExpressionOrValue; // REQUIRED — Scorecard id — string — The unique identifier of the scorecard.
      goalId?: ExpressionOrValue; // REQUIRED — Goal id — string — The unique identifier of the goal.
      pollingInterval?: ExpressionOrValue; // REQUIRED — Polling interval (sec) — number — Number of seconds between checks for new data. Minimum is 300.
    } & Record<string, ExpressionOrValue>,
    options?: ConnectorCallOptions,
  ): TriggerSpec {
    return buildConnectorCall({
      kind: "trigger",
      apiId: API_ID,
      defaultConnectionName: DEFAULT_CONNECTION_NAME,
      operationId: "GoalStatusChangeTrigger",
      parameters: parameters as Record<string, ExpressionOrValue>,
      options,
    }) as TriggerSpec;
  },

  /**
   * When current value of a goal changes (Preview)
   * @remarks This is a trigger operation; pass it to flowBuilder.setTrigger().
   * @returns Changed goal properties. - Changed goal - GoalValueChanged
   * Operation id: `GoalValueChangeTrigger`
   */
  goalValueChangeTrigger(
    parameters: {
      groupid?: ExpressionOrValue; // REQUIRED — Workspace — string — The unique identifier of the workspace.
      scorecardId?: ExpressionOrValue; // REQUIRED — Scorecard id — string — The unique identifier of the scorecard.
      goalId?: ExpressionOrValue; // REQUIRED — Goal id — string — The unique identifier of the goal.
      pollingInterval?: ExpressionOrValue; // REQUIRED — Polling interval (sec) — number — Number of seconds between checks for new data. Minimum is 300.
    } & Record<string, ExpressionOrValue>,
    options?: ConnectorCallOptions,
  ): TriggerSpec {
    return buildConnectorCall({
      kind: "trigger",
      apiId: API_ID,
      defaultConnectionName: DEFAULT_CONNECTION_NAME,
      operationId: "GoalValueChangeTrigger",
      parameters: parameters as Record<string, ExpressionOrValue>,
      options,
    }) as TriggerSpec;
  },

  /**
   * Create a check-in (Preview)
   * Operation id: `GoalValueCheckin`
   */
  goalValueCheckin(
    parameters: {
      groupid?: ExpressionOrValue; // REQUIRED — Workspace — string — The unique identifier of the workspace.
      scorecardId?: ExpressionOrValue; // REQUIRED — Scorecard id — string — The unique identifier of the scorecard.
      goalId?: ExpressionOrValue; // REQUIRED — Goal id — string — The unique identifier of the goal.
      timestamp?: ExpressionOrValue; // REQUIRED — Date — date — Check-in date. Example: 2021-07-21
      value?: ExpressionOrValue; // optional — Value — number
      status?: ExpressionOrValue; // optional — Status — string — Status of the goal.
      note?: ExpressionOrValue; // optional — Note — string — Can be multiline text
    } & Record<string, ExpressionOrValue>,
    options?: ConnectorCallOptions,
  ): ActionSpec {
    return buildConnectorCall({
      kind: "action",
      apiId: API_ID,
      defaultConnectionName: DEFAULT_CONNECTION_NAME,
      operationId: "GoalValueCheckin",
      parameters: parameters as Record<string, ExpressionOrValue>,
      options,
    }) as ActionSpec;
  },

  /**
   * Add a note to a check-in (Preview)
   * Operation id: `GoalValueCheckinNote`
   */
  goalValueCheckinNote(
    parameters: {
      groupid?: ExpressionOrValue; // REQUIRED — Workspace — string — The unique identifier of the workspace.
      scorecardId?: ExpressionOrValue; // REQUIRED — Scorecard id — string — The unique identifier of the scorecard.
      goalId?: ExpressionOrValue; // REQUIRED — Goal id — string — The unique identifier of the goal.
      goalCheckin?: ExpressionOrValue; // REQUIRED — Check-in date — date — Example: 2021-07-21
      note?: ExpressionOrValue; // REQUIRED — Note — string — Can be multiline text
    } & Record<string, ExpressionOrValue>,
    options?: ConnectorCallOptions,
  ): ActionSpec {
    return buildConnectorCall({
      kind: "action",
      apiId: API_ID,
      defaultConnectionName: DEFAULT_CONNECTION_NAME,
      operationId: "GoalValueCheckinNote",
      parameters: parameters as Record<string, ExpressionOrValue>,
      options,
    }) as ActionSpec;
  },

  /**
   * When someone adds or edits a goal check-in (Preview)
   * @remarks This is a trigger operation; pass it to flowBuilder.setTrigger().
   * @returns Added or changed goal check-ins or notes. - Updated goal - GoalValueOrNoteUpserted
   * Operation id: `GoalValueOrNoteUpsertTrigger`
   */
  goalValueOrNoteUpsertTrigger(
    parameters: {
      groupid?: ExpressionOrValue; // REQUIRED — Workspace — string — The unique identifier of the workspace.
      scorecardId?: ExpressionOrValue; // REQUIRED — Scorecard id — string — The unique identifier of the scorecard.
      goalId?: ExpressionOrValue; // REQUIRED — Goal id — string — The unique identifier of the goal.
      pollingInterval?: ExpressionOrValue; // REQUIRED — Polling interval (sec) — number — Number of seconds between checks for new data. Minimum is 300.
    } & Record<string, ExpressionOrValue>,
    options?: ConnectorCallOptions,
  ): TriggerSpec {
    return buildConnectorCall({
      kind: "trigger",
      apiId: API_ID,
      defaultConnectionName: DEFAULT_CONNECTION_NAME,
      operationId: "GoalValueOrNoteUpsertTrigger",
      parameters: parameters as Record<string, ExpressionOrValue>,
      options,
    }) as TriggerSpec;
  },

  /**
   * When someone assigns a new owner to a goal (Preview)
   * @remarks This is a trigger operation; pass it to flowBuilder.setTrigger().
   * @returns Assigned goals info. - Assigned - GoalsAssigned
   * Operation id: `GoalsAssignedTrigger`
   */
  goalsAssignedTrigger(
    parameters: {
      groupid?: ExpressionOrValue; // REQUIRED — Workspace — string — The unique identifier of the workspace.
      scorecardId?: ExpressionOrValue; // REQUIRED — Scorecard id — string — The unique identifier of the scorecard.
      pollingInterval?: ExpressionOrValue; // REQUIRED — Polling interval (sec) — number — Number of seconds between checks for new data. Minimum is 300.
      owner?: ExpressionOrValue; // optional — Owner — email — E-mail of an owner. Can be yours. Can be empty when tracking any owner.
    } & Record<string, ExpressionOrValue>,
    options?: ConnectorCallOptions,
  ): TriggerSpec {
    return buildConnectorCall({
      kind: "trigger",
      apiId: API_ID,
      defaultConnectionName: DEFAULT_CONNECTION_NAME,
      operationId: "GoalsAssignedTrigger",
      parameters: parameters as Record<string, ExpressionOrValue>,
      options,
    }) as TriggerSpec;
  },

  /**
   * Export To File for Paginated Reports
   * @returns The content of the file. - File Content - binary
   * Operation id: `InitiateExportToFileForPaginatedReports`
   */
  initiateExportToFileForPaginatedReports(
    parameters: {
      groupid?: ExpressionOrValue; // REQUIRED — Workspace — string — The unique identifier of the workspace.
      reportid?: ExpressionOrValue; // REQUIRED — Report — string — The unique identifier of a paginated report.
      format?: ExpressionOrValue; // REQUIRED — Export Format — string — The export format for the paginated report. The supported formats are: PPTX (PowerPoint), PDF, ACCESSIBLEPDF (Accessible
      username?: ExpressionOrValue; // REQUIRED — Username — string — The effective username reflected by a token for applying RLS rules (For OnPrem model, username can be composed of alpha-
      value?: ExpressionOrValue; // REQUIRED — Blob Value — string — OAuth2 access token for SQL Azure
      datasets?: ExpressionOrValue; // optional — Datasets — array of string — An array of datasets for which this identity applies
      roles?: ExpressionOrValue; // optional — Roles — array of string — An array of RLS roles reflected by a token when applying RLS rules (identity can contain up to 50 roles, role can be com
      customData?: ExpressionOrValue; // optional — CustomData — string — The value of customdata to be used for applying RLS rules. Only supported for live connections to Azure Analysis Service
      reports?: ExpressionOrValue; // optional — Reports — array of string — An array of reports for which this identity applies, Only supported for paginated reports
      formatSettings?: ExpressionOrValue; // optional — FormatSettings — object — Dictionary of format settings. The keys are the device info property names for the requested file format.
      name?: ExpressionOrValue; // optional — string — The report parameter name
    } & Record<string, ExpressionOrValue>,
    options?: ConnectorCallOptions,
  ): ActionSpec {
    return buildConnectorCall({
      kind: "action",
      apiId: API_ID,
      defaultConnectionName: DEFAULT_CONNECTION_NAME,
      operationId: "InitiateExportToFileForPaginatedReports",
      parameters: parameters as Record<string, ExpressionOrValue>,
      options,
    }) as ActionSpec;
  },

  /**
   * Export To File for Power BI Reports
   * @returns The content of the file. - File Content - binary
   * Operation id: `InitiateExportToFileForPbiReports`
   */
  initiateExportToFileForPbiReports(
    parameters: {
      groupid?: ExpressionOrValue; // REQUIRED — Workspace — string — The unique identifier of the workspace.
      reportid?: ExpressionOrValue; // REQUIRED — Report — string — The unique identifier of a pbi report.
      format?: ExpressionOrValue; // REQUIRED — Export Format — string — The export format for the Power BI report. The supported formats are: PPTX (PowerPoint), PDF, and PNG
      username?: ExpressionOrValue; // REQUIRED — Username — string — The effective username reflected by a token for applying RLS rules (For OnPrem model, username can be composed of alpha-
      value?: ExpressionOrValue; // REQUIRED — Blob Value — string — OAuth2 access token for SQL Azure
      locale?: ExpressionOrValue; // optional — Locale — string — The locale to apply
      includeHiddenPages?: ExpressionOrValue; // optional — Include Hidden Pages — boolean — A flag indicating whether to include hidden pages when exporting the entire report (when passing specific pages this pro
      name?: ExpressionOrValue; // optional — Bookmark Name — string — The bookmark name
      state?: ExpressionOrValue; // optional — Bookmark State — string — The bookmark state
      filter?: ExpressionOrValue; // optional — Filter — string — The filter to apply
      pageName?: ExpressionOrValue; // optional — string — The page name
      visualName?: ExpressionOrValue; // optional — string — (Optional) Visual name to be exported
      datasets?: ExpressionOrValue; // optional — Datasets — array of string — An array of datasets for which this identity applies
      roles?: ExpressionOrValue; // optional — Roles — array of string — An array of RLS roles reflected by a token when applying RLS rules (identity can contain up to 50 roles, role can be com
      customData?: ExpressionOrValue; // optional — CustomData — string — The value of customdata to be used for applying RLS rules. Only supported for live connections to Azure Analysis Service
      reports?: ExpressionOrValue; // optional — Reports — array of string — An array of reports for which this identity applies, Only supported for paginated reports
    } & Record<string, ExpressionOrValue>,
    options?: ConnectorCallOptions,
  ): ActionSpec {
    return buildConnectorCall({
      kind: "action",
      apiId: API_ID,
      defaultConnectionName: DEFAULT_CONNECTION_NAME,
      operationId: "InitiateExportToFileForPbiReports",
      parameters: parameters as Record<string, ExpressionOrValue>,
      options,
    }) as ActionSpec;
  },

  /**
   * Power BI button clicked
   * @remarks This is a trigger operation; pass it to flowBuilder.setTrigger().
   * @returns | Name | Path | Type | Description | | --- | --- | --- | --- | | rows | body.rows | array of object |  | | items | body.rows | object |  |
   * Operation id: `PowerBiButtonClicked`
   */
  powerBiButtonClicked(
    parameters: {
      operationId?: ExpressionOrValue; // REQUIRED — string
      parameters?: ExpressionOrValue; // REQUIRED — object
      host?: ExpressionOrValue; // optional — object
      headersSchema?: ExpressionOrValue; // optional — object
      schema?: ExpressionOrValue; // optional — object
    } & Record<string, ExpressionOrValue>,
    options?: ConnectorCallOptions,
  ): TriggerSpec {
    return buildConnectorCall({
      kind: "trigger",
      apiId: API_ID,
      defaultConnectionName: DEFAULT_CONNECTION_NAME,
      operationId: "PowerBiButtonClicked",
      parameters: parameters as Record<string, ExpressionOrValue>,
      options,
    }) as TriggerSpec;
  },

  /**
   * Refresh a dataset
   * Operation id: `RefreshDataset`
   */
  refreshDataset(
    parameters: {
      groupid?: ExpressionOrValue; // REQUIRED — Workspace — string — The unique identifier of the workspace.
      datasetid?: ExpressionOrValue; // REQUIRED — Dataset — string — The unique identifier of the dataset.
    } & Record<string, ExpressionOrValue>,
    options?: ConnectorCallOptions,
  ): ActionSpec {
    return buildConnectorCall({
      kind: "action",
      apiId: API_ID,
      defaultConnectionName: DEFAULT_CONNECTION_NAME,
      operationId: "RefreshDataset",
      parameters: parameters as Record<string, ExpressionOrValue>,
      options,
    }) as ActionSpec;
  },

  /**
   * Update a goal (Preview)
   * Operation id: `UpdateGoal`
   */
  updateGoal(
    parameters: {
      groupid?: ExpressionOrValue; // REQUIRED — Workspace — string — The unique identifier of the workspace.
      scorecardId?: ExpressionOrValue; // REQUIRED — Scorecard id — string — The unique identifier of the scorecard.
      goalId?: ExpressionOrValue; // REQUIRED — Goal id — string — The unique identifier of the goal.
      name?: ExpressionOrValue; // optional — Name — string — If provided, the new name of the goal.
      owner?: ExpressionOrValue; // optional — Owner — email — If provided, the email address of the new goal owner.
      value?: ExpressionOrValue; // optional — Current value — number — If provided, sets the new value of the goal.
      target?: ExpressionOrValue; // optional — Target value — number — If provided, sets the new goal target.
      status?: ExpressionOrValue; // optional — Status — string — If provided, sets the new status of the goal.
      startDate?: ExpressionOrValue; // optional — Start date — date — If provided, the new start date for the goal. Example: 2021-07-15.
      completionDate?: ExpressionOrValue; // optional — Completion date — date — If provided, the new date for the goal to be completed by. Example: 2021-07-29.
    } & Record<string, ExpressionOrValue>,
    options?: ConnectorCallOptions,
  ): ActionSpec {
    return buildConnectorCall({
      kind: "action",
      apiId: API_ID,
      defaultConnectionName: DEFAULT_CONNECTION_NAME,
      operationId: "UpdateGoal",
      parameters: parameters as Record<string, ExpressionOrValue>,
      options,
    }) as ActionSpec;
  },

  /**
   * Update a check-in (Preview)
   * Operation id: `UpdateGoalCheckin`
   */
  updateGoalCheckin(
    parameters: {
      groupid?: ExpressionOrValue; // REQUIRED — Workspace — string — The unique identifier of the workspace.
      scorecardId?: ExpressionOrValue; // REQUIRED — Scorecard id — string — The unique identifier of the scorecard.
      goalId?: ExpressionOrValue; // REQUIRED — Goal id — string — The unique identifier of the goal.
      goalCheckin?: ExpressionOrValue; // REQUIRED — Check-in date — date — Example: 2021-07-21
      value?: ExpressionOrValue; // optional — Value — number
      status?: ExpressionOrValue; // optional — Status — string — Status of the goal.
    } & Record<string, ExpressionOrValue>,
    options?: ConnectorCallOptions,
  ): ActionSpec {
    return buildConnectorCall({
      kind: "action",
      apiId: API_ID,
      defaultConnectionName: DEFAULT_CONNECTION_NAME,
      operationId: "UpdateGoalCheckin",
      parameters: parameters as Record<string, ExpressionOrValue>,
      options,
    }) as ActionSpec;
  },
} as const;
