// AUTO-GENERATED by packages/connectors/scripts/generate.ts.
// Do not edit by hand. Re-run `bun --filter @vibeflow/connectors generate`.
// Connector: shared_azureopenai — Azure OpenAI
// Source: https://learn.microsoft.com/en-us/connectors/azureopenai/?accept=text/markdown

import { buildConnectorCall, type ActionSpec, type ConnectorCallOptions, type ExpressionOrValue, type TriggerSpec } from "../_runtime.js";

const API_ID = "/providers/Microsoft.PowerApps/apis/shared_azureopenai";
const DEFAULT_CONNECTION_NAME = "shared_azureopenai";

export const AzureOpenAI = {
  /** Connector id (`shared_azureopenai`). */
  connectorId: "shared_azureopenai",
  /** Power Automate apiId for this connector. */
  apiId: API_ID,

  /**
   * Creates a completion for the chat message
   * @returns - Body - createChatCompletionResponse_2024Feb15Preview
   * Operation id: `ChatCompletions_Create_2024Feb15Preview`
   */
  chatCompletionsCreate2024Feb15Preview(
    parameters: {
      "deployment-id"?: ExpressionOrValue; // REQUIRED — Deployment ID of the deployed model — string — Deployment ID of the deployed model
      "api-version"?: ExpressionOrValue; // REQUIRED — API version — string — API version
      role?: ExpressionOrValue; // REQUIRED — string — The role of the messages author.
      content?: ExpressionOrValue; // REQUIRED — string — An array of content parts with a defined type, each can be of type `text`.
      "type"?: ExpressionOrValue; // REQUIRED — string — A representation of configuration data for a single Azure OpenAI chat extension. This will be used by a chat completions
      index_name?: ExpressionOrValue; // REQUIRED — string — The name of the index to use as available in the referenced Azure Search resource.
      deployment_name?: ExpressionOrValue; // REQUIRED — string — Specifies the name of the model deployment to use for vectorization. This model deployment must be in the same Azure Ope
      temperature?: ExpressionOrValue; // optional — number — What sampling temperature to use, between 0 and 2. Higher values like 0.8 will make the output more random, while lower 
      top_p?: ExpressionOrValue; // optional — number — An alternative to sampling with temperature, called nucleus sampling, where the model considers the results of the token
      stream?: ExpressionOrValue; // optional — boolean — If set, partial message deltas will be sent, like in ChatGPT. Tokens will be sent as data-only server-sent events as the
      stop?: ExpressionOrValue; // optional — array of string — Up to 4 sequences where the API will stop generating further tokens. The returned text will not contain the stop sequenc
      max_tokens?: ExpressionOrValue; // optional — integer — The maximum number of tokens allowed for the generated answer. By default, the number of tokens the model can return wil
      presence_penalty?: ExpressionOrValue; // optional — number — Number between -2.0 and 2.0. Positive values penalize new tokens based on whether they appear in the text so far, increa
      frequency_penalty?: ExpressionOrValue; // optional — number — Number between -2.0 and 2.0. Positive values penalize new tokens based on their existing frequency in the text so far, d
      logit_bias?: ExpressionOrValue; // optional — object — Modify the likelihood of specified tokens appearing in the completion. Accepts a json object that maps tokens (specified
      user?: ExpressionOrValue; // optional — string — A unique identifier representing your end-user, which can help Azure OpenAI to monitor and detect abuse.
      top_n_documents?: ExpressionOrValue; // optional — integer — The configured top number of documents to feature for the configured query.
      in_scope?: ExpressionOrValue; // optional — boolean — Whether queries should be restricted to use of indexed data.
      strictness?: ExpressionOrValue; // optional — integer — The configured strictness of the search relevance filtering. The higher of strictness, the higher of the precision but l
      role_information?: ExpressionOrValue; // optional — string — Give the model instructions about how it should behave and any context it should reference when generating a response. Y
      title_field?: ExpressionOrValue; // optional — string — The name of the index field to use as a title.
      url_field?: ExpressionOrValue; // optional — string — The name of the index field to use as a URL.
      filepath_field?: ExpressionOrValue; // optional — string — The name of the index field to use as a filepath.
      content_fields?: ExpressionOrValue; // optional — array of string — The names of index fields that should be treated as content.
      content_fields_separator?: ExpressionOrValue; // optional — string — The separator pattern that content fields should use.
      vector_fields?: ExpressionOrValue; // optional — array of string — The names of fields that represent vector data.
      query_type?: ExpressionOrValue; // optional — string — The type of Azure Search retrieval query that should be executed when using it as an Azure OpenAI chat extension.
      semantic_configuration?: ExpressionOrValue; // optional — string — The additional semantic configuration for the query.
      filter?: ExpressionOrValue; // optional — string — Search filter.
      n?: ExpressionOrValue; // optional — integer — How many chat completion choices to generate for each input message.
      seed?: ExpressionOrValue; // optional — integer — If specified, our system will make a best effort to sample deterministically, such that repeated requests with the same 
      logprobs?: ExpressionOrValue; // optional — boolean — Whether to return log probabilities of the output tokens or not. If true, returns the log probabilities of each output t
      top_logprobs?: ExpressionOrValue; // optional — integer — An integer between 0 and 5 specifying the number of most likely tokens to return at each token position, each with an as
    } & Record<string, ExpressionOrValue>,
    options?: ConnectorCallOptions,
  ): ActionSpec {
    return buildConnectorCall({
      kind: "action",
      apiId: API_ID,
      defaultConnectionName: DEFAULT_CONNECTION_NAME,
      operationId: "ChatCompletions_Create_2024Feb15Preview",
      parameters: parameters as Record<string, ExpressionOrValue>,
      options,
    }) as ActionSpec;
  },

  /**
   * Using extensions to create a completion for chat messages
   * @returns The response of the extensions chat completions. - Body - ExtensionsChatCompletionsResponse
   * Operation id: `ExtensionsChatCompletions_Create`
   */
  extensionsChatCompletionsCreate(
    parameters: {
      "deployment-id"?: ExpressionOrValue; // REQUIRED — Deployment ID of the deployed model — string — Deployment ID of the deployed model
      deploymentId?: ExpressionOrValue; // REQUIRED — Confirm Deployment ID of the deployed model — string — Confirm Deployment ID of the deployed model
      "api-version"?: ExpressionOrValue; // REQUIRED — API version — string — API version
      role?: ExpressionOrValue; // REQUIRED — string — The role of the author of this message.
      content?: ExpressionOrValue; // REQUIRED — string — The contents of the message
      "type"?: ExpressionOrValue; // REQUIRED — string — The data source type.
      index?: ExpressionOrValue; // optional — integer — The index of the message in the conversation.
      recipient?: ExpressionOrValue; // optional — string — The recipient of the message in the format of &lt;namespace&gt;.&lt;operation&gt;. Present if and only if the recipient 
      end_turn?: ExpressionOrValue; // optional — boolean — Whether the message ends the turn.
      parameters?: ExpressionOrValue; // optional — object — The parameters to be used for the data source in runtime.
      temperature?: ExpressionOrValue; // optional — number — What sampling temperature to use, between 0 and 2. Higher values like 0.8 will make the output more random, while lower 
      top_p?: ExpressionOrValue; // optional — number — An alternative to sampling with temperature, called nucleus sampling, where the model considers the results of the token
      stream?: ExpressionOrValue; // optional — boolean — If set, partial message deltas will be sent, like in ChatGPT. Tokens will be sent as data-only server-sent events as the
      stop?: ExpressionOrValue; // optional — array of string — Array minimum size of 1 and maximum of 4
      max_tokens?: ExpressionOrValue; // optional — integer — The maximum number of tokens allowed for the generated answer. By default, the number of tokens the model can return wil
      presence_penalty?: ExpressionOrValue; // optional — number — Number between -2.0 and 2.0. Positive values penalize new tokens based on whether they appear in the text so far, increa
      frequency_penalty?: ExpressionOrValue; // optional — number — Number between -2.0 and 2.0. Positive values penalize new tokens based on their existing frequency in the text so far, d
      logit_bias?: ExpressionOrValue; // optional — object — Modify the likelihood of specified tokens appearing in the completion. Accepts a json object that maps tokens (specified
      user?: ExpressionOrValue; // optional — string — A unique identifier representing your end-user, which can help Azure OpenAI to monitor and detect abuse.
    } & Record<string, ExpressionOrValue>,
    options?: ConnectorCallOptions,
  ): ActionSpec {
    return buildConnectorCall({
      kind: "action",
      apiId: API_ID,
      defaultConnectionName: DEFAULT_CONNECTION_NAME,
      operationId: "ExtensionsChatCompletions_Create",
      parameters: parameters as Record<string, ExpressionOrValue>,
      options,
    }) as ActionSpec;
  },

  /**
   * Get multiple embeddings
   * @returns - Body - getMultipleEmbeddingsResponse_2024Feb15Preview
   * Operation id: `MultipleEmbeddings_Create_2024Feb15Preview`
   */
  multipleEmbeddingsCreate2024Feb15Preview(
    parameters: {
      "deployment-id"?: ExpressionOrValue; // REQUIRED — Deployment ID of the deployed model — string — Deployment ID of the deployed model
      "api-version"?: ExpressionOrValue; // REQUIRED — API version — string — API version
      input?: ExpressionOrValue; // REQUIRED — array of string — Array of Input texts to get embeddings for, encoded as a string. Each Input string must not exceed 2048 tokens in length
      user?: ExpressionOrValue; // optional — string — A unique identifier representing your end-user, which can help Azure OpenAI to monitor and detect abuse.
      input_type?: ExpressionOrValue; // optional — string — The input type of embedding search to use.
    } & Record<string, ExpressionOrValue>,
    options?: ConnectorCallOptions,
  ): ActionSpec {
    return buildConnectorCall({
      kind: "action",
      apiId: API_ID,
      defaultConnectionName: DEFAULT_CONNECTION_NAME,
      operationId: "MultipleEmbeddings_Create_2024Feb15Preview",
      parameters: parameters as Record<string, ExpressionOrValue>,
      options,
    }) as ActionSpec;
  },

  /**
   * Get an embedding
   * @returns - Body - getSingleEmbeddingsResponse_2024Feb15Preview
   * Operation id: `SingleEmbeddings_Create_2024Feb15Preview`
   */
  singleEmbeddingsCreate2024Feb15Preview(
    parameters: {
      "deployment-id"?: ExpressionOrValue; // REQUIRED — Deployment ID of the deployed model — string — Deployment ID of the deployed model
      "api-version"?: ExpressionOrValue; // REQUIRED — API version — string — API version
      input?: ExpressionOrValue; // REQUIRED — string — Input text to get embeddings for, encoded as a string. Input string must not exceed 2048 tokens in length
      user?: ExpressionOrValue; // optional — string — A unique identifier representing your end-user, which can help Azure OpenAI to monitor and detect abuse.
      input_type?: ExpressionOrValue; // optional — string — The input type of embedding search to use.
    } & Record<string, ExpressionOrValue>,
    options?: ConnectorCallOptions,
  ): ActionSpec {
    return buildConnectorCall({
      kind: "action",
      apiId: API_ID,
      defaultConnectionName: DEFAULT_CONNECTION_NAME,
      operationId: "SingleEmbeddings_Create_2024Feb15Preview",
      parameters: parameters as Record<string, ExpressionOrValue>,
      options,
    }) as ActionSpec;
  },
} as const;
