// AUTO-GENERATED by packages/connectors/scripts/generate.ts.
// Do not edit by hand. Re-run `bun --filter @vibeflow/connectors generate`.
// Connector: shared_flowpush — Notifications
// Source: https://learn.microsoft.com/en-us/connectors/flowpush/?accept=text/markdown

import { buildConnectorCall, type ActionSpec, type ConnectorCallOptions, type ExpressionOrValue, type TriggerSpec } from "../_runtime.js";

const API_ID = "/providers/Microsoft.PowerApps/apis/shared_flowpush";
const DEFAULT_CONNECTION_NAME = "shared_flowpush";

export const Notifications = {
  /** Connector id (`shared_flowpush`). */
  connectorId: "shared_flowpush",
  /** Power Automate apiId for this connector. */
  apiId: API_ID,

  /**
   * Send me an email notification [DEPRECATED] [DEPRECATED]
   * @deprecated Marked deprecated by Microsoft.
   * Operation id: `SendEmailNotification`
   */
  sendEmailNotification(
    parameters: {
      notificationSubject?: ExpressionOrValue; // REQUIRED — Subject — string — Notification email subject
      notificationBody?: ExpressionOrValue; // REQUIRED — Body — string — Notification email body
    } & Record<string, ExpressionOrValue>,
    options?: ConnectorCallOptions,
  ): ActionSpec {
    return buildConnectorCall({
      kind: "action",
      apiId: API_ID,
      defaultConnectionName: DEFAULT_CONNECTION_NAME,
      operationId: "SendEmailNotification",
      parameters: parameters as Record<string, ExpressionOrValue>,
      options,
    }) as ActionSpec;
  },

  /**
   * Send me a mobile notification
   * Operation id: `SendNotification`
   */
  sendNotification(
    parameters: {
      notificationText?: ExpressionOrValue; // REQUIRED — Text — string — Create a notification message
      uri?: ExpressionOrValue; // optional — Link — string — Include a link in the notification
      label?: ExpressionOrValue; // optional — Link label — string — The display name for the link
    } & Record<string, ExpressionOrValue>,
    options?: ConnectorCallOptions,
  ): ActionSpec {
    return buildConnectorCall({
      kind: "action",
      apiId: API_ID,
      defaultConnectionName: DEFAULT_CONNECTION_NAME,
      operationId: "SendNotification",
      parameters: parameters as Record<string, ExpressionOrValue>,
      options,
    }) as ActionSpec;
  },
} as const;
